/** Brainy Buddies - 12th Grade core curriculum activities. */
import type { Activity } from "@/lib/brainy-data";

export const GRADE12_ACTIVITIES: Activity[] = [
  {
    id: "g12-math-precalculus-statistics",
    subjectId: "math",
    level: "grade12",
    title: "Precalculus & Statistical Reasoning",
    description: "Model periodic change, sequences, limits, probability, and statistical inference.",
    emoji: "📊",
    questions: [
      { id: "q1", prompt: "The period of y = sin(x) is...", choices: ["pi/2", "pi", "2 pi", "4 pi"], answer: 2 },
      { id: "q2", prompt: "A geometric sequence has a constant...", choices: ["difference", "ratio", "sum", "median"], answer: 1 },
      { id: "q3", prompt: "Correlation alone does not establish...", choices: ["causation", "association", "variation", "sample size"], answer: 0 },
      { id: "q4", prompt: "A confidence interval estimates...", choices: ["a plausible range for a population parameter", "every individual value", "a guaranteed prediction", "the sample size only"], answer: 0 },
      { id: "q5", prompt: "The limit of 1/x as x approaches infinity is...", choices: ["0", "1", "infinity", "undefined"], answer: 0 },
    ],
  },
  {
    id: "g12-sci-environmental",
    subjectId: "science",
    level: "grade12",
    title: "Environmental Science & Systems",
    description: "Evaluate climate, biodiversity, energy, and human choices using systems evidence.",
    emoji: "🌎",
    questions: [
      { id: "q1", prompt: "A positive climate feedback...", choices: ["amplifies an initial change", "always cools Earth", "stops all change", "removes uncertainty"], answer: 0 },
      { id: "q2", prompt: "Biodiversity can improve ecosystem resilience by...", choices: ["supporting varied responses to disturbance", "eliminating competition", "preventing evolution", "making every species identical"], answer: 0 },
      { id: "q3", prompt: "Life-cycle analysis evaluates impacts...", choices: ["from resource extraction through disposal", "during purchase only", "inside one factory only", "after disposal only"], answer: 0 },
      { id: "q4", prompt: "A carbon sink absorbs...", choices: ["more carbon than it releases", "all atmospheric oxygen", "only solar energy", "more water than carbon"], answer: 0 },
      { id: "q5", prompt: "Environmental justice examines whether...", choices: ["risks and benefits are distributed fairly", "all ecosystems are identical", "technology has no trade-offs", "only wildlife is affected"], answer: 0 },
    ],
  },
  {
    id: "g12-hist-government-civics",
    subjectId: "history",
    level: "grade12",
    title: "Government, Law & Civic Participation",
    description: "Analyze constitutional principles, public policy, rights, and democratic participation.",
    emoji: "🏛️",
    questions: [
      { id: "q1", prompt: "Judicial review allows courts to...", choices: ["evaluate whether laws are constitutional", "write the federal budget", "command the military", "hold elections"], answer: 0 },
      { id: "q2", prompt: "Federalism divides power between...", choices: ["national and state governments", "courts and juries", "voters and media", "cities and businesses only"], answer: 0 },
      { id: "q3", prompt: "Civil liberties primarily protect individuals from...", choices: ["government overreach", "all disagreement", "market competition", "jury service"], answer: 0 },
      { id: "q4", prompt: "Public policy analysis should compare...", choices: ["goals, evidence, costs, benefits, and trade-offs", "campaign slogans only", "one person's preference", "historical dates only"], answer: 0 },
      { id: "q5", prompt: "Civic participation includes...", choices: ["voting, organizing, deliberating, and contacting representatives", "voting only", "holding office only", "following news without action only"], answer: 0 },
    ],
  },
  {
    id: "g12-geo-economics-development",
    subjectId: "geography",
    level: "grade12",
    title: "Economics, Development & Interdependence",
    description: "Evaluate markets, inequality, development policy, and interconnected global risks.",
    emoji: "🌍",
    questions: [
      { id: "q1", prompt: "Inflation is a sustained increase in...", choices: ["the general price level", "population density", "exports only", "interest in a product"], answer: 0 },
      { id: "q2", prompt: "Real GDP adjusts nominal GDP for...", choices: ["price changes", "latitude", "population age only", "currency color"], answer: 0 },
      { id: "q3", prompt: "The Gini coefficient measures...", choices: ["income or wealth inequality", "life expectancy", "carbon emissions", "literacy only"], answer: 0 },
      { id: "q4", prompt: "Supply-chain diversification can reduce...", choices: ["dependence on a single source", "all production costs", "consumer choice", "international trade"], answer: 0 },
      { id: "q5", prompt: "Sustainable development aims to meet present needs while...", choices: ["protecting future generations' ability to meet theirs", "ending economic activity", "using only local products", "maximizing short-term output"], answer: 0 },
    ],
  },
  {
    id: "g12-lang-research-argument",
    subjectId: "language",
    level: "grade12",
    title: "Research, Argument & Public Voice",
    description: "Develop nuanced claims, synthesize evidence, and communicate for authentic audiences.",
    emoji: "🎙️",
    questions: [
      { id: "q1", prompt: "A nuanced thesis should...", choices: ["acknowledge complexity while making a clear claim", "avoid taking a position", "list every source", "use absolute language"], answer: 0 },
      { id: "q2", prompt: "Source triangulation means...", choices: ["checking a claim across multiple independent sources", "citing one source three times", "using only visual evidence", "removing counterclaims"], answer: 0 },
      { id: "q3", prompt: "A literature review primarily...", choices: ["synthesizes existing research and identifies patterns or gaps", "reports new experiment results", "lists titles alphabetically", "replaces a thesis"], answer: 0 },
      { id: "q4", prompt: "Adapting for an audience may change your...", choices: ["evidence, tone, and organization", "commitment to accuracy", "core facts", "citation honesty"], answer: 0 },
      { id: "q5", prompt: "Ethical paraphrasing requires...", choices: ["genuine restatement plus citation", "changing a few words without citation", "copying sentence structure", "removing the author's name"], answer: 0 },
    ],
  },
  {
    id: "g12-python-software-engineering",
    subjectId: "python",
    level: "grade12",
    title: "Python Software Engineering",
    description: "Design maintainable programs with APIs, tests, version control, and clear architecture.",
    emoji: "🧰",
    questions: [
      { id: "q1", prompt: "A unit test should ideally verify...", choices: ["one focused behavior", "an entire production system", "the programmer's style", "network speed only"], answer: 0 },
      { id: "q2", prompt: "Dependency injection improves testability by...", choices: ["allowing collaborators to be substituted", "making every dependency global", "removing interfaces", "avoiding functions"], answer: 0 },
      { id: "q3", prompt: "A REST API commonly identifies resources with...", choices: ["URLs", "CSS selectors", "file extensions only", "loop counters"], answer: 0 },
      { id: "q4", prompt: "A Git branch allows developers to...", choices: ["work on changes independently before merging", "delete repository history", "avoid commits", "run code without files"], answer: 0 },
      { id: "q5", prompt: "Refactoring changes code structure while preserving...", choices: ["observable behavior", "every line", "all variable names", "the file count"], answer: 0 },
    ],
  },
  {
    id: "g12-sel-life-readiness",
    subjectId: "sel",
    level: "grade12",
    title: "Life Readiness & Healthy Independence",
    description: "Prepare for adult transitions with practical boundaries, support systems, and adaptable plans.",
    emoji: "🚀",
    questions: [
      { id: "q1", prompt: "Healthy independence includes...", choices: ["making decisions while using support when needed", "handling every challenge alone", "avoiding commitments", "never changing plans"], answer: 0 },
      { id: "q2", prompt: "A basic personal budget should account for...", choices: ["income, needs, savings, and discretionary spending", "wants only", "income without expenses", "unexpected costs never"], answer: 0 },
      { id: "q3", prompt: "During a major transition, a support map identifies...", choices: ["people and services you can contact for different needs", "only emergency numbers", "future grades", "social media followers"], answer: 0 },
      { id: "q4", prompt: "A respectful roommate or workplace boundary should be...", choices: ["clear, specific, and open to discussion", "communicated through hints only", "used to control others", "enforced through retaliation"], answer: 0 },
      { id: "q5", prompt: "When a post-graduation plan changes, adaptability means...", choices: ["reassessing options without treating the change as failure", "giving up all goals", "hiding the change", "following the original plan at any cost"], answer: 0 },
    ],
  },
];