/**
 * Brainy Buddies — 3rd Grade activities.
 * Loaded by brainy-data.ts and merged into the ACTIVITIES list.
 */
import type { Activity } from "@/lib/brainy-data";

export const GRADE3_ACTIVITIES: Activity[] = [
  // -------- MATH --------
  {
    id: "g3-math-mult",
    subjectId: "math",
    level: "grade3",
    title: "Multiplication Facts",
    description: "Master times tables from 0 to 10.",
    emoji: "✖️",
    questions: [
      { id: "q1", prompt: "6 × 7 = ?", choices: ["36", "42", "48", "54"], answer: 1, explanation: "6 × 7 = 42. Think: 6 × 6 = 36, then add 6 more." },
      { id: "q2", prompt: "8 × 4 = ?", choices: ["28", "32", "36", "40"], answer: 1 },
      { id: "q3", prompt: "9 × 3 = ?", choices: ["21", "24", "27", "30"], answer: 2 },
      { id: "q4", prompt: "7 × 7 = ?", choices: ["42", "46", "49", "56"], answer: 2 },
      { id: "q5", prompt: "5 × 8 = ?", choices: ["35", "40", "45", "50"], answer: 1 },
      { id: "q6", prompt: "There are 6 boxes with 9 crayons each. How many crayons total?", choices: ["48", "54", "56", "63"], answer: 1 },
      { id: "q7", prompt: "4 × 4 = ?", choices: ["8", "12", "16", "20"], answer: 2 },
      { id: "q8", prompt: "10 × 7 = ?", choices: ["17", "57", "70", "77"], answer: 2 },
      { id: "q9", prompt: "3 × 9 = ?", choices: ["21", "27", "30", "33"], answer: 1 },
      { id: "q10", prompt: "6 × 6 = ?", choices: ["30", "34", "36", "42"], answer: 2 },
      { id: "q11", prompt: "8 × 8 = ?", choices: ["56", "60", "64", "72"], answer: 2 },
      { id: "q12", prompt: "Sam plants 5 rows of flowers with 7 in each row. How many flowers?", choices: ["30", "35", "40", "45"], answer: 1 },
      { id: "q13", prompt: "0 × 99 = ?", choices: ["0", "9", "99", "990"], answer: 0, explanation: "Any number times zero is always zero!" },
    ],
  },
  {
    id: "g3-math-div",
    subjectId: "math",
    level: "grade3",
    title: "Division Basics",
    description: "Divide fairly and find equal groups.",
    emoji: "➗",
    questions: [
      { id: "q1", prompt: "24 ÷ 6 = ?", choices: ["3", "4", "6", "8"], answer: 1, explanation: "Think: 6 × ? = 24. The answer is 4." },
      { id: "q2", prompt: "36 ÷ 9 = ?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q3", prompt: "42 ÷ 7 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
      { id: "q4", prompt: "18 cookies split equally among 3 friends. Each gets...", choices: ["4", "5", "6", "9"], answer: 2 },
      { id: "q5", prompt: "56 ÷ 8 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q6", prompt: "30 ÷ 5 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
      { id: "q7", prompt: "45 ÷ 9 = ?", choices: ["4", "5", "6", "7"], answer: 1 },
      { id: "q8", prompt: "32 ÷ 4 = ?", choices: ["6", "7", "8", "9"], answer: 2 },
      { id: "q9", prompt: "40 apples shared equally between 8 bags. Each bag has...", choices: ["4", "5", "6", "8"], answer: 1 },
      { id: "q10", prompt: "63 ÷ 7 = ?", choices: ["7", "8", "9", "10"], answer: 2 },
      { id: "q11", prompt: "Which equation is in the same fact family as 4 × 6 = 24?", choices: ["24 ÷ 3", "24 ÷ 4", "24 ÷ 8", "24 ÷ 12"], answer: 1 },
      { id: "q12", prompt: "72 ÷ 8 = ?", choices: ["7", "8", "9", "10"], answer: 2 },
      { id: "q13", prompt: "If you have 0 grapes and put them in 5 groups, each group has...", choices: ["0", "1", "5", "50"], answer: 0 },
    ],
  },
  {
    id: "g3-math-fractions",
    subjectId: "math",
    level: "grade3",
    title: "Fractions",
    description: "Understand halves, thirds, fourths, and more.",
    emoji: "🍕",
    questions: [
      { id: "q1", prompt: "A pizza is cut into 4 equal slices. You eat 1. What fraction did you eat?", choices: ["1/2", "1/3", "1/4", "4/1"], answer: 2 },
      { id: "q2", prompt: "Which fraction is greater: 1/2 or 1/4?", choices: ["1/4", "1/2", "They are equal", "Can't tell"], answer: 1, explanation: "The larger the denominator, the smaller the piece. 1/2 > 1/4." },
      { id: "q3", prompt: "What is 2/4 equivalent to?", choices: ["1/4", "1/3", "1/2", "2/3"], answer: 2 },
      { id: "q4", prompt: "A pie is cut into 8 equal pieces. 3 are eaten. What fraction is left?", choices: ["3/8", "5/8", "3/5", "5/3"], answer: 1 },
      { id: "q5", prompt: "Which fraction is CLOSEST to 1 whole?", choices: ["1/4", "1/3", "2/3", "3/4"], answer: 3 },
      { id: "q6", prompt: "3/3 equals...", choices: ["0", "1/3", "1", "3"], answer: 2, explanation: "Any fraction where the top and bottom are the same equals 1 whole." },
      { id: "q7", prompt: "A number line goes from 0 to 1. Where does 1/2 go?", choices: ["at 0", "at the middle", "at 1", "past 1"], answer: 1 },
      { id: "q8", prompt: "Which is less than 1/2?", choices: ["2/3", "3/4", "1/3", "5/8"], answer: 2 },
      { id: "q9", prompt: "A ribbon is 6/6 long. What whole number does that equal?", choices: ["0", "1/6", "1", "6"], answer: 2 },
      { id: "q10", prompt: "Order these from smallest to largest: 1/4, 1/2, 1/3", choices: ["1/4, 1/3, 1/2", "1/2, 1/3, 1/4", "1/3, 1/4, 1/2", "1/4, 1/2, 1/3"], answer: 0 },
    ],
  },
  {
    id: "g3-math-rounding",
    subjectId: "math",
    level: "grade3",
    title: "Rounding Numbers",
    description: "Round to the nearest 10 and 100.",
    emoji: "🎯",
    questions: [
      { id: "q1", prompt: "Round 47 to the nearest 10.", choices: ["40", "45", "50", "47"], answer: 2, explanation: "47 is closer to 50 than 40. Look at the ones digit: 7 ≥ 5, so round up." },
      { id: "q2", prompt: "Round 83 to the nearest 10.", choices: ["70", "80", "90", "85"], answer: 1 },
      { id: "q3", prompt: "Round 245 to the nearest 100.", choices: ["200", "240", "250", "300"], answer: 0, explanation: "The tens digit is 4 (less than 5), so round down to 200." },
      { id: "q4", prompt: "Round 762 to the nearest 100.", choices: ["700", "760", "770", "800"], answer: 3 },
      { id: "q5", prompt: "Round 35 to the nearest 10.", choices: ["30", "35", "40", "50"], answer: 2, explanation: "When the ones digit is 5, round UP. So 35 → 40." },
      { id: "q6", prompt: "Which number rounds to 500?", choices: ["439", "451", "545", "560"], answer: 1 },
      { id: "q7", prompt: "A school has 478 students. To the nearest 100, about how many?", choices: ["400", "470", "480", "500"], answer: 3 },
      { id: "q8", prompt: "Round 614 to the nearest 10.", choices: ["600", "610", "620", "614"], answer: 1 },
      { id: "q9", prompt: "Round 95 to the nearest 10.", choices: ["80", "90", "95", "100"], answer: 3 },
      { id: "q10", prompt: "Which number rounds to 300 when rounded to the nearest 100?", choices: ["249", "351", "250", "199"], answer: 2, explanation: "250 is exactly halfway — it rounds up to 300." },
    ],
  },
  {
    id: "g3-math-area",
    subjectId: "math",
    level: "grade3",
    title: "Area & Perimeter",
    description: "Measure the space inside and around shapes.",
    emoji: "📐",
    questions: [
      { id: "q1", prompt: "A rectangle is 4 cm long and 3 cm wide. What is its area?", choices: ["7 cm²", "12 cm²", "14 cm²", "24 cm²"], answer: 1, explanation: "Area = length × width = 4 × 3 = 12 cm²." },
      { id: "q2", prompt: "A square has sides of 5 cm. What is its perimeter?", choices: ["10 cm", "15 cm", "20 cm", "25 cm"], answer: 2, explanation: "Perimeter = 4 × side = 4 × 5 = 20 cm." },
      { id: "q3", prompt: "Perimeter is...", choices: ["the space inside a shape", "the distance around a shape", "height × width", "the number of sides"], answer: 1 },
      { id: "q4", prompt: "A garden is 6 m long and 2 m wide. What is the area?", choices: ["8 m²", "10 m²", "12 m²", "16 m²"], answer: 2 },
      { id: "q5", prompt: "A rectangle has an area of 20 cm² and a length of 5 cm. What is the width?", choices: ["2 cm", "4 cm", "10 cm", "15 cm"], answer: 1 },
      { id: "q6", prompt: "What is the area of a rectangle that is 8 units × 3 units?", choices: ["11 units²", "22 units²", "24 units²", "48 units²"], answer: 2 },
      { id: "q7", prompt: "A square room has 9 square tiles along each side. How many tiles cover the floor?", choices: ["18", "36", "72", "81"], answer: 3 },
      { id: "q8", prompt: "A path is 10 m long and 1 m wide. What is its area?", choices: ["5 m²", "10 m²", "11 m²", "100 m²"], answer: 1 },
      { id: "q9", prompt: "What unit is used to measure area?", choices: ["cm", "cm²", "cm³", "m"], answer: 1 },
      { id: "q10", prompt: "Two rectangles each have an area of 12 cm². They must be the same shape.", choices: ["True — area determines shape", "False — they can have different lengths and widths", "Only true if they are squares", "Only true for rectangles"], answer: 1 },
    ],
  },

  // -------- SCIENCE --------
  {
    id: "g3-sci-lifecycle",
    subjectId: "science",
    level: "grade3",
    title: "Life Cycles",
    description: "How plants and animals grow and change.",
    emoji: "🦋",
    questions: [
      { id: "q1", prompt: "What are the 4 stages of a butterfly's life cycle in order?", choices: ["egg, caterpillar, cocoon, butterfly", "egg, pupa, larva, butterfly", "larva, egg, pupa, adult", "cocoon, egg, larva, adult"], answer: 0 },
      { id: "q2", prompt: "A frog's life cycle goes: egg → tadpole → froglet → ?", choices: ["caterpillar", "pupa", "adult frog", "larva"], answer: 2 },
      { id: "q3", prompt: "What do we call the stage when a caterpillar is inside a chrysalis?", choices: ["larva", "pupa", "egg", "nymph"], answer: 1 },
      { id: "q4", prompt: "Which plant part contains the seed?", choices: ["leaf", "root", "stem", "fruit"], answer: 3 },
      { id: "q5", prompt: "A complete change in body form during a life cycle is called...", choices: ["hibernation", "metamorphosis", "germination", "migration"], answer: 1 },
      { id: "q6", prompt: "A grasshopper's life cycle has 3 stages: egg, nymph, adult. This is called...", choices: ["complete metamorphosis", "incomplete metamorphosis", "germination", "pollination"], answer: 1 },
      { id: "q7", prompt: "Which of the following shows plant germination?", choices: ["a leaf turning orange", "a seed sprouting into a seedling", "a flower making pollen", "roots soaking up water"], answer: 1 },
      { id: "q8", prompt: "Animals that lay eggs include...", choices: ["only birds", "only fish", "birds and reptiles and fish", "all animals"], answer: 2 },
      { id: "q9", prompt: "What is the first stage of a butterfly's life cycle?", choices: ["larva", "pupa", "egg", "adult"], answer: 2 },
      { id: "q10", prompt: "Seeds need ___ and ___ to germinate.", choices: ["light and wind", "water and warmth", "soil and insects", "cold and ice"], answer: 1 },
    ],
  },
  {
    id: "g3-sci-ecosystems",
    subjectId: "science",
    level: "grade3",
    title: "Ecosystems & Food Chains",
    description: "How living things depend on each other.",
    emoji: "🌿",
    questions: [
      { id: "q1", prompt: "In a food chain, what do plants use to make their own food?", choices: ["other animals", "sunlight", "meat", "rocks"], answer: 1 },
      { id: "q2", prompt: "A food chain starts with a...", choices: ["predator", "carnivore", "producer", "decomposer"], answer: 2, explanation: "Producers (plants) capture energy from the sun — they're always first." },
      { id: "q3", prompt: "What do decomposers do?", choices: ["eat plants", "eat animals", "break down dead things into soil", "make food from sunlight"], answer: 2 },
      { id: "q4", prompt: "In the chain: grass → rabbit → fox, the fox is a...", choices: ["producer", "primary consumer", "secondary consumer", "decomposer"], answer: 2 },
      { id: "q5", prompt: "What would most likely happen if all the rabbits disappeared from a meadow?", choices: ["foxes would have more food", "grass would grow less", "foxes would struggle to find food", "plants would die"], answer: 2 },
      { id: "q6", prompt: "An ecosystem includes...", choices: ["only living things", "only non-living things", "both living and non-living things", "only animals"], answer: 2 },
      { id: "q7", prompt: "Mushrooms that break down a fallen log are examples of...", choices: ["producers", "predators", "consumers", "decomposers"], answer: 3 },
      { id: "q8", prompt: "Which shows a correct food chain?", choices: ["fox → rabbit → grass", "grass → rabbit → fox", "rabbit → fox → grass", "sun → fox → grass"], answer: 1 },
      { id: "q9", prompt: "An animal that eats only meat is a...", choices: ["herbivore", "omnivore", "carnivore", "producer"], answer: 2 },
      { id: "q10", prompt: "Why do food chains always start with a plant?", choices: ["plants taste best", "plants can make their own food using sunlight", "animals cannot eat plants", "plants move fast"], answer: 1 },
    ],
  },
  {
    id: "g3-sci-matter",
    subjectId: "science",
    level: "grade3",
    title: "States of Matter",
    description: "Solids, liquids, gases, and how they change.",
    emoji: "⚗️",
    questions: [
      { id: "q1", prompt: "What are the three common states of matter?", choices: ["hot, cold, warm", "solid, liquid, gas", "rock, water, air", "ice, water, steam"], answer: 1 },
      { id: "q2", prompt: "When liquid water turns into ice it is called...", choices: ["melting", "evaporation", "freezing", "condensation"], answer: 2 },
      { id: "q3", prompt: "When ice turns into liquid water it is called...", choices: ["freezing", "melting", "boiling", "evaporation"], answer: 1 },
      { id: "q4", prompt: "Which property describes how heavy something is?", choices: ["volume", "mass", "texture", "color"], answer: 1 },
      { id: "q5", prompt: "A gas...", choices: ["has a definite shape and volume", "has a definite shape but not volume", "has no definite shape or volume", "is always invisible"], answer: 2 },
      { id: "q6", prompt: "Steam is water in which state?", choices: ["solid", "liquid", "gas", "plasma"], answer: 2 },
      { id: "q7", prompt: "What happens to most solids when they are heated?", choices: ["they freeze", "they turn into liquid", "they disappear", "they get heavier"], answer: 1 },
      { id: "q8", prompt: "A liquid...", choices: ["has a definite shape", "takes the shape of its container", "always floats", "cannot be poured"], answer: 1 },
      { id: "q9", prompt: "Which is an example of a solid?", choices: ["juice", "air", "rock", "steam"], answer: 2 },
      { id: "q10", prompt: "When liquid water evaporates, it becomes...", choices: ["ice", "a gas", "heavier", "a rock"], answer: 1 },
    ],
  },
  {
    id: "g3-sci-forces",
    subjectId: "science",
    level: "grade3",
    title: "Forces & Motion",
    description: "Pushes, pulls, and how objects move.",
    emoji: "🚀",
    questions: [
      { id: "q1", prompt: "A force is...", choices: ["always a push", "a push or a pull", "only made by machines", "only gravity"], answer: 1 },
      { id: "q2", prompt: "What force pulls objects toward Earth?", choices: ["magnetism", "friction", "gravity", "electricity"], answer: 2 },
      { id: "q3", prompt: "Friction is a force that...", choices: ["speeds things up", "pulls things down", "slows things down", "pushes things sideways"], answer: 2 },
      { id: "q4", prompt: "Which surface would create the MOST friction?", choices: ["ice", "sandpaper", "smooth glass", "polished wood"], answer: 1 },
      { id: "q5", prompt: "When two equal forces push in opposite directions, the object...", choices: ["speeds up", "slows down", "does not move", "spins in circles"], answer: 2 },
      { id: "q6", prompt: "A ball rolling across the floor slows down because of...", choices: ["gravity", "friction", "magnets", "wind"], answer: 1 },
      { id: "q7", prompt: "Which of these uses a magnet?", choices: ["a paper towel", "a rubber eraser", "a compass", "a glass of water"], answer: 2 },
      { id: "q8", prompt: "Magnets attract objects made of...", choices: ["plastic", "iron and steel", "wood", "rubber"], answer: 1 },
      { id: "q9", prompt: "What happens when you apply a larger force to push an object?", choices: ["it moves slower", "it moves faster", "it stays still", "it shrinks"], answer: 1 },
      { id: "q10", prompt: "Two magnets facing north pole to north pole will...", choices: ["attract each other", "repel each other", "stick together", "spin in circles"], answer: 1 },
    ],
  },

  // -------- HISTORY --------
  {
    id: "g3-hist-america",
    subjectId: "history",
    level: "grade3",
    title: "American Symbols & Heroes",
    description: "Famous people and symbols of the United States.",
    emoji: "🦅",
    questions: [
      { id: "q1", prompt: "Who was the first President of the United States?", choices: ["Abraham Lincoln", "George Washington", "Benjamin Franklin", "Thomas Jefferson"], answer: 1 },
      { id: "q2", prompt: "Abraham Lincoln helped end...", choices: ["World War I", "the Civil War and slavery", "the American Revolution", "the Great Depression"], answer: 1 },
      { id: "q3", prompt: "The Statue of Liberty is a symbol of...", choices: ["war", "freedom and welcome", "the president", "the military"], answer: 1 },
      { id: "q4", prompt: "Martin Luther King Jr. is famous for...", choices: ["winning a war", "inventing the telephone", "fighting for equal rights for all people", "becoming the first president"], answer: 2 },
      { id: "q5", prompt: "The national bird of the United States is the...", choices: ["robin", "owl", "bald eagle", "dove"], answer: 2 },
      { id: "q6", prompt: "The Declaration of Independence was signed in...", choices: ["1620", "1776", "1865", "1900"], answer: 1 },
      { id: "q7", prompt: "Who wrote the Declaration of Independence?", choices: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"], answer: 2 },
      { id: "q8", prompt: "The American flag has how many stripes?", choices: ["10", "13", "15", "50"], answer: 1, explanation: "13 stripes represent the original 13 colonies." },
      { id: "q9", prompt: "What does the Pledge of Allegiance honor?", choices: ["the president", "the army", "the flag and the country", "the Constitution"], answer: 2 },
      { id: "q10", prompt: "Susan B. Anthony fought for women's right to...", choices: ["go to school", "own land", "vote", "work"], answer: 2 },
      { id: "q11", prompt: "Independence Day is celebrated on...", choices: ["June 4th", "July 4th", "September 17th", "November 11th"], answer: 1 },
      { id: "q12", prompt: "Who led the colonists in fighting for independence from Britain?", choices: ["Abraham Lincoln", "George Washington", "Thomas Edison", "Benjamin Franklin"], answer: 1 },
    ],
  },
  {
    id: "g3-hist-communities",
    subjectId: "history",
    level: "grade3",
    title: "Communities & Government",
    description: "How communities are organized and governed.",
    emoji: "🏛️",
    questions: [
      { id: "q1", prompt: "The leader of a city is usually called the...", choices: ["president", "governor", "mayor", "senator"], answer: 2 },
      { id: "q2", prompt: "The leader of a U.S. state is called the...", choices: ["mayor", "governor", "president", "senator"], answer: 1 },
      { id: "q3", prompt: "The leader of the United States is the...", choices: ["mayor", "governor", "king", "president"], answer: 3 },
      { id: "q4", prompt: "Laws are rules that...", choices: ["only teachers follow", "everyone must follow", "only adults follow", "only the president follows"], answer: 1 },
      { id: "q5", prompt: "What do we call the basic rules that govern the United States?", choices: ["the Declaration", "the Constitution", "the Bill of Laws", "the Pledge"], answer: 1 },
      { id: "q6", prompt: "Citizens can choose their leaders by...", choices: ["writing letters", "voting", "marching", "paying taxes"], answer: 1 },
      { id: "q7", prompt: "A community is...", choices: ["a single family", "only a city", "a group of people who live and work near each other", "a school"], answer: 2 },
      { id: "q8", prompt: "Which is a community helper?", choices: ["a firefighter", "a volcano", "a rainstorm", "a mountain"], answer: 0 },
      { id: "q9", prompt: "The three branches of the U.S. government are legislative, executive, and...", choices: ["local", "judicial", "state", "community"], answer: 1 },
      { id: "q10", prompt: "The U.S. Congress makes...", choices: ["movies", "laws", "food", "weather"], answer: 1 },
    ],
  },

  // -------- GEOGRAPHY --------
  {
    id: "g3-geo-usmap",
    subjectId: "geography",
    level: "grade3",
    title: "U.S. Map & Regions",
    description: "States, capitals, and regions of the United States.",
    emoji: "🗺️",
    questions: [
      { id: "q1", prompt: "How many states are in the United States?", choices: ["48", "49", "50", "52"], answer: 2 },
      { id: "q2", prompt: "What is the capital of the United States?", choices: ["New York City", "Los Angeles", "Washington D.C.", "Chicago"], answer: 2 },
      { id: "q3", prompt: "The largest state by area is...", choices: ["Texas", "California", "Alaska", "Montana"], answer: 2 },
      { id: "q4", prompt: "Hawaii is located...", choices: ["next to California", "in the Pacific Ocean", "in the Atlantic Ocean", "near Florida"], answer: 1 },
      { id: "q5", prompt: "Which ocean is on the East Coast of the United States?", choices: ["Pacific Ocean", "Arctic Ocean", "Indian Ocean", "Atlantic Ocean"], answer: 3 },
      { id: "q6", prompt: "Which ocean is on the West Coast of the United States?", choices: ["Pacific Ocean", "Arctic Ocean", "Indian Ocean", "Atlantic Ocean"], answer: 0 },
      { id: "q7", prompt: "Which of these is a U.S. state?", choices: ["Ontario", "Quebec", "Texas", "Mexico City"], answer: 2 },
      { id: "q8", prompt: "The Great Plains region of the U.S. is known for...", choices: ["mountains", "flat farming land", "tropical forests", "deserts"], answer: 1 },
      { id: "q9", prompt: "What country is north of the United States?", choices: ["Mexico", "Cuba", "Canada", "Brazil"], answer: 2 },
      { id: "q10", prompt: "What country is south of the United States?", choices: ["Canada", "Brazil", "Mexico", "Peru"], answer: 2 },
      { id: "q11", prompt: "The Mississippi River flows from north to south through the...", choices: ["East Coast", "West Coast", "middle of the country", "Great Plains"], answer: 2 },
    ],
  },
  {
    id: "g3-geo-world",
    subjectId: "geography",
    level: "grade3",
    title: "Continents & Oceans",
    description: "Name and locate the 7 continents and 5 oceans.",
    emoji: "🌎",
    questions: [
      { id: "q1", prompt: "How many continents are there?", choices: ["5", "6", "7", "8"], answer: 2 },
      { id: "q2", prompt: "How many oceans are there?", choices: ["4", "5", "6", "7"], answer: 1 },
      { id: "q3", prompt: "The largest continent is...", choices: ["Africa", "North America", "Asia", "Europe"], answer: 2 },
      { id: "q4", prompt: "The smallest continent is...", choices: ["Europe", "Australia", "Antarctica", "South America"], answer: 1 },
      { id: "q5", prompt: "Which continent is mostly covered by ice?", choices: ["Africa", "Australia", "Antarctica", "Europe"], answer: 2 },
      { id: "q6", prompt: "The Amazon rainforest is in...", choices: ["Africa", "Asia", "North America", "South America"], answer: 3 },
      { id: "q7", prompt: "What is the largest ocean?", choices: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], answer: 2 },
      { id: "q8", prompt: "Europe and Asia are on the same landmass. Together they are called...", choices: ["Afro-Eurasia", "Eurasia", "The Old World", "The Supercontinent"], answer: 1 },
      { id: "q9", prompt: "The Sahara Desert is in...", choices: ["Asia", "Africa", "Australia", "South America"], answer: 1 },
      { id: "q10", prompt: "Which continent is the United States part of?", choices: ["South America", "Europe", "North America", "Asia"], answer: 2 },
      { id: "q11", prompt: "The Nile River is in...", choices: ["Asia", "Europe", "South America", "Africa"], answer: 3 },
    ],
  },
  {
    id: "g3-geo-maps",
    subjectId: "geography",
    level: "grade3",
    title: "Reading Maps",
    description: "Keys, compass roses, latitude, and longitude.",
    emoji: "🧭",
    questions: [
      { id: "q1", prompt: "The cardinal directions are...", choices: ["up, down, left, right", "north, south, east, west", "front, back, side, top", "positive, negative, zero, one"], answer: 1 },
      { id: "q2", prompt: "A map key (legend) tells you...", choices: ["how old the map is", "what the symbols on the map mean", "who made the map", "the distance between places"], answer: 1 },
      { id: "q3", prompt: "A compass rose shows...", choices: ["the size of a place", "directions on a map", "the weather", "the population"], answer: 1 },
      { id: "q4", prompt: "Lines on a map that run east-west and measure distance from the equator are called...", choices: ["longitudes", "latitudes", "meridians", "borders"], answer: 1 },
      { id: "q5", prompt: "The equator divides Earth into the Northern and...", choices: ["Eastern Hemisphere", "Western Hemisphere", "Southern Hemisphere", "Pacific Hemisphere"], answer: 2 },
      { id: "q6", prompt: "A scale on a map shows you...", choices: ["what colors mean", "how to read directions", "the real distance a map distance represents", "where water is"], answer: 2 },
      { id: "q7", prompt: "If you travel from New York to California, you are traveling...", choices: ["north", "south", "east", "west"], answer: 3 },
      { id: "q8", prompt: "A physical map shows...", choices: ["country borders only", "landforms like mountains and rivers", "only roads", "city populations"], answer: 1 },
      { id: "q9", prompt: "A political map shows...", choices: ["mountains and rivers", "weather patterns", "countries, states, and borders", "wildlife"], answer: 2 },
      { id: "q10", prompt: "The North Pole is at the very...", choices: ["bottom of Earth", "middle of Earth", "top of Earth", "side of Earth"], answer: 2 },
    ],
  },
];
