/** Brainy Buddies - 9th Grade core curriculum activities. */
import type { Activity } from "@/lib/brainy-data";

export const GRADE9_ACTIVITIES: Activity[] = [
  {
    id: "g9-math-algebra-models",
    subjectId: "math",
    level: "grade9",
    title: "Algebra I: Expressions & Models",
    description: "Build and solve equations, inequalities, and exponential models from real situations.",
    emoji: "📊",
    questions: [
      { id: "q1", prompt: "Solve 3(2x - 5) = 4x + 7.", choices: ["x = 7", "x = 9", "x = 11", "x = 22"], answer: 2, explanation: "6x - 15 = 4x + 7, so 2x = 22 and x = 11." },
      { id: "q2", prompt: "Which expression is equivalent to (x + 4)(x - 2)?", choices: ["x² + 2x - 8", "x² - 2x + 8", "x² + 6x - 8", "x² + 2x + 8"], answer: 0 },
      { id: "q3", prompt: "A population starts at 500 and grows 6% each year. Which model fits?", choices: ["500 + 0.06t", "500(0.06)^t", "500(1.06)^t", "506t"], answer: 2 },
      { id: "q4", prompt: "Solve -2x + 5 >= 13.", choices: ["x >= -4", "x <= -4", "x >= 4", "x <= 4"], answer: 1 },
      { id: "q5", prompt: "What is the factored form of x² - 9?", choices: ["(x - 3)²", "(x - 9)(x + 1)", "(x - 3)(x + 3)", "(x + 9)(x - 1)"], answer: 2 },
      { id: "q6", prompt: "Which sequence is arithmetic?", choices: ["2, 4, 8, 16", "5, 9, 13, 17", "1, 4, 9, 16", "3, 6, 12, 24"], answer: 1 },
    ],
  },
  {
    id: "g9-math-functions-coordinate",
    subjectId: "math",
    level: "grade9",
    title: "Functions & Coordinate Geometry",
    description: "Compare function representations and use coordinates to prove geometric relationships.",
    emoji: "📐",
    questions: [
      { id: "q1", prompt: "If f(x) = x² - 3x, what is f(-2)?", choices: ["-10", "-2", "2", "10"], answer: 3 },
      { id: "q2", prompt: "What is the vertex of y = (x - 3)² + 2?", choices: ["(-3, 2)", "(3, 2)", "(2, 3)", "(3, -2)"], answer: 1 },
      { id: "q3", prompt: "Which domain restriction makes f(x) = x² one-to-one?", choices: ["All real numbers", "x >= 0", "x != 0", "x <= 2"], answer: 1 },
      { id: "q4", prompt: "What is the midpoint of (-2, 5) and (6, 1)?", choices: ["(2, 3)", "(4, 6)", "(2, 2)", "(8, 4)"], answer: 0 },
      { id: "q5", prompt: "Lines with slopes 2/3 and -3/2 are...", choices: ["parallel", "perpendicular", "the same line", "both horizontal"], answer: 1 },
      { id: "q6", prompt: "For g(x) = 2x + 5, which value is g⁻¹(11)?", choices: ["2", "3", "6", "8"], answer: 1 },
    ],
  },
  {
    id: "g9-sci-biology-systems",
    subjectId: "science",
    level: "grade9",
    title: "Biology: Cells & Living Systems",
    description: "Explain how cells obtain energy, regulate processes, and organize into living systems.",
    emoji: "🔬",
    questions: [
      { id: "q1", prompt: "What is the main role of ATP in cells?", choices: ["Store genetic information", "Provide usable energy", "Build cell walls", "Carry oxygen in lungs"], answer: 1 },
      { id: "q2", prompt: "Cellular respiration converts energy in glucose into...", choices: ["ATP", "DNA", "sunlight", "nitrogen"], answer: 0 },
      { id: "q3", prompt: "Osmosis is the movement of...", choices: ["water across a selectively permeable membrane", "proteins into DNA", "cells through tissue", "energy without matter"], answer: 0 },
      { id: "q4", prompt: "Which level of organization includes similar cells working together?", choices: ["Organelle", "Tissue", "Organ system", "Organism"], answer: 1 },
      { id: "q5", prompt: "Enzymes speed reactions by...", choices: ["lowering activation energy", "raising the cell's temperature permanently", "creating new atoms", "being consumed as fuel"], answer: 0 },
      { id: "q6", prompt: "Homeostasis helps an organism...", choices: ["maintain stable internal conditions", "stop using energy", "avoid all environmental change", "produce identical offspring only"], answer: 0 },
    ],
  },
  {
    id: "g9-sci-matter-energy",
    subjectId: "science",
    level: "grade9",
    title: "Matter, Reactions & Energy",
    description: "Use atomic structure and conservation laws to reason about matter and energy changes.",
    emoji: "⚛️",
    questions: [
      { id: "q1", prompt: "An element's atomic number equals its number of...", choices: ["protons", "neutrons", "energy levels", "isotopes"], answer: 0 },
      { id: "q2", prompt: "Isotopes of the same element differ in their number of...", choices: ["protons", "neutrons", "valence rules", "chemical symbols"], answer: 1 },
      { id: "q3", prompt: "Why must a chemical equation be balanced?", choices: ["Atoms are conserved", "Products must weigh more", "Every reaction uses oxygen", "Coefficients must all be one"], answer: 0 },
      { id: "q4", prompt: "Which bond forms when atoms share electrons?", choices: ["Ionic", "Covalent", "Nuclear", "Gravitational"], answer: 1 },
      { id: "q5", prompt: "In an endothermic process, the system...", choices: ["absorbs energy", "releases energy", "destroys matter", "loses all motion"], answer: 0 },
      { id: "q6", prompt: "A solution with pH 3 is...", choices: ["acidic", "neutral", "basic", "always pure water"], answer: 0 },
    ],
  },
  {
    id: "g9-hist-modern-world",
    subjectId: "history",
    level: "grade9",
    title: "Revolutions & the Modern World",
    description: "Analyze how political ideas, industry, imperialism, and global conflict reshaped societies.",
    emoji: "🏭",
    questions: [
      { id: "q1", prompt: "Which idea strongly influenced Atlantic revolutions?", choices: ["Natural rights", "Feudal obligation", "Divine right only", "Economic isolation"], answer: 0 },
      { id: "q2", prompt: "Industrialization first accelerated in Britain partly because it had...", choices: ["coal, capital, and transportation networks", "no urban population", "few overseas connections", "a ban on machinery"], answer: 0 },
      { id: "q3", prompt: "One major social effect of industrialization was...", choices: ["rapid urbanization", "the end of wage labor", "the disappearance of cities", "equal wealth for all"], answer: 0 },
      { id: "q4", prompt: "European imperialism in the 1800s was often driven by...", choices: ["resources, markets, and strategic power", "a desire to end trade", "equal partnerships everywhere", "declining technology"], answer: 0 },
      { id: "q5", prompt: "Which factor helped turn a regional crisis into World War I?", choices: ["Alliance systems", "The printing press", "The Silk Road", "Decolonization"], answer: 0 },
      { id: "q6", prompt: "To evaluate a wartime propaganda poster, a historian should examine its...", choices: ["audience, purpose, and context", "color only", "market price", "paper size only"], answer: 0 },
    ],
  },
  {
    id: "g9-geo-development-environment",
    subjectId: "geography",
    level: "grade9",
    title: "Development, Resources & Environment",
    description: "Interpret development patterns and evaluate relationships among people, resources, and climate.",
    emoji: "🌍",
    questions: [
      { id: "q1", prompt: "The Human Development Index combines measures related to...", choices: ["health, education, and income", "longitude, rainfall, and elevation", "exports only", "military size only"], answer: 0 },
      { id: "q2", prompt: "A country's total GDP can rise while many people remain poor because...", choices: ["income may be distributed unevenly", "GDP measures rainfall", "all prices become zero", "population no longer matters"], answer: 0 },
      { id: "q3", prompt: "Desertification is...", choices: ["land degradation in dry regions", "the growth of glaciers", "urban growth near ports", "a shift from farms to forests"], answer: 0 },
      { id: "q4", prompt: "Which practice supports sustainable water use?", choices: ["Efficient irrigation and watershed protection", "Unlimited groundwater pumping", "Removing wetlands", "Paving recharge areas"], answer: 0 },
      { id: "q5", prompt: "A carbon footprint estimates...", choices: ["greenhouse gas emissions linked to an activity", "the size of a shoe", "all natural resources in a country", "distance traveled on foot"], answer: 0 },
      { id: "q6", prompt: "Geographic information systems help users...", choices: ["analyze layered spatial data", "translate every language", "predict events with certainty", "replace all field observations"], answer: 0 },
    ],
  },
  {
    id: "g9-lang-literature-rhetoric",
    subjectId: "language",
    level: "grade9",
    title: "Literature, Rhetoric & Research",
    description: "Interpret complex texts, analyze rhetorical choices, and judge the quality of research evidence.",
    emoji: "📚",
    questions: [
      { id: "q1", prompt: "A theme differs from a topic because a theme...", choices: ["expresses an insight about the topic", "is always one word", "names the main character", "summarizes every event"], answer: 0 },
      { id: "q2", prompt: "Which appeal relies on the speaker's credibility?", choices: ["Ethos", "Pathos", "Logos", "Irony"], answer: 0 },
      { id: "q3", prompt: "An unreliable narrator requires readers to...", choices: ["question the narrator's account", "accept every statement as fact", "ignore characterization", "skip the conclusion"], answer: 0 },
      { id: "q4", prompt: "Which source is strongest for a research claim about climate trends?", choices: ["A peer-reviewed dataset from a scientific agency", "An anonymous comment", "A product advertisement", "A fictional novel"], answer: 0 },
      { id: "q5", prompt: "A well-integrated quotation should include...", choices: ["context and an explanation of its relevance", "no citation", "the entire source", "only a page number"], answer: 0 },
      { id: "q6", prompt: "Dramatic irony occurs when...", choices: ["the audience knows more than a character", "a word imitates a sound", "two lines rhyme", "the narrator states the theme"], answer: 0 },
    ],
  },
  {
    id: "g9-python-algorithms-testing",
    subjectId: "python",
    level: "grade9",
    title: "Python Algorithms & Testing",
    description: "Trace algorithms, reason about complexity, and use tests to improve program reliability.",
    emoji: "💻",
    questions: [
      { id: "q1", prompt: "What is the main purpose of a unit test?", choices: ["Verify one behavior in a small piece of code", "Make code run faster automatically", "Replace all documentation", "Install dependencies"], answer: 0 },
      { id: "q2", prompt: "Binary search requires the input collection to be...", choices: ["sorted", "random", "made only of strings", "stored in a dictionary"], answer: 0 },
      { id: "q3", prompt: "What does Big O notation describe?", choices: ["How resource use grows with input size", "The exact runtime in seconds", "The programming language version", "The number of variable names"], answer: 0 },
      { id: "q4", prompt: "Which result does sorted([3, 1, 2]) return?", choices: ["[3, 1, 2]", "[1, 2, 3]", "[3, 2, 1]", "None"], answer: 1 },
      { id: "q5", prompt: "Why is a base case needed in a recursive function?", choices: ["To stop the recursive calls", "To import the function", "To make every value global", "To hide exceptions"], answer: 0 },
      { id: "q6", prompt: "What is an edge case?", choices: ["An unusual or boundary input worth testing", "A syntax error only", "The first line of every file", "A decorative comment"], answer: 0 },
    ],
  },
];