/**
 * Brainy Buddies — 1st Grade activities.
 * Loaded by brainy-data.ts and merged into the ACTIVITIES list.
 */
import type { Activity } from "@/lib/brainy-data";

export const GRADE1_ACTIVITIES: Activity[] = [
  // -------- MATH (1st Grade) --------
  {
    id: "g1-math-add20",
    subjectId: "math",
    level: "grade1",
    title: "Adding within 20",
    description: "Add numbers up to twenty.",
    emoji: "\u2795",
    questions: [
      { id: "q1", prompt: "6 + 5 = ?", choices: ["10", "11", "12", "13"], answer: 1 },
      { id: "q2", prompt: "7 + 4 = ?", choices: ["10", "11", "12", "13"], answer: 1 },
      { id: "q3", prompt: "8 + 6 = ?", choices: ["13", "14", "15", "16"], answer: 1 },
      { id: "q4", prompt: "9 + 9 = ?", choices: ["16", "17", "18", "19"], answer: 2 },
      { id: "q5", prompt: "10 + 7 = ?", choices: ["15", "16", "17", "18"], answer: 2 },
      { id: "q6", prompt: "12 + 5 = ?", choices: ["16", "17", "18", "19"], answer: 1 },
      { id: "q7", prompt: "11 + 8 = ?", choices: ["18", "19", "20", "21"], answer: 1 },
      { id: "q8", prompt: "You have 6 stickers and find 7 more. How many?", choices: ["12", "13", "14", "15"], answer: 1 },
      { id: "q9", prompt: "3 + 4 + 5 = ?", choices: ["11", "12", "13", "14"], answer: 1 },
      { id: "q10", prompt: "15 + 4 = ?", choices: ["18", "19", "20", "21"], answer: 1 },
      { id: "q11", prompt: "What plus 6 equals 14?", choices: ["6", "7", "8", "9"], answer: 2 },
    ],
  },
  {
    id: "g1-math-sub",
    subjectId: "math",
    level: "grade1",
    title: "Taking Away",
    description: "Subtraction within 20.",
    emoji: "\u2796",
    questions: [
      { id: "q1", prompt: "10 - 4 = ?", choices: ["4", "5", "6", "7"], answer: 2 },
      { id: "q2", prompt: "12 - 5 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q3", prompt: "15 - 7 = ?", choices: ["7", "8", "9", "10"], answer: 1 },
      { id: "q4", prompt: "9 - 3 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
      { id: "q5", prompt: "18 - 9 = ?", choices: ["8", "9", "10", "11"], answer: 1 },
      { id: "q6", prompt: "You had 14 grapes and ate 6. How many left?", choices: ["7", "8", "9", "10"], answer: 1 },
      { id: "q7", prompt: "20 - 10 = ?", choices: ["5", "10", "15", "20"], answer: 1 },
      { id: "q8", prompt: "13 - 8 = ?", choices: ["4", "5", "6", "7"], answer: 1 },
      { id: "q9", prompt: "11 - 4 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q10", prompt: "17 - 9 = ?", choices: ["7", "8", "9", "10"], answer: 1 },
    ],
  },
  {
    id: "g1-math-place",
    subjectId: "math",
    level: "grade1",
    title: "Tens and Ones",
    description: "Place value up to 100.",
    emoji: "\u{1F522}",
    questions: [
      { id: "q1", prompt: "In 34, the tens digit is...", choices: ["3", "4", "30", "34"], answer: 0 },
      { id: "q2", prompt: "In 47, the ones digit is...", choices: ["4", "7", "40", "47"], answer: 1 },
      { id: "q3", prompt: "5 tens and 2 ones make...", choices: ["25", "52", "7", "502"], answer: 1 },
      { id: "q4", prompt: "7 tens = ?", choices: ["7", "17", "70", "77"], answer: 2 },
      { id: "q5", prompt: "Which is bigger?", choices: ["49", "61", "48", "59"], answer: 1 },
      { id: "q6", prompt: "What comes just before 70?", choices: ["60", "69", "71", "79"], answer: 1 },
      { id: "q7", prompt: "What comes just after 89?", choices: ["88", "90", "99", "100"], answer: 1 },
      { id: "q8", prompt: "How many tens in 60?", choices: ["5", "6", "7", "60"], answer: 1 },
      { id: "q9", prompt: "40 + 3 = ?", choices: ["34", "43", "44", "73"], answer: 1 },
      { id: "q10", prompt: "Which number is the smallest?", choices: ["58", "85", "75", "68"], answer: 0 },
    ],
  },
  {
    id: "g1-math-time",
    subjectId: "math",
    level: "grade1",
    title: "Time & Money Basics",
    description: "Tell time to the hour and count coins.",
    emoji: "\u23F0",
    questions: [
      { id: "q1", prompt: "How many minutes in 1 hour?", choices: ["30", "45", "60", "100"], answer: 2 },
      { id: "q2", prompt: "A penny is worth...", choices: ["1 cent", "5 cents", "10 cents", "25 cents"], answer: 0 },
      { id: "q3", prompt: "A nickel is worth...", choices: ["1 cent", "5 cents", "10 cents", "25 cents"], answer: 1 },
      { id: "q4", prompt: "A dime is worth...", choices: ["1 cent", "5 cents", "10 cents", "25 cents"], answer: 2 },
      { id: "q5", prompt: "A quarter is worth...", choices: ["5 cents", "10 cents", "15 cents", "25 cents"], answer: 3 },
      { id: "q6", prompt: "3 dimes = ?", choices: ["3 cents", "15 cents", "30 cents", "50 cents"], answer: 2 },
      { id: "q7", prompt: "How many hours in a day?", choices: ["12", "20", "24", "30"], answer: 2 },
      { id: "q8", prompt: "A clock shows 3 o'clock. The long hand points to...", choices: ["12", "3", "6", "9"], answer: 0 },
      { id: "q9", prompt: "2 quarters = ?", choices: ["25 cents", "50 cents", "75 cents", "100 cents"], answer: 1 },
      { id: "q10", prompt: "How many days in a week?", choices: ["5", "6", "7", "10"], answer: 2 },
    ],
  },

  // -------- SCIENCE (1st Grade) --------
  {
    id: "g1-sci-habitats",
    subjectId: "science",
    level: "grade1",
    title: "Animal Habitats",
    description: "Where animals live and what they need.",
    emoji: "\u{1F438}",
    questions: [
      { id: "q1", prompt: "A polar bear lives in the...", choices: ["desert", "Arctic", "jungle", "ocean floor"], answer: 1 },
      { id: "q2", prompt: "A camel is best suited for the...", choices: ["forest", "desert", "ocean", "snow"], answer: 1 },
      { id: "q3", prompt: "Fish breathe using their...", choices: ["lungs", "gills", "nose", "skin"], answer: 1 },
      { id: "q4", prompt: "A frog lives in/near...", choices: ["sand", "ponds", "clouds", "caves only"], answer: 1 },
      { id: "q5", prompt: "All animals need food, water, and...", choices: ["toys", "shelter", "phones", "music"], answer: 1 },
      { id: "q6", prompt: "Which animal is a mammal?", choices: ["shark", "snake", "dolphin", "eagle"], answer: 2 },
      { id: "q7", prompt: "Reptiles like lizards have...", choices: ["feathers", "fur", "scales", "gills"], answer: 2 },
      { id: "q8", prompt: "A rainforest is...", choices: ["dry and cold", "warm and rainy", "frozen all year", "empty of life"], answer: 1 },
      { id: "q9", prompt: "Birds lay...", choices: ["eggs", "seeds", "shells", "leaves"], answer: 0 },
      { id: "q10", prompt: "An animal that eats only plants is a...", choices: ["carnivore", "herbivore", "omnivore", "recycler"], answer: 1 },
    ],
  },
  {
    id: "g1-sci-body",
    subjectId: "science",
    level: "grade1",
    title: "Our Amazing Body",
    description: "Body parts and staying healthy.",
    emoji: "\u{1F9B7}",
    questions: [
      { id: "q1", prompt: "Your heart pumps...", choices: ["air", "blood", "food", "water only"], answer: 1 },
      { id: "q2", prompt: "You breathe in with your...", choices: ["liver", "lungs", "stomach", "bones"], answer: 1 },
      { id: "q3", prompt: "Bones together make your...", choices: ["muscles", "skeleton", "skin", "brain"], answer: 1 },
      { id: "q4", prompt: "How many bones do adults usually have?", choices: ["around 50", "around 100", "around 200", "around 1000"], answer: 2 },
      { id: "q5", prompt: "To stay healthy, you should...", choices: ["never sleep", "eat fruit and veggies", "only eat candy", "never move"], answer: 1 },
      { id: "q6", prompt: "Brushing your teeth keeps them...", choices: ["dirty", "weak", "clean and strong", "colorful"], answer: 2 },
      { id: "q7", prompt: "You think with your...", choices: ["heart", "brain", "stomach", "feet"], answer: 1 },
      { id: "q8", prompt: "Muscles help you...", choices: ["see", "move", "taste", "hear"], answer: 1 },
      { id: "q9", prompt: "Food gets broken down in your...", choices: ["lungs", "stomach", "ears", "hair"], answer: 1 },
      { id: "q10", prompt: "Kids should sleep about how many hours?", choices: ["2", "5", "10", "20"], answer: 2 },
    ],
  },
  {
    id: "g1-sci-matter",
    subjectId: "science",
    level: "grade1",
    title: "Solid, Liquid, Gas",
    description: "States of matter all around us.",
    emoji: "\u{1F4A7}",
    questions: [
      { id: "q1", prompt: "Ice is a...", choices: ["solid", "liquid", "gas", "plasma"], answer: 0 },
      { id: "q2", prompt: "Water you drink is a...", choices: ["solid", "liquid", "gas", "rock"], answer: 1 },
      { id: "q3", prompt: "Steam from a kettle is a...", choices: ["solid", "liquid", "gas", "crystal"], answer: 2 },
      { id: "q4", prompt: "When ice gets warm it...", choices: ["freezes", "melts", "vanishes", "explodes"], answer: 1 },
      { id: "q5", prompt: "When water gets very cold it...", choices: ["melts", "boils", "freezes", "runs away"], answer: 2 },
      { id: "q6", prompt: "Air around you is mostly a...", choices: ["solid", "liquid", "gas", "flame"], answer: 2 },
      { id: "q7", prompt: "Which keeps its shape on its own?", choices: ["a solid", "a liquid", "a gas", "a cloud"], answer: 0 },
      { id: "q8", prompt: "Liquids take the shape of their...", choices: ["clothes", "container", "name", "sound"], answer: 1 },
      { id: "q9", prompt: "Boiling water turns into...", choices: ["ice", "steam", "sand", "snow"], answer: 1 },
      { id: "q10", prompt: "A rock is a...", choices: ["solid", "liquid", "gas", "rainbow"], answer: 0 },
    ],
  },
  {
    id: "g1-sci-space",
    subjectId: "science",
    level: "grade1",
    title: "Sun, Moon & Stars",
    description: "Day, night, and the sky.",
    emoji: "\u{1F31E}",
    questions: [
      { id: "q1", prompt: "The sun is a...", choices: ["planet", "star", "moon", "comet"], answer: 1 },
      { id: "q2", prompt: "Earth goes around the...", choices: ["moon", "sun", "stars", "clouds"], answer: 1 },
      { id: "q3", prompt: "The moon goes around...", choices: ["the sun", "Earth", "itself only", "Mars"], answer: 1 },
      { id: "q4", prompt: "It's night when our side of Earth faces...", choices: ["the sun", "away from the sun", "sideways", "the moon only"], answer: 1 },
      { id: "q5", prompt: "How long does it take Earth to spin one time?", choices: ["1 hour", "1 day", "1 week", "1 year"], answer: 1 },
      { id: "q6", prompt: "How long does Earth take to go around the sun?", choices: ["1 day", "1 month", "1 year", "100 years"], answer: 2 },
      { id: "q7", prompt: "The moon looks like it changes...", choices: ["color", "shape", "smell", "size"], answer: 1 },
      { id: "q8", prompt: "A shape of the moon you can see is the...", choices: ["square moon", "full moon", "flat moon", "upside-down moon"], answer: 1 },
      { id: "q9", prompt: "Stars look small because they are very...", choices: ["tiny", "close", "far away", "blue"], answer: 2 },
      { id: "q10", prompt: "Astronauts go to space in a...", choices: ["submarine", "rocket", "helicopter", "truck"], answer: 1 },
    ],
  },

  // -------- HISTORY (1st Grade) --------
  {
    id: "g1-hist-then-now",
    subjectId: "history",
    level: "grade1",
    title: "Then and Now",
    description: "How life has changed over time.",
    emoji: "\u{1F570}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "Long ago, people did NOT have...", choices: ["fire", "phones", "food", "clothes"], answer: 1 },
      { id: "q2", prompt: "Long ago, people often traveled by...", choices: ["airplane", "horse", "spaceship", "subway"], answer: 1 },
      { id: "q3", prompt: "A washing tub long ago is like today's...", choices: ["oven", "washing machine", "TV", "car"], answer: 1 },
      { id: "q4", prompt: "A candle long ago is like today's...", choices: ["radio", "lamp", "chair", "clock"], answer: 1 },
      { id: "q5", prompt: "Letters once took days. Today we send...", choices: ["emails", "smoke signals", "pigeons", "newspapers"], answer: 0 },
      { id: "q6", prompt: "A horse-drawn wagon is like today's...", choices: ["car", "phone", "house", "shoe"], answer: 0 },
      { id: "q7", prompt: "Things from long ago are studied as...", choices: ["math", "history", "science", "music"], answer: 1 },
      { id: "q8", prompt: "Old things kept in museums are called...", choices: ["toys", "artifacts", "snacks", "games"], answer: 1 },
      { id: "q9", prompt: "A person who studies the past is a...", choices: ["farmer", "historian", "pilot", "chef"], answer: 1 },
      { id: "q10", prompt: "Compared to long ago, today we have MORE...", choices: ["horses", "technology", "candles", "wagons"], answer: 1 },
    ],
  },
  {
    id: "g1-hist-presidents",
    subjectId: "history",
    level: "grade1",
    title: "Famous Americans",
    description: "People who shaped our country.",
    emoji: "\u{1F396}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "Who was the first U.S. president?", choices: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], answer: 1 },
      { id: "q2", prompt: "Abraham Lincoln helped end...", choices: ["winter", "slavery", "farming", "reading"], answer: 1 },
      { id: "q3", prompt: "Martin Luther King Jr. fought for...", choices: ["games", "civil rights", "trains", "food"], answer: 1 },
      { id: "q4", prompt: "Rosa Parks is known for refusing to give up her...", choices: ["snack", "bus seat", "book", "pencil"], answer: 1 },
      { id: "q5", prompt: "Benjamin Franklin flew a kite to study...", choices: ["wind", "electricity", "rain", "snow"], answer: 1 },
      { id: "q6", prompt: "Neil Armstrong was the first person to walk on the...", choices: ["sun", "moon", "Mars", "ocean floor"], answer: 1 },
      { id: "q7", prompt: "Susan B. Anthony fought for women's right to...", choices: ["run", "vote", "sing", "drive only"], answer: 1 },
      { id: "q8", prompt: "Harriet Tubman helped people escape from...", choices: ["school", "slavery", "snow", "work"], answer: 1 },
      { id: "q9", prompt: "Thomas Edison invented the...", choices: ["airplane", "light bulb", "car", "phone first"], answer: 1 },
      { id: "q10", prompt: "The Wright brothers built the first...", choices: ["car", "airplane", "computer", "radio"], answer: 1 },
    ],
  },
  {
    id: "g1-hist-symbols",
    subjectId: "history",
    level: "grade1",
    title: "American Symbols",
    description: "Symbols and songs of the U.S.",
    emoji: "\u{1F1FA}\u{1F1F8}",
    questions: [
      { id: "q1", prompt: "How many stripes are on the U.S. flag?", choices: ["7", "10", "13", "50"], answer: 2 },
      { id: "q2", prompt: "How many stars are on the U.S. flag?", choices: ["13", "25", "50", "100"], answer: 2 },
      { id: "q3", prompt: "Each star stands for a...", choices: ["state", "city", "president", "river"], answer: 0 },
      { id: "q4", prompt: "The bald eagle is our national...", choices: ["flower", "bird", "mascot", "sport"], answer: 1 },
      { id: "q5", prompt: "The Statue of Liberty was a gift from...", choices: ["England", "France", "Mexico", "Japan"], answer: 1 },
      { id: "q6", prompt: "The Liberty Bell is in...", choices: ["Boston", "Philadelphia", "Chicago", "Miami"], answer: 1 },
      { id: "q7", prompt: "Our national anthem is...", choices: ["Happy Birthday", "The Star-Spangled Banner", "Twinkle Twinkle", "Yankee Doodle"], answer: 1 },
      { id: "q8", prompt: "The president lives in the...", choices: ["Capitol", "White House", "Big House", "Mansion"], answer: 1 },
      { id: "q9", prompt: "The U.S. capital city is...", choices: ["New York", "Washington, D.C.", "Los Angeles", "Boston"], answer: 1 },
      { id: "q10", prompt: "Stripes on the flag stand for the original...", choices: ["13 colonies", "50 states", "presidents", "songs"], answer: 0 },
    ],
  },
  {
    id: "g1-hist-rules",
    subjectId: "history",
    level: "grade1",
    title: "Rules & Citizens",
    description: "Why we have rules and how we help.",
    emoji: "\u2696\u{FE0F}",
    questions: [
      { id: "q1", prompt: "Rules at school help us stay...", choices: ["bored", "safe and fair", "alone", "hungry"], answer: 1 },
      { id: "q2", prompt: "A leader of a city is called the...", choices: ["mayor", "king", "chef", "captain"], answer: 0 },
      { id: "q3", prompt: "People who follow country rules are good...", choices: ["citizens", "tourists", "animals", "trees"], answer: 0 },
      { id: "q4", prompt: "In the U.S., grown-ups choose leaders by...", choices: ["voting", "dancing", "jumping", "singing"], answer: 0 },
      { id: "q5", prompt: "A red traffic light means...", choices: ["go", "slow", "stop", "turn"], answer: 2 },
      { id: "q6", prompt: "At a crosswalk you should...", choices: ["run fast", "look both ways", "close eyes", "jump"], answer: 1 },
      { id: "q7", prompt: "Helping a friend pick up books is being a good...", choices: ["thief", "citizen", "stranger", "runner"], answer: 1 },
      { id: "q8", prompt: "Recycling helps the...", choices: ["trash", "environment", "TV", "phone"], answer: 1 },
      { id: "q9", prompt: "Listening to your teacher is being...", choices: ["silly", "respectful", "sleepy", "loud"], answer: 1 },
      { id: "q10", prompt: "A right we have in the U.S. is to...", choices: ["never share", "speak freely", "break rules", "yell anywhere"], answer: 1 },
    ],
  },

  // -------- GEOGRAPHY (1st Grade) --------
  {
    id: "g1-geo-continents",
    subjectId: "geography",
    level: "grade1",
    title: "Continents & Oceans",
    description: "The biggest pieces of land and water.",
    emoji: "\u{1F30E}",
    questions: [
      { id: "q1", prompt: "How many continents are there?", choices: ["5", "6", "7", "8"], answer: 2 },
      { id: "q2", prompt: "How many oceans are usually named?", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q3", prompt: "The United States is on which continent?", choices: ["Africa", "Asia", "North America", "Europe"], answer: 2 },
      { id: "q4", prompt: "Which is the LARGEST continent?", choices: ["Africa", "Asia", "Europe", "Australia"], answer: 1 },
      { id: "q5", prompt: "Which is the COLDEST continent?", choices: ["Antarctica", "Africa", "Asia", "Australia"], answer: 0 },
      { id: "q6", prompt: "The largest ocean is the...", choices: ["Atlantic", "Pacific", "Indian", "Arctic"], answer: 1 },
      { id: "q7", prompt: "Which continent is Egypt on?", choices: ["Africa", "Asia", "Europe", "North America"], answer: 0 },
      { id: "q8", prompt: "Australia is a country and a...", choices: ["city", "continent", "ocean", "state"], answer: 1 },
      { id: "q9", prompt: "Which is NOT a continent?", choices: ["Africa", "Europe", "Atlantic", "Asia"], answer: 2 },
      { id: "q10", prompt: "South America is south of...", choices: ["Africa", "Asia", "North America", "Antarctica"], answer: 2 },
    ],
  },
  {
    id: "g1-geo-maps",
    subjectId: "geography",
    level: "grade1",
    title: "Reading a Map",
    description: "Compass, keys, and directions.",
    emoji: "\u{1F5FA}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "On most maps, north is at the...", choices: ["top", "bottom", "left", "right"], answer: 0 },
      { id: "q2", prompt: "South is the opposite of...", choices: ["east", "north", "west", "up"], answer: 1 },
      { id: "q3", prompt: "The four main directions are N, S, E, and...", choices: ["O", "W", "P", "Q"], answer: 1 },
      { id: "q4", prompt: "A map key tells you what...", choices: ["symbols mean", "song to sing", "weather to expect", "day it is"], answer: 0 },
      { id: "q5", prompt: "A compass shows you...", choices: ["time", "directions", "music", "words"], answer: 1 },
      { id: "q6", prompt: "A globe is a model of...", choices: ["the moon", "a city", "Earth", "a house"], answer: 2 },
      { id: "q7", prompt: "Blue on a map usually shows...", choices: ["land", "water", "roads", "sky"], answer: 1 },
      { id: "q8", prompt: "Green on a map usually shows...", choices: ["oceans", "forests/land", "cities only", "deserts"], answer: 1 },
      { id: "q9", prompt: "A line that shows a road on a map is in the...", choices: ["title", "key", "sky", "date"], answer: 1 },
      { id: "q10", prompt: "If north is up, then east is to the...", choices: ["left", "right", "down", "top"], answer: 1 },
    ],
  },
  {
    id: "g1-geo-landforms",
    subjectId: "geography",
    level: "grade1",
    title: "Landforms",
    description: "Mountains, rivers, valleys, and more.",
    emoji: "\u26F0\u{FE0F}",
    questions: [
      { id: "q1", prompt: "A very tall landform is a...", choices: ["valley", "mountain", "plain", "lake"], answer: 1 },
      { id: "q2", prompt: "Flat, grassy land is called a...", choices: ["plain", "mountain", "river", "desert"], answer: 0 },
      { id: "q3", prompt: "A low area between mountains is a...", choices: ["hill", "valley", "cliff", "beach"], answer: 1 },
      { id: "q4", prompt: "Water that flows in a long path is a...", choices: ["pond", "river", "lake", "ocean"], answer: 1 },
      { id: "q5", prompt: "A piece of land with water all around is an...", choices: ["island", "valley", "plain", "forest"], answer: 0 },
      { id: "q6", prompt: "Tall, steep rock at the edge of land is a...", choices: ["cliff", "plain", "lake", "pond"], answer: 0 },
      { id: "q7", prompt: "A small mountain is called a...", choices: ["hill", "river", "sea", "island"], answer: 0 },
      { id: "q8", prompt: "A mountain that can erupt is a...", choices: ["volcano", "hill", "plain", "valley"], answer: 0 },
      { id: "q9", prompt: "A dry land with little rain is a...", choices: ["forest", "desert", "swamp", "jungle"], answer: 1 },
      { id: "q10", prompt: "A peninsula is land with water on...", choices: ["no sides", "one side", "three sides", "all sides"], answer: 2 },
    ],
  },
  {
    id: "g1-geo-weather",
    subjectId: "geography",
    level: "grade1",
    title: "Weather & Climate",
    description: "Weather, seasons, and where it happens.",
    emoji: "\u{1F324}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "The weather pattern of a place over many years is its...", choices: ["climate", "snack", "map", "clock"], answer: 0 },
      { id: "q2", prompt: "Places near the equator are usually...", choices: ["cold", "warm", "snowy", "dry only"], answer: 1 },
      { id: "q3", prompt: "Places near the poles are usually...", choices: ["hot", "warm", "very cold", "rainy"], answer: 2 },
      { id: "q4", prompt: "A storm with strong winds and rain near the ocean is a...", choices: ["hurricane", "tornado", "blizzard", "earthquake"], answer: 0 },
      { id: "q5", prompt: "A spinning storm on land is a...", choices: ["tornado", "hurricane", "flood", "drought"], answer: 0 },
      { id: "q6", prompt: "A long time with no rain is a...", choices: ["flood", "drought", "snow", "breeze"], answer: 1 },
      { id: "q7", prompt: "Lots of rain that covers land is a...", choices: ["drought", "flood", "sunshine", "frost"], answer: 1 },
      { id: "q8", prompt: "Snow is most common in which season?", choices: ["summer", "spring", "winter", "fall"], answer: 2 },
      { id: "q9", prompt: "A tool to measure temperature is a...", choices: ["ruler", "thermometer", "clock", "scale"], answer: 1 },
      { id: "q10", prompt: "Wind is moving...", choices: ["water", "air", "rock", "sand"], answer: 1 },
    ],
  },
];
