/** Brainy Buddies - 7th Grade core curriculum activities. */
import type { Activity } from "@/lib/brainy-data";

export const GRADE7_ACTIVITIES: Activity[] = [
  {
    id: "g7-math-proportions",
    subjectId: "math",
    level: "grade7",
    title: "Proportions & Rational Numbers",
    description: "Solve proportional relationships and operate confidently with positive and negative numbers.",
    emoji: "📈",
    questions: [
      { id: "q1", prompt: "If 3 tickets cost $18, how much do 5 tickets cost at the same rate?", choices: ["$24", "$30", "$36", "$90"], answer: 1 },
      { id: "q2", prompt: "What is -8 + 13?", choices: ["-21", "-5", "5", "21"], answer: 2 },
      { id: "q3", prompt: "What is (-6)(-4)?", choices: ["-24", "-10", "10", "24"], answer: 3 },
      { id: "q4", prompt: "Which equation represents a proportional relationship?", choices: ["y = 3x", "y = 3x + 2", "y = x²", "y = 3"], answer: 0 },
      { id: "q5", prompt: "A $40 jacket is discounted 25%. What is the sale price?", choices: ["$10", "$25", "$30", "$35"], answer: 2 },
      { id: "q6", prompt: "What is 3/4 divided by 1/2?", choices: ["3/8", "2/3", "1", "3/2"], answer: 3, explanation: "Multiply by the reciprocal: 3/4 x 2/1 = 6/4 = 3/2." },
      { id: "q7", prompt: "The point (4, 10) lies on y = kx. What is k?", choices: ["0.4", "2", "2.5", "6"], answer: 2 },
      { id: "q8", prompt: "A quantity increases from 50 to 60. What is the percent increase?", choices: ["10%", "20%", "50%", "60%"], answer: 1 },
      { id: "q9", prompt: "What is -2.5 - 3.5?", choices: ["-6", "-1", "1", "6"], answer: 0 },
      { id: "q10", prompt: "On a graph of a proportional relationship, what point must the line pass through?", choices: ["(0, 0)", "(0, 1)", "(1, 0)", "(1, 1)"], answer: 0 },
    ],
  },
  {
    id: "g7-sci-ecosystems",
    subjectId: "science",
    level: "grade7",
    title: "Ecosystems & Natural Selection",
    description: "Analyze energy flow, ecosystem change, inherited traits, and natural selection.",
    emoji: "🧬",
    questions: [
      { id: "q1", prompt: "Which organisms begin most food chains by capturing energy?", choices: ["Consumers", "Decomposers", "Producers", "Predators"], answer: 2 },
      { id: "q2", prompt: "Why is less energy available at higher trophic levels?", choices: ["Energy is used and released as heat", "Plants stop photosynthesis", "Predators create energy", "Matter disappears"], answer: 0 },
      { id: "q3", prompt: "Which is an abiotic factor in an ecosystem?", choices: ["Fungus", "Soil temperature", "Grass", "Bacteria"], answer: 1 },
      { id: "q4", prompt: "What is carrying capacity?", choices: ["The fastest an animal can move", "The largest population an environment can support", "The amount of DNA in a cell", "The number of food chains"], answer: 1 },
      { id: "q5", prompt: "A trait that improves survival and reproduction is called an...", choices: ["adaptation", "ecosystem", "extinction", "equilibrium"], answer: 0 },
      { id: "q6", prompt: "Natural selection acts directly on...", choices: ["acquired wishes", "heritable variation in a population", "all traits equally", "nonliving factors only"], answer: 1 },
      { id: "q7", prompt: "Which relationship benefits both species?", choices: ["Parasitism", "Competition", "Mutualism", "Predation"], answer: 2 },
      { id: "q8", prompt: "What role do decomposers play?", choices: ["They recycle nutrients", "They create sunlight", "They stop all competition", "They remove oxygen"], answer: 0 },
      { id: "q9", prompt: "If a top predator is removed, what can happen first?", choices: ["Prey populations may increase", "All producers disappear immediately", "Energy flow stops", "The climate changes instantly"], answer: 0 },
      { id: "q10", prompt: "Inherited information is stored in...", choices: ["minerals", "DNA", "sunlight", "water"], answer: 1 },
    ],
  },
  {
    id: "g7-hist-medieval-modern",
    subjectId: "history",
    level: "grade7",
    title: "Medieval to Early Modern World",
    description: "Trace how trade, belief, technology, and new ideas transformed societies.",
    emoji: "🏰",
    questions: [
      { id: "q1", prompt: "In feudal Europe, land was exchanged mainly for...", choices: ["military service and loyalty", "factory labor", "voting rights", "paper money"], answer: 0 },
      { id: "q2", prompt: "How did the Silk Road affect societies?", choices: ["It spread goods, ideas, and diseases", "It ended all wars", "It connected only two cities", "It prevented cultural exchange"], answer: 0 },
      { id: "q3", prompt: "The Magna Carta helped establish the idea that...", choices: ["the ruler is subject to law", "kings have unlimited power", "trade should end", "only nobles need laws"], answer: 0 },
      { id: "q4", prompt: "The Renaissance began in Italian cities partly because they...", choices: ["were wealthy centers of trade", "had no contact with other cultures", "banned ancient texts", "had no political competition"], answer: 0 },
      { id: "q5", prompt: "Humanism encouraged scholars to focus on...", choices: ["human potential and classical learning", "ending education", "military rule only", "rejecting all art"], answer: 0 },
      { id: "q6", prompt: "Why was Gutenberg's printing press important?", choices: ["It made books faster and cheaper to produce", "It invented handwriting", "It ended sea travel", "It replaced universities"], answer: 0 },
      { id: "q7", prompt: "One major effect of the Columbian Exchange was...", choices: ["the movement of crops, animals, people, and diseases", "the end of Atlantic travel", "the isolation of continents", "the disappearance of trade"], answer: 0 },
      { id: "q8", prompt: "Which development helped sailors navigate long ocean voyages?", choices: ["Astrolabe and improved maps", "Aqueducts", "Steam engines", "Telegraphs"], answer: 0 },
      { id: "q9", prompt: "A historian comparing conflicting accounts should first consider each author's...", choices: ["perspective and evidence", "handwriting only", "favorite color", "word count"], answer: 0 },
      { id: "q10", prompt: "The Scientific Revolution emphasized...", choices: ["observation and experimentation", "tradition without questions", "ending mathematics", "government by nobles"], answer: 0 },
    ],
  },
  {
    id: "g7-geo-population-economics",
    subjectId: "geography",
    level: "grade7",
    title: "Population, Trade & Development",
    description: "Interpret demographic patterns, global trade, urbanization, and measures of development.",
    emoji: "🧭",
    questions: [
      { id: "q1", prompt: "What is urbanization?", choices: ["Growth of cities and urban populations", "Decline in all trade", "Movement from cities to farms only", "Creation of mountain ranges"], answer: 0 },
      { id: "q2", prompt: "Which is a common pull factor for migration?", choices: ["War", "Drought", "Job opportunities", "Persecution"], answer: 2 },
      { id: "q3", prompt: "What does GDP broadly measure?", choices: ["Value of goods and services produced", "Only population size", "Average rainfall", "Land elevation"], answer: 0 },
      { id: "q4", prompt: "Why do countries specialize in certain products?", choices: ["Resources and skills differ by place", "Every country has identical resources", "Trade is always illegal", "Climate never affects production"], answer: 0 },
      { id: "q5", prompt: "An import is a good that is...", choices: ["brought into a country", "sent out of a country", "never traded", "made only by government"], answer: 0 },
      { id: "q6", prompt: "Which indicator can help compare quality of life?", choices: ["Life expectancy", "Longitude", "Number of borders", "Mountain height"], answer: 0 },
      { id: "q7", prompt: "A population pyramid with a very wide base usually suggests...", choices: ["a high birth rate", "no children", "a shrinking youth population", "equal ages everywhere"], answer: 0 },
      { id: "q8", prompt: "What is a trade-off of rapid urban growth?", choices: ["More jobs but greater pressure on housing and services", "No economic activity", "Fewer transportation needs", "No environmental effects"], answer: 0 },
      { id: "q9", prompt: "A tariff is...", choices: ["a tax on imported goods", "a type of climate", "a migration route", "a population count"], answer: 0 },
      { id: "q10", prompt: "Sustainable development aims to...", choices: ["meet present needs without harming future generations", "use resources as quickly as possible", "stop all economic growth", "eliminate cities"], answer: 0 },
    ],
  },
];