/** Brainy Buddies - 6th Grade core curriculum activities. */
import type { Activity } from "@/lib/brainy-data";

export const GRADE6_ACTIVITIES: Activity[] = [
  {
    id: "g6-math-ratios",
    subjectId: "math",
    level: "grade6",
    title: "Ratios, Rates & Percents",
    description: "Compare quantities, find unit rates, and connect fractions, decimals, and percents.",
    emoji: "📊",
    questions: [
      { id: "q1", prompt: "A recipe uses 2 cups of flour for 3 cups of oats. What is the ratio of flour to oats?", choices: ["2:3", "3:2", "2:5", "3:5"], answer: 0 },
      { id: "q2", prompt: "Five notebooks cost $15. What is the cost per notebook?", choices: ["$2", "$3", "$5", "$10"], answer: 1, explanation: "$15 divided by 5 notebooks is $3 per notebook." },
      { id: "q3", prompt: "Which ratio is equivalent to 4:6?", choices: ["2:3", "3:4", "6:8", "8:10"], answer: 0 },
      { id: "q4", prompt: "What is 25% written as a fraction in simplest form?", choices: ["1/2", "1/3", "1/4", "1/5"], answer: 2 },
      { id: "q5", prompt: "A car travels 180 miles in 3 hours. What is its average rate?", choices: ["30 mph", "60 mph", "90 mph", "540 mph"], answer: 1 },
      { id: "q6", prompt: "What is 0.6 written as a percent?", choices: ["6%", "16%", "60%", "600%"], answer: 2 },
      { id: "q7", prompt: "In a class of 30 students, 18 play a sport. What percent play a sport?", choices: ["40%", "50%", "60%", "80%"], answer: 2 },
      { id: "q8", prompt: "A map scale is 1 inch = 20 miles. How many miles does 3.5 inches represent?", choices: ["23.5", "60", "70", "80"], answer: 2 },
      { id: "q9", prompt: "Which is the better buy?", choices: ["4 pens for $8", "6 pens for $9", "They cost the same per pen", "Not enough information"], answer: 1, explanation: "The unit prices are $2 per pen and $1.50 per pen." },
      { id: "q10", prompt: "What is 15% of 80?", choices: ["8", "12", "15", "20"], answer: 1 },
    ],
  },
  {
    id: "g6-math-number-system",
    subjectId: "math",
    level: "grade6",
    title: "Integers & Rational Numbers",
    description: "Compare, order, and calculate with positive and negative rational numbers.",
    emoji: "➖",
    questions: [
      { id: "q1", prompt: "Which number is greater?", choices: ["-8", "-3", "They are equal", "Cannot be determined"], answer: 1 },
      { id: "q2", prompt: "What is the absolute value of -12?", choices: ["-12", "0", "12", "24"], answer: 2 },
      { id: "q3", prompt: "What is -4 + 9?", choices: ["-13", "-5", "5", "13"], answer: 2 },
      { id: "q4", prompt: "What is 6 - 11?", choices: ["-17", "-5", "5", "17"], answer: 1 },
      { id: "q5", prompt: "What is (-3)(7)?", choices: ["-21", "-10", "10", "21"], answer: 0 },
      { id: "q6", prompt: "What is -24 divided by -6?", choices: ["-4", "-3", "3", "4"], answer: 3 },
      { id: "q7", prompt: "Order from least to greatest: -2, 4, -7, 0", choices: ["-7, -2, 0, 4", "-2, -7, 0, 4", "4, 0, -2, -7", "-7, 0, -2, 4"], answer: 0 },
      { id: "q8", prompt: "A bank balance changes by -$15. What does this mean?", choices: ["$15 was deposited", "$15 was withdrawn", "The balance is $15", "Nothing changed"], answer: 1 },
      { id: "q9", prompt: "Which value is farthest from zero?", choices: ["-6", "5", "2", "-1"], answer: 0 },
      { id: "q10", prompt: "Which rational number lies between -1 and 0?", choices: ["-3/2", "-1/2", "1/2", "1"], answer: 1 },
    ],
  },
  {
    id: "g6-math-expressions-equations",
    subjectId: "math",
    level: "grade6",
    title: "Expressions & Equations",
    description: "Evaluate expressions, combine terms, and solve one-step equations.",
    emoji: "🧩",
    questions: [
      { id: "q1", prompt: "Evaluate 3x + 5 when x = 4.", choices: ["12", "17", "20", "32"], answer: 1 },
      { id: "q2", prompt: "Simplify 4a + 2a.", choices: ["6", "6a", "8a", "4a²"], answer: 1 },
      { id: "q3", prompt: "Which expression is equivalent to 3(x + 4)?", choices: ["3x + 4", "3x + 7", "3x + 12", "7x"], answer: 2 },
      { id: "q4", prompt: "Solve 2x + 7 = 19.", choices: ["x = 5", "x = 6", "x = 12", "x = 13"], answer: 1 },
      { id: "q5", prompt: "Solve y/5 = 3.", choices: ["y = 8", "y = 10", "y = 15", "y = 20"], answer: 2 },
      { id: "q6", prompt: "Solve 5n - 2 = 18.", choices: ["n = 3", "n = 4", "n = 5", "n = 10"], answer: 1 },
      { id: "q7", prompt: "Which inequality is equivalent to x + 3 > 8?", choices: ["x > 5", "x < 5", "x > 11", "x < 11"], answer: 0 },
      { id: "q8", prompt: "Which expression means 'five less than twice a number n'?", choices: ["5 - 2n", "2(n - 5)", "2n - 5", "5n - 2"], answer: 2 },
      { id: "q9", prompt: "Which value makes 4 + m = 13 true?", choices: ["7", "8", "9", "17"], answer: 2 },
      { id: "q10", prompt: "A number p is multiplied by 6 to get 42. What is p?", choices: ["6", "7", "8", "36"], answer: 1 },
    ],
  },
  {
    id: "g6-math-geometry",
    subjectId: "math",
    level: "grade6",
    title: "Area, Surface Area & Volume",
    description: "Find measurements of polygons and rectangular prisms.",
    emoji: "📐",
    questions: [
      { id: "q1", prompt: "What is the area of a triangle with base 8 cm and height 5 cm?", choices: ["13 cm²", "20 cm²", "40 cm²", "80 cm²"], answer: 1 },
      { id: "q2", prompt: "What is the area of a parallelogram with base 7 m and height 4 m?", choices: ["11 m²", "14 m²", "22 m²", "28 m²"], answer: 3 },
      { id: "q3", prompt: "What is the volume of a 3 by 4 by 5 rectangular prism?", choices: ["12", "20", "47", "60"], answer: 3 },
      { id: "q4", prompt: "A cube has side length 3 cm. What is its surface area?", choices: ["9 cm²", "18 cm²", "27 cm²", "54 cm²"], answer: 3 },
      { id: "q5", prompt: "Which formula gives the area of a triangle?", choices: ["bh", "1/2 bh", "2b + 2h", "b + h"], answer: 1 },
      { id: "q6", prompt: "A prism is 2.5 m long, 2 m wide, and 3 m high. What is its volume?", choices: ["7.5 m³", "10 m³", "15 m³", "18 m³"], answer: 2 },
      { id: "q7", prompt: "A net is...", choices: ["a 2D pattern that folds into a 3D figure", "the volume inside a prism", "a curved line", "a type of angle"], answer: 0 },
      { id: "q8", prompt: "An irregular polygon can often be measured by...", choices: ["guessing its area", "decomposing it into familiar shapes", "adding only its side lengths", "multiplying every side"], answer: 1 },
      { id: "q9", prompt: "Which unit is appropriate for volume?", choices: ["cm", "cm²", "cm³", "degrees"], answer: 2 },
      { id: "q10", prompt: "A rectangle has area 48 ft² and width 6 ft. What is its length?", choices: ["7 ft", "8 ft", "12 ft", "42 ft"], answer: 1 },
    ],
  },
  {
    id: "g6-math-statistics",
    subjectId: "math",
    level: "grade6",
    title: "Statistics & Data Displays",
    description: "Describe distributions using center, spread, and visual displays.",
    emoji: "📊",
    questions: [
      { id: "q1", prompt: "Which is a statistical question?", choices: ["How old am I?", "How many minutes do students in our class read each day?", "What is 8 + 7?", "Is today Monday?"], answer: 1 },
      { id: "q2", prompt: "Find the mean of 4, 6, 8, and 10.", choices: ["6", "7", "8", "28"], answer: 1 },
      { id: "q3", prompt: "Find the median of 2, 5, 7, 9, 12.", choices: ["5", "7", "9", "12"], answer: 1 },
      { id: "q4", prompt: "What is the range of 3, 8, 10, and 14?", choices: ["6", "10", "11", "17"], answer: 2 },
      { id: "q5", prompt: "What is the mode of 2, 3, 3, 4, 5?", choices: ["2", "3", "4", "5"], answer: 1 },
      { id: "q6", prompt: "Which display shows each individual data value along a number line?", choices: ["Dot plot", "Circle graph", "Map", "Timeline"], answer: 0 },
      { id: "q7", prompt: "A box plot is especially useful for showing...", choices: ["the five-number summary", "exact words in a survey", "geometric angles", "only the mode"], answer: 0 },
      { id: "q8", prompt: "An outlier is...", choices: ["the middle value", "a value far from the rest of the data", "the most common value", "the total number of values"], answer: 1 },
      { id: "q9", prompt: "Which measure is usually affected most by a very large outlier?", choices: ["Mean", "Median", "Mode", "Sample size"], answer: 0 },
      { id: "q10", prompt: "A small mean absolute deviation tells you the values are generally...", choices: ["clustered near the mean", "all negative", "very far apart", "missing"], answer: 0 },
    ],
  },
  {
    id: "g6-math-coordinate-plane",
    subjectId: "math",
    level: "grade6",
    title: "The Coordinate Plane",
    description: "Plot rational numbers and solve distance problems in four quadrants.",
    emoji: "🗺️",
    questions: [
      { id: "q1", prompt: "In the ordered pair (-3, 5), what is the x-coordinate?", choices: ["-5", "-3", "3", "5"], answer: 1 },
      { id: "q2", prompt: "Which quadrant contains the point (4, -2)?", choices: ["I", "II", "III", "IV"], answer: 3 },
      { id: "q3", prompt: "Which quadrant contains (-6, -1)?", choices: ["I", "II", "III", "IV"], answer: 2 },
      { id: "q4", prompt: "What is the reflection of (3, 2) across the y-axis?", choices: ["(3, -2)", "(-3, 2)", "(-3, -2)", "(2, 3)"], answer: 1 },
      { id: "q5", prompt: "How far apart are (-2, 4) and (5, 4)?", choices: ["3 units", "7 units", "9 units", "20 units"], answer: 1 },
      { id: "q6", prompt: "A point on the y-axis has...", choices: ["x = 0", "y = 0", "x = y", "positive coordinates only"], answer: 0 },
      { id: "q7", prompt: "Which point is in Quadrant II?", choices: ["(2, 3)", "(-2, 3)", "(-2, -3)", "(2, -3)"], answer: 1 },
      { id: "q8", prompt: "What is the reflection of (-4, -1) across the x-axis?", choices: ["(4, -1)", "(-4, 1)", "(4, 1)", "(-1, -4)"], answer: 1 },
      { id: "q9", prompt: "The point (0, 0) is called the...", choices: ["axis", "origin", "quadrant", "vertex"], answer: 1 },
      { id: "q10", prompt: "How far is (2, -6) from the x-axis?", choices: ["2 units", "4 units", "6 units", "8 units"], answer: 2 },
    ],
  },
  {
    id: "g6-sci-cells",
    subjectId: "science",
    level: "grade6",
    title: "Cells & Body Systems",
    description: "Explore cell structures, specialized cells, and how body systems work together.",
    emoji: "🔬",
    questions: [
      { id: "q1", prompt: "What is the smallest unit of life?", choices: ["Atom", "Cell", "Organ", "Tissue"], answer: 1 },
      { id: "q2", prompt: "Which organelle controls most cell activities and contains DNA?", choices: ["Nucleus", "Cell wall", "Vacuole", "Cytoplasm"], answer: 0 },
      { id: "q3", prompt: "Which structure is found in plant cells but not animal cells?", choices: ["Cell membrane", "Nucleus", "Chloroplast", "Cytoplasm"], answer: 2 },
      { id: "q4", prompt: "What is the main job of mitochondria?", choices: ["Store DNA", "Release usable energy from food", "Make cell walls", "Carry oxygen"], answer: 1 },
      { id: "q5", prompt: "A group of similar cells working together forms a...", choices: ["tissue", "organism", "system", "molecule"], answer: 0 },
      { id: "q6", prompt: "Which body systems work together to deliver oxygen to cells?", choices: ["Digestive and skeletal", "Respiratory and circulatory", "Nervous and muscular", "Skeletal and integumentary"], answer: 1 },
      { id: "q7", prompt: "Why are red blood cells shaped to have a large surface area?", choices: ["To store food", "To carry more oxygen", "To make hormones", "To digest bacteria"], answer: 1 },
      { id: "q8", prompt: "Which level of organization comes directly after tissue?", choices: ["Cell", "Organ", "Organ system", "Organism"], answer: 1 },
      { id: "q9", prompt: "What regulates what enters and leaves a cell?", choices: ["Cell membrane", "Nucleus", "Mitochondrion", "Ribosome"], answer: 0 },
      { id: "q10", prompt: "Photosynthesis occurs mainly in which organelle?", choices: ["Nucleus", "Chloroplast", "Vacuole", "Mitochondrion"], answer: 1 },
    ],
  },
  {
    id: "g6-sci-matter-atoms",
    subjectId: "science",
    level: "grade6",
    title: "Matter, Atoms & Elements",
    description: "Investigate particles, properties, and how substances are classified.",
    emoji: "⚛️",
    questions: [
      { id: "q1", prompt: "What is the smallest unit of an element that keeps that element's properties?", choices: ["Cell", "Atom", "Molecule", "Crystal"], answer: 1 },
      { id: "q2", prompt: "Which particle has a positive charge?", choices: ["Proton", "Neutron", "Electron", "Photon"], answer: 0 },
      { id: "q3", prompt: "Which particle has a negative charge?", choices: ["Proton", "Neutron", "Electron", "Nucleus"], answer: 2 },
      { id: "q4", prompt: "The atomic number of an element equals its number of...", choices: ["protons", "neutrons", "energy levels", "molecules"], answer: 0 },
      { id: "q5", prompt: "Water, H2O, is a...", choices: ["single atom", "compound", "element", "mixture only"], answer: 1 },
      { id: "q6", prompt: "Which is a mixture?", choices: ["Pure gold", "Oxygen gas", "Salt water", "Distilled water"], answer: 2 },
      { id: "q7", prompt: "Which is a physical change?", choices: ["Iron rusting", "Wood burning", "Ice melting", "Milk souring"], answer: 2 },
      { id: "q8", prompt: "Density is calculated by...", choices: ["mass x volume", "mass / volume", "volume / mass", "mass + volume"], answer: 1 },
      { id: "q9", prompt: "An object has a mass of 20 g and a volume of 5 cm3. What is its density?", choices: ["0.25 g/cm3", "4 g/cm3", "15 g/cm3", "100 g/cm3"], answer: 1 },
      { id: "q10", prompt: "On the periodic table, elements in the same column often have...", choices: ["similar chemical properties", "the same mass", "identical atoms", "the same state of matter"], answer: 0 },
    ],
  },
  {
    id: "g6-sci-forces-energy",
    subjectId: "science",
    level: "grade6",
    title: "Forces, Motion & Energy",
    description: "Connect motion, net force, work, and energy transformations.",
    emoji: "⚡",
    questions: [
      { id: "q1", prompt: "Speed is calculated by...", choices: ["distance / time", "time / distance", "distance x time", "mass / volume"], answer: 0 },
      { id: "q2", prompt: "A runner travels 100 meters in 20 seconds. What is the average speed?", choices: ["2 m/s", "5 m/s", "20 m/s", "80 m/s"], answer: 1 },
      { id: "q3", prompt: "Balanced forces on an object produce a net force of...", choices: ["0 N", "1 N", "10 N", "100 N"], answer: 0 },
      { id: "q4", prompt: "An unbalanced force can change an object's...", choices: ["motion", "chemical identity only", "mass", "number of atoms"], answer: 0 },
      { id: "q5", prompt: "Which object has the most gravitational potential energy?", choices: ["A book on the floor", "A book on a high shelf", "A rolling ball", "A parked bicycle"], answer: 1 },
      { id: "q6", prompt: "Kinetic energy is the energy of...", choices: ["motion", "position", "chemical bonds only", "stored food only"], answer: 0 },
      { id: "q7", prompt: "As a roller coaster moves downhill, gravitational potential energy mainly changes into...", choices: ["nuclear energy", "kinetic energy", "chemical energy", "light energy"], answer: 1 },
      { id: "q8", prompt: "Friction usually acts...", choices: ["in the direction of motion", "opposite the direction of motion", "only upward", "only on magnets"], answer: 1 },
      { id: "q9", prompt: "Work is done on an object when a force...", choices: ["causes it to move through a distance", "touches it without movement", "changes its color", "measures its mass"], answer: 0 },
      { id: "q10", prompt: "A lamp changes electrical energy mainly into...", choices: ["light and thermal energy", "chemical and nuclear energy", "motion only", "gravitational energy"], answer: 0 },
    ],
  },
  {
    id: "g6-sci-earth-systems",
    subjectId: "science",
    level: "grade6",
    title: "Earth Systems & Climate",
    description: "Explore rocks, water, atmosphere, weather, and climate patterns.",
    emoji: "🌎",
    questions: [
      { id: "q1", prompt: "Which Earth system includes all of Earth's water?", choices: ["Atmosphere", "Biosphere", "Geosphere", "Hydrosphere"], answer: 3 },
      { id: "q2", prompt: "Weather describes...", choices: ["short-term atmospheric conditions", "average conditions over decades", "only temperature", "movement of tectonic plates"], answer: 0 },
      { id: "q3", prompt: "Climate describes...", choices: ["today's rainfall", "long-term weather patterns", "one thunderstorm", "daily wind direction"], answer: 1 },
      { id: "q4", prompt: "In the water cycle, liquid water changing to vapor is...", choices: ["condensation", "evaporation", "precipitation", "infiltration"], answer: 1 },
      { id: "q5", prompt: "Clouds form when water vapor cools and...", choices: ["condenses", "evaporates", "melts", "erodes"], answer: 0 },
      { id: "q6", prompt: "Weathering differs from erosion because weathering...", choices: ["breaks rock down in place", "moves sediment", "forms only rivers", "occurs only in deserts"], answer: 0 },
      { id: "q7", prompt: "Sedimentary rock commonly forms when sediments are...", choices: ["compacted and cemented", "melted into magma", "evaporated into gas", "changed only by light"], answer: 0 },
      { id: "q8", prompt: "Metamorphic rock forms mainly through...", choices: ["heat and pressure", "freezing rain", "plant growth", "evaporation"], answer: 0 },
      { id: "q9", prompt: "Most weather occurs in which atmospheric layer?", choices: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], answer: 0 },
      { id: "q10", prompt: "Ocean currents influence climate by...", choices: ["redistributing thermal energy", "stopping all winds", "creating Earth's magnetic field", "preventing evaporation"], answer: 0 },
    ],
  },
  {
    id: "g6-sci-space-gravity",
    subjectId: "science",
    level: "grade6",
    title: "Space, Gravity & the Solar System",
    description: "Explain orbits, seasons, moon phases, and the scale of space.",
    emoji: "🪐",
    questions: [
      { id: "q1", prompt: "What force keeps planets in orbit around the Sun?", choices: ["Friction", "Gravity", "Magnetism", "Electricity"], answer: 1 },
      { id: "q2", prompt: "Earth completes one rotation in about...", choices: ["24 hours", "7 days", "30 days", "365 days"], answer: 0 },
      { id: "q3", prompt: "Earth completes one revolution around the Sun in about...", choices: ["24 hours", "30 days", "365 days", "10 years"], answer: 2 },
      { id: "q4", prompt: "Earth's seasons are mainly caused by...", choices: ["changing distance from the Sun", "Earth's tilted axis as it revolves", "the Moon's phases", "daily rotation"], answer: 1 },
      { id: "q5", prompt: "Moon phases occur because we see different portions of the Moon's...", choices: ["sunlit half", "dark material", "changing shape", "cloud cover"], answer: 0 },
      { id: "q6", prompt: "A solar eclipse occurs when...", choices: ["Earth is between the Sun and Moon", "the Moon is between the Sun and Earth", "the Sun is between Earth and Moon", "Mars blocks the Sun"], answer: 1 },
      { id: "q7", prompt: "A light-year measures...", choices: ["time", "distance", "brightness", "mass"], answer: 1 },
      { id: "q8", prompt: "Which planets are called the gas or ice giants?", choices: ["Mercury through Mars", "Jupiter through Neptune", "Earth and Mars only", "Venus and Earth only"], answer: 1 },
      { id: "q9", prompt: "Our solar system is located in the...", choices: ["Andromeda Galaxy", "Milky Way Galaxy", "Orion Nebula only", "Alpha Centauri system"], answer: 1 },
      { id: "q10", prompt: "Why do astronauts weigh less on the Moon?", choices: ["They lose mass", "The Moon has weaker gravity", "Space suits make them lighter", "The Moon has no gravity"], answer: 1 },
    ],
  },
  {
    id: "g6-hist-ancient",
    subjectId: "history",
    level: "grade6",
    title: "Ancient Civilizations",
    description: "Study the rivers, ideas, governments, and achievements that shaped early societies.",
    emoji: "🏺",
    questions: [
      { id: "q1", prompt: "Why did many early civilizations develop near rivers?", choices: ["Rivers blocked all travel", "Rivers provided water and fertile soil", "Rivers prevented farming", "Rivers made the climate colder"], answer: 1 },
      { id: "q2", prompt: "Mesopotamia developed between which two rivers?", choices: ["Nile and Congo", "Tigris and Euphrates", "Indus and Ganges", "Yellow and Yangtze"], answer: 1 },
      { id: "q3", prompt: "What writing system did ancient Egyptians use?", choices: ["Cuneiform", "Hieroglyphics", "Latin", "Sanskrit"], answer: 1 },
      { id: "q4", prompt: "Hammurabi is best known for...", choices: ["a written code of laws", "inventing democracy", "building the Great Wall", "discovering America"], answer: 0 },
      { id: "q5", prompt: "In ancient Athens, citizens participated in an early form of...", choices: ["democracy", "feudalism", "communism", "absolute monarchy"], answer: 0 },
      { id: "q6", prompt: "The Roman Republic influenced modern government through the idea of...", choices: ["elected representatives", "pharaohs", "city-states without laws", "rule by one emperor only"], answer: 0 },
      { id: "q7", prompt: "Which achievement is associated with the Indus Valley civilization?", choices: ["Planned cities and drainage systems", "Roman aqueducts", "Mayan calendars", "Viking longships"], answer: 0 },
      { id: "q8", prompt: "The Silk Road was important because it...", choices: ["connected regions for trade and cultural exchange", "was used only by soldiers", "surrounded Rome", "carried water to farms"], answer: 0 },
      { id: "q9", prompt: "Which Chinese philosophy emphasized respect, duty, and education?", choices: ["Confucianism", "Humanism", "Feudalism", "Mercantilism"], answer: 0 },
      { id: "q10", prompt: "What is a primary source?", choices: ["A modern textbook", "Evidence created during the time being studied", "A fictional story", "A summary written centuries later"], answer: 1 },
    ],
  },
  {
    id: "g6-geo-human-physical",
    subjectId: "geography",
    level: "grade6",
    title: "Physical & Human Geography",
    description: "Connect landforms, climate, resources, migration, and the ways people shape places.",
    emoji: "🌍",
    questions: [
      { id: "q1", prompt: "Which is an example of physical geography?", choices: ["Languages spoken", "Mountain ranges", "Population density", "National borders"], answer: 1 },
      { id: "q2", prompt: "Which is an example of human geography?", choices: ["River valleys", "Climate zones", "Settlement patterns", "Tectonic plates"], answer: 2 },
      { id: "q3", prompt: "Lines of latitude measure distance...", choices: ["east or west of the Prime Meridian", "north or south of the Equator", "above sea level", "between time zones"], answer: 1 },
      { id: "q4", prompt: "What is population density?", choices: ["The total land area", "The number of people per unit of area", "The birth rate only", "The number of cities"], answer: 1 },
      { id: "q5", prompt: "A reason that pushes people to leave a place is called a...", choices: ["pull factor", "push factor", "trade barrier", "natural resource"], answer: 1 },
      { id: "q6", prompt: "Which resource is renewable?", choices: ["Coal", "Oil", "Solar energy", "Natural gas"], answer: 2 },
      { id: "q7", prompt: "A rain shadow commonly forms on which side of a mountain?", choices: ["Windward", "Leeward", "Northern only", "Coastal only"], answer: 1 },
      { id: "q8", prompt: "Why are many large cities located near coasts or rivers?", choices: ["Easier trade and transportation", "No risk of flooding", "Colder weather everywhere", "Fewer natural resources"], answer: 0 },
      { id: "q9", prompt: "A region sharing language, religion, or traditions is a...", choices: ["physical region", "cultural region", "climate zone", "watershed"], answer: 1 },
      { id: "q10", prompt: "What does a map scale help you determine?", choices: ["Actual distance", "Population age", "Climate history", "Political leadership"], answer: 0 },
    ],
  },
];