/**
 * Brainy Buddies — Kindergarten activities.
 * Loaded by brainy-data.ts and merged into the ACTIVITIES list.
 */
import type { Activity } from "@/lib/brainy-data";

export const KINDERGARTEN_ACTIVITIES: Activity[] = [
  // -------- MATH (Kindergarten) --------
  {
    id: "k-math-count",
    subjectId: "math",
    level: "kindergarten",
    title: "Counting 1 to 10",
    description: "Count things and match the number.",
    emoji: "\u{1F522}",
    questions: [
      { id: "q1", prompt: "How many? \u{1F34E}\u{1F34E}\u{1F34E}", choices: ["2", "3", "4", "5"], answer: 1 },
      { id: "q2", prompt: "How many? \u{1F436}\u{1F436}\u{1F436}\u{1F436}\u{1F436}", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q3", prompt: "How many? \u{1F31F}", choices: ["0", "1", "2", "3"], answer: 1 },
      { id: "q4", prompt: "What comes after 6?", choices: ["5", "6", "7", "8"], answer: 2 },
      { id: "q5", prompt: "What comes before 4?", choices: ["2", "3", "5", "6"], answer: 1 },
      { id: "q6", prompt: "How many? \u{1F431}\u{1F431}\u{1F431}\u{1F431}\u{1F431}\u{1F431}\u{1F431}", choices: ["5", "6", "7", "8"], answer: 2 },
      { id: "q7", prompt: "Which number is the biggest?", choices: ["2", "5", "9", "7"], answer: 2 },
      { id: "q8", prompt: "Which number is the smallest?", choices: ["3", "1", "4", "8"], answer: 1 },
      { id: "q9", prompt: "Count: 1, 2, 3, 4, ?", choices: ["5", "6", "3", "7"], answer: 0 },
      { id: "q10", prompt: "How many? \u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}", choices: ["8", "9", "10", "11"], answer: 2 },
      { id: "q11", prompt: "What number is missing? 7, 8, ?, 10", choices: ["6", "9", "11", "12"], answer: 1 },
      { id: "q12", prompt: "How many fingers on one hand?", choices: ["3", "4", "5", "10"], answer: 2 },
    ],
  },
  {
    id: "k-math-shapes",
    subjectId: "math",
    level: "kindergarten",
    title: "Shape Friends",
    description: "Circles, squares, triangles, and rectangles.",
    emoji: "\u{1F537}",
    questions: [
      { id: "q1", prompt: "A ball is shaped like a...", choices: ["square", "circle", "triangle", "star"], answer: 1 },
      { id: "q2", prompt: "A pizza slice is shaped like a...", choices: ["circle", "square", "triangle", "diamond"], answer: 2 },
      { id: "q3", prompt: "How many sides does a triangle have?", choices: ["2", "3", "4", "5"], answer: 1 },
      { id: "q4", prompt: "How many sides does a square have?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q5", prompt: "A book cover is usually a...", choices: ["circle", "rectangle", "triangle", "star"], answer: 1 },
      { id: "q6", prompt: "Which shape has NO corners?", choices: ["square", "triangle", "circle", "rectangle"], answer: 2 },
      { id: "q7", prompt: "How many corners does a square have?", choices: ["2", "3", "4", "5"], answer: 2 },
      { id: "q8", prompt: "A clock face is usually a...", choices: ["square", "triangle", "circle", "diamond"], answer: 2 },
      { id: "q9", prompt: "How many points does a star have? (the usual one)", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q10", prompt: "A door is usually shaped like a...", choices: ["circle", "triangle", "rectangle", "star"], answer: 2 },
    ],
  },
  {
    id: "k-math-add",
    subjectId: "math",
    level: "kindergarten",
    title: "Simple Adding",
    description: "Add small numbers up to 10.",
    emoji: "\u2795",
    questions: [
      { id: "q1", prompt: "1 + 1 = ?", choices: ["1", "2", "3", "4"], answer: 1 },
      { id: "q2", prompt: "2 + 2 = ?", choices: ["2", "3", "4", "5"], answer: 2 },
      { id: "q3", prompt: "3 + 1 = ?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q4", prompt: "2 + 3 = ?", choices: ["4", "5", "6", "7"], answer: 1 },
      { id: "q5", prompt: "4 + 1 = ?", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q6", prompt: "3 + 3 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
      { id: "q7", prompt: "5 + 2 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q8", prompt: "4 + 4 = ?", choices: ["6", "7", "8", "9"], answer: 2 },
      { id: "q9", prompt: "5 + 5 = ?", choices: ["8", "9", "10", "11"], answer: 2 },
      { id: "q10", prompt: "You have 2 cookies. Mom gives you 1 more. How many now?", choices: ["1", "2", "3", "4"], answer: 2 },
      { id: "q11", prompt: "3 birds + 2 birds = ?", choices: ["4", "5", "6", "7"], answer: 1 },
    ],
  },
  {
    id: "k-math-colors",
    subjectId: "math",
    level: "kindergarten",
    title: "Patterns & Colors",
    description: "Spot patterns and matching colors.",
    emoji: "\u{1F308}",
    questions: [
      { id: "q1", prompt: "What comes next? red, blue, red, blue, ?", choices: ["red", "blue", "green", "yellow"], answer: 0 },
      { id: "q2", prompt: "What comes next? yellow, yellow, red, yellow, yellow, ?", choices: ["yellow", "red", "blue", "green"], answer: 1 },
      { id: "q3", prompt: "The sun is mostly which color?", choices: ["yellow", "blue", "green", "purple"], answer: 0 },
      { id: "q4", prompt: "Grass is mostly which color?", choices: ["red", "green", "blue", "pink"], answer: 1 },
      { id: "q5", prompt: "The sky on a clear day is...", choices: ["green", "yellow", "blue", "orange"], answer: 2 },
      { id: "q6", prompt: "What comes next? green, green, orange, green, green, ?", choices: ["green", "orange", "red", "blue"], answer: 1 },
      { id: "q7", prompt: "A stop sign is what color?", choices: ["green", "yellow", "red", "blue"], answer: 2 },
      { id: "q8", prompt: "Mix red and yellow to get...", choices: ["green", "purple", "orange", "pink"], answer: 2 },
      { id: "q9", prompt: "Mix blue and yellow to get...", choices: ["green", "orange", "purple", "black"], answer: 0 },
      { id: "q10", prompt: "A banana is usually what color?", choices: ["red", "yellow", "blue", "green"], answer: 1 },
    ],
  },

  // -------- SCIENCE (Kindergarten) --------
  {
    id: "k-sci-animals",
    subjectId: "science",
    level: "kindergarten",
    title: "Animal Sounds & Babies",
    description: "What animals say and what their babies are called.",
    emoji: "\u{1F436}",
    questions: [
      { id: "q1", prompt: "What sound does a cow make?", choices: ["woof", "meow", "moo", "quack"], answer: 2 },
      { id: "q2", prompt: "What sound does a duck make?", choices: ["moo", "quack", "oink", "baa"], answer: 1 },
      { id: "q3", prompt: "A baby dog is called a...", choices: ["kitten", "puppy", "calf", "foal"], answer: 1 },
      { id: "q4", prompt: "A baby cat is called a...", choices: ["puppy", "kitten", "chick", "cub"], answer: 1 },
      { id: "q5", prompt: "Which animal can fly?", choices: ["fish", "bird", "frog", "horse"], answer: 1 },
      { id: "q6", prompt: "What sound does a sheep make?", choices: ["baa", "moo", "meow", "oink"], answer: 0 },
      { id: "q7", prompt: "A baby chicken is a...", choices: ["duckling", "chick", "colt", "joey"], answer: 1 },
      { id: "q8", prompt: "Which animal lives in water?", choices: ["cow", "fish", "dog", "horse"], answer: 1 },
      { id: "q9", prompt: "Which animal has feathers?", choices: ["dog", "bird", "cat", "pig"], answer: 1 },
      { id: "q10", prompt: "A baby cow is called a...", choices: ["calf", "kid", "foal", "piglet"], answer: 0 },
      { id: "q11", prompt: "Which animal hops?", choices: ["snake", "frog", "fish", "snail"], answer: 1 },
    ],
  },
  {
    id: "k-sci-weather",
    subjectId: "science",
    level: "kindergarten",
    title: "Weather & Seasons",
    description: "Sunny, rainy, snowy, and the four seasons.",
    emoji: "\u26C5",
    questions: [
      { id: "q1", prompt: "What falls from clouds when it rains?", choices: ["snow", "water", "sand", "leaves"], answer: 1 },
      { id: "q2", prompt: "Which season has snow?", choices: ["summer", "spring", "winter", "fall"], answer: 2 },
      { id: "q3", prompt: "Which season is hot and sunny?", choices: ["winter", "summer", "fall", "spring"], answer: 1 },
      { id: "q4", prompt: "In fall, leaves change color and...", choices: ["grow back", "fall off trees", "turn blue", "sing"], answer: 1 },
      { id: "q5", prompt: "What do you wear when it rains?", choices: ["shorts", "a raincoat", "a swimsuit", "sandals"], answer: 1 },
      { id: "q6", prompt: "How many seasons are in a year?", choices: ["2", "3", "4", "5"], answer: 2 },
      { id: "q7", prompt: "What shines in the sky in the daytime?", choices: ["moon", "sun", "stars", "clouds"], answer: 1 },
      { id: "q8", prompt: "What do you see in the sky at night?", choices: ["sun", "rainbow", "stars", "snowman"], answer: 2 },
      { id: "q9", prompt: "After rain we sometimes see a colorful...", choices: ["snowman", "rainbow", "cloud", "rocket"], answer: 1 },
      { id: "q10", prompt: "Which is COLD?", choices: ["a hot tea", "an ice cube", "the sun", "a candle"], answer: 1 },
    ],
  },
  {
    id: "k-sci-fivesenses",
    subjectId: "science",
    level: "kindergarten",
    title: "My Five Senses",
    description: "See, hear, smell, taste, and touch.",
    emoji: "\u{1F441}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "You use your eyes to...", choices: ["hear", "see", "smell", "taste"], answer: 1 },
      { id: "q2", prompt: "You use your ears to...", choices: ["see", "hear", "touch", "taste"], answer: 1 },
      { id: "q3", prompt: "You use your nose to...", choices: ["hear", "smell", "see", "taste"], answer: 1 },
      { id: "q4", prompt: "You use your tongue to...", choices: ["smell", "see", "taste", "hear"], answer: 2 },
      { id: "q5", prompt: "You use your hands to...", choices: ["hear", "touch", "smell", "see"], answer: 1 },
      { id: "q6", prompt: "How many senses do you have?", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q7", prompt: "Ice feels...", choices: ["hot", "warm", "cold", "spicy"], answer: 2 },
      { id: "q8", prompt: "A lemon usually tastes...", choices: ["sweet", "sour", "salty", "spicy"], answer: 1 },
      { id: "q9", prompt: "Sugar tastes...", choices: ["bitter", "sour", "sweet", "salty"], answer: 2 },
      { id: "q10", prompt: "A bell makes a sound you can...", choices: ["see", "taste", "hear", "smell"], answer: 2 },
    ],
  },
  {
    id: "k-sci-plants",
    subjectId: "science",
    level: "kindergarten",
    title: "Plants & Living Things",
    description: "What plants need and living vs. not living.",
    emoji: "\u{1F331}",
    questions: [
      { id: "q1", prompt: "Plants need ___ to grow.", choices: ["water", "toys", "books", "music"], answer: 0 },
      { id: "q2", prompt: "Plants also need...", choices: ["sunlight", "the moon", "the wind", "rocks"], answer: 0 },
      { id: "q3", prompt: "A baby plant comes from a...", choices: ["rock", "seed", "cloud", "shell"], answer: 1 },
      { id: "q4", prompt: "Which is a living thing?", choices: ["rock", "chair", "tree", "toy car"], answer: 2 },
      { id: "q5", prompt: "Which is NOT living?", choices: ["dog", "flower", "book", "bird"], answer: 2 },
      { id: "q6", prompt: "The part of a plant that holds it down is the...", choices: ["leaf", "flower", "root", "sky"], answer: 2 },
      { id: "q7", prompt: "A flower can grow into a...", choices: ["car", "fruit", "shoe", "rock"], answer: 1 },
      { id: "q8", prompt: "Trees are usually very...", choices: ["tiny", "tall", "flat", "soft"], answer: 1 },
      { id: "q9", prompt: "Plants make a gas that we breathe called...", choices: ["smoke", "oxygen", "steam", "sugar"], answer: 1 },
      { id: "q10", prompt: "You eat the seeds of which plant?", choices: ["a rose", "a sunflower", "a dandelion", "grass"], answer: 1 },
    ],
  },

  // -------- HISTORY (Kindergarten) --------
  {
    id: "k-hist-helpers",
    subjectId: "history",
    level: "kindergarten",
    title: "Helpers in My Town",
    description: "People who help in our community.",
    emoji: "\u{1F692}",
    questions: [
      { id: "q1", prompt: "Who puts out fires?", choices: ["a doctor", "a firefighter", "a teacher", "a chef"], answer: 1 },
      { id: "q2", prompt: "Who helps you when you are sick?", choices: ["a doctor", "a mail carrier", "a farmer", "a baker"], answer: 0 },
      { id: "q3", prompt: "Who teaches you at school?", choices: ["a chef", "a teacher", "a vet", "a builder"], answer: 1 },
      { id: "q4", prompt: "Who brings your mail?", choices: ["a vet", "a mail carrier", "a baker", "a pilot"], answer: 1 },
      { id: "q5", prompt: "Who helps sick animals?", choices: ["a doctor", "a vet", "a chef", "a pilot"], answer: 1 },
      { id: "q6", prompt: "Who flies an airplane?", choices: ["a pilot", "a builder", "a chef", "a teacher"], answer: 0 },
      { id: "q7", prompt: "Who bakes bread?", choices: ["a pilot", "a baker", "a vet", "a farmer"], answer: 1 },
      { id: "q8", prompt: "Who grows food on a farm?", choices: ["a farmer", "a doctor", "a chef", "a librarian"], answer: 0 },
      { id: "q9", prompt: "Who helps keep our streets safe?", choices: ["a police officer", "a chef", "a builder", "a pilot"], answer: 0 },
      { id: "q10", prompt: "Who helps you find books?", choices: ["a chef", "a librarian", "a pilot", "a vet"], answer: 1 },
    ],
  },
  {
    id: "k-hist-family",
    subjectId: "history",
    level: "kindergarten",
    title: "Family & Long Ago",
    description: "Yesterday, today, and family.",
    emoji: "\u{1F46A}",
    questions: [
      { id: "q1", prompt: "Your mom's mom is your...", choices: ["sister", "aunt", "grandma", "cousin"], answer: 2 },
      { id: "q2", prompt: "Your dad's dad is your...", choices: ["uncle", "grandpa", "brother", "friend"], answer: 1 },
      { id: "q3", prompt: "Things that happened a long time ago are in the...", choices: ["future", "present", "past", "sky"], answer: 2 },
      { id: "q4", prompt: "Right now is called the...", choices: ["past", "present", "future", "finish"], answer: 1 },
      { id: "q5", prompt: "Tomorrow is in the...", choices: ["past", "present", "future", "middle"], answer: 2 },
      { id: "q6", prompt: "A long time ago people often traveled by...", choices: ["airplane", "horse and wagon", "spaceship", "car"], answer: 1 },
      { id: "q7", prompt: "Old photos are usually...", choices: ["brand new", "black and white", "made of plastic", "in 3D"], answer: 1 },
      { id: "q8", prompt: "A birthday celebrates the day you were...", choices: ["born", "asleep", "eating", "swimming"], answer: 0 },
      { id: "q9", prompt: "Your parents' brother is your...", choices: ["cousin", "uncle", "grandpa", "nephew"], answer: 1 },
      { id: "q10", prompt: "Children grow up to be...", choices: ["smaller", "the same size", "adults", "animals"], answer: 2 },
    ],
  },
  {
    id: "k-hist-holidays",
    subjectId: "history",
    level: "kindergarten",
    title: "Fun Holidays",
    description: "Holidays kids know and love.",
    emoji: "\u{1F389}",
    questions: [
      { id: "q1", prompt: "On which holiday do kids wear costumes and get candy?", choices: ["Halloween", "Easter", "Thanksgiving", "July 4th"], answer: 0 },
      { id: "q2", prompt: "On Thanksgiving we say...", choices: ["boo!", "thank you", "goodbye", "surprise"], answer: 1 },
      { id: "q3", prompt: "What do we see lots of on July 4th?", choices: ["snowmen", "fireworks", "pumpkins", "valentines"], answer: 1 },
      { id: "q4", prompt: "Valentine's Day is in which month?", choices: ["December", "February", "July", "October"], answer: 1 },
      { id: "q5", prompt: "Which holiday has a tree with lights?", choices: ["Christmas", "Earth Day", "Memorial Day", "Mother's Day"], answer: 0 },
      { id: "q6", prompt: "On your birthday we usually have...", choices: ["pumpkins", "a cake", "snowmen", "raincoats"], answer: 1 },
      { id: "q7", prompt: "On New Year's we celebrate a new...", choices: ["week", "day", "year", "hour"], answer: 2 },
      { id: "q8", prompt: "Mother's Day is to thank...", choices: ["teachers", "moms", "firefighters", "chefs"], answer: 1 },
      { id: "q9", prompt: "Father's Day is to thank...", choices: ["moms", "dads", "friends", "cousins"], answer: 1 },
      { id: "q10", prompt: "Earth Day helps us care for the...", choices: ["moon", "planet", "sun", "stars"], answer: 1 },
    ],
  },
  {
    id: "k-hist-symbols",
    subjectId: "history",
    level: "kindergarten",
    title: "Our Country",
    description: "Simple symbols of the U.S.",
    emoji: "\u{1F1FA}\u{1F1F8}",
    questions: [
      { id: "q1", prompt: "What colors are on the U.S. flag?", choices: ["red, white, blue", "green and gold", "pink and purple", "orange and black"], answer: 0 },
      { id: "q2", prompt: "The leader of our country is the...", choices: ["mayor", "president", "chef", "captain"], answer: 1 },
      { id: "q3", prompt: "Our country is called the...", choices: ["United States", "Canada", "Mexico", "France"], answer: 0 },
      { id: "q4", prompt: "The bird that stands for the U.S. is the...", choices: ["chicken", "bald eagle", "penguin", "owl"], answer: 1 },
      { id: "q5", prompt: "Our flag has stars and...", choices: ["hearts", "stripes", "circles", "smiles"], answer: 1 },
      { id: "q6", prompt: "We say the Pledge of Allegiance to the...", choices: ["book", "flag", "chair", "window"], answer: 1 },
      { id: "q7", prompt: "The president lives in the...", choices: ["Red House", "White House", "Big House", "Star House"], answer: 1 },
      { id: "q8", prompt: "The Statue of Liberty is a big...", choices: ["bird", "statue", "painting", "toy"], answer: 1 },
      { id: "q9", prompt: "Stars on the flag stand for the...", choices: ["states", "trees", "books", "days"], answer: 0 },
      { id: "q10", prompt: "The American flag has stripes that are red and...", choices: ["blue", "white", "yellow", "green"], answer: 1 },
    ],
  },

  // -------- GEOGRAPHY (Kindergarten) --------
  {
    id: "k-geo-earth",
    subjectId: "geography",
    level: "kindergarten",
    title: "Our Big Earth",
    description: "Land, water, and our planet.",
    emoji: "\u{1F30D}",
    questions: [
      { id: "q1", prompt: "What is the shape of Earth?", choices: ["a flat square", "a round ball", "a triangle", "a star"], answer: 1 },
      { id: "q2", prompt: "Most of Earth is covered by...", choices: ["sand", "grass", "water", "rocks"], answer: 2 },
      { id: "q3", prompt: "A really big body of water is called an...", choices: ["ocean", "puddle", "pond", "cup"], answer: 0 },
      { id: "q4", prompt: "A tall, pointy land shape is called a...", choices: ["river", "mountain", "valley", "beach"], answer: 1 },
      { id: "q5", prompt: "A hot, sandy, dry place is a...", choices: ["jungle", "desert", "ocean", "forest"], answer: 1 },
      { id: "q6", prompt: "Where do fish live?", choices: ["in trees", "in water", "in the sky", "in caves"], answer: 1 },
      { id: "q7", prompt: "Sand is mostly found at the...", choices: ["mountains", "beach", "snow", "office"], answer: 1 },
      { id: "q8", prompt: "Earth is also called our...", choices: ["planet", "star", "moon", "toy"], answer: 0 },
      { id: "q9", prompt: "A round model of Earth is called a...", choices: ["map", "globe", "flag", "sign"], answer: 1 },
      { id: "q10", prompt: "The really cold places at the top and bottom of Earth are the...", choices: ["deserts", "poles", "oceans", "hills"], answer: 1 },
    ],
  },
  {
    id: "k-geo-directions",
    subjectId: "geography",
    level: "kindergarten",
    title: "Where Things Are",
    description: "Up, down, left, right, and simple maps.",
    emoji: "\u{1F9ED}",
    questions: [
      { id: "q1", prompt: "The sun rises in the morning in the...", choices: ["east", "west", "north", "south"], answer: 0 },
      { id: "q2", prompt: "The sun sets in the evening in the...", choices: ["east", "west", "north", "south"], answer: 1 },
      { id: "q3", prompt: "A picture that shows where things are is a...", choices: ["map", "book", "phone", "shoe"], answer: 0 },
      { id: "q4", prompt: "'Up' is the opposite of...", choices: ["left", "right", "down", "in"], answer: 2 },
      { id: "q5", prompt: "'Left' is the opposite of...", choices: ["right", "up", "down", "behind"], answer: 0 },
      { id: "q6", prompt: "'In front' is the opposite of...", choices: ["behind", "above", "under", "near"], answer: 0 },
      { id: "q7", prompt: "The pet is UNDER the table. Where is the table?", choices: ["under the pet", "above the pet", "behind the pet", "inside the pet"], answer: 1 },
      { id: "q8", prompt: "Birds usually fly in the...", choices: ["sky", "ocean", "ground", "tunnel"], answer: 0 },
      { id: "q9", prompt: "Cars drive on the...", choices: ["sea", "sky", "road", "roof"], answer: 2 },
      { id: "q10", prompt: "If you are NEXT TO your friend, you are...", choices: ["far away", "beside them", "on top", "under"], answer: 1 },
    ],
  },
  {
    id: "k-geo-water",
    subjectId: "geography",
    level: "kindergarten",
    title: "Water Places",
    description: "Rivers, lakes, oceans, and ponds.",
    emoji: "\u{1F30A}",
    questions: [
      { id: "q1", prompt: "A small body of water you can walk around is a...", choices: ["ocean", "pond", "mountain", "forest"], answer: 1 },
      { id: "q2", prompt: "A long, flowing water with two sides of land is a...", choices: ["river", "lake", "sea", "desert"], answer: 0 },
      { id: "q3", prompt: "The biggest water of all is an...", choices: ["ocean", "puddle", "pond", "glass"], answer: 0 },
      { id: "q4", prompt: "Sand meets the ocean at the...", choices: ["forest", "beach", "hill", "barn"], answer: 1 },
      { id: "q5", prompt: "Boats float on...", choices: ["grass", "sand", "water", "trees"], answer: 2 },
      { id: "q6", prompt: "Which animal lives in the ocean?", choices: ["cow", "whale", "horse", "goat"], answer: 1 },
      { id: "q7", prompt: "Water from rain forms a small puddle on the...", choices: ["sky", "ground", "moon", "roof of stars"], answer: 1 },
      { id: "q8", prompt: "Ice cubes are water that is...", choices: ["hot", "warm", "frozen", "singing"], answer: 2 },
      { id: "q9", prompt: "A lake is mostly surrounded by...", choices: ["water", "sky", "land", "clouds"], answer: 2 },
      { id: "q10", prompt: "Salt water tastes...", choices: ["sweet", "salty", "sour", "spicy"], answer: 1 },
    ],
  },
  {
    id: "k-geo-home",
    subjectId: "geography",
    level: "kindergarten",
    title: "Around My Home",
    description: "Places near where we live.",
    emoji: "\u{1F3E1}",
    questions: [
      { id: "q1", prompt: "You learn at...", choices: ["a school", "a bakery", "a farm", "a beach"], answer: 0 },
      { id: "q2", prompt: "You buy food at the...", choices: ["library", "grocery store", "zoo", "airport"], answer: 1 },
      { id: "q3", prompt: "You borrow books at the...", choices: ["hospital", "library", "bank", "park"], answer: 1 },
      { id: "q4", prompt: "Sick people go to the...", choices: ["playground", "hospital", "school", "barn"], answer: 1 },
      { id: "q5", prompt: "Animals you can visit live at the...", choices: ["library", "zoo", "office", "airport"], answer: 1 },
      { id: "q6", prompt: "You can swing and slide at the...", choices: ["bank", "playground", "library", "hospital"], answer: 1 },
      { id: "q7", prompt: "Airplanes take off and land at the...", choices: ["airport", "farm", "library", "pond"], answer: 0 },
      { id: "q8", prompt: "Cows, pigs, and chickens often live on a...", choices: ["beach", "farm", "airport", "library"], answer: 1 },
      { id: "q9", prompt: "Many trees and trails are at the...", choices: ["park", "office", "bank", "store"], answer: 0 },
      { id: "q10", prompt: "Houses, streets, and stores together make a...", choices: ["forest", "town", "ocean", "sky"], answer: 1 },
    ],
  },
];
