/**
 * Language Arts — activity data.
 * All activities available at every grade level (allLevels: true).
 * Topics: synonyms, antonyms, prefixes, suffixes, Greek roots, Latin roots, homophones.
 */
import type { Activity } from "@/lib/brainy-data";

export const LANGUAGE_ACTIVITIES: Activity[] = [

  // ── Synonyms ─────────────────────────────────────────────────────────────
  {
    id: "lang-synonyms",
    subjectId: "language",
    title: "Synonyms",
    description: "Find words that share the same meaning.",
    emoji: "🟰",
    allLevels: true,
    questions: [
      { id: "q1", prompt: "Which word means the same as \"happy\"?", choices: ["angry", "joyful", "tired", "slow"], answer: 1, explanation: "Joyful is a synonym for happy — both mean feeling great!" },
      { id: "q2", prompt: "Which word is a synonym for \"big\"?", choices: ["tiny", "quick", "large", "cold"], answer: 2, explanation: "Large and big both describe something of great size." },
      { id: "q3", prompt: "Which word means the same as \"fast\"?", choices: ["slow", "quick", "loud", "calm"], answer: 1, explanation: "Quick is a synonym for fast — both mean moving with speed." },
      { id: "q4", prompt: "Which word is a synonym for \"angry\"?", choices: ["happy", "mad", "tired", "sleepy"], answer: 1, explanation: "Mad and angry both describe feeling upset or furious." },
      { id: "q5", prompt: "Which word means the same as \"tired\"?", choices: ["bright", "cold", "sleepy", "loud"], answer: 2, explanation: "Sleepy is a synonym for tired — both mean needing rest." },
      { id: "q6", prompt: "Which word is a synonym for \"begin\"?", choices: ["end", "wait", "start", "stop"], answer: 2, explanation: "Start and begin both mean to get going on something." },
      { id: "q7", prompt: "\"Difficult\" means the same as...", choices: ["easy", "hard", "soft", "slow"], answer: 1, explanation: "Hard and difficult both describe something that is not easy to do." },
      { id: "q8", prompt: "Which word is a synonym for \"small\"?", choices: ["tall", "round", "tiny", "loud"], answer: 2, explanation: "Tiny is a synonym for small — both describe something not very big." },
      { id: "q9", prompt: "\"Beautiful\" means the same as...", choices: ["ugly", "boring", "quiet", "pretty"], answer: 3, explanation: "Pretty is a synonym for beautiful — both mean pleasing to look at." },
      { id: "q10", prompt: "Which word means the same as \"friend\"?", choices: ["bully", "stranger", "enemy", "pal"], answer: 3, explanation: "Pal is a synonym for friend — both mean someone you like and trust." },
      { id: "q11", prompt: "Which word is a synonym for \"shout\"?", choices: ["whisper", "yell", "hum", "mumble"], answer: 1, explanation: "Yell and shout both mean to speak in a very loud voice." },
      { id: "q12", prompt: "\"Scared\" means the same as...", choices: ["brave", "bored", "afraid", "happy"], answer: 2, explanation: "Afraid is a synonym for scared — both mean feeling fear." },
      { id: "q13", prompt: "Which word is a synonym for \"reply\"?", choices: ["question", "listen", "answer", "speak"], answer: 2, explanation: "Answer and reply both mean to respond to what someone said." },
      { id: "q14", prompt: "\"Unhappy\" means the same as...", choices: ["cheerful", "excited", "grumpy", "sad"], answer: 3, explanation: "Sad is a synonym for unhappy — both mean not feeling good inside." },
      { id: "q15", prompt: "Which word means the same as \"cold\"?", choices: ["warm", "chilly", "bright", "loud"], answer: 1, explanation: "Chilly is a synonym for cold — both describe a low temperature." },
      { id: "q16", prompt: "Which word is a synonym for \"smart\"?", choices: ["silly", "quiet", "clever", "tall"], answer: 2, explanation: "Clever and smart both describe someone who learns and thinks well." },
      { id: "q17", prompt: "Which word means the same as \"jump\"?", choices: ["leap", "crawl", "sit", "walk"], answer: 0, explanation: "Leap is a synonym for jump — both mean to push off the ground into the air." },
      { id: "q18", prompt: "\"Gift\" means the same as...", choices: ["problem", "game", "story", "present"], answer: 3, explanation: "Present is a synonym for gift — both mean something you give to someone." },
    ],
  },

  // ── Antonyms ──────────────────────────────────────────────────────────────
  {
    id: "lang-antonyms",
    subjectId: "language",
    title: "Antonyms",
    description: "Match words to their exact opposite.",
    emoji: "↔️",
    allLevels: true,
    questions: [
      { id: "q1", prompt: "What is the opposite of \"hot\"?", choices: ["warm", "cold", "bright", "fast"], answer: 1, explanation: "Cold is the antonym of hot — they are complete opposites in temperature." },
      { id: "q2", prompt: "What is the opposite of \"happy\"?", choices: ["excited", "tired", "sad", "joyful"], answer: 2, explanation: "Sad is the antonym of happy — one is a good feeling, the other is not." },
      { id: "q3", prompt: "What is the opposite of \"fast\"?", choices: ["quick", "large", "slow", "rough"], answer: 2, explanation: "Slow is the antonym of fast — they describe opposite speeds." },
      { id: "q4", prompt: "What is the opposite of \"day\"?", choices: ["sun", "bright", "morning", "night"], answer: 3, explanation: "Night is the antonym of day — when the sun is down, night begins." },
      { id: "q5", prompt: "What is the opposite of \"up\"?", choices: ["over", "down", "high", "across"], answer: 1, explanation: "Down is the antonym of up — they are opposite directions." },
      { id: "q6", prompt: "What is the antonym of \"open\"?", choices: ["wide", "large", "locked", "closed"], answer: 3, explanation: "Closed is the antonym of open — a door is either open or closed." },
      { id: "q7", prompt: "What is the opposite of \"push\"?", choices: ["move", "shove", "carry", "pull"], answer: 3, explanation: "Pull is the antonym of push — you pull a door open and push it closed." },
      { id: "q8", prompt: "What is the opposite of \"quiet\"?", choices: ["calm", "peaceful", "loud", "soft"], answer: 2, explanation: "Loud is the antonym of quiet — a library is quiet; a concert is loud." },
      { id: "q9", prompt: "What is the antonym of \"heavy\"?", choices: ["large", "solid", "light", "full"], answer: 2, explanation: "Light is the antonym of heavy — a feather is light; a rock is heavy." },
      { id: "q10", prompt: "What is the opposite of \"friend\"?", choices: ["stranger", "enemy", "partner", "buddy"], answer: 1, explanation: "Enemy is the antonym of friend — one is someone you care about, the other is not." },
      { id: "q11", prompt: "What is the opposite of \"begin\"?", choices: ["pause", "wait", "start", "end"], answer: 3, explanation: "End is the antonym of begin — a story begins at the start and ends at the finish." },
      { id: "q12", prompt: "What is the antonym of \"always\"?", choices: ["sometimes", "often", "never", "usually"], answer: 2, explanation: "Never is the antonym of always — always means every time; never means not one time." },
      { id: "q13", prompt: "What is the opposite of \"inside\"?", choices: ["between", "around", "across", "outside"], answer: 3, explanation: "Outside is the antonym of inside — you are inside your house or outside of it." },
      { id: "q14", prompt: "What is the antonym of \"brave\"?", choices: ["strong", "cowardly", "careful", "calm"], answer: 1, explanation: "Cowardly is the antonym of brave — brave means facing your fears; cowardly means running away from them." },
      { id: "q15", prompt: "What is the opposite of \"big\"?", choices: ["tall", "small", "wide", "round"], answer: 1, explanation: "Small is the antonym of big — they describe opposite sizes." },
      { id: "q16", prompt: "What is the opposite of \"wet\"?", choices: ["damp", "moist", "dry", "cold"], answer: 2, explanation: "Dry is the antonym of wet — a towel can be wet or dry." },
      { id: "q17", prompt: "What is the antonym of \"full\"?", choices: ["empty", "heavy", "round", "clean"], answer: 0, explanation: "Empty is the antonym of full — a glass is either full of water or empty." },
      { id: "q18", prompt: "What is the opposite of \"first\"?", choices: ["second", "next", "middle", "last"], answer: 3, explanation: "Last is the antonym of first — the first one is at the front; the last one is at the end." },
    ],
  },

  // ── Prefixes ──────────────────────────────────────────────────────────────
  {
    id: "lang-prefixes",
    subjectId: "language",
    title: "Prefixes",
    description: "Discover how prefixes change the meaning of words.",
    emoji: "⬅️",
    allLevels: true,
    questions: [
      { id: "q1", prompt: "The prefix \"un-\" means...", choices: ["again", "before", "not", "wrong"], answer: 2, explanation: "Un- means NOT. Unhappy = not happy. Unkind = not kind. Unfair = not fair." },
      { id: "q2", prompt: "\"Unhappy\" means...", choices: ["very happy", "not happy", "happy again", "happy before"], answer: 1, explanation: "The prefix un- changes happy to its opposite: NOT happy." },
      { id: "q3", prompt: "The prefix \"re-\" means...", choices: ["before", "not", "again", "under"], answer: 2, explanation: "Re- means AGAIN. Redo = do again. Replay = play again. Reread = read again." },
      { id: "q4", prompt: "If you \"redo\" your homework, you...", choices: ["start it for the first time", "do it again", "skip it", "do it before school"], answer: 1, explanation: "Re- means again, so redo means to do something one more time." },
      { id: "q5", prompt: "The prefix \"pre-\" means...", choices: ["after", "not", "again", "before"], answer: 3, explanation: "Pre- means BEFORE. Preview = see before. Preheat = heat before. Preschool = school before kindergarten." },
      { id: "q6", prompt: "\"Preheat the oven\" means you heat the oven...", choices: ["after cooking", "without electricity", "before cooking", "while eating"], answer: 2, explanation: "Pre- means before, so preheat means to heat before you start cooking." },
      { id: "q7", prompt: "The prefix \"dis-\" means...", choices: ["again", "not or opposite", "before", "under"], answer: 1, explanation: "Dis- means NOT or the OPPOSITE. Dislike = not like. Disagree = not agree. Dishonest = not honest." },
      { id: "q8", prompt: "\"Disagree\" means...", choices: ["agree strongly", "agree again", "not agree", "agree before"], answer: 2, explanation: "Dis- flips the meaning: disagree means to NOT agree with someone." },
      { id: "q9", prompt: "The prefix \"mis-\" means...", choices: ["wrongly or badly", "before", "again", "under"], answer: 0, explanation: "Mis- means WRONGLY. Misspell = spell wrongly. Misread = read wrongly. Mistake = a wrong action." },
      { id: "q10", prompt: "If you \"misread\" the instructions, you...", choices: ["read them perfectly", "read them again", "read them before class", "read them incorrectly"], answer: 3, explanation: "Mis- means wrongly, so misread means you did not read it correctly." },
      { id: "q11", prompt: "Which prefix would change \"kind\" to mean \"not kind\"?", choices: ["re-", "pre-", "un-", "mis-"], answer: 2, explanation: "Un- + kind = unkind. Un- is the most common prefix meaning NOT." },
      { id: "q12", prompt: "Which word uses the prefix \"over-\" to mean \"too much\"?", choices: ["undo", "preview", "overflow", "misplace"], answer: 2, explanation: "Over- means too much. Overflow = flow over the top. Overdo = do too much." },
      { id: "q13", prompt: "\"Preschool\" is the school you attend...", choices: ["after first grade", "before kindergarten", "on weekends", "in middle school"], answer: 1, explanation: "Pre- means before, so preschool is the school you attend BEFORE kindergarten." },
      { id: "q14", prompt: "Which prefix means \"again\"?", choices: ["un-", "dis-", "pre-", "re-"], answer: 3, explanation: "Re- means again: redo, replay, rewrite, reread — all done a second time." },
      { id: "q15", prompt: "The prefix \"sub-\" means...", choices: ["above", "between", "under / below", "against"], answer: 2, explanation: "Sub- = UNDER or BELOW. Submarine = vessel under water. Subway = train under the street. Subzero = below zero degrees." },
      { id: "q16", prompt: "A \"submarine\" travels...", choices: ["above the clouds", "through outer space", "under the water", "across mountains"], answer: 2, explanation: "Sub (under) + marine (sea) = submarine — a vehicle that travels beneath the ocean." },
      { id: "q17", prompt: "The prefix \"super-\" means...", choices: ["under", "above / beyond", "against", "before"], answer: 1, explanation: "Super- = ABOVE or BEYOND. Superhero = hero beyond normal limits. Supernatural = beyond nature. Supermarket = market bigger than a regular store." },
      { id: "q18", prompt: "The prefix \"inter-\" means...", choices: ["under", "against", "between / among", "after"], answer: 2, explanation: "Inter- = BETWEEN or AMONG. International = between nations. Interact = act between each other. Internet = network that connects between computers." },
      { id: "q19", prompt: "The prefix \"non-\" means...", choices: ["again", "not / no", "before", "under"], answer: 1, explanation: "Non- = NOT or NO. Nonfiction = not fiction (real events). Nonstop = without stopping. Nonprofit = not for earning profit." },
      { id: "q20", prompt: "A \"nonfiction\" book contains...", choices: ["made-up stories", "fairy tales", "real facts and true events", "fantasy adventures"], answer: 2, explanation: "Non- means not, so nonfiction = NOT fiction. It's based on real facts and real events." },
      { id: "q21", prompt: "The prefix \"trans-\" means...", choices: ["under", "against", "again", "across / through"], answer: 3, explanation: "Trans- = ACROSS or THROUGH. Transport = carry across. Transform = change completely. Translate = carry words across languages." },
      { id: "q22", prompt: "The prefix \"anti-\" means...", choices: ["in favor of", "before", "against / opposite", "behind"], answer: 2, explanation: "Anti- = AGAINST. Antibiotic = fights against bacteria. Antifreeze = works against freezing. Antisocial = against being social." },
      { id: "q23", prompt: "The prefix \"fore-\" means...", choices: ["after", "beside", "under", "in front of / before"], answer: 3, explanation: "Fore- = IN FRONT OF or BEFORE. Foreground = in front of the background. Forecast = predict before it happens. Forehead = front of the head." },
      { id: "q24", prompt: "The prefix \"mid-\" means...", choices: ["after", "in the middle of", "under", "again"], answer: 1, explanation: "Mid- = MIDDLE. Midnight = middle of the night. Midterm = middle of the school term. Midfield = the middle of the field." },
    ],
  },

  // ── Suffixes ──────────────────────────────────────────────────────────────
  {
    id: "lang-suffixes",
    subjectId: "language",
    title: "Suffixes",
    description: "See how suffixes attached to the end of words change their meaning.",
    emoji: "➡️",
    allLevels: true,
    questions: [
      { id: "q1", prompt: "The suffix \"-ful\" means...", choices: ["without", "full of", "the act of", "one who"], answer: 1, explanation: "-ful means FULL OF. Joyful = full of joy. Careful = full of care. Helpful = full of help." },
      { id: "q2", prompt: "\"Careful\" means...", choices: ["without care", "full of care", "care again", "very caring person"], answer: 1, explanation: "-ful means full of, so careful means full of care — paying close attention." },
      { id: "q3", prompt: "The suffix \"-less\" means...", choices: ["full of", "again", "without", "like"], answer: 2, explanation: "-less means WITHOUT. Careless = without care. Hopeless = without hope. Useless = without use." },
      { id: "q4", prompt: "\"Hopeless\" means...", choices: ["full of hope", "hoping again", "without hope", "a hopeful person"], answer: 2, explanation: "-less means without, so hopeless means without any hope." },
      { id: "q5", prompt: "The suffix \"-ness\" turns an adjective into...", choices: ["a verb (action)", "an adjective (describing word)", "a noun (a thing)", "an adverb (how)"], answer: 2, explanation: "-ness creates a noun from an adjective: happy → happiness, kind → kindness, dark → darkness." },
      { id: "q6", prompt: "\"Kindness\" comes from the root word...", choices: ["kind", "kin", "king", "kindle"], answer: 0, explanation: "Kind + -ness = kindness. The -ness suffix turns the adjective 'kind' into a noun." },
      { id: "q7", prompt: "The suffix \"-ly\" tells us...", choices: ["full of", "how something is done", "without", "the most"], answer: 1, explanation: "-ly turns an adjective into an adverb: quick → quickly, slow → slowly, loud → loudly." },
      { id: "q8", prompt: "\"Quickly\" is formed from \"quick\" + which suffix?", choices: ["-ful", "-less", "-ness", "-ly"], answer: 3, explanation: "Quick + -ly = quickly. The -ly suffix means 'in a way', so quickly means 'in a quick way'." },
      { id: "q9", prompt: "The suffix \"-er\" is used to...", choices: ["make a noun", "compare two things", "mean without", "mean again"], answer: 1, explanation: "-er compares two things: tall → taller (than someone else), fast → faster." },
      { id: "q10", prompt: "The suffix \"-est\" means...", choices: ["more than one other", "less than all", "the most of all", "done again"], answer: 2, explanation: "-est means THE MOST of all: tallest = the most tall, fastest = the most fast." },
      { id: "q11", prompt: "The suffix \"-able\" means...", choices: ["full of", "without", "can be done", "the act of"], answer: 2, explanation: "-able means CAN BE DONE. Readable = can be read. Lovable = can be loved. Washable = can be washed." },
      { id: "q12", prompt: "\"Enjoyable\" means...", choices: ["without enjoyment", "enjoyed again", "able to be enjoyed", "full of enjoyment"], answer: 2, explanation: "Enjoy + -able = enjoyable. Something enjoyable is something you can enjoy!" },
      { id: "q13", prompt: "Which word uses the suffix \"-ment\" to mean \"the result of\"?", choices: ["quickly", "careless", "movement", "joyful"], answer: 2, explanation: "Move + -ment = movement. -ment creates a noun showing the result: excitement, payment, enjoyment." },
      { id: "q14", prompt: "Which suffix would you add to \"sad\" to create the noun \"sadness\"?", choices: ["-ful", "-less", "-ness", "-able"], answer: 2, explanation: "Sad + -ness = sadness. The -ness suffix turns describing words into naming words (nouns)." },
      { id: "q15", prompt: "The suffix \"-ish\" means...", choices: ["full of", "again", "somewhat or like", "without"], answer: 2, explanation: "-ish means SOMEWHAT or LIKE. Reddish = somewhat red. Childish = like a child. Greenish = a little green." },
      { id: "q16", prompt: "A person who plays the piano can be called a \"pianist.\" The suffix \"-ist\" means...", choices: ["one who does something", "without", "full of", "the most"], answer: 0, explanation: "-ist means ONE WHO does something. Artist = one who makes art. Scientist = one who does science." },
      { id: "q17", prompt: "\"Cloudy\" uses the suffix \"-y.\" It means...", choices: ["without clouds", "full of or covered with clouds", "cloud again", "the most cloud"], answer: 1, explanation: "-y means full of or having. Cloudy = full of clouds. Rainy = full of rain. Sunny = full of sun." },
      { id: "q18", prompt: "The suffix \"-tion\" turns a verb into...", choices: ["a noun (a thing)", "an adverb (how)", "an adjective (describing word)", "a verb (action)"], answer: 0, explanation: "-tion creates a noun from a verb: act → action, celebrate → celebration, invent → invention." },
    ],
  },

  // ── Greek Roots ───────────────────────────────────────────────────────────
  {
    id: "lang-greek-roots",
    subjectId: "language",
    title: "Greek Word Roots",
    description: "Unlock the meaning of hundreds of words by learning Greek roots.",
    emoji: "🏛️",
    allLevels: true,
    questions: [
      { id: "q1",  prompt: "The Greek root \"bio\" means...", choices: ["earth", "light", "life", "water"], answer: 2, explanation: "Bio = LIFE. Biology = study of life. Biography = the life story of a person." },
      { id: "q2",  prompt: "\"Biology\" is the study of...", choices: ["rocks and earth", "stars and planets", "living things", "weather"], answer: 2, explanation: "Bio (life) + ‑ology (study of) = biology, the science of all living things." },
      { id: "q3",  prompt: "The Greek root \"geo\" means...", choices: ["water", "earth", "far", "small"], answer: 1, explanation: "Geo = EARTH. Geography = writing about Earth's features. Geology = study of the earth." },
      { id: "q4",  prompt: "The Greek root \"hydro\" means...", choices: ["fire", "earth", "air", "water"], answer: 3, explanation: "Hydro = WATER. Hydrogen is part of water (H₂O). Hydroplane = skim over water." },
      { id: "q5",  prompt: "The Greek root \"photo\" means...", choices: ["sound", "light", "write", "earth"], answer: 1, explanation: "Photo = LIGHT. Photography = capturing light to make images. Photosynthesis = plants using light to make food." },
      { id: "q6",  prompt: "The Greek root \"tele\" means...", choices: ["small", "sound", "far / distance", "write"], answer: 2, explanation: "Tele = FAR. Telephone = sound from far away. Telescope = see far away. Television = see from a distance." },
      { id: "q7",  prompt: "The Greek root \"micro\" means...", choices: ["large", "far", "small", "many"], answer: 2, explanation: "Micro = SMALL. Microscope = tool to see tiny things. Microphone = amplifies small sounds." },
      { id: "q8",  prompt: "The Greek root \"graph\" means...", choices: ["see/look", "water", "write/record", "earth"], answer: 2, explanation: "Graph = WRITE or RECORD. Paragraph = written section. Autograph = self-written signature." },
      { id: "q9",  prompt: "The Greek root \"auto\" means...", choices: ["self", "again", "many", "around"], answer: 0, explanation: "Auto = SELF. Autobiography = a story you write about yourself. Automatic = works by itself." },
      { id: "q10", prompt: "The Greek root \"-ology\" means...", choices: ["the love of", "the fear of", "the study of", "the opposite of"], answer: 2, explanation: "-ology = STUDY OF. Biology, geology, zoology, psychology — all end in the 'study of' something." },
      { id: "q11", prompt: "The Greek root \"phon\" means...", choices: ["light", "sound/voice", "far", "write"], answer: 1, explanation: "Phon = SOUND or VOICE. Microphone = amplifies sound. Phonics = learning sounds of letters. Symphony = beautiful sounds together." },
      { id: "q12", prompt: "The Greek root \"therm\" means...", choices: ["cold", "heat", "light", "wind"], answer: 1, explanation: "Therm = HEAT. Thermometer = tool that measures heat. Thermostat = device that controls room temperature." },
      { id: "q13", prompt: "A \"thermometer\" measures...", choices: ["wind speed", "rainfall", "temperature (heat)", "air pressure"], answer: 2, explanation: "Therm (heat) + meter (measure) = thermometer. It tells you how hot or cold something is." },
      { id: "q14", prompt: "The Greek root \"chron\" means...", choices: ["color", "time", "mind", "star"], answer: 1, explanation: "Chron = TIME. Chronological = arranged in order of time. Chronicle = a record of events over time." },
      { id: "q15", prompt: "Events listed in \"chronological\" order are arranged by...", choices: ["size", "importance", "alphabet", "time"], answer: 3, explanation: "Chron (time) + logical = chronological — arranged from earliest to latest, in order of time." },
      { id: "q16", prompt: "The Greek root \"astro\" (or \"aster\") means...", choices: ["earth", "water", "star", "air"], answer: 2, explanation: "Astro/aster = STAR. Astronomy = study of stars. Astronaut = star sailor (space traveler). Asteroid = rock shaped like a star." },
      { id: "q17", prompt: "An \"astronaut\" is someone who...", choices: ["studies rocks", "travels into space", "maps the ocean", "predicts weather"], answer: 1, explanation: "Astro (star) + naut (sailor) = astronaut — a 'star sailor' who travels through space." },
      { id: "q18", prompt: "The Greek root \"dem\" (or \"demo\") means...", choices: ["leader", "people", "power", "land"], answer: 1, explanation: "Demo = PEOPLE. Democracy = rule by the people. Demographics = data about groups of people." },
      { id: "q19", prompt: "\"Democracy\" is a system of government ruled by...", choices: ["a king", "a general", "the people", "judges"], answer: 2, explanation: "Demo (people) + cracy (rule) = democracy, a government where the people have the power to vote." },
      { id: "q20", prompt: "The Greek root \"psych\" means...", choices: ["body", "mind/soul", "sound", "earth"], answer: 1, explanation: "Psych = MIND or SOUL. Psychology = study of the mind. Psychiatrist = a doctor who treats mental health." },
      { id: "q21", prompt: "The Greek root \"zoo\" means...", choices: ["plant", "rock", "animal", "water"], answer: 2, explanation: "Zoo = ANIMAL. Zoology = the study of animals. A zoo is a place where animals live and are studied." },
      { id: "q22", prompt: "The Greek root \"poly\" means...", choices: ["one", "two", "many", "none"], answer: 2, explanation: "Poly = MANY. Polygon = a shape with many sides. Polyglot = a person who speaks many languages." },
      { id: "q23", prompt: "A \"polygon\" is a shape with...", choices: ["one side", "exactly four sides", "many sides", "curved sides"], answer: 2, explanation: "Poly (many) + gon (angle/side) = polygon. Triangles, squares, hexagons — all are polygons with many sides." },
      { id: "q24", prompt: "The Greek root \"mono\" means...", choices: ["one", "two", "many", "half"], answer: 0, explanation: "Mono = ONE. Monotone = speaking in one flat tone. Monologue = one person speaking. Monopoly = one company controls everything." },
      { id: "q25", prompt: "The Greek root \"scope\" means...", choices: ["write", "measure", "look at / examine", "carry"], answer: 2, explanation: "Scope = LOOK AT or EXAMINE. Telescope = look at things far away. Microscope = look at tiny things. Stethoscope = examine chest sounds." },
      { id: "q26", prompt: "The Greek root \"meter\" (or \"metr\") means...", choices: ["write", "measure", "carry", "heat"], answer: 1, explanation: "Meter = MEASURE. Thermometer = measures heat. Barometer = measures air pressure. Centimeter = a unit of measure." },
      { id: "q27", prompt: "The Greek root \"chrom\" means...", choices: ["time", "sound", "color", "life"], answer: 2, explanation: "Chrom = COLOR. Chromosome = the colored body in cells. Chromatic = relating to color. Chrome = shiny, colorful coating." },
      { id: "q28", prompt: "The Greek root \"path\" means...", choices: ["feeling/disease", "earth", "star", "measure"], answer: 0, explanation: "Path = FEELING or DISEASE. Sympathy = feeling together with someone. Pathology = study of disease. Empathy = understanding others' feelings." },
    ],
  },

  // ── Latin Roots ───────────────────────────────────────────────────────────
  {
    id: "lang-latin-roots",
    subjectId: "language",
    title: "Latin Word Roots",
    description: "Learn Latin roots to decode and understand thousands of English words.",
    emoji: "📜",
    allLevels: true,
    questions: [
      { id: "q1", prompt: "The Latin root \"aqua\" means...", choices: ["fire", "earth", "air", "water"], answer: 3, explanation: "Aqua = WATER. Aquarium = a tank of water. Aquatic = living in water. Aqueduct = channel for water." },
      { id: "q2", prompt: "An \"aquarium\" is a place that holds...", choices: ["birds", "land animals", "fish and water creatures", "rocks and minerals"], answer: 2, explanation: "Aqua (water) + arium (place for) = aquarium. It's filled with water and aquatic animals." },
      { id: "q3", prompt: "The Latin root \"port\" means...", choices: ["sail", "carry", "open", "build"], answer: 1, explanation: "Port = CARRY. Transport = carry across. Portable = able to be carried. Import = carry into a country." },
      { id: "q4", prompt: "\"Portable\" means...", choices: ["able to be built", "able to be seen", "able to be carried", "able to be heard"], answer: 2, explanation: "Port (carry) + -able (can be done) = portable. A portable device can be carried anywhere." },
      { id: "q5", prompt: "The Latin root \"rupt\" means...", choices: ["build", "grow", "break", "flow"], answer: 2, explanation: "Rupt = BREAK. Erupt = break out (like a volcano). Interrupt = break into a conversation. Corrupt = break down." },
      { id: "q6", prompt: "When a volcano \"erupts,\" it...", choices: ["goes dormant", "fills with water", "breaks open and releases lava", "grows taller"], answer: 2, explanation: "E + rupt (break) = erupt. The volcano 'breaks' open and lava bursts out." },
      { id: "q7", prompt: "The Latin root \"dict\" means...", choices: ["hear", "see", "write", "say/speak"], answer: 3, explanation: "Dict = SAY or SPEAK. Dictionary = a book of words and their meanings. Predict = say before. Dictate = speak aloud." },
      { id: "q8", prompt: "A \"dictionary\" is a book that...", choices: ["tells stories", "shows maps", "lists words and their meanings", "tracks the weather"], answer: 2, explanation: "Dict (say/word) + -ionary (relating to) = dictionary, a reference book of words." },
      { id: "q9", prompt: "The Latin root \"aud\" means...", choices: ["see", "speak", "hear", "carry"], answer: 2, explanation: "Aud = HEAR. Audience = people listening. Auditorium = place to hear performances. Audio = relating to sound." },
      { id: "q10", prompt: "The \"audience\" at a performance is there to...", choices: ["perform on stage", "listen and watch", "write reviews", "sell tickets"], answer: 1, explanation: "Aud (hear) + -ience = audience. The audience is the group of people who listen and watch." },
      { id: "q11", prompt: "The Latin root \"vis\" (or \"vid\") means...", choices: ["hear", "feel", "smell", "see"], answer: 3, explanation: "Vis/vid = SEE. Visible = able to be seen. Video = something you see. Vision = the ability to see." },
      { id: "q12", prompt: "Something that is \"visible\" can be...", choices: ["heard", "smelled", "touched", "seen"], answer: 3, explanation: "Vis (see) + -ible (able to) = visible. If it's visible, your eyes can see it." },
      { id: "q13", prompt: "The Latin root \"scrib\" or \"script\" means...", choices: ["speak", "write", "build", "move"], answer: 1, explanation: "Scrib/script = WRITE. Describe = write about. Manuscript = hand-written document. Inscription = written words." },
      { id: "q14", prompt: "\"Predict\" uses the Latin root \"dict\" (say). \"Predict\" means to...", choices: ["say it again", "say it wrong", "say what will happen before it does", "refuse to say"], answer: 2, explanation: "Pre (before) + dict (say) = predict. To predict is to say what you think will happen BEFORE it does." },
      { id: "q15", prompt: "The Latin root \"struct\" means...", choices: ["break", "build / arrange", "carry", "see"], answer: 1, explanation: "Struct = BUILD. Construct = build together. Structure = something that was built. Instruct = build knowledge in someone." },
      { id: "q16", prompt: "To \"construct\" something means to...", choices: ["destroy it", "sell it", "build it", "paint it"], answer: 2, explanation: "Con (together) + struct (build) = construct \u2014 to build something by putting parts together." },
      { id: "q17", prompt: "The Latin root \"form\" means...", choices: ["break", "carry", "shape / form", "say"], answer: 2, explanation: "Form = SHAPE. Transform = change shape completely. Uniform = one shape/style for everyone. Reform = reshape or improve." },
      { id: "q18", prompt: "To \"transform\" something means to...", choices: ["carry it away", "say it aloud", "break it apart", "change its shape completely"], answer: 3, explanation: "Trans (across) + form (shape) = transform \u2014 to change something into a completely different form." },
      { id: "q19", prompt: "The Latin root \"spec\" or \"spect\" means...", choices: ["hear", "carry", "look / see", "write"], answer: 2, explanation: "Spec/spect = LOOK or SEE. Inspect = look closely. Spectator = one who looks on. Spectacular = worth looking at!" },
      { id: "q20", prompt: "A \"spectator\" at a game...", choices: ["plays on the field", "coaches the team", "watches and looks on", "sells tickets"], answer: 2, explanation: "Spect (look) + -ator (one who) = spectator \u2014 a person who watches an event." },
      { id: "q21", prompt: "The Latin root \"terr\" means...", choices: ["water", "fire", "earth / land", "sky"], answer: 2, explanation: "Terr = EARTH or LAND. Territory = a piece of land. Terrain = the type of land in an area. Terrarium = a container with earth and plants." },
      { id: "q22", prompt: "A \"terrarium\" is a glass container filled with...", choices: ["fish and water", "soil, plants, or small animals", "cooking ingredients", "scientific chemicals"], answer: 1, explanation: "Terr (earth) + arium (place for) = terrarium \u2014 a mini environment with soil and living things." },
      { id: "q23", prompt: "The Latin root \"duc\" or \"duct\" means...", choices: ["break", "lead / guide", "write", "hear"], answer: 1, explanation: "Duc/duct = LEAD or GUIDE. Conduct = lead together. Educate = lead out knowledge. Introduce = lead into a new situation." },
      { id: "q24", prompt: "To \"educate\" someone means to...", choices: ["carry them somewhere", "build something for them", "lead knowledge out of them / teach them", "say goodbye to them"], answer: 2, explanation: "E (out) + duc (lead) = educate \u2014 to lead knowledge out. A teacher guides students to discover what they know." },
      { id: "q25", prompt: "The Latin root \"mit\" or \"miss\" means...", choices: ["write", "see", "send", "carry"], answer: 2, explanation: "Mit/miss = SEND. Transmit = send across. Dismiss = send away. Mission = something you are sent to do. Admit = send in." },
      { id: "q26", prompt: "To \"transmit\" a message means to...", choices: ["write it down", "say it aloud", "send it across to someone", "receive it from someone"], answer: 2, explanation: "Trans (across) + mit (send) = transmit \u2014 to send something from one place to another." },
      { id: "q27", prompt: "The Latin root \"temp\" means...", choices: ["carry", "time", "build", "break"], answer: 1, explanation: "Temp = TIME. Temporary = lasting only a short time. Contemporary = living at the same time. Tempo = the speed/timing of music." },
      { id: "q28", prompt: "Something \"temporary\" is...", choices: ["built to last forever", "very large and important", "lasting only a short time", "made from metal"], answer: 2, explanation: "Temp (time) + -ary = temporary \u2014 it only lasts for a limited period of time, then it ends." },
    ],
  },

  // ── Homophones ────────────────────────────────────────────────────────────
  {
    id: "lang-homophones",
    subjectId: "language",
    title: "Homophones",
    description: "Words that sound the same but have different spellings and meanings.",
    emoji: "👂",
    allLevels: true,
    questions: [
      { id: "q1", prompt: "Which word completes this sentence? \"There ___ four apples on the table.\" (to exist/be)", choices: ["are", "our", "or", "oar"], answer: 0, explanation: "'Are' shows existence. 'Our' means belonging to us. They sound different but 'are' fits here." },
      { id: "q2", prompt: "\"Two,\" \"to,\" and \"too\" all sound alike. \"I have ___ cats.\" (the number)", choices: ["to", "too", "two", "tu"], answer: 2, explanation: "'Two' = the number 2. 'To' = a direction. 'Too' = also or very (like 'too hot')." },
      { id: "q3", prompt: "\"The book is over _____.\" (that place, not this place)", choices: ["their", "they're", "there", "thear"], answer: 2, explanation: "'There' points to a place. 'Their' shows ownership. 'They're' = they are." },
      { id: "q4", prompt: "\"_____ going to the park!\" (they are)", choices: ["There", "Their", "They're", "Thare"], answer: 2, explanation: "'They're' is a contraction of 'they are'. Always read contractions fully to check." },
      { id: "q5", prompt: "\"I can _____ the music.\" (using your ears)", choices: ["here", "hear", "heer", "heir"], answer: 1, explanation: "'Hear' uses your ears to receive sound. 'Here' is a place (come here, I'm here)." },
      { id: "q6", prompt: "\"She is coming, _____!\" (also)", choices: ["two", "to", "too", "tew"], answer: 2, explanation: "'Too' means also or very ('me too!', 'too loud'). 'To' shows direction ('I went to school')." },
      { id: "q7", prompt: "\"Please _____ your name on the paper.\" (use a pen/pencil)", choices: ["right", "wright", "rite", "write"], answer: 3, explanation: "'Write' = put words on paper. 'Right' = correct or a direction. They sound identical!" },
      { id: "q8", prompt: "\"I _____ the answer to that question.\" (to be aware of)", choices: ["no", "now", "know", "new"], answer: 2, explanation: "'Know' = to have knowledge. 'No' = the opposite of yes. 'Now' = this moment." },
      { id: "q9", prompt: "\"The team _____ the championship game!\" (past tense of win)", choices: ["one", "wan", "wun", "won"], answer: 3, explanation: "'Won' is the past tense of win. 'One' is the number 1. They are homophones!" },
      { id: "q10", prompt: "\"Can you _____ me this book at the store?\" (purchase)", choices: ["by", "bye", "buy", "bi"], answer: 2, explanation: "'Buy' = to purchase something. 'By' = near or by whom. 'Bye' = goodbye. All three sound the same!" },
      { id: "q11", prompt: "\"A _____ of socks\" (a set of two matching items)", choices: ["pear", "pare", "pair", "pier"], answer: 2, explanation: "'Pair' = two matching items. 'Pear' = a fruit. They sound identical but mean completely different things." },
      { id: "q12", prompt: "\"I feel _____ this week.\" (not strong or energetic)", choices: ["week", "wick", "weak", "weke"], answer: 2, explanation: "'Weak' = not strong. 'Week' = seven days. These homophones are spelled differently but sound the same." },
      { id: "q13", prompt: "\"The _____ in the sky is very bright today.\" (our star)", choices: ["son", "sen", "sun", "sone"], answer: 2, explanation: "'Sun' = the star our Earth orbits. 'Son' = a male child. They are homophones — same sound, different meanings." },
      { id: "q14", prompt: "\"I _____ my shoe.\" (past tense of lose)", choices: ["lost", "lossed", "losed", "lust"], answer: 0, explanation: "Lost is the past tense of lose. This tests irregular past tense, not a true homophone — but tests careful word choice." },
      { id: "q15", prompt: "\"We need _____ to bake the bread.\" (the powder used in baking)", choices: ["flower", "flour", "flowur", "floor"], answer: 1, explanation: "'Flour' is the powder used to bake. 'Flower' is the colorful part of a plant. They sound the same!" },
      { id: "q16", prompt: "\"The dog wagged its _____.\" (the back part of an animal)", choices: ["tale", "tael", "tial", "tail"], answer: 3, explanation: "'Tail' is the part on the back of an animal. 'Tale' is a story. They are homophones." },
      { id: "q17", prompt: "\"We swam in the _____.\" (the ocean)", choices: ["sea", "see", "si", "seah"], answer: 0, explanation: "'Sea' is a large body of salt water. 'See' means to look with your eyes. Same sound, different meanings." },
      { id: "q18", prompt: "\"The brave _____ wore shining armor.\" (a warrior who served a king)", choices: ["night", "nite", "knight", "knite"], answer: 2, explanation: "'Knight' is a warrior in armor — the 'k' is silent. 'Night' is when the sky is dark. They sound identical!" },
    ],
  },
];
