import type { Activity } from "@/lib/brainy-data";

export const HISTORY_EXPANSION_ACTIVITIES: Activity[] = [
  {
    id: "g3-hist-indigenous-regions",
    subjectId: "history",
    level: "grade3",
    title: "Indigenous Peoples & Regions",
    description: "Learn how Native nations built diverse communities across North America.",
    emoji: "🌽",
    questions: [
      { id: "q1", prompt: "Before European settlers arrived, North America was home to...", choices: ["many different Native nations", "one single tribe", "no communities", "only explorers"], answer: 0 },
      { id: "q2", prompt: "Why did homes differ across Native nations?", choices: ["People used local materials and adapted to climate", "Everyone followed one plan", "Homes had no purpose", "Only color mattered"], answer: 0 },
      { id: "q3", prompt: "Which crop was important to many Indigenous communities?", choices: ["Corn", "Coffee", "Olives", "Tea"], answer: 0 },
      { id: "q4", prompt: "The Haudenosaunee Confederacy joined nations to...", choices: ["cooperate and make decisions", "stop all farming", "build pyramids", "cross the Atlantic"], answer: 0 },
      { id: "q5", prompt: "People of the Great Plains traditionally relied heavily on...", choices: ["bison", "whales", "rice fields", "olive trees"], answer: 0 },
      { id: "q6", prompt: "Northwest Coast peoples used abundant cedar to make...", choices: ["homes, canoes, and tools", "desert wells only", "steel trains", "stone pyramids"], answer: 0 },
      { id: "q7", prompt: "An oral tradition passes history through...", choices: ["spoken stories", "weather reports", "math symbols", "traffic signs"], answer: 0 },
      { id: "q8", prompt: "Native nations today are...", choices: ["living communities with distinct cultures and governments", "only part of the distant past", "all exactly alike", "found only in museums"], answer: 0 },
      { id: "q9", prompt: "A respectful way to study Indigenous history is to...", choices: ["learn the names and perspectives of specific nations", "treat every nation as identical", "repeat stereotypes", "ignore Native voices"], answer: 0 },
      { id: "q10", prompt: "Which statement is true?", choices: ["Environment influenced food, clothing, and shelter", "Geography never affected communities", "Every nation spoke one language", "Traditions never changed"], answer: 0 },
    ],
  },
  {
    id: "g3-hist-exploration-encounters",
    subjectId: "history",
    level: "grade3",
    title: "Exploration & Encounters",
    description: "Explore why people traveled and what happened when cultures met.",
    emoji: "⛵",
    questions: [
      { id: "q1", prompt: "Why did many European explorers sail long distances?", choices: ["To seek trade routes, wealth, and knowledge", "To avoid all maps", "To stop travel", "To find dinosaurs"], answer: 0 },
      { id: "q2", prompt: "A compass helps sailors find...", choices: ["direction", "temperature", "food", "depth only"], answer: 0 },
      { id: "q3", prompt: "Europeans learned that the Americas were already...", choices: ["home to millions of Indigenous people", "empty", "one country", "covered only by ice"], answer: 0 },
      { id: "q4", prompt: "An encounter happens when...", choices: ["people or groups meet", "a ship stays in port", "a map is folded", "the Sun sets"], answer: 0 },
      { id: "q5", prompt: "The Columbian Exchange moved plants, animals, and...", choices: ["diseases between hemispheres", "planets between galaxies", "mountains across oceans", "seasons between years"], answer: 0 },
      { id: "q6", prompt: "Which American crop became important in Europe?", choices: ["Potato", "Olive", "Wheat", "Barley"], answer: 0 },
      { id: "q7", prompt: "Diseases brought by Europeans harmed Indigenous peoples because...", choices: ["they had little immunity to them", "all medicine disappeared", "ships blocked sunlight", "maps caused illness"], answer: 0 },
      { id: "q8", prompt: "Historical encounters can be understood best by...", choices: ["considering more than one perspective", "reading only one viewpoint", "ignoring consequences", "guessing without evidence"], answer: 0 },
      { id: "q9", prompt: "A primary source from a voyage might be...", choices: ["a sailor's journal", "a modern cartoon", "a future prediction", "a fictional space story"], answer: 0 },
      { id: "q10", prompt: "Exploration led to trade and new knowledge, but also to...", choices: ["conflict, conquest, and forced change", "peace everywhere", "the end of migration", "one world language"], answer: 0 },
    ],
  },
  {
    id: "g3-hist-colonial-life",
    subjectId: "history",
    level: "grade3",
    title: "Life in the Colonies",
    description: "Compare work, school, family life, and communities in colonial America.",
    emoji: "🏘️",
    questions: [
      { id: "q1", prompt: "The thirteen colonies were located along the...", choices: ["Atlantic coast", "Pacific coast", "Great Plains only", "Arctic Ocean"], answer: 0 },
      { id: "q2", prompt: "Many colonial families produced food by...", choices: ["farming", "ordering online", "using factories only", "flying planes"], answer: 0 },
      { id: "q3", prompt: "An apprentice learned a trade by...", choices: ["working with a skilled craftsperson", "watching television", "traveling to space", "avoiding practice"], answer: 0 },
      { id: "q4", prompt: "A blacksmith made useful objects from...", choices: ["iron", "paper", "wool", "glass only"], answer: 0 },
      { id: "q5", prompt: "A one-room schoolhouse often taught...", choices: ["children of several ages", "only adults", "one student ever", "sailors only"], answer: 0 },
      { id: "q6", prompt: "Town meetings gave some colonists a way to...", choices: ["discuss local decisions", "control the weather", "end all laws", "choose a king"], answer: 0 },
      { id: "q7", prompt: "Colonial society included people who were...", choices: ["enslaved and denied freedom", "all equally free", "all landowners", "all born in Europe"], answer: 0 },
      { id: "q8", prompt: "Indigenous peoples influenced colonial survival by sharing...", choices: ["knowledge of local land and crops", "factory machines", "airplane plans", "electric lights"], answer: 0 },
      { id: "q9", prompt: "Colonial regions developed differently partly because of...", choices: ["climate and natural resources", "identical geography", "one required crop", "the same jobs everywhere"], answer: 0 },
      { id: "q10", prompt: "Which source could show daily colonial life?", choices: ["A household tool from the time", "A future calendar", "A satellite photo of Mars", "A modern video game"], answer: 0 },
    ],
  },
  {
    id: "g4-hist-indigenous-early-america",
    subjectId: "history",
    level: "grade4",
    title: "Indigenous Nations & Early America",
    description: "Study Native nations, European settlement, cooperation, and conflict.",
    emoji: "🪶",
    questions: [
      { id: "q1", prompt: "Indigenous nations in North America developed cultures shaped partly by...", choices: ["their environments", "one European law", "a single language", "modern borders"], answer: 0 },
      { id: "q2", prompt: "The Haudenosaunee Great Law of Peace helped nations...", choices: ["govern together", "build Roman roads", "cross the Pacific", "end agriculture"], answer: 0 },
      { id: "q3", prompt: "Why were alliances important to both Native nations and colonists?", choices: ["They affected trade, diplomacy, and war", "They controlled seasons", "They erased all differences", "They prevented travel"], answer: 0 },
      { id: "q4", prompt: "European settlement often caused Native peoples to lose...", choices: ["land and political control", "all traditions immediately", "the ability to farm", "knowledge of geography"], answer: 0 },
      { id: "q5", prompt: "Which source best includes a Native perspective?", choices: ["An oral history from that nation", "Only a settler's map", "A fictional advertisement", "A weather chart"], answer: 0 },
      { id: "q6", prompt: "The Powhatan people lived in the region where which colony began?", choices: ["Virginia", "California", "Hawaii", "Alaska"], answer: 0 },
      { id: "q7", prompt: "The Wampanoag helped early Plymouth colonists by sharing...", choices: ["local agricultural knowledge", "steam engines", "railroad maps", "electric tools"], answer: 0 },
      { id: "q8", prompt: "Conflicts often grew when colonists...", choices: ["claimed more Indigenous land", "learned local languages", "traded fairly", "respected agreements"], answer: 0 },
      { id: "q9", prompt: "A treaty is...", choices: ["a formal agreement between nations", "a farming tool", "a type of ship", "a religious holiday"], answer: 0 },
      { id: "q10", prompt: "Why should historians use multiple sources?", choices: ["To compare perspectives and evidence", "To make every story identical", "To avoid hard questions", "To replace facts with guesses"], answer: 0 },
    ],
  },
  {
    id: "g4-hist-civic-change",
    subjectId: "history",
    level: "grade4",
    title: "Reformers & Civic Change",
    description: "Meet Americans who organized to make rights and opportunities more equal.",
    emoji: "✊",
    questions: [
      { id: "q1", prompt: "A reform movement works to...", choices: ["improve society", "avoid every change", "erase history", "replace elections with games"], answer: 0 },
      { id: "q2", prompt: "Frederick Douglass spoke and wrote against...", choices: ["slavery", "public libraries", "railroads", "national parks"], answer: 0 },
      { id: "q3", prompt: "Susan B. Anthony worked for women's right to...", choices: ["vote", "own no property", "avoid school", "serve as queen"], answer: 0 },
      { id: "q4", prompt: "The 19th Amendment protected voting rights for...", choices: ["women", "only senators", "only governors", "foreign kings"], answer: 0 },
      { id: "q5", prompt: "Rosa Parks challenged segregation by refusing to...", choices: ["give up her bus seat", "attend school", "write a speech", "join a march"], answer: 0 },
      { id: "q6", prompt: "Martin Luther King Jr. promoted change through...", choices: ["nonviolent protest", "secret voting bans", "military conquest", "ending free speech"], answer: 0 },
      { id: "q7", prompt: "The Civil Rights Act of 1964 outlawed many forms of...", choices: ["segregation and discrimination", "public education", "peaceful assembly", "newspapers"], answer: 0 },
      { id: "q8", prompt: "Cesar Chavez organized farmworkers to seek...", choices: ["fair pay and safer conditions", "fewer rights", "an end to farming", "royal titles"], answer: 0 },
      { id: "q9", prompt: "A petition shows civic participation by...", choices: ["collecting support for a requested change", "hiding an issue", "canceling all laws", "choosing a mascot"], answer: 0 },
      { id: "q10", prompt: "Which action can help create civic change?", choices: ["Speaking, organizing, voting, and serving", "Ignoring every problem", "Destroying evidence", "Silencing other views"], answer: 0 },
    ],
  },
  {
    id: "g5-hist-indigenous-america",
    subjectId: "history",
    level: "grade5",
    title: "Indigenous North America",
    description: "Examine diverse Native societies, sovereignty, and change over time.",
    emoji: "🌎",
    questions: [
      { id: "q1", prompt: "The term sovereignty means a nation has the authority to...", choices: ["govern itself", "control the weather", "ignore all agreements", "erase its history"], answer: 0 },
      { id: "q2", prompt: "Which civilization built large cities in the Mississippi River valley?", choices: ["Mississippian", "Roman", "Viking", "Mongol"], answer: 0 },
      { id: "q3", prompt: "The Three Sisters crops are...", choices: ["corn, beans, and squash", "wheat, rice, and oats", "apples, pears, and plums", "tea, coffee, and cocoa"], answer: 0 },
      { id: "q4", prompt: "The Haudenosaunee Confederacy is an example of...", choices: ["nations forming a political alliance", "a European colony", "a mining company", "a Spanish mission"], answer: 0 },
      { id: "q5", prompt: "European diseases caused devastating population loss because Indigenous peoples...", choices: ["had not developed immunity to them", "lived only in cities", "stopped growing food", "could not use medicine"], answer: 0 },
      { id: "q6", prompt: "Treaties between the United States and Native nations are...", choices: ["formal agreements", "fictional stories", "weather records", "private diaries"], answer: 0 },
      { id: "q7", prompt: "The forced removal known as the Trail of Tears affected the Cherokee and...", choices: ["other southeastern nations", "only European traders", "Roman citizens", "Canadian provinces"], answer: 0 },
      { id: "q8", prompt: "Boarding schools attempted to force Native children to...", choices: ["give up languages and cultures", "become elected leaders", "study overseas trade", "build railroads"], answer: 0 },
      { id: "q9", prompt: "Native nations today...", choices: ["continue to govern communities and sustain cultures", "exist only in history books", "all use one government", "have no distinct traditions"], answer: 0 },
      { id: "q10", prompt: "A strong historical account of Native history should...", choices: ["include Indigenous voices and sources", "rely only on stereotypes", "describe all nations as one", "end before the present"], answer: 0 },
    ],
  },
  {
    id: "g5-hist-founding-nation",
    subjectId: "history",
    level: "grade5",
    title: "Revolution & the New Nation",
    description: "Trace independence, the Constitution, and debates in the early republic.",
    emoji: "📜",
    questions: [
      { id: "q1", prompt: "Colonists protested taxation without...", choices: ["representation in Parliament", "newspapers", "local farms", "ocean trade"], answer: 0 },
      { id: "q2", prompt: "The Declaration of Independence argued that people have natural...", choices: ["rights", "titles", "armies", "monarchs"], answer: 0 },
      { id: "q3", prompt: "The American Revolution ended with independence from...", choices: ["Great Britain", "France", "Spain", "Portugal"], answer: 0 },
      { id: "q4", prompt: "A weakness of the Articles of Confederation was that the national government...", choices: ["had too little power to solve shared problems", "had an elected king", "controlled every school", "had three presidents"], answer: 0 },
      { id: "q5", prompt: "The Constitution created which three branches?", choices: ["Legislative, executive, judicial", "Local, state, global", "Army, navy, courts", "City, county, school"], answer: 0 },
      { id: "q6", prompt: "Checks and balances are designed to...", choices: ["prevent one branch from becoming too powerful", "end elections", "give judges every power", "remove state governments"], answer: 0 },
      { id: "q7", prompt: "The Bill of Rights protects...", choices: ["individual freedoms", "royal privileges", "trade routes only", "state capitals"], answer: 0 },
      { id: "q8", prompt: "Federalism divides power between...", choices: ["national and state governments", "courts and newspapers", "cities and schools only", "voters and soldiers"], answer: 0 },
      { id: "q9", prompt: "One contradiction at the nation's founding was that ideals of liberty existed alongside...", choices: ["slavery and unequal rights", "universal voting", "equal education", "peace with every nation"], answer: 0 },
      { id: "q10", prompt: "The peaceful transfer of presidential power helped establish...", choices: ["a democratic tradition", "a monarchy", "military rule", "colonial government"], answer: 0 },
    ],
  },
  {
    id: "g6-hist-egypt-kush",
    subjectId: "history",
    level: "grade6",
    title: "Ancient Egypt & Kush",
    description: "Investigate Nile societies, belief systems, trade, and leadership.",
    emoji: "𓂀",
    questions: [
      { id: "q1", prompt: "The Nile's yearly floods helped farmers by leaving...", choices: ["fertile soil", "salt deposits", "volcanic rock", "frozen ground"], answer: 0 },
      { id: "q2", prompt: "The ruler of ancient Egypt was called a...", choices: ["pharaoh", "consul", "shogun", "senator"], answer: 0 },
      { id: "q3", prompt: "Hieroglyphics were...", choices: ["an Egyptian writing system", "Roman laws", "Greek coins", "Kushite ships"], answer: 0 },
      { id: "q4", prompt: "Why did Egyptians practice mummification?", choices: ["They believed the body was needed in the afterlife", "They wanted faster travel", "They lacked tombs", "They feared written records"], answer: 0 },
      { id: "q5", prompt: "Pyramids primarily served as...", choices: ["monumental tombs", "marketplaces", "aqueducts", "harbors"], answer: 0 },
      { id: "q6", prompt: "Kush developed mainly south of Egypt along the...", choices: ["Nile", "Tigris", "Indus", "Danube"], answer: 0 },
      { id: "q7", prompt: "Kush became wealthy partly through trade in gold and...", choices: ["iron", "silk", "tea", "olive oil"], answer: 0 },
      { id: "q8", prompt: "Meroe was known as a center of...", choices: ["iron production", "Viking navigation", "democratic voting", "paper money"], answer: 0 },
      { id: "q9", prompt: "Which shows cultural exchange between Egypt and Kush?", choices: ["Shared and adapted religious and artistic traditions", "No contact at all", "Identical governments forever", "The end of trade"], answer: 0 },
      { id: "q10", prompt: "Archaeologists learn about these societies by studying...", choices: ["artifacts, buildings, and inscriptions", "future forecasts", "only legends", "modern borders"], answer: 0 },
    ],
  },
  {
    id: "g6-hist-greece",
    subjectId: "history",
    level: "grade6",
    title: "Ancient Greece",
    description: "Compare city-states and explore Greek politics, culture, and ideas.",
    emoji: "🏛️",
    questions: [
      { id: "q1", prompt: "Mountainous geography helped ancient Greece develop into separate...", choices: ["city-states", "empires overseas", "river kingdoms", "provinces of Rome"], answer: 0 },
      { id: "q2", prompt: "Athens is associated with an early form of...", choices: ["direct democracy", "feudalism", "absolute monarchy", "communism"], answer: 0 },
      { id: "q3", prompt: "Athenian democracy excluded women, enslaved people, and...", choices: ["non-citizens", "all landowners", "all soldiers", "all merchants"], answer: 0 },
      { id: "q4", prompt: "Sparta emphasized...", choices: ["military discipline", "ocean exploration", "pyramid building", "representative elections"], answer: 0 },
      { id: "q5", prompt: "The Olympic Games honored the Greek god...", choices: ["Zeus", "Ra", "Mars", "Odin"], answer: 0 },
      { id: "q6", prompt: "Socrates encouraged learning by...", choices: ["asking probing questions", "banning debate", "writing laws only", "leading armies"], answer: 0 },
      { id: "q7", prompt: "Greek myths helped explain...", choices: ["nature, values, and human behavior", "only tax records", "factory systems", "modern elections"], answer: 0 },
      { id: "q8", prompt: "Alexander the Great spread Greek culture across parts of...", choices: ["Europe, Africa, and Asia", "North America only", "Australia only", "Antarctica"], answer: 0 },
      { id: "q9", prompt: "Hellenistic culture blended Greek ideas with...", choices: ["local cultures across conquered regions", "no outside influences", "only Roman law", "only Egyptian writing"], answer: 0 },
      { id: "q10", prompt: "A lasting Greek influence can be seen in modern...", choices: ["government, theater, architecture, and science", "steam engines only", "printing presses", "air travel"], answer: 0 },
    ],
  },
  {
    id: "g6-hist-rome",
    subjectId: "history",
    level: "grade6",
    title: "Ancient Rome",
    description: "Follow Rome from republic to empire and examine its lasting influence.",
    emoji: "🏟️",
    questions: [
      { id: "q1", prompt: "In the Roman Republic, citizens elected...", choices: ["representatives", "pharaohs", "emperors for life", "foreign kings"], answer: 0 },
      { id: "q2", prompt: "The Twelve Tables were an early Roman...", choices: ["written code of laws", "calendar of festivals", "military map", "trade route"], answer: 0 },
      { id: "q3", prompt: "Roman consuls were officials who...", choices: ["led the government and army", "served as gods", "built every road", "ruled distant kingdoms"], answer: 0 },
      { id: "q4", prompt: "Julius Caesar's rise contributed to the decline of the...", choices: ["Republic", "Pax Romana", "Byzantine Empire", "Silk Road"], answer: 0 },
      { id: "q5", prompt: "Augustus became Rome's first...", choices: ["emperor", "pharaoh", "pope", "elected mayor"], answer: 0 },
      { id: "q6", prompt: "The Pax Romana was a long period of relative...", choices: ["peace and stability", "famine only", "democratic expansion", "isolation"], answer: 0 },
      { id: "q7", prompt: "Aqueducts carried...", choices: ["water to cities", "soldiers across oceans", "messages through air", "grain into pyramids"], answer: 0 },
      { id: "q8", prompt: "Roman roads helped the empire move armies, goods, and...", choices: ["information", "mountains", "rivers", "seasons"], answer: 0 },
      { id: "q9", prompt: "Christianity began in the Roman Empire and eventually...", choices: ["became its official religion", "disappeared in one year", "remained only in Egypt", "replaced all languages"], answer: 0 },
      { id: "q10", prompt: "One factor in the western empire's fall was...", choices: ["political instability and invasions", "too much democracy", "the invention of printing", "the end of roads"], answer: 0 },
    ],
  },
  {
    id: "g6-hist-india-china",
    subjectId: "history",
    level: "grade6",
    title: "Ancient India & China",
    description: "Connect river civilizations, belief systems, empires, and innovations.",
    emoji: "🪷",
    questions: [
      { id: "q1", prompt: "The Indus Valley civilization is known for...", choices: ["planned cities and drainage", "Roman roads", "Viking ships", "feudal castles"], answer: 0 },
      { id: "q2", prompt: "Hinduism developed on the Indian subcontinent and includes ideas such as...", choices: ["dharma and karma", "consuls and senates", "feudal contracts", "divine right"], answer: 0 },
      { id: "q3", prompt: "Buddhism began with the teachings of...", choices: ["Siddhartha Gautama", "Confucius", "Julius Caesar", "Hammurabi"], answer: 0 },
      { id: "q4", prompt: "Ashoka promoted Buddhism after witnessing the costs of...", choices: ["war", "trade", "farming", "writing"], answer: 0 },
      { id: "q5", prompt: "The Huang He is also called China's...", choices: ["Yellow River", "Red River", "Sacred Lake", "Grand Canal"], answer: 0 },
      { id: "q6", prompt: "The Mandate of Heaven was used to explain...", choices: ["a ruler's right to govern", "how paper was made", "river flooding", "Silk Road prices"], answer: 0 },
      { id: "q7", prompt: "Confucius emphasized...", choices: ["education, duty, and respectful relationships", "military conquest", "mummification", "direct democracy"], answer: 0 },
      { id: "q8", prompt: "The Qin dynasty is known for unifying China and standardizing...", choices: ["weights, measures, and writing", "Greek myths", "Roman law", "Egyptian religion"], answer: 0 },
      { id: "q9", prompt: "The Han dynasty expanded trade along the...", choices: ["Silk Road", "Royal Road", "Appian Way", "Northwest Passage"], answer: 0 },
      { id: "q10", prompt: "Which innovation originated in ancient China?", choices: ["Paper", "Aqueducts", "Cuneiform", "Democracy"], answer: 0 },
    ],
  },
  {
    id: "g7-hist-medieval-societies",
    subjectId: "history",
    level: "grade7",
    title: "Medieval Societies",
    description: "Compare power, belief, trade, and daily life across medieval regions.",
    emoji: "🏰",
    questions: [
      { id: "q1", prompt: "Feudalism in medieval Europe linked landholding with...", choices: ["service and loyalty", "factory wages", "direct democracy", "ocean trade only"], answer: 0 },
      { id: "q2", prompt: "A manor was...", choices: ["an agricultural estate", "a Roman senate", "a trade ship", "an Islamic school"], answer: 0 },
      { id: "q3", prompt: "The medieval Catholic Church influenced education, politics, and...", choices: ["daily life", "only farming tools", "ocean currents", "coin design only"], answer: 0 },
      { id: "q4", prompt: "The Byzantine Empire preserved and adapted...", choices: ["Greek and Roman traditions", "Mayan calendars", "Viking religion only", "Incan roads"], answer: 0 },
      { id: "q5", prompt: "The Islamic Golden Age advanced learning in mathematics, medicine, and...", choices: ["astronomy", "feudal warfare only", "mummification", "steam power"], answer: 0 },
      { id: "q6", prompt: "Mansa Musa ruled the wealthy West African empire of...", choices: ["Mali", "Rome", "Aztec", "Ottoman"], answer: 0 },
      { id: "q7", prompt: "Trans-Saharan trade exchanged gold, salt, and...", choices: ["ideas", "railroads", "steam engines", "airplanes"], answer: 0 },
      { id: "q8", prompt: "China's civil service examinations were based largely on...", choices: ["Confucian learning", "Roman law", "Viking sagas", "feudal contracts"], answer: 0 },
      { id: "q9", prompt: "The Mongol Empire increased connections across...", choices: ["Eurasia", "Antarctica", "Australia only", "the Americas only"], answer: 0 },
      { id: "q10", prompt: "The Black Death caused major population loss and...", choices: ["economic and social change", "the start of Rome", "the end of trade forever", "the invention of agriculture"], answer: 0 },
    ],
  },
  {
    id: "g7-hist-renaissance-reformation",
    subjectId: "history",
    level: "grade7",
    title: "Renaissance & Reformation",
    description: "Explore new ideas in art, learning, religion, and communication.",
    emoji: "🎨",
    questions: [
      { id: "q1", prompt: "The Renaissance began in Italian city-states partly because of wealth from...", choices: ["trade", "serfdom", "gold mines only", "Atlantic colonies"], answer: 0 },
      { id: "q2", prompt: "Humanism emphasized the study of classical texts and...", choices: ["human potential", "military obedience", "feudal taxes", "royal bloodlines"], answer: 0 },
      { id: "q3", prompt: "Renaissance artists used perspective to create an illusion of...", choices: ["depth", "sound", "motion only", "temperature"], answer: 0 },
      { id: "q4", prompt: "Leonardo da Vinci is remembered as an artist, inventor, and...", choices: ["scientific observer", "Roman emperor", "religious reformer", "feudal knight"], answer: 0 },
      { id: "q5", prompt: "Gutenberg's printing press made books...", choices: ["faster and less expensive to produce", "illegal everywhere", "available only in Latin", "handwritten again"], answer: 0 },
      { id: "q6", prompt: "Martin Luther criticized practices of the Catholic Church and helped begin the...", choices: ["Protestant Reformation", "Crusades", "Industrial Revolution", "Roman Republic"], answer: 0 },
      { id: "q7", prompt: "Printing helped Reformation ideas spread by...", choices: ["producing many copies quickly", "ending literacy", "closing universities", "blocking translation"], answer: 0 },
      { id: "q8", prompt: "The Catholic Reformation included efforts to...", choices: ["reform the Church and respond to Protestantism", "restore Roman emperors", "end all missions", "ban education"], answer: 0 },
      { id: "q9", prompt: "Religious conflict in Europe contributed to...", choices: ["wars and political change", "complete unity", "the end of monarchies immediately", "no migration"], answer: 0 },
      { id: "q10", prompt: "A major result of this era was...", choices: ["wider debate about knowledge and authority", "the end of printed books", "one church worldwide", "less interest in science"], answer: 0 },
    ],
  },
  {
    id: "g7-hist-global-exchange",
    subjectId: "history",
    level: "grade7",
    title: "Global Exploration & Exchange",
    description: "Analyze exploration, colonization, trade networks, and their consequences.",
    emoji: "🧭",
    questions: [
      { id: "q1", prompt: "European states sponsored ocean voyages mainly to gain...", choices: ["trade routes, wealth, and power", "less territory", "fewer resources", "isolation"], answer: 0 },
      { id: "q2", prompt: "Which technology helped sailors determine direction?", choices: ["Magnetic compass", "Printing press", "Steam engine", "Telegraph"], answer: 0 },
      { id: "q3", prompt: "The Columbian Exchange connected the Eastern and Western...", choices: ["Hemispheres", "mountain ranges", "empires only", "religions only"], answer: 0 },
      { id: "q4", prompt: "American crops such as maize and potatoes contributed to...", choices: ["population growth in other regions", "the end of farming", "less global trade", "the fall of Rome"], answer: 0 },
      { id: "q5", prompt: "European diseases devastated Indigenous populations because of...", choices: ["limited immunity", "poor navigation", "lack of agriculture", "cold climates only"], answer: 0 },
      { id: "q6", prompt: "Mercantilism encouraged colonies to provide...", choices: ["raw materials and markets", "equal voting rights", "independent governments", "free trade for all"], answer: 0 },
      { id: "q7", prompt: "The transatlantic slave trade forcibly transported millions of Africans to...", choices: ["the Americas", "Antarctica", "Australia only", "Japan"], answer: 0 },
      { id: "q8", prompt: "The Middle Passage was...", choices: ["the brutal Atlantic voyage endured by enslaved Africans", "a European road", "an Asian trade fair", "a peaceful treaty"], answer: 0 },
      { id: "q9", prompt: "Colonized peoples responded through adaptation, negotiation, and...", choices: ["resistance", "total acceptance only", "isolation from culture", "ending agriculture"], answer: 0 },
      { id: "q10", prompt: "A complete account of exploration should include...", choices: ["the perspectives and consequences for multiple peoples", "only explorers' achievements", "only ship designs", "no discussion of colonization"], answer: 0 },
    ],
  },
  {
    id: "g7-hist-revolutions-industry",
    subjectId: "history",
    level: "grade7",
    title: "Revolutions & Industrialization",
    description: "Connect political revolutions with the economic and social changes of industry.",
    emoji: "⚙️",
    questions: [
      { id: "q1", prompt: "Enlightenment thinkers argued that government should protect natural...", choices: ["rights", "titles", "monopolies", "armies"], answer: 0 },
      { id: "q2", prompt: "The American and French Revolutions challenged rule by...", choices: ["hereditary monarchy", "elected assemblies", "local councils", "written constitutions"], answer: 0 },
      { id: "q3", prompt: "The French Declaration of the Rights of Man promoted legal...", choices: ["equality", "serfdom", "censorship", "nobility privileges"], answer: 0 },
      { id: "q4", prompt: "The Haitian Revolution resulted in...", choices: ["an independent nation founded by formerly enslaved people", "a restored French monarchy", "the end of Caribbean agriculture", "a British colony"], answer: 0 },
      { id: "q5", prompt: "Industrialization began in Britain partly because it had coal, capital, and...", choices: ["transportation networks", "no cities", "few inventions", "no overseas trade"], answer: 0 },
      { id: "q6", prompt: "The factory system changed production by...", choices: ["concentrating workers and machines", "returning entirely to handcrafts", "ending wage labor", "eliminating cities"], answer: 0 },
      { id: "q7", prompt: "Urbanization means the growth of...", choices: ["cities", "farms", "monarchies", "oceans"], answer: 0 },
      { id: "q8", prompt: "Early factory workers often faced...", choices: ["long hours and dangerous conditions", "short days and high pay", "complete job security", "no child labor"], answer: 0 },
      { id: "q9", prompt: "Labor unions formed to seek...", choices: ["better pay and working conditions", "fewer worker protections", "longer child workdays", "an end to negotiation"], answer: 0 },
      { id: "q10", prompt: "Industrialization increased production but also created...", choices: ["pollution and social inequality", "only positive effects", "the end of migration", "less demand for resources"], answer: 0 },
    ],
  },
];