/** Brainy Buddies - 8th Grade core curriculum activities. */
import type { Activity } from "@/lib/brainy-data";

export const GRADE8_ACTIVITIES: Activity[] = [
  {
    id: "g8-math-linear-equations",
    subjectId: "math",
    level: "grade8",
    title: "Linear Equations & Systems",
    description: "Model relationships with slope, equations, and systems of linear equations.",
    emoji: "📉",
    questions: [
      { id: "q1", prompt: "What is the slope of the line through (2, 3) and (6, 11)?", choices: ["1/2", "2", "4", "8"], answer: 1, explanation: "Slope = (11 - 3) / (6 - 2) = 8 / 4 = 2." },
      { id: "q2", prompt: "Which equation has slope 3 and y-intercept -4?", choices: ["y = -4x + 3", "y = 3x - 4", "y = 4x - 3", "y = 3x + 4"], answer: 1 },
      { id: "q3", prompt: "Solve 5x - 7 = 2x + 8.", choices: ["x = 3", "x = 5", "x = 7", "x = 15"], answer: 1 },
      { id: "q4", prompt: "What is the solution to y = 2x + 1 and y = -x + 7?", choices: ["(1, 3)", "(2, 5)", "(3, 4)", "(5, 2)"], answer: 1 },
      { id: "q5", prompt: "Two parallel nonvertical lines always have...", choices: ["equal slopes", "opposite slopes", "equal y-intercepts", "slope 0"], answer: 0 },
      { id: "q6", prompt: "A line passes through (0, -2) and has slope 4. Which equation represents it?", choices: ["y = -2x + 4", "y = 4x - 2", "y = 4x + 2", "y = 2x - 4"], answer: 1 },
    ],
  },
  {
    id: "g8-math-functions-geometry",
    subjectId: "math",
    level: "grade8",
    title: "Functions, Transformations & Pythagoras",
    description: "Analyze functions and transformations, then use the Pythagorean theorem in context.",
    emoji: "📐",
    questions: [
      { id: "q1", prompt: "Which relation is a function?", choices: ["{(1, 2), (1, 3)}", "{(1, 2), (2, 3)}", "{(2, 1), (2, 4)}", "{(3, 1), (3, 2)}"], answer: 1 },
      { id: "q2", prompt: "If f(x) = 3x - 2, what is f(5)?", choices: ["8", "13", "15", "17"], answer: 1 },
      { id: "q3", prompt: "A right triangle has legs 6 and 8. What is its hypotenuse?", choices: ["10", "12", "14", "48"], answer: 0 },
      { id: "q4", prompt: "A point (3, -2) is reflected across the y-axis. Where does it land?", choices: ["(-3, -2)", "(3, 2)", "(-3, 2)", "(2, -3)"], answer: 0 },
      { id: "q5", prompt: "Which transformation changes a figure's size but preserves its shape?", choices: ["Reflection", "Rotation", "Translation", "Dilation"], answer: 3 },
      { id: "q6", prompt: "What is the distance between (1, 2) and (1, 9)?", choices: ["7", "8", "10", "11"], answer: 0 },
    ],
  },
  {
    id: "g8-sci-forces-motion",
    subjectId: "science",
    level: "grade8",
    title: "Forces, Motion & Energy",
    description: "Use Newton's laws and energy models to explain how objects move and interact.",
    emoji: "🚀",
    questions: [
      { id: "q1", prompt: "A car travels 150 meters in 10 seconds. What is its average speed?", choices: ["10 m/s", "15 m/s", "25 m/s", "1500 m/s"], answer: 1 },
      { id: "q2", prompt: "According to Newton's first law, an object's motion changes when...", choices: ["an unbalanced force acts", "its mass disappears", "time passes", "all forces are balanced"], answer: 0 },
      { id: "q3", prompt: "If the same force is applied to two objects, which accelerates more?", choices: ["The object with greater mass", "The object with less mass", "They always accelerate equally", "Neither can accelerate"], answer: 1 },
      { id: "q4", prompt: "A book resting on a table has balanced forces. The upward force is the...", choices: ["friction force", "magnetic force", "normal force", "applied force"], answer: 2 },
      { id: "q5", prompt: "Which change increases an object's kinetic energy?", choices: ["Reducing its speed", "Increasing its speed", "Lowering its height while still", "Cooling it"], answer: 1 },
      { id: "q6", prompt: "Action and reaction forces act on...", choices: ["the same object", "different objects", "only moving objects", "only objects in space"], answer: 1 },
    ],
  },
  {
    id: "g8-sci-cells-genetics",
    subjectId: "science",
    level: "grade8",
    title: "Cells, Genes & Natural Selection",
    description: "Connect cell processes, inheritance, variation, and changes in populations over time.",
    emoji: "🧬",
    questions: [
      { id: "q1", prompt: "Which organelle contains most of a eukaryotic cell's DNA?", choices: ["Cell membrane", "Nucleus", "Ribosome", "Vacuole"], answer: 1 },
      { id: "q2", prompt: "Mitosis usually produces...", choices: ["two genetically similar cells", "four genetically different cells", "one gamete", "a new species"], answer: 0 },
      { id: "q3", prompt: "A gene is best described as...", choices: ["a section of DNA with instructions", "an entire organism", "a type of cell", "an acquired behavior"], answer: 0 },
      { id: "q4", prompt: "Why can siblings inherit different combinations of traits?", choices: ["Genes vanish after birth", "Gametes carry different allele combinations", "All traits are learned", "DNA is identical in every species"], answer: 1 },
      { id: "q5", prompt: "Natural selection can change a population when a heritable trait...", choices: ["improves reproductive success", "is practiced often", "is needed by one individual", "appears in every organism at once"], answer: 0 },
      { id: "q6", prompt: "Photosynthesis stores light energy primarily in...", choices: ["glucose", "oxygen", "soil", "carbon dioxide"], answer: 0 },
    ],
  },
  {
    id: "g8-hist-us-foundations",
    subjectId: "history",
    level: "grade8",
    title: "U.S. Foundations to Reconstruction",
    description: "Evaluate the ideas, conflicts, and consequences that shaped the early United States.",
    emoji: "🏛️",
    questions: [
      { id: "q1", prompt: "Which Enlightenment idea appears in the Declaration of Independence?", choices: ["Divine right", "Natural rights", "Mercantilism", "Feudal loyalty"], answer: 1 },
      { id: "q2", prompt: "Why did the Constitution create three branches of government?", choices: ["To prevent one branch from holding all power", "To eliminate elections", "To give states no authority", "To avoid written laws"], answer: 0 },
      { id: "q3", prompt: "The Bill of Rights was added mainly to...", choices: ["protect individual liberties", "create a monarchy", "expand foreign territory", "end state governments"], answer: 0 },
      { id: "q4", prompt: "Which issue was central to the Civil War?", choices: ["Expansion and preservation of slavery", "Control of the Silk Road", "Religious rule in Europe", "The space race"], answer: 0 },
      { id: "q5", prompt: "The 13th Amendment...", choices: ["abolished slavery", "defined citizenship", "protected voting rights for women", "created the Supreme Court"], answer: 0 },
      { id: "q6", prompt: "A primary source from the Civil War era would be...", choices: ["a soldier's 1863 letter", "a modern textbook chapter", "a recent documentary", "a historian's new biography"], answer: 0 },
    ],
  },
  {
    id: "g8-geo-human-systems",
    subjectId: "geography",
    level: "grade8",
    title: "Human Systems & Global Connections",
    description: "Analyze migration, settlement, resources, trade, and human impacts across regions.",
    emoji: "🌐",
    questions: [
      { id: "q1", prompt: "Which is a pull factor that can influence migration?", choices: ["War", "Drought", "Job opportunities", "Political persecution"], answer: 2 },
      { id: "q2", prompt: "Population density measures...", choices: ["people per unit of area", "births per year only", "a country's total wealth", "distance from the Equator"], answer: 0 },
      { id: "q3", prompt: "Why are many major cities located near coasts or rivers?", choices: ["Access to transportation and trade", "Rivers prevent settlement", "Coasts have no hazards", "Elevation is always highest there"], answer: 0 },
      { id: "q4", prompt: "A renewable resource is one that...", choices: ["can replenish naturally", "can never be used", "exists only underground", "forms only over millions of years"], answer: 0 },
      { id: "q5", prompt: "Globalization generally increases...", choices: ["connections among economies and cultures", "the isolation of every country", "identical climates", "the distance between places"], answer: 0 },
      { id: "q6", prompt: "Which map is best for comparing population density by country?", choices: ["Political map", "Choropleth thematic map", "Road map", "Topographic trail map"], answer: 1 },
    ],
  },
  {
    id: "g8-lang-argument-analysis",
    subjectId: "language",
    level: "grade8",
    title: "Argument, Evidence & Style",
    description: "Evaluate claims, evidence, reasoning, word choice, and structure in complex texts.",
    emoji: "📝",
    questions: [
      { id: "q1", prompt: "Which evidence best supports a claim about student sleep?", choices: ["A friend's opinion", "A peer-reviewed study with a large sample", "An unrelated advertisement", "A fictional story"], answer: 1 },
      { id: "q2", prompt: "A counterclaim is...", choices: ["an opposing position", "a repeated conclusion", "a spelling correction", "the title of an essay"], answer: 0 },
      { id: "q3", prompt: "Which transition signals contrast?", choices: ["Similarly", "For example", "However", "Therefore"], answer: 2 },
      { id: "q4", prompt: "What makes reasoning valid in an argument?", choices: ["It logically connects evidence to the claim", "It uses the longest words", "It ignores other views", "It repeats the claim"], answer: 0 },
      { id: "q5", prompt: "Verbal irony occurs when a speaker...", choices: ["says something different from what is meant", "gives stage directions", "uses only facts", "defines a word"], answer: 0 },
      { id: "q6", prompt: "Which revision is most concise?", choices: ["Due to the fact that rain fell, the game stopped", "Because it rained, the game stopped", "Rain was a thing that caused the game to stop", "The game, because of rain falling, had stopped"], answer: 1 },
    ],
  },
  {
    id: "g8-python-data-functions",
    subjectId: "python",
    level: "grade8",
    title: "Python Functions & Data",
    description: "Reason about reusable functions, collections, and common data transformations.",
    emoji: "🐍",
    questions: [
      { id: "q1", prompt: "What does a Python function's return statement do?", choices: ["Sends a value back to the caller", "Repeats the function forever", "Imports a module", "Renames every variable"], answer: 0 },
      { id: "q2", prompt: "What is the value of [x * 2 for x in [1, 2, 3]]?", choices: ["[1, 2, 3, 2]", "[2, 4, 6]", "[1, 4, 9]", "6"], answer: 1 },
      { id: "q3", prompt: "Which Python collection stores key-value pairs?", choices: ["list", "tuple", "dictionary", "string"], answer: 2 },
      { id: "q4", prompt: "What does values.get('score', 0) provide if 'score' is missing?", choices: ["An error", "None only", "0", "The word score"], answer: 2 },
      { id: "q5", prompt: "Why use parameters in a function?", choices: ["To let the function work with different inputs", "To prevent all output", "To delete the function", "To install Python"], answer: 0 },
      { id: "q6", prompt: "Which block handles an exception in Python?", choices: ["if/else", "for/in", "try/except", "def/return"], answer: 2 },
    ],
  },
];