/**
 * Brainy Buddies — 5th Grade activities.
 * Loaded by brainy-data.ts and merged into the ACTIVITIES list.
 */
import type { Activity } from "@/lib/brainy-data";

export const GRADE5_ACTIVITIES: Activity[] = [

  // ── MATH ─────────────────────────────────────────────────────────────────

  {
    id: "g5-math-decimals",
    subjectId: "math",
    level: "grade5",
    title: "Decimals & Place Value",
    description: "Read, compare, round, add, and subtract decimals to the thousandths.",
    emoji: "🔢",
    questions: [
      { id: "q1",  prompt: "In the number 4.276, which digit is in the hundredths place?", choices: ["4", "2", "7", "6"], answer: 2, explanation: "After the decimal: 2 = tenths, 7 = hundredths, 6 = thousandths." },
      { id: "q2",  prompt: "Which decimal is the LARGEST?", choices: ["0.5", "0.45", "0.505", "0.055"], answer: 2, explanation: "0.505 is greater than 0.500 (0.5), 0.45, and 0.055." },
      { id: "q3",  prompt: "What is 3.6 + 2.45?", choices: ["5.05", "6.05", "6.5", "5.51"], answer: 1, explanation: "Line up decimals: 3.60 + 2.45 = 6.05." },
      { id: "q4",  prompt: "What is 7.5 − 2.8?", choices: ["4.3", "4.7", "5.3", "5.7"], answer: 1 },
      { id: "q5",  prompt: "Round 6.472 to the nearest tenth.", choices: ["6.4", "6.5", "6.47", "7.0"], answer: 1, explanation: "The hundredths digit is 7, so round the tenths up: 6.5." },
      { id: "q6",  prompt: "How do you write 'five and twelve hundredths' as a decimal?", choices: ["5.012", "5.12", "5.120", "512.0"], answer: 1 },
      { id: "q7",  prompt: "Which sign makes this true: 0.7 ___ 0.70?", choices: ["<", ">", "=", "≠"], answer: 2, explanation: "0.7 and 0.70 are equal — trailing zeros don't change the value." },
      { id: "q8",  prompt: "What is 10 − 3.65?", choices: ["6.35", "6.45", "7.35", "6.65"], answer: 0 },
      { id: "q9",  prompt: "Which decimal equals the fraction 3/10?", choices: ["0.03", "0.3", "3.0", "0.003"], answer: 1 },
      { id: "q10", prompt: "Round 12.849 to the nearest whole number.", choices: ["12", "12.8", "13", "12.9"], answer: 2 },
      { id: "q11", prompt: "In 58.093, what is the value of the 9?", choices: ["9 tenths", "9 hundredths", "9 thousandths", "9 ones"], answer: 1 },
      { id: "q12", prompt: "What is 4.25 + 0.75?", choices: ["4.90", "5.00", "5.10", "4.95"], answer: 1, explanation: "4.25 + 0.75 = 5.00 exactly." },
      { id: "q13", prompt: "Order from least to greatest: 0.8, 0.08, 0.88.", choices: ["0.08, 0.8, 0.88", "0.8, 0.08, 0.88", "0.88, 0.8, 0.08", "0.08, 0.88, 0.8"], answer: 0 },
      { id: "q14", prompt: "A pencil costs $0.85. How much do 2 pencils cost?", choices: ["$1.60", "$1.70", "$1.75", "$1.65"], answer: 1 },
      { id: "q15", prompt: "What is 9.4 − 6.75?", choices: ["2.65", "2.75", "3.25", "2.35"], answer: 0 },
      { id: "q16", prompt: "Which decimal is between 0.3 and 0.4?", choices: ["0.25", "0.35", "0.45", "0.5"], answer: 1 },
      { id: "q17", prompt: "Write 0.007 in words.", choices: ["seven tenths", "seven hundredths", "seven thousandths", "seven ones"], answer: 2 },
      { id: "q18", prompt: "What is 1.5 + 2.5 + 3.5?", choices: ["6.5", "7.0", "7.5", "8.0"], answer: 2, explanation: "1.5 + 2.5 = 4.0, then + 3.5 = 7.5." },
    ],
  },

  {
    id: "g5-math-decimal-ops",
    subjectId: "math",
    level: "grade5",
    title: "Multiplying & Dividing Decimals",
    description: "Multiply and divide decimals by whole numbers and powers of ten.",
    emoji: "✖️",
    questions: [
      { id: "q1",  prompt: "What is 0.6 × 4?", choices: ["2.4", "0.24", "24", "0.024"], answer: 0, explanation: "6 × 4 = 24, and there's 1 decimal place, so 2.4." },
      { id: "q2",  prompt: "What is 1.2 × 3?", choices: ["3.2", "3.6", "0.36", "36"], answer: 1 },
      { id: "q3",  prompt: "What is 4.5 × 10?", choices: ["4.5", "45", "450", "0.45"], answer: 1, explanation: "Multiplying by 10 moves the decimal one place right: 45." },
      { id: "q4",  prompt: "What is 7.8 ÷ 2?", choices: ["3.4", "3.9", "4.9", "3.8"], answer: 1 },
      { id: "q5",  prompt: "What is 0.25 × 100?", choices: ["2.5", "25", "250", "0.25"], answer: 1, explanation: "×100 moves the decimal two places right: 25." },
      { id: "q6",  prompt: "What is 9.6 ÷ 3?", choices: ["3.1", "3.2", "3.3", "3.4"], answer: 1 },
      { id: "q7",  prompt: "What is 0.4 × 0.2?", choices: ["0.8", "0.08", "0.008", "8"], answer: 1, explanation: "4 × 2 = 8, and 2 decimal places total, so 0.08." },
      { id: "q8",  prompt: "What is 6.4 ÷ 10?", choices: ["64", "0.64", "0.064", "6.4"], answer: 1, explanation: "÷10 moves the decimal one place left: 0.64." },
      { id: "q9",  prompt: "A ribbon is 2.5 m long. How long are 4 ribbons?", choices: ["8 m", "10 m", "10.5 m", "9.5 m"], answer: 1 },
      { id: "q10", prompt: "What is 12.6 ÷ 6?", choices: ["2.0", "2.1", "2.2", "2.6"], answer: 1 },
      { id: "q11", prompt: "What is 3.14 × 2?", choices: ["6.14", "6.28", "5.28", "6.24"], answer: 1 },
      { id: "q12", prompt: "What is 5.5 × 100?", choices: ["55", "550", "5,500", "5.5"], answer: 1 },
      { id: "q13", prompt: "Four friends split a $18.40 bill equally. Each pays...", choices: ["$4.10", "$4.60", "$4.40", "$4.80"], answer: 1, explanation: "18.40 ÷ 4 = 4.60." },
      { id: "q14", prompt: "What is 0.9 × 5?", choices: ["4.5", "0.45", "45", "5.4"], answer: 0 },
      { id: "q15", prompt: "What is 8.1 ÷ 9?", choices: ["0.8", "0.9", "1.0", "0.09"], answer: 1 },
      { id: "q16", prompt: "What is 2.3 × 4?", choices: ["8.2", "9.2", "9.6", "8.6"], answer: 1 },
      { id: "q17", prompt: "A hiker walks 4.5 miles each day for 6 days. What is 4.5 × 6?", choices: ["24", "27", "28", "30"], answer: 1 },
      { id: "q18", prompt: "What is 15.6 ÷ 4?", choices: ["3.6", "3.9", "4.1", "3.8"], answer: 1, explanation: "15.6 ÷ 4 = 3.9." },
    ],
  },

  {
    id: "g5-math-fractions",
    subjectId: "math",
    level: "grade5",
    title: "Fractions: Add, Subtract & Multiply",
    description: "Add and subtract fractions with unlike denominators, and multiply fractions.",
    emoji: "🍕",
    questions: [
      { id: "q1",  prompt: "What is 1/2 + 1/4?", choices: ["2/6", "3/4", "2/4", "1/6"], answer: 1, explanation: "1/2 = 2/4, so 2/4 + 1/4 = 3/4." },
      { id: "q2",  prompt: "What is 1/3 + 1/6?", choices: ["2/9", "1/2", "2/6", "1/3"], answer: 1, explanation: "1/3 = 2/6, so 2/6 + 1/6 = 3/6 = 1/2." },
      { id: "q3",  prompt: "What is 3/4 − 1/2?", choices: ["1/4", "2/2", "1/2", "2/4"], answer: 0, explanation: "1/2 = 2/4, so 3/4 − 2/4 = 1/4." },
      { id: "q4",  prompt: "What is 1/2 × 1/3?", choices: ["1/5", "1/6", "2/5", "2/6"], answer: 1, explanation: "Multiply across: 1×1=1, 2×3=6, so 1/6." },
      { id: "q5",  prompt: "What is 2/3 × 1/2?", choices: ["2/5", "1/3", "3/5", "2/6"], answer: 1, explanation: "2/6 simplifies to 1/3." },
      { id: "q6",  prompt: "What is 5/6 − 1/3?", choices: ["1/2", "4/6", "1/3", "4/3"], answer: 0, explanation: "1/3 = 2/6, so 5/6 − 2/6 = 3/6 = 1/2." },
      { id: "q7",  prompt: "What is 1/4 + 1/4 + 1/4?", choices: ["1/12", "3/4", "3/12", "1/4"], answer: 1 },
      { id: "q8",  prompt: "What is 3 × 2/5?", choices: ["5/6", "6/5", "5/5", "6/15"], answer: 1, explanation: "3 × 2/5 = 6/5 (or 1 1/5)." },
      { id: "q9",  prompt: "Which fraction is equivalent to 2/3?", choices: ["3/4", "4/6", "2/6", "3/6"], answer: 1 },
      { id: "q10", prompt: "What is 7/8 − 3/8?", choices: ["4/8", "1/2", "Both A and B", "4/16"], answer: 2, explanation: "7/8 − 3/8 = 4/8, which equals 1/2." },
      { id: "q11", prompt: "What is 1/2 of 10?", choices: ["4", "5", "6", "20"], answer: 1 },
      { id: "q12", prompt: "What is 2/3 + 1/4?", choices: ["3/7", "11/12", "5/12", "3/12"], answer: 1, explanation: "Common denom 12: 8/12 + 3/12 = 11/12." },
      { id: "q13", prompt: "A recipe needs 3/4 cup flour. You make half the recipe. How much flour?", choices: ["1/4 cup", "3/8 cup", "1/2 cup", "3/4 cup"], answer: 1, explanation: "1/2 × 3/4 = 3/8 cup." },
      { id: "q14", prompt: "What is 5/6 as a mixed number if it were 7/6?", choices: ["1 1/6", "1 1/7", "7/6", "1 6/7"], answer: 0, explanation: "7/6 = 6/6 + 1/6 = 1 1/6." },
      { id: "q15", prompt: "What is 3/4 × 4?", choices: ["3", "4", "12", "3/16"], answer: 0, explanation: "3/4 × 4 = 12/4 = 3." },
      { id: "q16", prompt: "What is 1 − 1/3?", choices: ["1/3", "2/3", "1/2", "3/3"], answer: 1, explanation: "1 = 3/3, so 3/3 − 1/3 = 2/3." },
      { id: "q17", prompt: "Which is greater: 3/5 or 1/2?", choices: ["3/5", "1/2", "They're equal", "Can't tell"], answer: 0, explanation: "3/5 = 6/10 and 1/2 = 5/10, so 3/5 is greater." },
      { id: "q18", prompt: "What is 2/5 + 2/5?", choices: ["4/10", "4/5", "2/5", "4/25"], answer: 1 },
    ],
  },

  {
    id: "g5-math-operations",
    subjectId: "math",
    level: "grade5",
    title: "Order of Operations",
    description: "Use PEMDAS to solve expressions with parentheses, multiplication, and more.",
    emoji: "🧮",
    questions: [
      { id: "q1",  prompt: "What is 2 + 3 × 4?", choices: ["20", "14", "24", "11"], answer: 1, explanation: "Multiply first: 3×4=12, then 2+12 = 14." },
      { id: "q2",  prompt: "What is (2 + 3) × 4?", choices: ["14", "20", "24", "10"], answer: 1, explanation: "Parentheses first: 2+3=5, then 5×4 = 20." },
      { id: "q3",  prompt: "In PEMDAS, what does the 'P' stand for?", choices: ["Plus", "Parentheses", "Powers", "Product"], answer: 1 },
      { id: "q4",  prompt: "What is 10 − 2 × 3?", choices: ["24", "4", "8", "6"], answer: 1, explanation: "2×3=6 first, then 10−6 = 4." },
      { id: "q5",  prompt: "What is 12 ÷ 4 + 2?", choices: ["5", "2", "12", "6"], answer: 0, explanation: "12÷4=3, then 3+2 = 5." },
      { id: "q6",  prompt: "What is 3 × (6 − 2)?", choices: ["16", "12", "10", "14"], answer: 1, explanation: "6−2=4 first, then 3×4 = 12." },
      { id: "q7",  prompt: "What is 5 + 4 × 2 − 1?", choices: ["16", "12", "17", "9"], answer: 1, explanation: "4×2=8, then 5+8−1 = 12." },
      { id: "q8",  prompt: "What is 2 × 3 + 4 × 5?", choices: ["50", "26", "70", "34"], answer: 1, explanation: "6 + 20 = 26 (do both multiplications first)." },
      { id: "q9",  prompt: "What is (8 + 2) ÷ 5?", choices: ["1", "2", "3", "10"], answer: 1, explanation: "8+2=10, then 10÷5 = 2." },
      { id: "q10", prompt: "What is 4 + 2²?", choices: ["12", "8", "36", "16"], answer: 1, explanation: "2²=4 (exponent first), then 4+4 = 8." },
      { id: "q11", prompt: "What is 20 ÷ (2 + 3)?", choices: ["4", "13", "10", "5"], answer: 0, explanation: "2+3=5 first, then 20÷5 = 4." },
      { id: "q12", prompt: "What is 6 + 6 ÷ 6?", choices: ["2", "7", "1", "12"], answer: 1, explanation: "6÷6=1 first, then 6+1 = 7." },
      { id: "q13", prompt: "What is 3² + 1?", choices: ["7", "10", "9", "12"], answer: 1, explanation: "3²=9, then 9+1 = 10." },
      { id: "q14", prompt: "What is (10 − 4) × (2 + 1)?", choices: ["18", "15", "12", "21"], answer: 0, explanation: "6 × 3 = 18." },
      { id: "q15", prompt: "What is 15 − 3 × 2 + 4?", choices: ["28", "13", "20", "10"], answer: 1, explanation: "3×2=6, then 15−6+4 = 13." },
      { id: "q16", prompt: "Which operation comes FIRST in 8 − 2 + 5?", choices: ["Addition", "Subtraction (left to right)", "Either", "Multiplication"], answer: 1, explanation: "With only + and −, work left to right: 8−2 first." },
      { id: "q17", prompt: "What is 2 × (5 + 3) − 4?", choices: ["12", "14", "10", "16"], answer: 0, explanation: "5+3=8, 2×8=16, then 16−4 = 12." },
      { id: "q18", prompt: "What is 100 ÷ 10 ÷ 2?", choices: ["20", "5", "2", "50"], answer: 1, explanation: "Left to right: 100÷10=10, then 10÷2 = 5." },
    ],
  },

  {
    id: "g5-math-geometry",
    subjectId: "math",
    level: "grade5",
    title: "Volume, Area & Geometry",
    description: "Find volume of rectangular prisms, area, perimeter, and plot points.",
    emoji: "📐",
    questions: [
      { id: "q1",  prompt: "What is the volume of a box that is 3 × 4 × 2?", choices: ["9", "24", "14", "48"], answer: 1, explanation: "Volume = length × width × height = 3×4×2 = 24 cubic units." },
      { id: "q2",  prompt: "What unit is used to measure VOLUME?", choices: ["Square units", "Linear units", "Cubic units", "Degrees"], answer: 2 },
      { id: "q3",  prompt: "What is the area of a rectangle 6 cm by 5 cm?", choices: ["11 cm²", "22 cm²", "30 cm²", "60 cm²"], answer: 2, explanation: "Area = length × width = 6×5 = 30 cm²." },
      { id: "q4",  prompt: "What is the perimeter of a square with sides of 7 cm?", choices: ["14 cm", "21 cm", "28 cm", "49 cm"], answer: 2, explanation: "Perimeter = 4 × side = 4×7 = 28 cm." },
      { id: "q5",  prompt: "A cube has edges of 5 units. What is its volume?", choices: ["15", "25", "100", "125"], answer: 3, explanation: "Volume of a cube = side³ = 5×5×5 = 125." },
      { id: "q6",  prompt: "On a coordinate grid, the point (0, 0) is called the...", choices: ["Axis", "Origin", "Quadrant", "Center point"], answer: 1 },
      { id: "q7",  prompt: "In the point (3, 5), which number is the x-coordinate?", choices: ["3", "5", "8", "Neither"], answer: 0, explanation: "The x-coordinate always comes first: (x, y)." },
      { id: "q8",  prompt: "A triangle's angles always add up to...", choices: ["90°", "180°", "270°", "360°"], answer: 1 },
      { id: "q9",  prompt: "What is the area of a triangle with base 8 and height 4?", choices: ["12", "16", "24", "32"], answer: 1, explanation: "Area = ½ × base × height = ½ × 8 × 4 = 16." },
      { id: "q10", prompt: "A fish tank is 10 × 4 × 6 inches. Its volume is...", choices: ["120 in³", "200 in³", "240 in³", "60 in³"], answer: 2, explanation: "10 × 4 × 6 = 240 cubic inches." },
      { id: "q11", prompt: "A shape with 4 equal sides and 4 right angles is a...", choices: ["Rectangle", "Rhombus", "Square", "Trapezoid"], answer: 2 },
      { id: "q12", prompt: "How many degrees are in a right angle?", choices: ["45°", "90°", "180°", "360°"], answer: 1 },
      { id: "q13", prompt: "To find the volume of a prism you multiply the area of the base by the...", choices: ["Width", "Perimeter", "Height", "Length only"], answer: 2 },
      { id: "q14", prompt: "A rectangle is 12 m long with a perimeter of 32 m. What is its width?", choices: ["4 m", "6 m", "8 m", "10 m"], answer: 0, explanation: "32 = 2(12 + w), so 16 = 12 + w, w = 4 m." },
      { id: "q15", prompt: "Which quadrilateral has exactly one pair of parallel sides?", choices: ["Square", "Rectangle", "Trapezoid", "Rhombus"], answer: 2 },
      { id: "q16", prompt: "A point is plotted 4 right and 2 up from the origin. Its coordinates are...", choices: ["(2, 4)", "(4, 2)", "(4, 4)", "(2, 2)"], answer: 1 },
      { id: "q17", prompt: "How many faces does a cube have?", choices: ["4", "6", "8", "12"], answer: 1 },
      { id: "q18", prompt: "Two boxes each 2×2×2 are stacked. What is the total volume?", choices: ["8", "12", "16", "24"], answer: 2, explanation: "Each box = 8, and 8 + 8 = 16 cubic units." },
    ],
  },

  // ── SCIENCE ──────────────────────────────────────────────────────────────

  {
    id: "g5-sci-matter",
    subjectId: "science",
    level: "grade5",
    title: "Matter & Its Changes",
    description: "Explore states of matter, mixtures, and physical vs. chemical changes.",
    emoji: "⚗️",
    questions: [
      { id: "q1",  prompt: "Everything around us that has mass and takes up space is called...", choices: ["Energy", "Matter", "Force", "Gravity"], answer: 1 },
      { id: "q2",  prompt: "Which is NOT one of the three common states of matter?", choices: ["Solid", "Liquid", "Gas", "Energy"], answer: 3 },
      { id: "q3",  prompt: "When ice melts into water, this is an example of a...", choices: ["Chemical change", "Physical change", "New substance", "Reaction"], answer: 1, explanation: "Melting changes the state but it's still water — a physical change." },
      { id: "q4",  prompt: "When wood burns and turns to ash, this is a...", choices: ["Physical change", "Chemical change", "Change of state", "Reversible change"], answer: 1, explanation: "Burning creates new substances (ash, smoke) — a chemical change." },
      { id: "q5",  prompt: "Tiny particles that make up all matter are called...", choices: ["Cells", "Atoms", "Molecules only", "Germs"], answer: 1 },
      { id: "q6",  prompt: "A mixture of salt fully dissolved in water is called a...", choices: ["Suspension", "Solution", "Compound", "Colloid"], answer: 1 },
      { id: "q7",  prompt: "Which state of matter has a fixed shape and fixed volume?", choices: ["Gas", "Liquid", "Solid", "Plasma"], answer: 2 },
      { id: "q8",  prompt: "When water turns to steam (gas), the process is called...", choices: ["Condensation", "Freezing", "Evaporation", "Melting"], answer: 2 },
      { id: "q9",  prompt: "When water vapor cools and turns back into liquid, it is called...", choices: ["Evaporation", "Condensation", "Sublimation", "Melting"], answer: 1 },
      { id: "q10", prompt: "Which of these is a sign that a CHEMICAL change happened?", choices: ["Ice cube melts", "Paper is folded", "A new gas or color forms", "Water is poured"], answer: 2 },
      { id: "q11", prompt: "Gases like the air in a balloon...", choices: ["Have a fixed shape", "Take the shape of their container", "Cannot be squeezed", "Are always visible"], answer: 1 },
      { id: "q12", prompt: "Mixing sand and water makes a mixture where the sand can be...", choices: ["Never separated", "Filtered out again", "Turned into a new substance", "Dissolved completely"], answer: 1, explanation: "Sand doesn't dissolve; it can be filtered — showing it's a mixture." },
      { id: "q13", prompt: "The temperature at which water freezes is...", choices: ["0°C (32°F)", "100°C (212°F)", "50°C", "−10°C"], answer: 0 },
      { id: "q14", prompt: "When you dissolve sugar in water, the sugar particles...", choices: ["Disappear forever", "Spread evenly between water particles", "Turn into water", "React chemically"], answer: 1 },
      { id: "q15", prompt: "Which change can usually be REVERSED?", choices: ["Baking a cake", "Rusting iron", "Freezing water", "Burning a log"], answer: 2, explanation: "Freezing is physical and reversible; the others form new substances." },
      { id: "q16", prompt: "The amount of matter in an object is its...", choices: ["Volume", "Weight", "Mass", "Density"], answer: 2 },
      { id: "q17", prompt: "The temperature at which water boils at sea level is...", choices: ["50°C", "0°C", "100°C", "212°C"], answer: 2 },
      { id: "q18", prompt: "Rusting metal is a chemical change because...", choices: ["The metal melts", "A new substance (rust) forms", "It changes shape", "It gets colder"], answer: 1 },
    ],
  },

  {
    id: "g5-sci-ecosystems",
    subjectId: "science",
    level: "grade5",
    title: "Ecosystems & Food Webs",
    description: "Learn how energy flows through producers, consumers, and decomposers.",
    emoji: "🌿",
    questions: [
      { id: "q1",  prompt: "Organisms that make their own food using sunlight are called...", choices: ["Consumers", "Producers", "Decomposers", "Predators"], answer: 1, explanation: "Plants are producers — they make food through photosynthesis." },
      { id: "q2",  prompt: "An animal that eats ONLY plants is a...", choices: ["Carnivore", "Herbivore", "Omnivore", "Decomposer"], answer: 1 },
      { id: "q3",  prompt: "An animal that eats ONLY other animals is a...", choices: ["Herbivore", "Producer", "Carnivore", "Omnivore"], answer: 2 },
      { id: "q4",  prompt: "Organisms like fungi and bacteria that break down dead matter are...", choices: ["Producers", "Consumers", "Decomposers", "Predators"], answer: 2 },
      { id: "q5",  prompt: "The original source of energy for almost every food web is the...", choices: ["Soil", "Sun", "Water", "Wind"], answer: 1 },
      { id: "q6",  prompt: "In a food chain, an arrow points in the direction that...", choices: ["Energy flows", "Animals walk", "The sun shines", "Water moves"], answer: 0, explanation: "Arrows show energy flowing FROM the food TO the eater." },
      { id: "q7",  prompt: "A living thing's role or 'job' in its ecosystem is called its...", choices: ["Habitat", "Niche", "Biome", "Population"], answer: 1 },
      { id: "q8",  prompt: "The place where an organism lives is its...", choices: ["Niche", "Habitat", "Community", "Food web"], answer: 1 },
      { id: "q9",  prompt: "An animal that eats both plants and animals is an...", choices: ["Herbivore", "Carnivore", "Omnivore", "Producer"], answer: 2 },
      { id: "q10", prompt: "During photosynthesis, plants take in carbon dioxide and release...", choices: ["Nitrogen", "Oxygen", "Hydrogen", "Water vapor only"], answer: 1 },
      { id: "q11", prompt: "If all the plants in an ecosystem died, what would happen first to herbivores?", choices: ["They would thrive", "They would lose their food source", "They would become producers", "Nothing"], answer: 1 },
      { id: "q12", prompt: "A group of the same species living in one area is a...", choices: ["Community", "Population", "Ecosystem", "Biome"], answer: 1 },
      { id: "q13", prompt: "Which of these is a decomposer?", choices: ["Rabbit", "Mushroom", "Hawk", "Grass"], answer: 1 },
      { id: "q14", prompt: "A large region defined by its climate, plants, and animals (like a desert) is a...", choices: ["Habitat", "Niche", "Biome", "Population"], answer: 2 },
      { id: "q15", prompt: "Animals that hunt other animals for food are called...", choices: ["Prey", "Predators", "Producers", "Herbivores"], answer: 1 },
      { id: "q16", prompt: "As energy moves up a food chain, the amount of available energy...", choices: ["Increases", "Decreases", "Stays the same", "Disappears completely"], answer: 1, explanation: "Energy is lost as heat at each step, so less is available higher up." },
      { id: "q17", prompt: "A food WEB is different from a food chain because it shows...", choices: ["Only one path", "Many connected feeding paths", "Only plants", "Only the sun"], answer: 1 },
      { id: "q18", prompt: "Which is an example of adaptation?", choices: ["A cactus storing water in its stem", "A rock rolling downhill", "Rain falling", "A car moving"], answer: 0, explanation: "Adaptations are traits that help a living thing survive its environment." },
    ],
  },

  {
    id: "g5-sci-space",
    subjectId: "science",
    level: "grade5",
    title: "Earth, Sun & Solar System",
    description: "Understand day and night, seasons, moon phases, and the planets.",
    emoji: "🪐",
    questions: [
      { id: "q1",  prompt: "What causes day and night on Earth?", choices: ["Earth orbits the Sun", "Earth rotates on its axis", "The Moon blocks the Sun", "Clouds move"], answer: 1, explanation: "Earth spins on its axis once every 24 hours, giving us day and night." },
      { id: "q2",  prompt: "How long does Earth take to orbit (revolve around) the Sun once?", choices: ["24 hours", "1 month", "1 year", "1 week"], answer: 2 },
      { id: "q3",  prompt: "Which planet is closest to the Sun?", choices: ["Venus", "Earth", "Mercury", "Mars"], answer: 2 },
      { id: "q4",  prompt: "Which is the LARGEST planet in our solar system?", choices: ["Saturn", "Jupiter", "Neptune", "Earth"], answer: 1 },
      { id: "q5",  prompt: "The changing shapes of the Moon we see are called moon...", choices: ["Rotations", "Phases", "Eclipses", "Orbits"], answer: 1 },
      { id: "q6",  prompt: "What causes Earth's seasons?", choices: ["Distance from the Sun", "Earth's tilted axis as it orbits the Sun", "The Moon's gravity", "Clouds and rain"], answer: 1, explanation: "Earth's axis is tilted, so different areas get more direct sunlight at different times." },
      { id: "q7",  prompt: "The Sun is a...", choices: ["Planet", "Moon", "Star", "Comet"], answer: 2 },
      { id: "q8",  prompt: "Which planet is known as the 'Red Planet'?", choices: ["Venus", "Mars", "Jupiter", "Saturn"], answer: 1 },
      { id: "q9",  prompt: "How many planets are in our solar system?", choices: ["7", "8", "9", "10"], answer: 1, explanation: "There are 8 planets since Pluto was reclassified as a dwarf planet." },
      { id: "q10", prompt: "A moon that orbits a planet is also called a...", choices: ["Star", "Satellite", "Comet", "Meteor"], answer: 1 },
      { id: "q11", prompt: "Which planet is famous for its beautiful rings?", choices: ["Mars", "Saturn", "Mercury", "Venus"], answer: 1 },
      { id: "q12", prompt: "When the Moon passes between the Sun and Earth, blocking the Sun, it is a...", choices: ["Lunar eclipse", "Solar eclipse", "Full moon", "New moon"], answer: 1 },
      { id: "q13", prompt: "Earth is the ___ planet from the Sun.", choices: ["1st", "2nd", "3rd", "4th"], answer: 2 },
      { id: "q14", prompt: "The force that keeps planets orbiting the Sun is...", choices: ["Magnetism", "Gravity", "Friction", "Wind"], answer: 1 },
      { id: "q15", prompt: "Why does the Sun look bigger and brighter than other stars?", choices: ["It is the biggest star", "It is much closer to Earth", "It is the hottest star", "It never sets"], answer: 1 },
      { id: "q16", prompt: "A full rotation of Earth on its axis takes about...", choices: ["1 hour", "12 hours", "24 hours", "365 days"], answer: 2 },
      { id: "q17", prompt: "The planets, asteroids, and comets that orbit the Sun make up the...", choices: ["Galaxy", "Universe", "Solar System", "Milky Way"], answer: 2 },
      { id: "q18", prompt: "Shooting stars are actually small space rocks burning up in Earth's atmosphere, called...", choices: ["Comets", "Meteors", "Satellites", "Asteroids"], answer: 1 },
    ],
  },

  {
    id: "g5-sci-body",
    subjectId: "science",
    level: "grade5",
    title: "Human Body Systems",
    description: "Discover how the organs and systems in your body work together.",
    emoji: "🫀",
    questions: [
      { id: "q1",  prompt: "Which organ pumps blood throughout the body?", choices: ["Lungs", "Brain", "Heart", "Liver"], answer: 2 },
      { id: "q2",  prompt: "The system that includes the heart and blood vessels is the...", choices: ["Digestive system", "Circulatory system", "Nervous system", "Skeletal system"], answer: 1 },
      { id: "q3",  prompt: "Which organs allow you to breathe in oxygen?", choices: ["Kidneys", "Lungs", "Stomach", "Liver"], answer: 1 },
      { id: "q4",  prompt: "The system that breaks down food so your body can use it is the...", choices: ["Respiratory system", "Digestive system", "Muscular system", "Nervous system"], answer: 1 },
      { id: "q5",  prompt: "Which organ is the control center of the nervous system?", choices: ["Heart", "Brain", "Stomach", "Lungs"], answer: 1 },
      { id: "q6",  prompt: "Bones together make up the body's ___ system.", choices: ["Muscular", "Skeletal", "Digestive", "Circulatory"], answer: 1 },
      { id: "q7",  prompt: "Which body part carries messages between the brain and body?", choices: ["Blood vessels", "Nerves", "Muscles", "Bones"], answer: 1 },
      { id: "q8",  prompt: "Blood carries oxygen to the body using tiny cells called...", choices: ["White blood cells", "Red blood cells", "Nerve cells", "Skin cells"], answer: 1 },
      { id: "q9",  prompt: "Muscles help you move by...", choices: ["Growing longer only", "Contracting (pulling) on bones", "Storing food", "Filtering blood"], answer: 1 },
      { id: "q10", prompt: "Which organ filters waste out of the blood to make urine?", choices: ["Liver", "Kidneys", "Lungs", "Heart"], answer: 1 },
      { id: "q11", prompt: "The largest organ of the human body is the...", choices: ["Heart", "Brain", "Skin", "Liver"], answer: 2 },
      { id: "q12", prompt: "When you breathe in, your lungs take in oxygen and get rid of...", choices: ["Nitrogen", "Carbon dioxide", "Water only", "Hydrogen"], answer: 1 },
      { id: "q13", prompt: "The tube that carries food from your mouth to your stomach is the...", choices: ["Windpipe", "Esophagus", "Intestine", "Vein"], answer: 1 },
      { id: "q14", prompt: "Which system works with bones to help you move?", choices: ["Digestive system", "Muscular system", "Respiratory system", "Circulatory system"], answer: 1 },
      { id: "q15", prompt: "Most of the digestion and absorbing of nutrients happens in the...", choices: ["Stomach", "Small intestine", "Mouth", "Liver"], answer: 1 },
      { id: "q16", prompt: "Your heart is mostly made of which type of tissue?", choices: ["Bone", "Muscle", "Skin", "Fat"], answer: 1 },
      { id: "q17", prompt: "The rib cage's main job is to...", choices: ["Help you digest food", "Protect the heart and lungs", "Filter blood", "Send nerve signals"], answer: 1 },
      { id: "q18", prompt: "Body systems are important because they...", choices: ["Work alone and never connect", "Work together to keep you alive", "Only work when you sleep", "Only matter for athletes"], answer: 1 },
    ],
  },

  {
    id: "g5-sci-energy",
    subjectId: "science",
    level: "grade5",
    title: "Energy, Force & Motion",
    description: "Explore forms of energy, gravity, friction, and how forces move objects.",
    emoji: "⚡",
    questions: [
      { id: "q1",  prompt: "A push or a pull on an object is called a...", choices: ["Speed", "Force", "Mass", "Weight"], answer: 1 },
      { id: "q2",  prompt: "The force that pulls objects toward the center of the Earth is...", choices: ["Friction", "Gravity", "Magnetism", "Electricity"], answer: 1 },
      { id: "q3",  prompt: "The force that slows objects down when they rub together is...", choices: ["Gravity", "Friction", "Magnetism", "Momentum"], answer: 1 },
      { id: "q4",  prompt: "Energy that is stored and ready to be used is called ___ energy.", choices: ["Kinetic", "Potential", "Thermal", "Solar"], answer: 1, explanation: "Potential energy is stored energy, like a stretched rubber band." },
      { id: "q5",  prompt: "Energy of MOTION is called ___ energy.", choices: ["Potential", "Kinetic", "Chemical", "Nuclear"], answer: 1 },
      { id: "q6",  prompt: "Energy from the Sun is called ___ energy.", choices: ["Nuclear", "Solar", "Wind", "Sound"], answer: 1 },
      { id: "q7",  prompt: "Which of these is a form of energy?", choices: ["Light", "Heat", "Sound", "All of these"], answer: 3 },
      { id: "q8",  prompt: "A ball at the top of a hill has a lot of ___ energy.", choices: ["Kinetic", "Potential", "Sound", "Electrical"], answer: 1 },
      { id: "q9",  prompt: "When you turn on a lamp, electrical energy changes into light and ___ energy.", choices: ["Sound", "Heat", "Chemical", "Nuclear"], answer: 1 },
      { id: "q10", prompt: "Which surface would create the MOST friction?", choices: ["Smooth ice", "Rough sandpaper", "Polished glass", "Wet tile"], answer: 1 },
      { id: "q11", prompt: "Energy cannot be created or destroyed, only...", choices: ["Multiplied", "Changed from one form to another", "Deleted", "Frozen"], answer: 1 },
      { id: "q12", prompt: "A magnet attracts objects made of...", choices: ["Wood", "Plastic", "Iron", "Glass"], answer: 2 },
      { id: "q13", prompt: "The energy stored in food and batteries is ___ energy.", choices: ["Chemical", "Solar", "Sound", "Light"], answer: 0 },
      { id: "q14", prompt: "When a moving car's brakes are used, friction turns motion energy into...", choices: ["Light", "Heat", "Sound only", "Gravity"], answer: 1 },
      { id: "q15", prompt: "The greater an object's mass and speed, the more ___ energy it has.", choices: ["Potential", "Kinetic", "Solar", "Electrical"], answer: 1 },
      { id: "q16", prompt: "Which is a renewable energy source?", choices: ["Coal", "Oil", "Wind", "Natural gas"], answer: 2 },
      { id: "q17", prompt: "If no force acts on a still object, it will...", choices: ["Speed up", "Stay still", "Fall down", "Turn"], answer: 1, explanation: "An object at rest stays at rest unless a force acts on it." },
      { id: "q18", prompt: "A roller coaster car speeding down a hill is changing potential energy into...", choices: ["Chemical energy", "Kinetic energy", "Light energy", "Nuclear energy"], answer: 1 },
    ],
  },

  // ── HISTORY ──────────────────────────────────────────────────────────────

  {
    id: "g5-hist-exploration",
    subjectId: "history",
    level: "grade5",
    title: "Age of Exploration",
    description: "Meet the explorers who connected continents and changed the world.",
    emoji: "🧭",
    questions: [
      { id: "q1",  prompt: "In 1492, which explorer sailed west and reached the Americas while looking for Asia?", choices: ["Ferdinand Magellan", "Christopher Columbus", "Vasco da Gama", "Marco Polo"], answer: 1 },
      { id: "q2",  prompt: "Columbus's voyage was funded by which country?", choices: ["England", "France", "Spain", "Portugal"], answer: 2 },
      { id: "q3",  prompt: "Which explorer's crew was the first to sail all the way around the world?", choices: ["Columbus", "Magellan", "Hudson", "Cortés"], answer: 1, explanation: "Magellan's expedition completed the first circumnavigation (though he died along the way)." },
      { id: "q4",  prompt: "The exchange of plants, animals, and diseases between the Americas and Europe is called the ___ Exchange.", choices: ["Atlantic", "Columbian", "European", "Spanish"], answer: 1 },
      { id: "q5",  prompt: "Which of these foods came from the Americas to Europe?", choices: ["Wheat", "Potatoes", "Rice", "Bananas"], answer: 1 },
      { id: "q6",  prompt: "European explorers were searching for new sea routes to trade for spices and silk from...", choices: ["Africa", "Asia", "Australia", "Antarctica"], answer: 1 },
      { id: "q7",  prompt: "The Native peoples already living in the Americas when Europeans arrived are called...", choices: ["Colonists", "Indigenous peoples", "Pilgrims", "Settlers"], answer: 1 },
      { id: "q8",  prompt: "Which explorer conquered the Aztec Empire in Mexico?", choices: ["Francisco Pizarro", "Hernán Cortés", "John Cabot", "Henry Hudson"], answer: 1 },
      { id: "q9",  prompt: "The invention of the ___ helped sailors find direction at sea.", choices: ["Telescope", "Compass", "Printing press", "Steam engine"], answer: 1 },
      { id: "q10", prompt: "One tragic result of European contact was the spread of ___ that killed many Native Americans.", choices: ["New foods", "Diseases", "Maps", "Gold"], answer: 1 },
      { id: "q11", prompt: "Henry Hudson explored the river and bay in North America that now bear his...", choices: ["Ship's name", "Name", "Country's name", "King's name"], answer: 1 },
      { id: "q12", prompt: "Which explorer conquered the Inca Empire in South America?", choices: ["Hernán Cortés", "Francisco Pizarro", "Amerigo Vespucci", "Vasco da Gama"], answer: 1 },
      { id: "q13", prompt: "The Americas were named after which explorer?", choices: ["Christopher Columbus", "Amerigo Vespucci", "Ferdinand Magellan", "John Cabot"], answer: 1 },
      { id: "q14", prompt: "Portuguese explorer Vasco da Gama found a sea route to India by sailing around...", choices: ["South America", "Africa", "Australia", "Europe"], answer: 1 },
      { id: "q15", prompt: "Spanish explorers searching for gold and glory in the Americas were called...", choices: ["Pilgrims", "Conquistadors", "Pioneers", "Puritans"], answer: 1 },
      { id: "q16", prompt: "Which crop native to the Americas became a hugely important food crop worldwide?", choices: ["Corn (maize)", "Wheat", "Barley", "Oats"], answer: 0 },
      { id: "q17", prompt: "The time period of major European ocean voyages (1400s–1600s) is called the Age of...", choices: ["Empires", "Exploration", "Revolution", "Industry"], answer: 1 },
      { id: "q18", prompt: "Horses were brought to the Americas by which group?", choices: ["Native Americans", "Europeans", "Africans", "Asians"], answer: 1, explanation: "Horses came from Europe and greatly changed life for many Native American nations." },
    ],
  },

  {
    id: "g5-hist-civilwar",
    subjectId: "history",
    level: "grade5",
    title: "The Civil War & Reconstruction",
    description: "Learn how America was divided, reunited, and worked to rebuild.",
    emoji: "🎖️",
    questions: [
      { id: "q1",  prompt: "The American Civil War was fought between the Northern states (Union) and the Southern states (the...)", choices: ["Colonies", "Confederacy", "Allies", "Republic"], answer: 1 },
      { id: "q2",  prompt: "Who was President of the United States during the Civil War?", choices: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "Andrew Jackson"], answer: 2 },
      { id: "q3",  prompt: "A major cause of the Civil War was a disagreement over...", choices: ["Trade with Europe", "Slavery", "The national anthem", "Building railroads"], answer: 1 },
      { id: "q4",  prompt: "In what year did the Civil War begin?", choices: ["1776", "1812", "1861", "1901"], answer: 2 },
      { id: "q5",  prompt: "The document Lincoln issued in 1863 to free enslaved people in Confederate states was the...", choices: ["Bill of Rights", "Emancipation Proclamation", "Declaration of Independence", "Gettysburg Address"], answer: 1 },
      { id: "q6",  prompt: "Who led the Confederate Army as its top general?", choices: ["Ulysses S. Grant", "Robert E. Lee", "George McClellan", "Stonewall Jackson"], answer: 1 },
      { id: "q7",  prompt: "Who was the top Union general and later became President?", choices: ["Robert E. Lee", "Ulysses S. Grant", "William Sherman", "George Meade"], answer: 1 },
      { id: "q8",  prompt: "The famous speech Lincoln gave honoring soldiers at a battlefield was the...", choices: ["Emancipation Proclamation", "Gettysburg Address", "Farewell Address", "State of the Union"], answer: 1 },
      { id: "q9",  prompt: "The Civil War ended in 1865 when General Lee surrendered at...", choices: ["Gettysburg", "Appomattox Court House", "Fort Sumter", "Bull Run"], answer: 1 },
      { id: "q10", prompt: "The 13th Amendment to the Constitution officially...", choices: ["Gave women the vote", "Abolished (ended) slavery", "Created income tax", "Ended the war"], answer: 1 },
      { id: "q11", prompt: "The period after the war when the nation worked to rebuild the South was called...", choices: ["The Gilded Age", "Reconstruction", "The Great Depression", "Manifest Destiny"], answer: 1 },
      { id: "q12", prompt: "Harriet Tubman was famous for helping enslaved people escape to freedom using the...", choices: ["Oregon Trail", "Underground Railroad", "Transcontinental Railroad", "Pony Express"], answer: 1 },
      { id: "q13", prompt: "The Southern states that left the Union were said to have ___ from the United States.", choices: ["Retreated", "Seceded", "Surrendered", "Migrated"], answer: 1 },
      { id: "q14", prompt: "The first shots of the Civil War were fired at...", choices: ["Fort Sumter", "Gettysburg", "Antietam", "Vicksburg"], answer: 0 },
      { id: "q15", prompt: "Sadly, President Lincoln was ___ shortly after the war ended in 1865.", choices: ["Voted out", "Assassinated", "Retired", "Impeached"], answer: 1 },
      { id: "q16", prompt: "The 14th and 15th Amendments were passed during Reconstruction to protect the rights of...", choices: ["Soldiers", "Formerly enslaved people", "Immigrants", "Farmers"], answer: 1 },
      { id: "q17", prompt: "Which side had more factories, railroads, and people during the war?", choices: ["The South", "The North", "They were equal", "Neither"], answer: 1 },
      { id: "q18", prompt: "The battle often seen as the turning point of the Civil War was...", choices: ["Fort Sumter", "Gettysburg", "Yorktown", "Lexington"], answer: 1, explanation: "The Union victory at Gettysburg in 1863 was a major turning point." },
    ],
  },

  {
    id: "g5-hist-industry",
    subjectId: "history",
    level: "grade5",
    title: "Industry & Immigration",
    description: "Explore inventions, factories, and the immigrants who built modern America.",
    emoji: "🏭",
    questions: [
      { id: "q1",  prompt: "The period when machines and factories rapidly changed how goods were made is called the ___ Revolution.", choices: ["American", "Industrial", "French", "Scientific"], answer: 1 },
      { id: "q2",  prompt: "Thomas Edison is most famous for inventing a practical...", choices: ["Telephone", "Light bulb", "Airplane", "Car"], answer: 1 },
      { id: "q3",  prompt: "Who invented the telephone?", choices: ["Thomas Edison", "Alexander Graham Bell", "Henry Ford", "The Wright Brothers"], answer: 1 },
      { id: "q4",  prompt: "The Wright Brothers are known for the first powered...", choices: ["Automobile", "Airplane flight", "Steamboat", "Train"], answer: 1 },
      { id: "q5",  prompt: "Henry Ford made cars affordable by using the ___ line to build them faster.", choices: ["Railroad", "Assembly", "Telegraph", "Steam"], answer: 1 },
      { id: "q6",  prompt: "Millions of immigrants entering the U.S. on the East Coast passed through ___ Island.", choices: ["Rhode", "Ellis", "Long", "Coney"], answer: 1 },
      { id: "q7",  prompt: "The statue that welcomed many immigrants to New York Harbor is the Statue of...", choices: ["Freedom", "Liberty", "Justice", "Democracy"], answer: 1 },
      { id: "q8",  prompt: "Many immigrants came to America hoping for...", choices: ["A new king", "Freedom and better opportunities", "Colder weather", "Fewer jobs"], answer: 1 },
      { id: "q9",  prompt: "Factories in growing cities needed many workers, which led to rapid growth of...", choices: ["Farms", "Cities", "Forests", "Deserts"], answer: 1 },
      { id: "q10", prompt: "The telegraph, developed by Samuel Morse, sent messages using...", choices: ["Radio waves", "Morse code (dots and dashes)", "Sound recordings", "Pictures"], answer: 1 },
      { id: "q11", prompt: "Workers formed groups called ___ to demand better pay and safer conditions.", choices: ["Unions", "Clubs", "Teams", "Parties"], answer: 0 },
      { id: "q12", prompt: "Poor, crowded, and unsafe factory conditions often affected even...", choices: ["Only adults", "Children who worked long hours", "Only farmers", "No one"], answer: 1 },
      { id: "q13", prompt: "The Transcontinental Railroad, finished in 1869, allowed goods and people to cross the country by...", choices: ["Boat", "Train", "Car", "Airplane"], answer: 1 },
      { id: "q14", prompt: "Which new energy source powered many factories during the Industrial Revolution?", choices: ["Solar power", "Steam (from burning coal)", "Wind turbines", "Nuclear power"], answer: 1 },
      { id: "q15", prompt: "Immigrants on the West Coast often first arrived through ___ Island near San Francisco.", choices: ["Ellis", "Angel", "Coney", "Staten"], answer: 1 },
      { id: "q16", prompt: "A person who starts and runs a business, often taking risks, is called an...", choices: ["Employee", "Entrepreneur", "Immigrant", "Inventor"], answer: 1 },
      { id: "q17", prompt: "Andrew Carnegie became very wealthy in which industry?", choices: ["Oil", "Steel", "Railroads", "Banking"], answer: 1 },
      { id: "q18", prompt: "As factories grew, more Americans moved from farms in the country to jobs in the...", choices: ["Mountains", "Cities", "Oceans", "Deserts"], answer: 1 },
    ],
  },

  // ── GEOGRAPHY ────────────────────────────────────────────────────────────

  {
    id: "g5-geo-world",
    subjectId: "geography",
    level: "grade5",
    title: "World Countries & Capitals",
    description: "Match countries with their capitals, continents, and major features.",
    emoji: "🌎",
    questions: [
      { id: "q1",  prompt: "What is the capital of France?", choices: ["London", "Berlin", "Paris", "Rome"], answer: 2 },
      { id: "q2",  prompt: "What is the capital of Japan?", choices: ["Beijing", "Seoul", "Tokyo", "Bangkok"], answer: 2 },
      { id: "q3",  prompt: "What is the capital of Egypt?", choices: ["Cairo", "Lagos", "Nairobi", "Casablanca"], answer: 0 },
      { id: "q4",  prompt: "Which country is home to the Amazon Rainforest and the city of Rio de Janeiro?", choices: ["Argentina", "Brazil", "Peru", "Colombia"], answer: 1 },
      { id: "q5",  prompt: "What is the capital of Canada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: 2, explanation: "Ottawa is the capital, even though Toronto is larger." },
      { id: "q6",  prompt: "The Great Pyramids are located near which capital city?", choices: ["Athens", "Cairo", "Rome", "Istanbul"], answer: 1 },
      { id: "q7",  prompt: "Which country is both a continent and a country?", choices: ["Greenland", "Australia", "India", "Madagascar"], answer: 1 },
      { id: "q8",  prompt: "What is the capital of Italy?", choices: ["Milan", "Venice", "Rome", "Naples"], answer: 2 },
      { id: "q9",  prompt: "Which country has the Eiffel Tower?", choices: ["Italy", "Spain", "France", "Germany"], answer: 2 },
      { id: "q10", prompt: "Mount Everest sits on the border of Nepal and which country?", choices: ["India", "China", "Pakistan", "Bhutan"], answer: 1 },
      { id: "q11", prompt: "What is the capital of Mexico?", choices: ["Cancún", "Mexico City", "Guadalajara", "Tijuana"], answer: 1 },
      { id: "q12", prompt: "Which continent has the most countries?", choices: ["Asia", "Europe", "Africa", "South America"], answer: 2, explanation: "Africa has 54 countries — the most of any continent." },
      { id: "q13", prompt: "The Nile River flows through which country famous for pyramids?", choices: ["Libya", "Egypt", "Sudan", "Ethiopia"], answer: 1 },
      { id: "q14", prompt: "What is the capital of the United Kingdom?", choices: ["Dublin", "London", "Edinburgh", "Manchester"], answer: 1 },
      { id: "q15", prompt: "Which country is shaped like a boot?", choices: ["Spain", "Greece", "Italy", "Portugal"], answer: 2 },
      { id: "q16", prompt: "The Sahara Desert covers much of northern...", choices: ["Asia", "Africa", "Australia", "South America"], answer: 1 },
      { id: "q17", prompt: "What is the capital of China?", choices: ["Shanghai", "Hong Kong", "Beijing", "Guangzhou"], answer: 2 },
      { id: "q18", prompt: "Which country is directly south of the United States?", choices: ["Canada", "Cuba", "Mexico", "Guatemala"], answer: 2 },
    ],
  },

  {
    id: "g5-geo-economy",
    subjectId: "geography",
    level: "grade5",
    title: "Economy & Natural Resources",
    description: "Learn how people use resources, trade goods, and build economies.",
    emoji: "💰",
    questions: [
      { id: "q1",  prompt: "Natural resources are materials from the Earth that people use, such as...", choices: ["Cars and phones", "Water, trees, and minerals", "Money and banks", "Roads and bridges"], answer: 1 },
      { id: "q2",  prompt: "A resource that can be replaced naturally over time, like trees or wind, is called...", choices: ["Nonrenewable", "Renewable", "Artificial", "Manufactured"], answer: 1 },
      { id: "q3",  prompt: "Which of these is a NONrenewable resource?", choices: ["Sunlight", "Wind", "Oil (petroleum)", "Water"], answer: 2, explanation: "Oil takes millions of years to form, so it is nonrenewable." },
      { id: "q4",  prompt: "Goods are physical things you can buy. A service is...", choices: ["A type of factory", "Work someone does for you, like a haircut", "A natural resource", "A kind of money"], answer: 1 },
      { id: "q5",  prompt: "Buying and selling goods between countries is called...", choices: ["Farming", "Trade", "Mining", "Manufacturing"], answer: 1 },
      { id: "q6",  prompt: "Goods a country sells to other countries are called...", choices: ["Imports", "Exports", "Taxes", "Tariffs"], answer: 1, explanation: "Exports go OUT; imports come IN." },
      { id: "q7",  prompt: "Goods a country buys from other countries are called...", choices: ["Exports", "Imports", "Profits", "Resources"], answer: 1 },
      { id: "q8",  prompt: "Turning raw materials into finished products in factories is called...", choices: ["Agriculture", "Manufacturing", "Trade", "Mining"], answer: 1 },
      { id: "q9",  prompt: "Growing crops and raising animals for food is called...", choices: ["Manufacturing", "Agriculture", "Mining", "Trade"], answer: 1 },
      { id: "q10", prompt: "When there is a limited amount of something people want, we call it...", choices: ["Surplus", "Scarcity", "Demand", "Supply"], answer: 1 },
      { id: "q11", prompt: "The Midwest of the U.S. is often called the nation's 'breadbasket' because it produces so much...", choices: ["Oil", "Grain and corn", "Steel", "Coal"], answer: 1 },
      { id: "q12", prompt: "Which resource is used to make most electricity in many countries by being burned?", choices: ["Gold", "Coal", "Silver", "Diamonds"], answer: 1 },
      { id: "q13", prompt: "A place's location and resources often determine its main...", choices: ["Language", "Industries and jobs", "Flag", "Holidays"], answer: 1 },
      { id: "q14", prompt: "Which is an example of a service worker?", choices: ["A farmer growing wheat", "A factory building cars", "A doctor treating patients", "A miner digging coal"], answer: 2 },
      { id: "q15", prompt: "Solar and wind power are popular because they are ___ and cleaner.", choices: ["Nonrenewable", "Renewable", "Expensive to replace", "Running out fast"], answer: 1 },
      { id: "q16", prompt: "The money a business earns after paying its costs is called...", choices: ["Tax", "Profit", "Debt", "Import"], answer: 1 },
      { id: "q17", prompt: "Countries often trade because no single country has ALL the...", choices: ["People it needs", "Resources it needs", "Money in the world", "Languages"], answer: 1 },
      { id: "q18", prompt: "Fishing is a major industry in regions located near...", choices: ["Deserts", "Oceans and coasts", "Mountains", "Prairies"], answer: 1 },
    ],
  },

  {
    id: "g5-geo-ancient",
    subjectId: "geography",
    level: "grade5",
    title: "Ancient Civilizations & Maps",
    description: "Explore early civilizations along rivers and sharpen your map skills.",
    emoji: "🏛️",
    questions: [
      { id: "q1",  prompt: "Ancient Egypt grew up along which great river?", choices: ["Tigris", "Nile", "Amazon", "Yangtze"], answer: 1 },
      { id: "q2",  prompt: "Early civilizations often started near rivers because rivers provided...", choices: ["Gold", "Water and rich soil for farming", "Mountains", "Deserts"], answer: 1 },
      { id: "q3",  prompt: "The civilization of Mesopotamia grew between the Tigris and ___ Rivers.", choices: ["Nile", "Euphrates", "Indus", "Jordan"], answer: 1 },
      { id: "q4",  prompt: "The ancient Egyptians are famous for building giant tombs called...", choices: ["Temples", "Pyramids", "Castles", "Ziggurats"], answer: 1 },
      { id: "q5",  prompt: "On most maps, which direction is at the TOP?", choices: ["South", "East", "North", "West"], answer: 2 },
      { id: "q6",  prompt: "A map's key or ___ explains what the symbols mean.", choices: ["Compass", "Legend", "Scale", "Grid"], answer: 1 },
      { id: "q7",  prompt: "A map's ___ shows how distance on the map compares to real distance.", choices: ["Legend", "Scale", "Compass rose", "Title"], answer: 1 },
      { id: "q8",  prompt: "The symbol on a map that shows the directions N, S, E, and W is the...", choices: ["Scale", "Legend", "Compass rose", "Grid"], answer: 2 },
      { id: "q9",  prompt: "Ancient Greece is known for creating the earliest form of...", choices: ["Democracy", "Pyramids", "Silk", "Paper money"], answer: 0 },
      { id: "q10", prompt: "The ancient Romans were famous for building roads and structures like...", choices: ["Pyramids", "Aqueducts", "Igloos", "Skyscrapers"], answer: 1, explanation: "Aqueducts carried fresh water across long distances into Roman cities." },
      { id: "q11", prompt: "Which ancient civilization built the Great Wall over many centuries?", choices: ["Egypt", "China", "Greece", "Rome"], answer: 1 },
      { id: "q12", prompt: "Writing helped early civilizations by allowing them to...", choices: ["Fly", "Record laws, trade, and history", "Build rivers", "Grow taller"], answer: 1 },
      { id: "q13", prompt: "The Indus Valley Civilization developed along the Indus River in what is today...", choices: ["Egypt", "Pakistan and India", "Italy", "Greece"], answer: 1 },
      { id: "q14", prompt: "A ___ map shows physical features like mountains, rivers, and elevation.", choices: ["Political", "Physical", "Road", "Weather"], answer: 1 },
      { id: "q15", prompt: "A ___ map shows borders, countries, states, and capital cities.", choices: ["Physical", "Political", "Climate", "Resource"], answer: 1 },
      { id: "q16", prompt: "The ancient Egyptian system of picture writing was called...", choices: ["Cuneiform", "Hieroglyphics", "Alphabet", "Braille"], answer: 1 },
      { id: "q17", prompt: "Halfway between North and East on a compass is the direction...", choices: ["Northwest", "Northeast", "Southeast", "Southwest"], answer: 1 },
      { id: "q18", prompt: "Ancient civilizations traded goods along routes, including the famous Silk ___ connecting Asia and Europe.", choices: ["River", "Road", "Sea", "Wall"], answer: 1 },
    ],
  },
];
