/**
 * Brainy Buddies — Social & Emotional Learning (SEL) activities.
 * Age-appropriate content aligned with CASEL competencies:
 *   Self-Awareness · Self-Management · Social Awareness
 *   Relationship Skills · Responsible Decision-Making
 */
import type { Activity } from "@/lib/brainy-data";

export const SEL_ACTIVITIES: Activity[] = [

  // ─────────────────────────────────────────────
  // KINDERGARTEN
  // ─────────────────────────────────────────────
  {
    id: "sel-k-feelings",
    subjectId: "sel",
    level: "kindergarten",
    title: "Feelings & Faces",
    description: "Learn the names of different feelings.",
    emoji: "😊",
    questions: [
      { id: "q1", prompt: "You get a birthday present you really wanted. How do you feel?", choices: ["Sad", "Happy", "Scared", "Angry"], answer: 1, explanation: "Getting something special usually makes us feel happy!" },
      { id: "q2", prompt: "A loud thunder sound wakes you up at night. How might you feel?", choices: ["Happy", "Bored", "Scared", "Proud"], answer: 2, explanation: "Sudden loud noises can make us feel scared. That's okay!" },
      { id: "q3", prompt: "Someone takes your toy without asking. How might you feel?", choices: ["Excited", "Angry", "Silly", "Calm"], answer: 1, explanation: "It's normal to feel angry when something isn't fair." },
      { id: "q4", prompt: "Your best friend moves away. How might you feel?", choices: ["Bored", "Proud", "Silly", "Sad"], answer: 3, explanation: "Missing someone we love makes us feel sad." },
      { id: "q5", prompt: "You learn to tie your shoes all by yourself. How do you feel?", choices: ["Proud", "Scared", "Angry", "Surprised"], answer: 0, explanation: "Doing something new and hard makes us feel proud!" },
      { id: "q6", prompt: "Which face shows a happy feeling?", choices: ["😢", "😠", "😊", "😨"], answer: 2 },
      { id: "q7", prompt: "You are waiting a very long time and you have nothing to do. How might you feel?", choices: ["Excited", "Bored", "Happy", "Proud"], answer: 1, explanation: "Waiting with nothing to do can feel boring." },
      { id: "q8", prompt: "You see a big dog running toward you and you don't know it. How might you feel?", choices: ["Bored", "Proud", "Nervous", "Silly"], answer: 2, explanation: "Feeling nervous around something unknown is normal and keeps us safe." },
      { id: "q9", prompt: "Your teacher says your drawing is beautiful. How do you feel?", choices: ["Angry", "Sad", "Scared", "Happy"], answer: 3 },
      { id: "q10", prompt: "You fall down on the playground and hurt your knee. How might you feel?", choices: ["Excited", "Proud", "Hurt and sad", "Bored"], answer: 2, explanation: "When we get hurt, our body and feelings both hurt. That's okay." },
    ],
  },
  {
    id: "sel-k-kindness",
    subjectId: "sel",
    level: "kindergarten",
    title: "Being Kind",
    description: "Learn how to show kindness to others.",
    emoji: "💛",
    questions: [
      { id: "q1", prompt: "A new student looks lonely on the playground. What is the kindest thing to do?", choices: ["Ignore them", "Laugh at them", "Ask them to play with you", "Tell them to go away"], answer: 2, explanation: "Including someone who is alone is a great act of kindness!" },
      { id: "q2", prompt: "Your friend drops all their crayons. What should you do?", choices: ["Walk away", "Help pick them up", "Laugh", "Take some crayons"], answer: 1 },
      { id: "q3", prompt: "You have two snacks and your friend has none. What would a kind friend do?", choices: ["Eat both snacks", "Share one snack", "Hide the snacks", "Say 'too bad'"], answer: 1, explanation: "Sharing shows we care about others." },
      { id: "q4", prompt: "Your friend is crying. What is a kind thing to say?", choices: ["Stop crying, it's silly!", "I don't care.", "Are you okay? I'm here for you.", "Ha ha!"], answer: 2, explanation: "Checking in and being there for a friend is true kindness." },
      { id: "q5", prompt: "Someone holds the door open for you. What do you say?", choices: ["Nothing", "Go away", "Thank you!", "You're weird"], answer: 2 },
      { id: "q6", prompt: "You accidentally bumped into someone. What should you say?", choices: ["Nothing", "That was your fault", "I'm sorry!", "Whatever"], answer: 2 },
      { id: "q7", prompt: "Your classmate got a good grade and feels proud. What's a kind thing to say?", choices: ["Show off!", "I don't care.", "Great job! I knew you could do it!", "That's not that great"], answer: 2, explanation: "Celebrating others' success is called being supportive." },
      { id: "q8", prompt: "Kindness means...", choices: ["Only thinking about yourself", "Treating others the way you want to be treated", "Getting the most toys", "Being the loudest"], answer: 1 },
      { id: "q9", prompt: "Which is an example of kindness at home?", choices: ["Leaving a mess for others", "Helping set the table without being asked", "Taking the biggest piece for yourself", "Ignoring your sibling"], answer: 1 },
      { id: "q10", prompt: "How does being kind usually make YOU feel?", choices: ["Sad", "Angry", "Good inside", "Bored"], answer: 2, explanation: "Kindness feels good for both the giver and receiver!" },
    ],
  },
  {
    id: "sel-k-calmdown",
    subjectId: "sel",
    level: "kindergarten",
    title: "Calming Down",
    description: "Learn ways to feel better when upset.",
    emoji: "🌬️",
    questions: [
      { id: "q1", prompt: "When you feel very angry, one good thing to do is...", choices: ["Hit someone", "Take slow deep breaths", "Scream as loud as you can", "Break something"], answer: 1, explanation: "Deep breaths help your body calm down." },
      { id: "q2", prompt: "You feel really sad. A good way to feel better is...", choices: ["Stay alone and feel worse", "Tell a trusted adult how you feel", "Scream at others", "Do nothing"], answer: 1, explanation: "Talking to someone you trust always helps." },
      { id: "q3", prompt: "You feel nervous about something new. You can...", choices: ["Run away and never try", "Remind yourself it's okay to feel nervous and try anyway", "Yell at your teacher", "Cry all day"], answer: 1 },
      { id: "q4", prompt: "Which of these helps our body calm down?", choices: ["Counting slowly to 10", "Punching a pillow hard", "Screaming", "Holding your breath forever"], answer: 0, explanation: "Counting slowly gives your brain time to calm." },
      { id: "q5", prompt: "When something upsets you at school, who is a good person to talk to?", choices: ["Nobody", "Your teacher or counselor", "A stranger", "Someone who is also upset"], answer: 1 },
      { id: "q6", prompt: "Squeezing your muscles tight and then letting go is called...", choices: ["Fighting", "A tension release", "Running", "Hiding"], answer: 1, explanation: "Tensing and releasing muscles is a great calm-down trick!" },
      { id: "q7", prompt: "If you feel like you might explode with anger, the FIRST thing to do is...", choices: ["Push someone", "Take space and breathe", "Throw things", "Scream in class"], answer: 1 },
      { id: "q8", prompt: "Thinking of a happy place in your mind when upset is called...", choices: ["Daydreaming to escape", "Visualization", "Ignoring problems", "Being sneaky"], answer: 1, explanation: "Imagining a calm, happy place can help our brain relax." },
      { id: "q9", prompt: "Which activity can help you feel calm?", choices: ["Drawing or coloring", "Breaking toys", "Hitting a friend", "Yelling"], answer: 0 },
      { id: "q10", prompt: "Everyone feels upset or sad sometimes. This is...", choices: ["Wrong and embarrassing", "Only for babies", "Normal and okay", "Something to hide always"], answer: 2, explanation: "All feelings are normal. What matters is how we handle them." },
    ],
  },

  // ─────────────────────────────────────────────
  // GRADE 1
  // ─────────────────────────────────────────────
  {
    id: "sel-g1-emotions",
    subjectId: "sel",
    level: "grade1",
    title: "Emotion Words",
    description: "Expand your feelings vocabulary.",
    emoji: "🎭",
    questions: [
      { id: "q1", prompt: "Feeling a little nervous but also excited about something new is called...", choices: ["Bored", "Nervous-excited", "Angry", "Sleepy"], answer: 1, explanation: "We can feel two things at once! That mix of excited and nervous is very normal." },
      { id: "q2", prompt: "When you feel left out of a group, you might feel...", choices: ["Proud", "Excluded", "Silly", "Strong"], answer: 1 },
      { id: "q3", prompt: "Feeling good about yourself and your work is called...", choices: ["Jealousy", "Sadness", "Pride", "Frustration"], answer: 2 },
      { id: "q4", prompt: "When something is not fair, you might feel...", choices: ["Grateful", "Frustrated", "Silly", "Calm"], answer: 1 },
      { id: "q5", prompt: "Feeling thankful for something nice someone did is called...", choices: ["Jealousy", "Anger", "Gratitude", "Fear"], answer: 2, explanation: "Gratitude means being thankful." },
      { id: "q6", prompt: "When you really want something someone else has, you might feel...", choices: ["Jealous", "Proud", "Calm", "Excited"], answer: 0 },
      { id: "q7", prompt: "Feeling very calm, peaceful, and comfortable is called...", choices: ["Anxious", "Relaxed", "Furious", "Confused"], answer: 1 },
      { id: "q8", prompt: "You worked hard on a puzzle but can't finish it. You might feel...", choices: ["Proud", "Grateful", "Frustrated", "Excited"], answer: 2 },
      { id: "q9", prompt: "Feeling safe and cared for by people around you is called feeling...", choices: ["Scared", "Alone", "Secure", "Angry"], answer: 2 },
      { id: "q10", prompt: "When something unexpected happens and you don't know what to think, you might feel...", choices: ["Relaxed", "Proud", "Confused", "Grateful"], answer: 2 },
    ],
  },
  {
    id: "sel-g1-friendship",
    subjectId: "sel",
    level: "grade1",
    title: "Good Friends",
    description: "What makes a great friendship?",
    emoji: "🤝",
    questions: [
      { id: "q1", prompt: "A good friend...", choices: ["Always wins the argument", "Listens to you when you are sad", "Takes your things without asking", "Makes fun of your ideas"], answer: 1 },
      { id: "q2", prompt: "Your friend wants to play a game you don't like. A good thing to do is...", choices: ["Storm off", "Take turns choosing games", "Force them to play your game", "Ignore them"], answer: 1, explanation: "Taking turns shows respect for each other's interests." },
      { id: "q3", prompt: "A friend tells you a secret. You should...", choices: ["Tell everyone at school", "Keep it to yourself (unless it's unsafe)", "Laugh about it", "Forget about it"], answer: 1 },
      { id: "q4", prompt: "You are upset with your friend. The best first step is...", choices: ["Never talk to them again", "Calmly tell them how you feel", "Push them", "Tell everyone to dislike them"], answer: 1 },
      { id: "q5", prompt: "Good friends treat each other...", choices: ["Differently based on mood", "With kindness and respect", "Only nicely when others watch", "However they want"], answer: 1 },
      { id: "q6", prompt: "When you hurt a friend's feelings by accident, you should...", choices: ["Pretend it didn't happen", "Apologize and mean it", "Blame them", "Laugh it off"], answer: 1 },
      { id: "q7", prompt: "A friend asks you to leave someone out. You should...", choices: ["Go along with it", "Include everyone and tell your friend it's not kind to exclude", "Ignore both of them", "Tell a teacher immediately every time"], answer: 1 },
      { id: "q8", prompt: "What does it mean to be a trustworthy friend?", choices: ["Keeping promises and being honest", "Only being nice when you want something", "Telling everyone everything", "Always agreeing"], answer: 0 },
      { id: "q9", prompt: "You notice a classmate sitting alone every day. Being a good friend means...", choices: ["Pointing it out loudly", "Inviting them to join you", "Ignoring them", "Laughing with others"], answer: 1 },
      { id: "q10", prompt: "Disagreements between friends...", choices: ["Mean the friendship is over", "Are normal and can be worked through", "Mean someone is bad", "Should always be kept secret"], answer: 1 },
    ],
  },
  {
    id: "sel-g1-selfcontrol",
    subjectId: "sel",
    level: "grade1",
    title: "Self-Control",
    description: "Learn to pause before you act.",
    emoji: "🛑",
    questions: [
      { id: "q1", prompt: "Self-control means...", choices: ["Doing whatever you feel like", "Pausing to think before you act", "Letting others control you", "Ignoring your feelings"], answer: 1 },
      { id: "q2", prompt: "You want to shout an answer out loud. Using self-control, you...", choices: ["Shout anyway", "Raise your hand and wait", "Give up answering", "Talk to your neighbor"], answer: 1 },
      { id: "q3", prompt: "You are angry and want to push someone. Using self-control, you...", choices: ["Push them anyway", "Walk away and breathe", "Scream at them", "Break something"], answer: 1 },
      { id: "q4", prompt: "You want to eat all the cookies but there are others. Self-control means...", choices: ["Eating them all quickly", "Taking your fair share", "Hiding the cookies", "Crying until you get more"], answer: 1 },
      { id: "q5", prompt: "Which phrase helps you use self-control?", choices: ["'I do what I want!'", "'Stop and think first'", "'No rules for me'", "'Others don't matter'"], answer: 1 },
      { id: "q6", prompt: "Self-control helps you...", choices: ["Make better decisions", "Get everything you want", "Avoid all feelings", "Be perfect"], answer: 0 },
      { id: "q7", prompt: "It takes practice to have self-control. This is...", choices: ["A weakness", "True — everyone is still learning", "Only true for babies", "False — you either have it or don't"], answer: 1 },
      { id: "q8", prompt: "Your friend has a new toy and you want it RIGHT NOW. Self-control means...", choices: ["Grabbing it", "Asking nicely and waiting your turn", "Throwing a tantrum", "Breaking your own toy"], answer: 1 },
      { id: "q9", prompt: "When you feel yourself getting really angry, a good first step is...", choices: ["Act on it immediately", "STOP and take three deep breaths", "Scream very loud", "Run away from school"], answer: 1 },
      { id: "q10", prompt: "People who practice self-control...", choices: ["Never feel angry", "Feel better and have better friendships", "Get everything they want", "Don't need friends"], answer: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // GRADE 2
  // ─────────────────────────────────────────────
  {
    id: "sel-g2-empathy",
    subjectId: "sel",
    level: "grade2",
    title: "Empathy",
    description: "Understanding how others feel.",
    emoji: "❤️",
    questions: [
      { id: "q1", prompt: "Empathy means...", choices: ["Feeling sorry for yourself", "Understanding and sharing someone else's feelings", "Being the most popular", "Winning every game"], answer: 1 },
      { id: "q2", prompt: "Your classmate is crying because they lost their pet. You...", choices: ["Laugh because it's not your pet", "Tell them to get over it", "Listen kindly and say you're sorry", "Walk away"], answer: 2, explanation: "Listening and being kind when others hurt is empathy in action." },
      { id: "q3", prompt: "Thinking about how YOU would feel in someone else's situation is called...", choices: ["Perspective-taking", "Day-dreaming", "Judging", "Ignoring"], answer: 0 },
      { id: "q4", prompt: "A new student is nervous on their first day. How can you show empathy?", choices: ["Stare at them", "Introduce yourself and show them around", "Ignore them", "Point and whisper"], answer: 1 },
      { id: "q5", prompt: "Empathy means you have to...", choices: ["Agree with everything they do", "Understand their feelings even if you'd feel differently", "Fix all their problems", "Feel exactly the same as them"], answer: 1 },
      { id: "q6", prompt: "Someone is being made fun of. Showing empathy means...", choices: ["Joining in to fit in", "Standing up for them or checking in later", "Pretending you didn't see", "Telling them to ignore it"], answer: 1 },
      { id: "q7", prompt: "Which question shows empathy?", choices: ["Why are you so weird?", "What's wrong with you?", "How are you feeling? Is there anything I can do?", "Why do you always cry?"], answer: 2 },
      { id: "q8", prompt: "Empathy makes friendships...", choices: ["Harder", "Weaker", "Stronger and more trusting", "More competitive"], answer: 2 },
      { id: "q9", prompt: "You disagree with a friend's decision. Showing empathy means...", choices: ["Calling them wrong", "Trying to understand why they decided that", "Ignoring them", "Telling everyone"], answer: 1 },
      { id: "q10", prompt: "Why is empathy important?", choices: ["It makes you look good", "It helps people feel understood and less alone", "It means you never have problems", "It makes you the most popular person"], answer: 1 },
    ],
  },
  {
    id: "sel-g2-conflict",
    subjectId: "sel",
    level: "grade2",
    title: "Solving Problems Together",
    description: "Work through disagreements peacefully.",
    emoji: "🤜🤛",
    questions: [
      { id: "q1", prompt: "When two people disagree, the best first step is...", choices: ["Argue until someone gives up", "Calm down, then talk it out", "Ignore each other forever", "Get adults to fight for you"], answer: 1 },
      { id: "q2", prompt: "Both you and a friend want to use the swing. You should...", choices: ["Push them off", "Take turns", "Never use the swing", "Cry until you get it"], answer: 1 },
      { id: "q3", prompt: "When someone shares their side of a disagreement, you should...", choices: ["Interrupt them", "Talk over them", "Listen without interrupting", "Roll your eyes"], answer: 2 },
      { id: "q4", prompt: "A compromise means...", choices: ["One person wins, one loses", "Both people get everything", "Both people give a little to find a middle ground", "Adults decide everything"], answer: 2 },
      { id: "q5", prompt: "Someone keeps calling you a name you don't like. You tell them...", choices: ["Call them a worse name back", "Hit them", "Please stop. I don't like being called that.", "Tell everyone they're mean"], answer: 2, explanation: "Using 'I' statements and being direct but calm is called assertive communication." },
      { id: "q6", prompt: "You and a friend both want to be team captain. A fair solution is...", choices: ["Neither of you play", "Rock-paper-scissors or take turns", "The loudest one wins", "Ask a teacher to decide without input"], answer: 1 },
      { id: "q7", prompt: "What should you do if a conflict is getting too heated?", choices: ["Keep arguing until someone cries", "Take a break and come back when calm", "Involve everyone on the playground", "Stop being friends forever"], answer: 1 },
      { id: "q8", prompt: "Starting a sentence with 'I feel...' instead of 'You always...' is...", choices: ["Weak", "A helpful way to share feelings without blaming", "Only for adults", "The wrong way to talk"], answer: 1 },
      { id: "q9", prompt: "After a conflict is resolved, a good thing to do is...", choices: ["Keep reminding them of the problem", "Move forward and rebuild the friendship", "Tell others about who was wrong", "Act like nothing happened ever"], answer: 1 },
      { id: "q10", prompt: "When is it important to get an adult involved in a conflict?", choices: ["Every single time you disagree", "Never — handle everything yourself", "When someone is being hurt or bullied", "When you want to win"], answer: 2 },
    ],
  },
  {
    id: "sel-g2-choices",
    subjectId: "sel",
    level: "grade2",
    title: "Making Good Choices",
    description: "Think about how your choices affect others.",
    emoji: "⭐",
    questions: [
      { id: "q1", prompt: "Before making a choice, it helps to think about...", choices: ["What looks coolest", "How it might affect you and others", "What your enemy would do", "Whatever is fastest"], answer: 1 },
      { id: "q2", prompt: "You find money on the ground at school. The responsible thing to do is...", choices: ["Keep it for yourself", "Hand it in to a teacher", "Show everyone", "Buy candy with it"], answer: 1 },
      { id: "q3", prompt: "Your friend wants you to laugh at someone who tripped. You should...", choices: ["Laugh loudly", "Ignore it and walk away", "Check if the person is okay instead", "Tell your friend to be mean"], answer: 2 },
      { id: "q4", prompt: "Making a responsible choice means...", choices: ["Always doing what your friends want", "Thinking about what's right, not just what's fun", "Never having fun", "Doing whatever adults say without thinking"], answer: 1 },
      { id: "q5", prompt: "You made a mistake. The responsible thing is to...", choices: ["Blame someone else", "Own it and try to fix it", "Pretend it didn't happen", "Get angry at others"], answer: 1 },
      { id: "q6", prompt: "If you're unsure if a choice is okay, a good test is...", choices: ["Would I be okay with my teacher or parent seeing me do this?", "Would it be the fastest option?", "Would my enemy like it?", "Is it the most expensive choice?"], answer: 0 },
      { id: "q7", prompt: "Peer pressure means...", choices: ["Getting homework help", "When others push you to do something, even if you don't want to", "Competing in a game", "Helping a friend"], answer: 1 },
      { id: "q8", prompt: "Your friends dare you to something that doesn't feel right. You can say...", choices: ["Sure, anything for you guys", "No thanks, that doesn't feel right to me", "I hate all of you", "I'll only do it if no one finds out"], answer: 1 },
      { id: "q9", prompt: "Thinking about consequences means...", choices: ["Only thinking about right now", "Thinking about what might happen because of your choice", "Ignoring the future", "Doing whatever feels good immediately"], answer: 1 },
      { id: "q10", prompt: "Good choices usually...", choices: ["Feel the hardest and always fail", "Help you and others feel good in the long run", "Only matter when adults are watching", "Never need thought"], answer: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // GRADE 3
  // ─────────────────────────────────────────────
  {
    id: "sel-g3-perspective",
    subjectId: "sel",
    level: "grade3",
    title: "Seeing Other Points of View",
    description: "Practice perspective-taking to understand others better.",
    emoji: "🔭",
    questions: [
      { id: "q1", prompt: "Perspective-taking means...", choices: ["Always agreeing with others", "Understanding how someone else sees a situation", "Staring at people", "Being the only one who's right"], answer: 1 },
      { id: "q2", prompt: "Two kids argue about who should use the computer first. Each is sure THEY are right. What would help?", choices: ["Yelling louder", "Each explaining their reason calmly and finding a solution together", "Asking the teacher to punish one of them", "Never using the computer again"], answer: 1 },
      { id: "q3", prompt: "Your friend thinks your favorite movie is boring. You should...", choices: ["End the friendship", "Accept that people have different tastes", "Convince them they're wrong", "Never talk about movies"], answer: 1 },
      { id: "q4", prompt: "Understanding someone's perspective helps you...", choices: ["Control them", "Have less empathy", "Solve problems and strengthen relationships", "Always get your way"], answer: 2 },
      { id: "q5", prompt: "A classmate who just moved here acts differently than your group. You might think...", choices: ["They're weird and wrong", "Their background and experiences are different, not bad", "You should avoid them", "They need to change immediately"], answer: 1 },
      { id: "q6", prompt: "When you try to see something from another's viewpoint, you are practicing...", choices: ["Selfishness", "Empathy and perspective-taking", "Judgment", "Bossiness"], answer: 1 },
      { id: "q7", prompt: "You feel left out when friends make plans without you. Looking at it from their perspective, they might have...", choices: ["Done it to be mean", "Simply not thought about it or made plans with a smaller group", "Hated you all along", "Been told to exclude you"], answer: 1, explanation: "Perspective-taking can prevent us from assuming the worst." },
      { id: "q8", prompt: "Which question helps you take another's perspective?", choices: ["Why are they always wrong?", "How might they be feeling right now?", "How can I make them feel bad?", "Why can't they think like me?"], answer: 1 },
      { id: "q9", prompt: "Taking someone else's perspective is...", choices: ["Easy and automatic for everyone", "A skill that takes practice", "Only important for adults", "Unnecessary if you're right"], answer: 1 },
      { id: "q10", prompt: "How can perspective-taking make your school community better?", choices: ["It makes everyone think the same", "It reduces conflict and helps people get along", "It means you always give in", "It has no effect"], answer: 1 },
    ],
  },
  {
    id: "sel-g3-managing-emotions",
    subjectId: "sel",
    level: "grade3",
    title: "Managing Strong Feelings",
    description: "Strategies for handling big emotions.",
    emoji: "🌊",
    questions: [
      { id: "q1", prompt: "When you feel overwhelmed, the first helpful step is...", choices: ["Act immediately on your feelings", "Pause, breathe, and notice what you're feeling", "Ignore everyone", "Pretend you're fine"], answer: 1 },
      { id: "q2", prompt: "Journaling (writing or drawing your feelings) is a good way to...", choices: ["Hide from problems", "Process and understand your emotions", "Avoid talking to people", "Make others feel bad"], answer: 1 },
      { id: "q3", prompt: "Which strategy helps manage anxiety before a test?", choices: ["Stay up all night worrying", "Prepare, breathe deeply, and remind yourself you've done your best", "Give up before starting", "Complain to everyone"], answer: 1 },
      { id: "q4", prompt: "You feel jealous of a friend's new bike. A healthy response is...", choices: ["Break their bike", "Recognize the feeling and talk to someone or redirect your energy", "Pretend you don't care and lie", "Tell everyone your friend is spoiled"], answer: 1 },
      { id: "q5", prompt: "Physical exercise can help with strong emotions because...", choices: ["It tires you out so you forget everything", "It releases energy and chemicals that improve mood", "It avoids the problem", "It makes you stronger to fight"], answer: 1 },
      { id: "q6", prompt: "Talking to a trusted adult when feelings get too big is...", choices: ["A sign of weakness", "Smart and brave", "Only for little kids", "Always unnecessary"], answer: 1 },
      { id: "q7", prompt: "Feeling angry at someone doesn't mean you should...", choices: ["Talk to them later when calm", "Think about why you're angry", "Act aggressively toward them", "Take deep breaths"], answer: 2 },
      { id: "q8", prompt: "Mindfulness means...", choices: ["Thinking about everything at once", "Paying attention to the present moment on purpose", "Ignoring your feelings", "Being silent always"], answer: 1 },
      { id: "q9", prompt: "Healthy ways to express anger include...", choices: ["Hitting others", "Drawing, writing, exercising, or talking to someone", "Saying mean things", "Ignoring everyone for days"], answer: 1 },
      { id: "q10", prompt: "Emotions are signals that...", choices: ["You are broken", "Tell you something about what you need or care about", "Should always be hidden", "Mean things are out of control"], answer: 1 },
    ],
  },
  {
    id: "sel-g3-responsibility",
    subjectId: "sel",
    level: "grade3",
    title: "Being Responsible",
    description: "Own your actions and their impact.",
    emoji: "🏆",
    questions: [
      { id: "q1", prompt: "Responsibility means...", choices: ["Only doing what you enjoy", "Being accountable for your choices and actions", "Letting others handle everything", "Blaming others when things go wrong"], answer: 1 },
      { id: "q2", prompt: "You forgot to do your homework. The responsible thing is...", choices: ["Blame your parent for not reminding you", "Lie and say you did it", "Tell your teacher honestly and make a plan to finish it", "Copy a friend's work quickly"], answer: 2 },
      { id: "q3", prompt: "You accidentally broke something at a friend's house. You should...", choices: ["Sneak away without saying anything", "Tell your friend and offer to help fix or replace it", "Blame the family pet", "Pretend it was already broken"], answer: 1 },
      { id: "q4", prompt: "Being responsible at school means...", choices: ["Only working when the teacher watches", "Doing your best, being honest, and respecting others", "Making sure others do the work", "Having the best supplies"], answer: 1 },
      { id: "q5", prompt: "Taking care of a classroom plant or pet teaches...", choices: ["Nothing useful", "Responsibility for living things", "How to avoid work", "That animals aren't important"], answer: 1 },
      { id: "q6", prompt: "You made a promise to help a friend but now don't feel like it. Responsibility means...", choices: ["Cancel last minute — feelings matter most", "Keep your promise unless there's a real emergency", "Make an excuse and lie", "Avoid your friend"], answer: 1 },
      { id: "q7", prompt: "Community responsibility means...", choices: ["Only taking care of your own stuff", "Playing a part in keeping your community clean and kind", "Letting the government do everything", "Doing the minimum always"], answer: 1 },
      { id: "q8", prompt: "You see litter on the playground even though it's not yours. A responsible choice is...", choices: ["Leave it — not your problem", "Pick it up and toss it", "Tell everyone who did it", "Complain but do nothing"], answer: 1 },
      { id: "q9", prompt: "If a group project isn't going well because you didn't do your part, you should...", choices: ["Blame the team leader", "Apologize and do your share immediately", "Quit the project", "Pretend you tried your best"], answer: 1 },
      { id: "q10", prompt: "Responsible people are more trusted because...", choices: ["They are always perfect", "People know they will follow through on their word", "They tell on everyone", "They never make mistakes"], answer: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // GRADE 4
  // ─────────────────────────────────────────────
  {
    id: "sel-g4-identity",
    subjectId: "sel",
    level: "grade4",
    title: "Who Am I?",
    description: "Explore your values, strengths, and identity.",
    emoji: "🌟",
    questions: [
      { id: "q1", prompt: "Your personal values are...", choices: ["What grades you get", "The things that matter most to you and guide your choices", "What your friends believe", "Whatever is popular right now"], answer: 1 },
      { id: "q2", prompt: "A personal strength is...", choices: ["Something you're naturally perfect at", "A skill or quality you do well that you can build on", "Only things others tell you about", "Only athletic abilities"], answer: 1 },
      { id: "q3", prompt: "Having a growth mindset means believing...", choices: ["You are as smart as you'll ever be", "Abilities can grow with effort and learning", "Only some people can improve", "Mistakes mean you should give up"], answer: 1 },
      { id: "q4", prompt: "Your identity includes...", choices: ["Only your appearance", "Your culture, experiences, personality, values, and more", "Just your grades and sports", "Whatever your friends define for you"], answer: 1 },
      { id: "q5", prompt: "When you do something that goes against your values, you might feel...", choices: ["Proud and happy", "Uncomfortable or guilty", "Like nothing matters", "Like a winner"], answer: 1, explanation: "This uncomfortable feeling is your conscience — it keeps you aligned with your values." },
      { id: "q6", prompt: "Self-awareness means...", choices: ["Thinking about yourself all day", "Knowing your feelings, values, and how you affect others", "Being selfish", "Only focusing on your weaknesses"], answer: 1 },
      { id: "q7", prompt: "It is okay for your identity to change as you grow. This is...", choices: ["Wrong — pick an identity and stick to it", "True — growth and change are natural", "A sign of weakness", "Only true for adults"], answer: 1 },
      { id: "q8", prompt: "Being proud of your cultural background means...", choices: ["Thinking other cultures are lesser", "Celebrating where you come from while respecting others' backgrounds too", "Ignoring other cultures", "Keeping it secret"], answer: 1 },
      { id: "q9", prompt: "A healthy self-image means you...", choices: ["Think you're better than everyone", "Recognize both your strengths and areas to grow, and feel worthy", "Only focus on flaws", "Depend on others to feel good about yourself"], answer: 1 },
      { id: "q10", prompt: "Someone makes fun of something unique about you. The healthiest response is...", choices: ["Change yourself to fit in", "Recognize that uniqueness is a strength, not a flaw", "Make fun of them back", "Agree with them"], answer: 1 },
    ],
  },
  {
    id: "sel-g4-peer-pressure",
    subjectId: "sel",
    level: "grade4",
    title: "Peer Pressure & Decisions",
    description: "Make choices that reflect YOUR values.",
    emoji: "🧭",
    questions: [
      { id: "q1", prompt: "Peer pressure is when...", choices: ["A friend helps you study", "Others influence you to do something, sometimes against your better judgment", "You disagree with a teacher", "You try a new activity you chose yourself"], answer: 1 },
      { id: "q2", prompt: "Which is an example of POSITIVE peer pressure?", choices: ["Friends daring you to skip class", "Friends encouraging you to study for a test", "Friends pressuring you to exclude someone", "Friends telling you to lie to a teacher"], answer: 1 },
      { id: "q3", prompt: "When you feel pressured to do something wrong, a good response is...", choices: ["Do it so they'll like you", "Confidently say no and explain your reason", "Pretend you agree then do nothing", "Blame your parents"], answer: 1 },
      { id: "q4", prompt: "Making decisions based on your own values rather than others' pressure is called...", choices: ["Being antisocial", "Integrity", "Being stubborn", "Showing off"], answer: 1, explanation: "Integrity means doing what's right even when it's hard or unpopular." },
      { id: "q5", prompt: "If a 'friend' threatens to stop being your friend if you don't do something wrong, this is...", choices: ["True friendship being tested", "Manipulation — true friends respect your boundaries", "Normal friend behavior", "You being too sensitive"], answer: 1 },
      { id: "q6", prompt: "The best decisions come from...", choices: ["What everyone else is doing", "Your own values plus careful thought about consequences", "Acting as fast as possible", "Whatever feels best in the moment"], answer: 1 },
      { id: "q7", prompt: "When deciding whether to do something, asking 'Would I be okay if my parents could see me right now?' is called...", choices: ["Being paranoid", "The parent test — a quick integrity check", "Asking permission", "Being scared"], answer: 1 },
      { id: "q8", prompt: "Feeling conflicted when pressured means...", choices: ["You should just go along with it", "Your values and instincts are working — pay attention", "You are weak", "You need new friends immediately"], answer: 1 },
      { id: "q9", prompt: "What can you do if you need time to decide something?", choices: ["Always say yes to avoid conflict", "Say 'I need to think about it' and walk away", "Do whatever the loudest person says", "Ignore the situation"], answer: 1 },
      { id: "q10", prompt: "The people you spend time with...", choices: ["Have no influence on you", "Can positively or negatively influence your choices", "Only matter in middle school", "Are always good influences"], answer: 1 },
    ],
  },
  {
    id: "sel-g4-inclusion",
    subjectId: "sel",
    level: "grade4",
    title: "Inclusion & Respect",
    description: "Celebrate differences and build a welcoming community.",
    emoji: "🌍",
    questions: [
      { id: "q1", prompt: "Inclusion means...", choices: ["Only including your best friends", "Making sure everyone feels welcome, valued, and respected", "Tolerating people you dislike", "Treating everyone exactly the same"], answer: 1 },
      { id: "q2", prompt: "Respect for differences means...", choices: ["Pretending differences don't exist", "Accepting that people have different backgrounds, ideas, and abilities — and that's good", "Only respecting people like you", "Forcing everyone to agree"], answer: 1 },
      { id: "q3", prompt: "You hear someone make a negative comment about a group of people. You could...", choices: ["Laugh along to fit in", "Calmly say that's not cool and explain why", "Record it and post it", "Ignore it always"], answer: 1 },
      { id: "q4", prompt: "Stereotypes are...", choices: ["Always true about groups", "Oversimplified beliefs about groups that ignore individuality", "A form of respect", "Only about physical appearance"], answer: 1 },
      { id: "q5", prompt: "A student with a disability joins your class. Inclusion means...", choices: ["Treating them differently to 'protect' them", "Making fun of them to seem cool", "Including them normally and offering help only if they want it", "Ignoring their presence"], answer: 2 },
      { id: "q6", prompt: "Celebrating cultural differences in your school makes the community...", choices: ["Confusing and divided", "Richer and more interesting for everyone", "Less equal", "Harder to manage"], answer: 1 },
      { id: "q7", prompt: "Bystander behavior means...", choices: ["Being the one who causes harm", "Watching something wrong happen without acting", "Standing up for others", "Reporting every small conflict"], answer: 1 },
      { id: "q8", prompt: "An 'upstander' is someone who...", choices: ["Watches and does nothing", "Takes action when they see something wrong", "Reports everything to adults", "Always agrees with the popular crowd"], answer: 1 },
      { id: "q9", prompt: "Why is it important for everyone to feel they belong?", choices: ["It isn't important", "People learn and grow better when they feel safe and valued", "Only certain people need to belong", "It makes things easier for teachers only"], answer: 1 },
      { id: "q10", prompt: "How can YOU build a more inclusive classroom?", choices: ["Wait for teachers to do it", "Invite others in, listen with curiosity, and stand up for fairness", "Only include people who are like you", "Complain about unfairness without acting"], answer: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // GRADE 5
  // ─────────────────────────────────────────────
  {
    id: "sel-g5-goals-growth",
    subjectId: "sel",
    level: "grade5",
    title: "Goals & Growth Mindset",
    description: "Set useful goals and turn setbacks into next steps.",
    emoji: "🎯",
    questions: [
      { id: "q1", prompt: "Which goal is specific and measurable?", choices: ["Get better at math", "Practice multiplication for 15 minutes four days this week", "Be the best student", "Never make a mistake"], answer: 1, explanation: "A specific goal says exactly what you will do and how you will track it." },
      { id: "q2", prompt: "You do poorly on a quiz after studying. A growth-mindset response is...", choices: ["I'm just bad at this", "I'll review my errors and try a new study strategy", "The grade can never improve", "I'll avoid the subject"], answer: 1 },
      { id: "q3", prompt: "Breaking a large goal into smaller steps helps because...", choices: ["each step is easier to plan and track", "the goal disappears", "someone else does the work", "you no longer need effort"], answer: 0 },
      { id: "q4", prompt: "Useful feedback should help you...", choices: ["feel embarrassed", "identify a next step for improvement", "compare yourself with everyone", "prove you cannot learn"], answer: 1 },
      { id: "q5", prompt: "What is a healthy response when progress is slower than expected?", choices: ["Quit immediately", "Adjust the plan and keep practicing", "Hide the problem", "Blame someone else"], answer: 1 },
      { id: "q6", prompt: "Celebrating small progress can...", choices: ["build motivation to continue", "replace all future effort", "make goals less important", "guarantee perfection"], answer: 0 },
    ],
  },
  {
    id: "sel-g5-digital-citizenship",
    subjectId: "sel",
    level: "grade5",
    title: "Digital Citizenship",
    description: "Communicate responsibly and protect yourself and others online.",
    emoji: "🛡️",
    questions: [
      { id: "q1", prompt: "Before posting a photo of a friend, you should...", choices: ["post it quickly", "ask for their permission", "add their location", "send it to strangers"], answer: 1 },
      { id: "q2", prompt: "A message online makes you feel unsafe. What should you do?", choices: ["Reply with personal information", "Save the evidence, block the sender, and tell a trusted adult", "Keep it secret", "Forward it to classmates"], answer: 1 },
      { id: "q3", prompt: "Why can online words have a lasting impact?", choices: ["Messages can be saved and shared", "Online words are never real", "Posts always vanish instantly", "Only adults read them"], answer: 0 },
      { id: "q4", prompt: "Which information should stay private online?", choices: ["A favorite book", "A home address and password", "A favorite color", "A public school mascot"], answer: 1 },
      { id: "q5", prompt: "You see someone being bullied in a group chat. A responsible response is...", choices: ["Join in", "Support the person and report the behavior", "Share screenshots publicly", "Pretend it is funny"], answer: 1 },
      { id: "q6", prompt: "A digital footprint is...", choices: ["the trail of information created by online activity", "a computer repair tool", "a private password", "the size of a screen"], answer: 0 },
    ],
  },
  {
    id: "sel-g5-teamwork-conflict",
    subjectId: "sel",
    level: "grade5",
    title: "Teamwork & Fair Conflict",
    description: "Share responsibility, listen actively, and repair disagreements.",
    emoji: "🤝",
    questions: [
      { id: "q1", prompt: "A productive team begins by...", choices: ["letting one person do everything", "agreeing on roles and a shared goal", "avoiding different ideas", "choosing the loudest leader"], answer: 1 },
      { id: "q2", prompt: "Active listening includes...", choices: ["planning your reply while others talk", "summarizing what you heard before responding", "interrupting incorrect ideas", "agreeing with everything"], answer: 1 },
      { id: "q3", prompt: "A teammate misses a deadline. What is the best first response?", choices: ["Insult them", "Ask what happened and make a recovery plan together", "Remove their name secretly", "Complain to everyone else"], answer: 1 },
      { id: "q4", prompt: "A fair compromise means...", choices: ["one side gets everything", "everyone gives up their values", "the solution considers the important needs of each side", "the conflict is ignored"], answer: 2 },
      { id: "q5", prompt: "Which statement is assertive rather than aggressive?", choices: ["Your idea is terrible", "I disagree because the evidence points another way", "Be quiet and do what I say", "Whatever, I don't care"], answer: 1 },
      { id: "q6", prompt: "After hurting a teammate's feelings, a sincere repair includes...", choices: ["an apology and changed behavior", "an excuse only", "pretending it never happened", "demanding forgiveness"], answer: 0 },
    ],
  },

  // ─────────────────────────────────────────────
  // GRADE 6
  // ─────────────────────────────────────────────
  {
    id: "sel-g6-stress-regulation",
    subjectId: "sel",
    level: "grade6",
    title: "Stress Signals & Regulation",
    description: "Recognize stress early and choose strategies that fit the situation.",
    emoji: "🌤️",
    questions: [
      { id: "q1", prompt: "Which can be a physical signal of stress?", choices: ["Tight muscles or a fast heartbeat", "Knowing every answer", "Growing taller instantly", "Never needing sleep"], answer: 0 },
      { id: "q2", prompt: "Before a presentation, slow breathing can help by...", choices: ["calming the body's stress response", "erasing the presentation", "guaranteeing a perfect grade", "avoiding preparation"], answer: 0 },
      { id: "q3", prompt: "Which strategy addresses the cause of feeling overwhelmed by assignments?", choices: ["Ignore every deadline", "Make a prioritized task list and start one step", "Stay awake all night", "Compare your workload online"], answer: 1 },
      { id: "q4", prompt: "Positive stress can sometimes...", choices: ["provide energy for a challenge", "remove every difficult feeling", "make sleep unnecessary", "solve problems without action"], answer: 0 },
      { id: "q5", prompt: "When stress keeps interfering with sleep or daily life, a wise step is to...", choices: ["hide it", "talk with a trusted adult or counselor", "stop all activities forever", "criticize yourself"], answer: 1 },
      { id: "q6", prompt: "Which self-talk is most balanced?", choices: ["I must be perfect", "This is challenging, and I can take it one step at a time", "Everything will go wrong", "I should already know this"], answer: 1 },
    ],
  },
  {
    id: "sel-g6-boundaries-friendships",
    subjectId: "sel",
    level: "grade6",
    title: "Healthy Friendships & Boundaries",
    description: "Build relationships based on trust, consent, honesty, and respect.",
    emoji: "🧩",
    questions: [
      { id: "q1", prompt: "A personal boundary communicates...", choices: ["what helps you feel safe and respected", "how to control another person", "that friendship is over", "a rule everyone must share"], answer: 0 },
      { id: "q2", prompt: "A friend asks to read your private messages. You do not want to share them. You can say...", choices: ["I have to let you", "No, those are private. Please respect that", "I'll share yours instead", "Nothing and feel resentful"], answer: 1 },
      { id: "q3", prompt: "In a healthy friendship, disagreement should...", choices: ["be handled with respect", "lead to threats", "require one person to give in", "be shared online"], answer: 0 },
      { id: "q4", prompt: "Which behavior is a warning sign in a friendship?", choices: ["Respecting time with other friends", "Pressuring someone after they say no", "Apologizing after a mistake", "Celebrating each other's success"], answer: 1 },
      { id: "q5", prompt: "Consent means a person...", choices: ["freely and clearly agrees", "stays silent", "agreed once in the past", "is pressured to say yes"], answer: 0 },
      { id: "q6", prompt: "If a boundary is repeatedly ignored, you should...", choices: ["assume it is your fault", "seek support from a trusted adult", "ignore your discomfort", "retaliate publicly"], answer: 1 },
    ],
  },
  {
    id: "sel-g6-organization-balance",
    subjectId: "sel",
    level: "grade6",
    title: "Organization & Healthy Balance",
    description: "Manage growing responsibilities while protecting rest and well-being.",
    emoji: "🗓️",
    questions: [
      { id: "q1", prompt: "Which task should usually come first?", choices: ["A project due tomorrow", "A game with no deadline", "Reorganizing old photos", "Choosing a weekend movie"], answer: 0 },
      { id: "q2", prompt: "A calendar is most useful for tracking...", choices: ["deadlines and scheduled commitments", "other people's private information", "every thought you have", "only completed work"], answer: 0 },
      { id: "q3", prompt: "Why include breaks in a study plan?", choices: ["Short breaks can restore focus", "Breaks finish the work", "Learning only happens during breaks", "Deadlines stop during breaks"], answer: 0 },
      { id: "q4", prompt: "You underestimate how long homework will take. What should you change next time?", choices: ["Stop planning", "Record the actual time and adjust your estimate", "Skip difficult tasks", "Blame the schedule"], answer: 1 },
      { id: "q5", prompt: "Healthy balance includes time for...", choices: ["responsibilities, sleep, movement, and connection", "schoolwork every waking hour", "screens instead of sleep", "avoiding every challenge"], answer: 0 },
      { id: "q6", prompt: "When several tasks feel equally urgent, it helps to...", choices: ["choose randomly", "compare deadlines and importance", "do none of them", "start the easiest and ignore the rest"], answer: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // GRADE 7
  // ─────────────────────────────────────────────
  {
    id: "sel-g7-identity-values",
    subjectId: "sel",
    level: "grade7",
    title: "Identity, Values & Belonging",
    description: "Explore how values and social groups shape choices without defining your limits.",
    emoji: "🧭",
    questions: [
      { id: "q1", prompt: "A personal value is...", choices: ["a principle that guides your choices", "whatever is popular today", "a grade someone gives you", "a rule that never changes for anyone"], answer: 0 },
      { id: "q2", prompt: "Your identity can include...", choices: ["interests, culture, experiences, roles, and values", "only your appearance", "only other people's opinions", "one fixed label"], answer: 0 },
      { id: "q3", prompt: "You notice yourself changing an opinion after learning new evidence. This can show...", choices: ["weakness", "reflection and growth", "dishonesty", "lack of identity"], answer: 1 },
      { id: "q4", prompt: "A strong sense of belonging should allow you to...", choices: ["be respected without hiding important parts of yourself", "agree with the group at all times", "exclude outsiders", "avoid individual goals"], answer: 0 },
      { id: "q5", prompt: "When two of your values seem to conflict, it helps to...", choices: ["consider consequences and which value matters most in that situation", "let someone else always decide", "act before thinking", "pretend neither value matters"], answer: 0 },
      { id: "q6", prompt: "Stereotype threat can affect someone when they...", choices: ["worry about confirming a negative stereotype about their group", "learn about another culture", "join a supportive team", "change an ordinary preference"], answer: 0 },
    ],
  },
  {
    id: "sel-g7-decisions-consequences",
    subjectId: "sel",
    level: "grade7",
    title: "Decisions, Risk & Consequences",
    description: "Pause, evaluate evidence and pressure, and choose with long-term consequences in mind.",
    emoji: "⚖️",
    questions: [
      { id: "q1", prompt: "Before a high-impact decision, the most useful first step is to...", choices: ["identify the decision and possible outcomes", "follow the crowd", "choose the fastest option", "assume there is no risk"], answer: 0 },
      { id: "q2", prompt: "A short-term reward may be a poor choice when it...", choices: ["creates serious long-term harm", "requires planning", "helps someone else", "matches your values"], answer: 0 },
      { id: "q3", prompt: "Friends pressure you to share an embarrassing video. Which response shows integrity?", choices: ["Share it before it disappears", "Refuse and ask that it be deleted", "Watch but do not comment", "Send it privately"], answer: 1 },
      { id: "q4", prompt: "Reliable evidence for a decision should be...", choices: ["relevant and from trustworthy sources", "the first claim you see", "popular but unverified", "based only on fear"], answer: 0 },
      { id: "q5", prompt: "If emotions are making a decision feel urgent, you can...", choices: ["pause until you can think more clearly", "act immediately", "ignore all consequences", "ask only someone who agrees"], answer: 0 },
      { id: "q6", prompt: "Taking responsibility after a poor choice means...", choices: ["acknowledging the impact, repairing harm, and changing course", "giving a convincing excuse", "hiding all evidence", "blaming the person affected"], answer: 0 },
    ],
  },
  {
    id: "sel-g7-resilience-support",
    subjectId: "sel",
    level: "grade7",
    title: "Resilience & Asking for Support",
    description: "Recover from setbacks, respond to unhelpful thoughts, and know when to seek help.",
    emoji: "🌱",
    questions: [
      { id: "q1", prompt: "Resilience means...", choices: ["never feeling upset", "adapting and recovering after difficulty", "handling every problem alone", "avoiding all risks"], answer: 1 },
      { id: "q2", prompt: "After not making a team, a resilient next step might be to...", choices: ["identify skills to practice and another opportunity to participate", "decide you have no ability", "insult the selected players", "avoid the activity forever"], answer: 0 },
      { id: "q3", prompt: "Which thought is an example of reframing?", choices: ["One setback proves I'll always fail", "This result hurts, but it can show me what to work on", "Nothing I do matters", "Everyone is judging me"], answer: 1 },
      { id: "q4", prompt: "Asking for help is especially important when...", choices: ["a problem feels unsafe or too heavy to manage alone", "you want to avoid all effort", "you already know the answer", "someone tells you help is weak"], answer: 0 },
      { id: "q5", prompt: "Which person could be part of a support network?", choices: ["A trusted family member, teacher, coach, or counselor", "Only someone your age", "An anonymous stranger", "Nobody but yourself"], answer: 0 },
      { id: "q6", prompt: "A friend says they may hurt themselves. What should you do?", choices: ["Keep it secret", "Tell a trusted adult immediately, even if your friend asks you not to", "Try to manage it alone", "Wait several days"], answer: 1, explanation: "Safety comes first. A trusted adult can connect your friend with immediate support." },
    ],
  },

  // ─────────────────────────────────────────────
  // GRADE 8
  // ─────────────────────────────────────────────
  {
    id: "sel-g8-digital-wellbeing",
    subjectId: "sel",
    level: "grade8",
    title: "Digital Well-Being & Social Comparison",
    description: "Use social media intentionally and protect your attention, mood, and self-worth.",
    emoji: "📱",
    questions: [
      { id: "q1", prompt: "Why can comparing your life with social media posts be misleading?", choices: ["Posts often show selected highlights rather than the whole picture", "Every post is fictional", "Online experiences never affect emotions", "Only adults edit photos"], answer: 0 },
      { id: "q2", prompt: "You notice scrolling late at night is affecting your sleep. A useful boundary is to...", choices: ["keep your phone under your pillow", "set a device cutoff and charge it outside the bedroom", "turn up screen brightness", "open more apps"], answer: 1 },
      { id: "q3", prompt: "Which sign suggests an online space may be harming your well-being?", choices: ["You regularly leave it feeling anxious or worse about yourself", "You learn a useful skill", "You connect with a trusted friend", "You take planned breaks"], answer: 0 },
      { id: "q4", prompt: "A healthy response to an upsetting post is to...", choices: ["reply immediately while angry", "pause, check the context, and choose whether engaging is useful", "share it without reading", "assume it represents everyone"], answer: 1 },
      { id: "q5", prompt: "Curating your feed means...", choices: ["choosing accounts that support your interests and well-being", "making every account public", "following anyone who asks", "hiding all online activity"], answer: 0 },
      { id: "q6", prompt: "Which habit best protects focused study time?", choices: ["Keeping every notification on", "Using a planned focus period with notifications silenced", "Switching apps every few minutes", "Studying only when messages stop"], answer: 1 },
    ],
  },
  {
    id: "sel-g8-communication-repair",
    subjectId: "sel",
    level: "grade8",
    title: "Communication, Conflict & Repair",
    description: "Handle misunderstandings directly, listen for meaning, and rebuild trust after conflict.",
    emoji: "💬",
    questions: [
      { id: "q1", prompt: "Which opening is most likely to support a productive conflict conversation?", choices: ["You always ruin everything", "I felt left out when plans changed without telling me", "Everyone agrees you're wrong", "Forget it; it doesn't matter"], answer: 1 },
      { id: "q2", prompt: "Reflective listening means...", choices: ["repeating every word exactly", "checking that you understood the speaker's meaning", "planning your argument while they speak", "agreeing with every opinion"], answer: 1 },
      { id: "q3", prompt: "A text message sounds rude, but its tone is unclear. What is the best next step?", choices: ["Post it publicly", "Ask the sender what they meant before assuming intent", "Send a harsher reply", "End the friendship immediately"], answer: 1 },
      { id: "q4", prompt: "A complete apology includes...", choices: ["acknowledging the impact and explaining how you will act differently", "the words 'I'm sorry' followed by blame", "a demand for immediate forgiveness", "pretending the harm was small"], answer: 0 },
      { id: "q5", prompt: "When a conversation becomes too heated, a respectful pause should include...", choices: ["leaving without explanation", "agreeing on when to return to the conversation", "refusing to discuss it again", "asking others to take sides"], answer: 1 },
      { id: "q6", prompt: "Trust is most likely to rebuild when someone...", choices: ["makes repeated promises", "consistently follows through on changed behavior", "avoids the person affected", "explains why the other person overreacted"], answer: 1 },
    ],
  },
  {
    id: "sel-g8-stress-planning",
    subjectId: "sel",
    level: "grade8",
    title: "Stress, Priorities & Coping Plans",
    description: "Distinguish controllable problems from worries and build a realistic coping plan.",
    emoji: "🧠",
    questions: [
      { id: "q1", prompt: "Which action focuses on something you can control before an exam?", choices: ["Predicting every question", "Making a study schedule and asking for clarification", "Controlling other students' scores", "Guaranteeing the final grade"], answer: 1 },
      { id: "q2", prompt: "A coping plan is most useful when it...", choices: ["names your warning signs, strategies, and support people", "depends on never feeling stressed", "uses the same strategy in every situation", "keeps concerns secret"], answer: 0 },
      { id: "q3", prompt: "You have three major assignments due soon. What is the strongest first step?", choices: ["Avoid checking deadlines", "List each task, deadline, and next concrete action", "Begin all three at the same time", "Wait until motivation appears"], answer: 1 },
      { id: "q4", prompt: "Problem-focused coping is best illustrated by...", choices: ["asking a teacher for help with confusing directions", "pretending the assignment does not exist", "criticizing yourself", "staying awake worrying"], answer: 0 },
      { id: "q5", prompt: "Emotion-focused coping can help when...", choices: ["you need to calm your body before solving a problem", "you want every problem to disappear", "deadlines do not matter", "you can control another person's choices"], answer: 0 },
      { id: "q6", prompt: "If stress remains intense and interferes with daily life, you should...", choices: ["handle it entirely alone", "tell a trusted adult, counselor, or health professional", "stop sleeping to catch up", "hide it from people who care"], answer: 1 },
    ],
  },

  // ─────────────────────────────────────────────
  // GRADE 9
  // ─────────────────────────────────────────────
  {
    id: "sel-g9-independence-executive-skills",
    subjectId: "sel",
    level: "grade9",
    title: "Independence & Executive Skills",
    description: "Manage high-school responsibilities with planning, self-advocacy, and flexible routines.",
    emoji: "🗂️",
    questions: [
      { id: "q1", prompt: "Self-advocacy means...", choices: ["communicating what you need and taking part in finding a solution", "expecting others to notice every problem", "avoiding difficult conversations", "demanding that rules never apply"], answer: 0 },
      { id: "q2", prompt: "You do not understand an assignment. Which message shows effective self-advocacy?", choices: ["This makes no sense", "Could you clarify the evidence required for the final section?", "I'll just skip it", "Someone else should explain everything"], answer: 1 },
      { id: "q3", prompt: "Planning backward from a deadline means...", choices: ["starting with the due date and scheduling earlier milestones", "waiting until the final day", "doing the last step first", "changing the deadline yourself"], answer: 0 },
      { id: "q4", prompt: "Which approach helps when a routine stops working?", choices: ["Identify the obstacle, adjust the system, and test the change", "Assume you lack willpower", "Abandon every goal", "Copy another person's schedule exactly"], answer: 0 },
      { id: "q5", prompt: "Prioritizing by urgency and importance helps you...", choices: ["decide what deserves attention first", "avoid all difficult tasks", "make every task equally urgent", "finish work without effort"], answer: 0 },
      { id: "q6", prompt: "Responsible independence includes...", choices: ["knowing when to act alone and when to seek support", "never asking questions", "making choices without considering others", "hiding mistakes"], answer: 0 },
    ],
  },
  {
    id: "sel-g9-healthy-relationships",
    subjectId: "sel",
    level: "grade9",
    title: "Healthy Relationships & Consent",
    description: "Recognize mutual respect, communicate boundaries, and respond safely to controlling behavior.",
    emoji: "🤝",
    questions: [
      { id: "q1", prompt: "A healthy relationship is built on...", choices: ["mutual respect, trust, and honest communication", "constant access to each other's accounts", "one person making every decision", "avoiding all disagreement"], answer: 0 },
      { id: "q2", prompt: "Consent should be...", choices: ["freely given, informed, specific, and reversible", "assumed from silence", "permanent once given", "required to avoid disappointing someone"], answer: 0 },
      { id: "q3", prompt: "Which behavior may signal an unhealthy relationship?", choices: ["Supporting separate interests", "Demanding passwords and monitoring locations", "Respecting a request for space", "Discussing disagreements calmly"], answer: 1 },
      { id: "q4", prompt: "Someone sets a boundary you do not understand. A respectful response is to...", choices: ["honor it and ask questions without pressure", "test whether they really mean it", "take it as a personal attack", "ask friends to change their mind"], answer: 0 },
      { id: "q5", prompt: "Jealousy is a feeling, but it does not justify...", choices: ["controlling another person's friendships or choices", "talking honestly about insecurity", "taking time to calm down", "reflecting on what triggered it"], answer: 0 },
      { id: "q6", prompt: "If you feel controlled or unsafe in a relationship, a strong next step is to...", choices: ["isolate yourself", "contact a trusted adult, counselor, or support service", "keep it secret to protect the relationship", "respond with threats"], answer: 1 },
    ],
  },
  {
    id: "sel-g9-mental-health-literacy",
    subjectId: "sel",
    level: "grade9",
    title: "Mental Health Literacy & Support",
    description: "Understand mental well-being, challenge stigma, and connect yourself or a friend with help.",
    emoji: "🌿",
    questions: [
      { id: "q1", prompt: "Mental health refers to...", choices: ["emotional, psychological, and social well-being", "feeling happy at all times", "a person's physical strength only", "something that matters only during a crisis"], answer: 0 },
      { id: "q2", prompt: "Which change may be a reason to check in and seek support?", choices: ["Persistent distress that interferes with sleep, school, or relationships", "Enjoying a new hobby", "Having one difficult afternoon", "Wanting quiet time after a busy day"], answer: 0 },
      { id: "q3", prompt: "Stigma can prevent people from getting help because it...", choices: ["creates shame or fear of judgment", "makes support easier to find", "provides accurate information", "improves communication"], answer: 0 },
      { id: "q4", prompt: "A friend says they have been struggling emotionally. A supportive response is...", choices: ["Listen without judgment and help them connect with a trusted adult", "Diagnose the problem yourself", "Promise to keep every concern secret", "Tell them others have it worse"], answer: 0 },
      { id: "q5", prompt: "If someone talks about suicide or immediate self-harm, you should...", choices: ["tell a trusted adult or emergency support immediately and stay with them if safe", "wait to see whether they mention it again", "promise secrecy", "try to solve it without help"], answer: 0, explanation: "Treat talk of suicide or self-harm seriously. Immediate adult or emergency support can protect a life." },
      { id: "q6", prompt: "Professional mental-health support can...", choices: ["provide assessment, coping tools, and treatment", "guarantee life has no stress", "replace every personal relationship", "help only after an emergency"], answer: 0 },
    ],
  },
];
