/**
 * Brainy Buddies — 1st Grade activities.
 * Loaded by brainy-data.ts and merged into the ACTIVITIES list.
 */
import type { Activity } from "@/lib/brainy-data";

export const GRADE1_ACTIVITIES: Activity[] = [
  // -------- MATH (1st Grade) --------
  {
    id: "g1-math-add20",
    subjectId: "math",
    level: "grade1",
    title: "Adding within 20",
    description: "Add numbers up to twenty.",
    emoji: "\u2795",
    questions: [
      { id: "q1", prompt: "6 + 5 = ?", choices: ["10", "11", "12", "13"], answer: 1 },
      { id: "q2", prompt: "7 + 4 = ?", choices: ["10", "11", "12", "13"], answer: 1 },
      { id: "q3", prompt: "8 + 6 = ?", choices: ["13", "14", "15", "16"], answer: 1 },
      { id: "q4", prompt: "9 + 9 = ?", choices: ["16", "17", "18", "19"], answer: 2 },
      { id: "q5", prompt: "10 + 7 = ?", choices: ["15", "16", "17", "18"], answer: 2 },
      { id: "q6", prompt: "12 + 5 = ?", choices: ["16", "17", "18", "19"], answer: 1 },
      { id: "q7", prompt: "11 + 8 = ?", choices: ["18", "19", "20", "21"], answer: 1 },
      { id: "q8", prompt: "You have 6 stickers and find 7 more. How many?", choices: ["12", "13", "14", "15"], answer: 1 },
      { id: "q9", prompt: "3 + 4 + 5 = ?", choices: ["11", "12", "13", "14"], answer: 1 },
      { id: "q10", prompt: "15 + 4 = ?", choices: ["18", "19", "20", "21"], answer: 1 },
      { id: "q11", prompt: "What plus 6 equals 14?", choices: ["6", "7", "8", "9"], answer: 2 },
      { id: "q12", prompt: "5 + 8 = ?", choices: ["13", "12", "11", "14"], answer: 0, explanation: "5 and 8 make 13." },
      { id: "q13", prompt: "9 + 6 = ?", choices: ["13", "14", "15", "16"], answer: 2 },
      { id: "q14", prompt: "7 + 7 = ?", choices: ["12", "13", "14", "15"], answer: 2, explanation: "Doubles: 7 + 7 = 14." },
      { id: "q15", prompt: "4 + 9 = ?", choices: ["13", "14", "15", "12"], answer: 0 },
      { id: "q16", prompt: "10 + 10 = ?", choices: ["18", "19", "20", "21"], answer: 2, explanation: "Two tens make 20." },
      { id: "q17", prompt: "8 + 4 = ?", choices: ["12", "11", "10", "13"], answer: 0 },
      { id: "q18", prompt: "You have 9 marbles and get 5 more. How many?", choices: ["13", "14", "15", "16"], answer: 1, explanation: "9 + 5 = 14." },
    ],
  },
  {
    id: "g1-math-sub",
    subjectId: "math",
    level: "grade1",
    title: "Taking Away",
    description: "Subtraction within 20.",
    emoji: "\u2796",
    questions: [
      { id: "q1", prompt: "10 - 4 = ?", choices: ["4", "5", "6", "7"], answer: 2 },
      { id: "q2", prompt: "12 - 5 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q3", prompt: "15 - 7 = ?", choices: ["7", "8", "9", "10"], answer: 1 },
      { id: "q4", prompt: "9 - 3 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
      { id: "q5", prompt: "18 - 9 = ?", choices: ["8", "9", "10", "11"], answer: 1 },
      { id: "q6", prompt: "You had 14 grapes and ate 6. How many left?", choices: ["7", "8", "9", "10"], answer: 1 },
      { id: "q7", prompt: "20 - 10 = ?", choices: ["5", "10", "15", "20"], answer: 1 },
      { id: "q8", prompt: "13 - 8 = ?", choices: ["4", "5", "6", "7"], answer: 1 },
      { id: "q9", prompt: "11 - 4 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q10", prompt: "17 - 9 = ?", choices: ["7", "8", "9", "10"], answer: 1 },
      { id: "q11", prompt: "16 - 7 = ?", choices: ["9", "8", "10", "11"], answer: 0, explanation: "16 take away 7 leaves 9." },
      { id: "q12", prompt: "14 - 5 = ?", choices: ["7", "8", "9", "10"], answer: 2 },
      { id: "q13", prompt: "19 - 9 = ?", choices: ["8", "9", "10", "11"], answer: 2, explanation: "19 minus 9 is 10." },
      { id: "q14", prompt: "12 - 8 = ?", choices: ["4", "5", "6", "7"], answer: 0 },
      { id: "q15", prompt: "15 - 6 = ?", choices: ["8", "9", "10", "11"], answer: 1, explanation: "15 take away 6 leaves 9." },
      { id: "q16", prompt: "You had 13 stickers and gave away 7. How many left?", choices: ["6", "7", "8", "9"], answer: 0 },
      { id: "q17", prompt: "10 - 7 = ?", choices: ["1", "2", "3", "4"], answer: 2 },
      { id: "q18", prompt: "16 - 8 = ?", choices: ["7", "8", "9", "10"], answer: 1, explanation: "Half of 16 is 8." },
    ],
  },
  {
    id: "g1-math-place",
    subjectId: "math",
    level: "grade1",
    title: "Tens and Ones",
    description: "Place value up to 100.",
    emoji: "\u{1F522}",
    questions: [
      { id: "q1", prompt: "In 34, the tens digit is...", choices: ["3", "4", "30", "34"], answer: 0 },
      { id: "q2", prompt: "In 47, the ones digit is...", choices: ["4", "7", "40", "47"], answer: 1 },
      { id: "q3", prompt: "5 tens and 2 ones make...", choices: ["25", "52", "7", "502"], answer: 1 },
      { id: "q4", prompt: "7 tens = ?", choices: ["7", "17", "70", "77"], answer: 2 },
      { id: "q5", prompt: "Which is bigger?", choices: ["49", "61", "48", "59"], answer: 1 },
      { id: "q6", prompt: "What comes just before 70?", choices: ["60", "69", "71", "79"], answer: 1 },
      { id: "q7", prompt: "What comes just after 89?", choices: ["88", "90", "99", "100"], answer: 1 },
      { id: "q8", prompt: "How many tens in 60?", choices: ["5", "6", "7", "60"], answer: 1 },
      { id: "q9", prompt: "40 + 3 = ?", choices: ["34", "43", "44", "73"], answer: 1 },
      { id: "q10", prompt: "Which number is the smallest?", choices: ["58", "85", "75", "68"], answer: 0 },
      { id: "q11", prompt: "In 56, the tens digit is...", choices: ["5", "6", "50", "56"], answer: 0 },
      { id: "q12", prompt: "In 83, the ones digit is...", choices: ["8", "3", "80", "83"], answer: 1 },
      { id: "q13", prompt: "6 tens and 4 ones make...", choices: ["46", "64", "10", "604"], answer: 1, explanation: "6 tens is 60, plus 4 is 64." },
      { id: "q14", prompt: "9 tens = ?", choices: ["9", "19", "90", "99"], answer: 2 },
      { id: "q15", prompt: "What comes just after 49?", choices: ["48", "50", "59", "40"], answer: 1 },
      { id: "q16", prompt: "What comes just before 30?", choices: ["20", "28", "29", "31"], answer: 2, explanation: "29 comes right before 30." },
      { id: "q17", prompt: "50 + 6 = ?", choices: ["56", "65", "506", "11"], answer: 0 },
      { id: "q18", prompt: "How many tens are in 80?", choices: ["7", "8", "9", "80"], answer: 1, explanation: "80 is 8 groups of ten." },
    ],
  },
  {
    id: "g1-math-time",
    subjectId: "math",
    level: "grade1",
    title: "Time & Money Basics",
    description: "Tell time to the hour and count coins.",
    emoji: "\u23F0",
    questions: [
      { id: "q1", prompt: "How many minutes in 1 hour?", choices: ["30", "45", "60", "100"], answer: 2 },
      { id: "q2", prompt: "A penny is worth...", choices: ["1 cent", "5 cents", "10 cents", "25 cents"], answer: 0 },
      { id: "q3", prompt: "A nickel is worth...", choices: ["1 cent", "5 cents", "10 cents", "25 cents"], answer: 1 },
      { id: "q4", prompt: "A dime is worth...", choices: ["1 cent", "5 cents", "10 cents", "25 cents"], answer: 2 },
      { id: "q5", prompt: "A quarter is worth...", choices: ["5 cents", "10 cents", "15 cents", "25 cents"], answer: 3 },
      { id: "q6", prompt: "3 dimes = ?", choices: ["3 cents", "15 cents", "30 cents", "50 cents"], answer: 2 },
      { id: "q7", prompt: "How many hours in a day?", choices: ["12", "20", "24", "30"], answer: 2 },
      { id: "q8", prompt: "A clock shows 3 o'clock. The long hand points to...", choices: ["12", "3", "6", "9"], answer: 0 },
      { id: "q9", prompt: "2 quarters = ?", choices: ["25 cents", "50 cents", "75 cents", "100 cents"], answer: 1 },
      { id: "q10", prompt: "How many days in a week?", choices: ["5", "6", "7", "10"], answer: 2 },
      { id: "q11", prompt: "How many minutes are in half an hour?", choices: ["15", "30", "45", "60"], answer: 1 },
      { id: "q12", prompt: "2 nickels = ?", choices: ["5 cents", "10 cents", "15 cents", "20 cents"], answer: 1, explanation: "Each nickel is 5 cents, so two make 10." },
      { id: "q13", prompt: "4 quarters = ?", choices: ["50 cents", "75 cents", "100 cents", "125 cents"], answer: 2, explanation: "Four quarters make one dollar, or 100 cents." },
      { id: "q14", prompt: "How many months are in a year?", choices: ["7", "10", "12", "24"], answer: 2 },
      { id: "q15", prompt: "A clock shows 6 o'clock. The short hand points to...", choices: ["3", "6", "9", "12"], answer: 1 },
      { id: "q16", prompt: "5 pennies = ?", choices: ["1 cent", "5 cents", "10 cents", "25 cents"], answer: 1 },
      { id: "q17", prompt: "How many seasons are in a year?", choices: ["2", "3", "4", "5"], answer: 2, explanation: "Spring, summer, fall, and winter." },
      { id: "q18", prompt: "1 dime and 1 nickel together = ?", choices: ["10 cents", "15 cents", "20 cents", "25 cents"], answer: 1, explanation: "10 cents plus 5 cents is 15 cents." },
    ],
  },

  // -------- SCIENCE (1st Grade) --------
  {
    id: "g1-sci-habitats",
    subjectId: "science",
    level: "grade1",
    title: "Animal Habitats",
    description: "Where animals live and what they need.",
    emoji: "\u{1F438}",
    questions: [
      { id: "q1", prompt: "A polar bear lives in the...", choices: ["desert", "Arctic", "jungle", "ocean floor"], answer: 1 },
      { id: "q2", prompt: "A camel is best suited for the...", choices: ["forest", "desert", "ocean", "snow"], answer: 1 },
      { id: "q3", prompt: "Fish breathe using their...", choices: ["lungs", "gills", "nose", "skin"], answer: 1 },
      { id: "q4", prompt: "A frog lives in/near...", choices: ["sand", "ponds", "clouds", "caves only"], answer: 1 },
      { id: "q5", prompt: "All animals need food, water, and...", choices: ["toys", "shelter", "phones", "music"], answer: 1 },
      { id: "q6", prompt: "Which animal is a mammal?", choices: ["shark", "snake", "dolphin", "eagle"], answer: 2 },
      { id: "q7", prompt: "Reptiles like lizards have...", choices: ["feathers", "fur", "scales", "gills"], answer: 2 },
      { id: "q8", prompt: "A rainforest is...", choices: ["dry and cold", "warm and rainy", "frozen all year", "empty of life"], answer: 1 },
      { id: "q9", prompt: "Birds lay...", choices: ["eggs", "seeds", "shells", "leaves"], answer: 0 },
      { id: "q10", prompt: "An animal that eats only plants is a...", choices: ["carnivore", "herbivore", "omnivore", "recycler"], answer: 1 },
      { id: "q11", prompt: "A bird's home is called a...", choices: ["nest", "den", "web", "hive"], answer: 0 },
      { id: "q12", prompt: "Bees live together in a...", choices: ["hive", "nest", "cave", "pond"], answer: 0, explanation: "A bee colony lives in a hive." },
      { id: "q13", prompt: "Which animal lives in the ocean?", choices: ["lion", "whale", "camel", "squirrel"], answer: 1 },
      { id: "q14", prompt: "An animal that eats both plants and meat is an...", choices: ["herbivore", "carnivore", "omnivore", "producer"], answer: 2, explanation: "Omnivores eat plants and animals." },
      { id: "q15", prompt: "A desert habitat is very...", choices: ["wet", "dry", "icy", "green"], answer: 1 },
      { id: "q16", prompt: "A forest is a habitat full of...", choices: ["trees", "waves", "sand dunes", "icebergs"], answer: 0 },
      { id: "q17", prompt: "A spider catches food in its...", choices: ["nest", "web", "shell", "den"], answer: 1, explanation: "Spiders spin webs to trap insects." },
      { id: "q18", prompt: "Animals need air, food, water, and a safe...", choices: ["toy", "home", "phone", "hat"], answer: 1 },
    ],
  },
  {
    id: "g1-sci-body",
    subjectId: "science",
    level: "grade1",
    title: "Our Amazing Body",
    description: "Body parts and staying healthy.",
    emoji: "\u{1F9B7}",
    questions: [
      { id: "q1", prompt: "Your heart pumps...", choices: ["air", "blood", "food", "water only"], answer: 1 },
      { id: "q2", prompt: "You breathe in with your...", choices: ["liver", "lungs", "stomach", "bones"], answer: 1 },
      { id: "q3", prompt: "Bones together make your...", choices: ["muscles", "skeleton", "skin", "brain"], answer: 1 },
      { id: "q4", prompt: "How many bones do adults usually have?", choices: ["around 50", "around 100", "around 200", "around 1000"], answer: 2 },
      { id: "q5", prompt: "To stay healthy, you should...", choices: ["never sleep", "eat fruit and veggies", "only eat candy", "never move"], answer: 1 },
      { id: "q6", prompt: "Brushing your teeth keeps them...", choices: ["dirty", "weak", "clean and strong", "colorful"], answer: 2 },
      { id: "q7", prompt: "You think with your...", choices: ["heart", "brain", "stomach", "feet"], answer: 1 },
      { id: "q8", prompt: "Muscles help you...", choices: ["see", "move", "taste", "hear"], answer: 1 },
      { id: "q9", prompt: "Food gets broken down in your...", choices: ["lungs", "stomach", "ears", "hair"], answer: 1 },
      { id: "q10", prompt: "Kids should sleep about how many hours?", choices: ["2", "5", "10", "20"], answer: 2 },
      { id: "q11", prompt: "You see with your...", choices: ["ears", "eyes", "nose", "hands"], answer: 1 },
      { id: "q12", prompt: "You smell with your...", choices: ["tongue", "ears", "nose", "feet"], answer: 2 },
      { id: "q13", prompt: "You hear with your...", choices: ["ears", "eyes", "mouth", "knees"], answer: 0 },
      { id: "q14", prompt: "Skin covers and protects your...", choices: ["bones only", "body", "hair only", "food"], answer: 1, explanation: "Skin is the body's outer cover." },
      { id: "q15", prompt: "Your tongue helps you...", choices: ["see", "taste", "hear", "smell"], answer: 1 },
      { id: "q16", prompt: "Washing your hands helps stop...", choices: ["games", "germs", "grass", "growth"], answer: 1, explanation: "Clean hands keep germs away." },
      { id: "q17", prompt: "Exercise makes your body...", choices: ["weaker", "stronger", "sleepy", "smaller"], answer: 1 },
      { id: "q18", prompt: "How many senses do people have?", choices: ["3", "4", "5", "6"], answer: 2, explanation: "Sight, hearing, smell, taste, and touch." },
    ],
  },
  {
    id: "g1-sci-matter",
    subjectId: "science",
    level: "grade1",
    title: "Solid, Liquid, Gas",
    description: "States of matter all around us.",
    emoji: "\u{1F4A7}",
    questions: [
      { id: "q1", prompt: "Ice is a...", choices: ["solid", "liquid", "gas", "plasma"], answer: 0 },
      { id: "q2", prompt: "Water you drink is a...", choices: ["solid", "liquid", "gas", "rock"], answer: 1 },
      { id: "q3", prompt: "Steam from a kettle is a...", choices: ["solid", "liquid", "gas", "crystal"], answer: 2 },
      { id: "q4", prompt: "When ice gets warm it...", choices: ["freezes", "melts", "vanishes", "explodes"], answer: 1 },
      { id: "q5", prompt: "When water gets very cold it...", choices: ["melts", "boils", "freezes", "runs away"], answer: 2 },
      { id: "q6", prompt: "Air around you is mostly a...", choices: ["solid", "liquid", "gas", "flame"], answer: 2 },
      { id: "q7", prompt: "Which keeps its shape on its own?", choices: ["a solid", "a liquid", "a gas", "a cloud"], answer: 0 },
      { id: "q8", prompt: "Liquids take the shape of their...", choices: ["clothes", "container", "name", "sound"], answer: 1 },
      { id: "q9", prompt: "Boiling water turns into...", choices: ["ice", "steam", "sand", "snow"], answer: 1 },
      { id: "q10", prompt: "A rock is a...", choices: ["solid", "liquid", "gas", "rainbow"], answer: 0 },
      { id: "q11", prompt: "Milk you pour is a...", choices: ["solid", "liquid", "gas", "star"], answer: 1 },
      { id: "q12", prompt: "A wooden block is a...", choices: ["solid", "liquid", "gas", "cloud"], answer: 0 },
      { id: "q13", prompt: "The bubbles in soda are a...", choices: ["solid", "liquid", "gas", "metal"], answer: 2, explanation: "The fizz is gas bubbles." },
      { id: "q14", prompt: "Heating ice makes it...", choices: ["colder", "melt", "freeze", "harder"], answer: 1 },
      { id: "q15", prompt: "Water can be ice, liquid water, or...", choices: ["sand", "steam", "wood", "glass"], answer: 1, explanation: "Steam is water as a gas." },
      { id: "q16", prompt: "A balloon is filled with...", choices: ["a solid", "a liquid", "gas", "a rock"], answer: 2 },
      { id: "q17", prompt: "Juice takes the shape of its...", choices: ["shoe", "cup", "name", "color"], answer: 1, explanation: "Liquids fit the shape of their container." },
      { id: "q18", prompt: "Which one can you pour?", choices: ["a brick", "water", "a rock", "a book"], answer: 1 },
    ],
  },
  {
    id: "g1-sci-space",
    subjectId: "science",
    level: "grade1",
    title: "Sun, Moon & Stars",
    description: "Day, night, and the sky.",
    emoji: "\u{1F31E}",
    questions: [
      { id: "q1", prompt: "The sun is a...", choices: ["planet", "star", "moon", "comet"], answer: 1 },
      { id: "q2", prompt: "Earth goes around the...", choices: ["moon", "sun", "stars", "clouds"], answer: 1 },
      { id: "q3", prompt: "The moon goes around...", choices: ["the sun", "Earth", "itself only", "Mars"], answer: 1 },
      { id: "q4", prompt: "It's night when our side of Earth faces...", choices: ["the sun", "away from the sun", "sideways", "the moon only"], answer: 1 },
      { id: "q5", prompt: "How long does it take Earth to spin one time?", choices: ["1 hour", "1 day", "1 week", "1 year"], answer: 1 },
      { id: "q6", prompt: "How long does Earth take to go around the sun?", choices: ["1 day", "1 month", "1 year", "100 years"], answer: 2 },
      { id: "q7", prompt: "The moon looks like it changes...", choices: ["color", "shape", "smell", "size"], answer: 1 },
      { id: "q8", prompt: "A shape of the moon you can see is the...", choices: ["square moon", "full moon", "flat moon", "upside-down moon"], answer: 1 },
      { id: "q9", prompt: "Stars look small because they are very...", choices: ["tiny", "close", "far away", "blue"], answer: 2 },
      { id: "q10", prompt: "Astronauts go to space in a...", choices: ["submarine", "rocket", "helicopter", "truck"], answer: 1 },
      { id: "q11", prompt: "The sun gives us light and...", choices: ["snow", "heat", "rain", "wind"], answer: 1 },
      { id: "q12", prompt: "We see the sun during the...", choices: ["night", "day", "midnight", "sleep"], answer: 1 },
      { id: "q13", prompt: "We can often see the moon and stars at...", choices: ["noon", "night", "breakfast", "lunch"], answer: 1 },
      { id: "q14", prompt: "Earth is shaped like a...", choices: ["square", "ball", "flat plate", "triangle"], answer: 1, explanation: "Earth is round like a ball." },
      { id: "q15", prompt: "The planet we live on is...", choices: ["Mars", "Earth", "Venus", "the moon"], answer: 1 },
      { id: "q16", prompt: "A group of stars that makes a picture is a...", choices: ["puddle", "constellation", "rainbow", "cloud"], answer: 1, explanation: "Constellations are star patterns." },
      { id: "q17", prompt: "The sun is the closest...", choices: ["planet", "star", "moon", "cloud"], answer: 1 },
      { id: "q18", prompt: "You should never look straight at the...", choices: ["moon", "sun", "stars", "clouds"], answer: 1, explanation: "The bright sun can hurt your eyes." },
    ],
  },

  // -------- HISTORY (1st Grade) --------
  {
    id: "g1-hist-then-now",
    subjectId: "history",
    level: "grade1",
    title: "Then and Now",
    description: "How life has changed over time.",
    emoji: "\u{1F570}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "Long ago, people did NOT have...", choices: ["fire", "phones", "food", "clothes"], answer: 1 },
      { id: "q2", prompt: "Long ago, people often traveled by...", choices: ["airplane", "horse", "spaceship", "subway"], answer: 1 },
      { id: "q3", prompt: "A washing tub long ago is like today's...", choices: ["oven", "washing machine", "TV", "car"], answer: 1 },
      { id: "q4", prompt: "A candle long ago is like today's...", choices: ["radio", "lamp", "chair", "clock"], answer: 1 },
      { id: "q5", prompt: "Letters once took days. Today we send...", choices: ["emails", "smoke signals", "pigeons", "newspapers"], answer: 0 },
      { id: "q6", prompt: "A horse-drawn wagon is like today's...", choices: ["car", "phone", "house", "shoe"], answer: 0 },
      { id: "q7", prompt: "Things from long ago are studied as...", choices: ["math", "history", "science", "music"], answer: 1 },
      { id: "q8", prompt: "Old things kept in museums are called...", choices: ["toys", "artifacts", "snacks", "games"], answer: 1 },
      { id: "q9", prompt: "A person who studies the past is a...", choices: ["farmer", "historian", "pilot", "chef"], answer: 1 },
      { id: "q10", prompt: "Compared to long ago, today we have MORE...", choices: ["horses", "technology", "candles", "wagons"], answer: 1 },
      { id: "q11", prompt: "Long ago, kids often wrote on small...", choices: ["tablets", "slates", "laptops", "phones"], answer: 1, explanation: "They wrote with chalk on slates." },
      { id: "q12", prompt: "Today we keep food cold in a...", choices: ["campfire", "refrigerator", "cave", "well"], answer: 1 },
      { id: "q13", prompt: "Long ago, many people made their own...", choices: ["clothes", "cars", "computers", "planes"], answer: 0 },
      { id: "q14", prompt: "Old photographs were often black and...", choices: ["blue", "white", "green", "red"], answer: 1 },
      { id: "q15", prompt: "To talk to faraway friends today, we use...", choices: ["smoke signals", "phones", "drums", "flags"], answer: 1 },
      { id: "q16", prompt: "A covered wagon carried families looking for new...", choices: ["homes", "phones", "cars", "TVs"], answer: 0, explanation: "Pioneers traveled west to find land." },
      { id: "q17", prompt: "Before electric lights, people read by...", choices: ["candlelight", "flashlight", "TV", "phone"], answer: 0 },
      { id: "q18", prompt: "A way we learn about the past is by reading...", choices: ["the future", "history books", "comic ads", "menus"], answer: 1, explanation: "Books and stories tell us about long ago." },
    ],
  },
  {
    id: "g1-hist-presidents",
    subjectId: "history",
    level: "grade1",
    title: "Famous Americans",
    description: "People who shaped our country.",
    emoji: "\u{1F396}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "Who was the first U.S. president?", choices: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], answer: 1 },
      { id: "q2", prompt: "Abraham Lincoln helped end...", choices: ["winter", "slavery", "farming", "reading"], answer: 1 },
      { id: "q3", prompt: "Martin Luther King Jr. fought for...", choices: ["games", "civil rights", "trains", "food"], answer: 1 },
      { id: "q4", prompt: "Rosa Parks is known for refusing to give up her...", choices: ["snack", "bus seat", "book", "pencil"], answer: 1 },
      { id: "q5", prompt: "Benjamin Franklin flew a kite to study...", choices: ["wind", "electricity", "rain", "snow"], answer: 1 },
      { id: "q6", prompt: "Neil Armstrong was the first person to walk on the...", choices: ["sun", "moon", "Mars", "ocean floor"], answer: 1 },
      { id: "q7", prompt: "Susan B. Anthony fought for women's right to...", choices: ["run", "vote", "sing", "drive only"], answer: 1 },
      { id: "q8", prompt: "Harriet Tubman helped people escape from...", choices: ["school", "slavery", "snow", "work"], answer: 1 },
      { id: "q9", prompt: "Thomas Edison invented the...", choices: ["airplane", "light bulb", "car", "phone first"], answer: 1 },
      { id: "q10", prompt: "The Wright brothers built the first...", choices: ["car", "airplane", "computer", "radio"], answer: 1 },
      { id: "q11", prompt: "Helen Keller showed that people who cannot see or hear can still...", choices: ["fly", "learn", "drive", "sleep"], answer: 1, explanation: "She learned to read, write, and speak." },
      { id: "q12", prompt: "Amelia Earhart was a famous...", choices: ["singer", "pilot", "painter", "cook"], answer: 1 },
      { id: "q13", prompt: "Sacagawea helped explorers find their way across the...", choices: ["ocean", "land", "moon", "sky"], answer: 1 },
      { id: "q14", prompt: "Betsy Ross is said to have sewn an early American...", choices: ["dress", "flag", "blanket", "sail"], answer: 1, explanation: "She is famous for an early U.S. flag." },
      { id: "q15", prompt: "George Washington Carver studied...", choices: ["stars", "plants", "cars", "music"], answer: 1 },
      { id: "q16", prompt: "Who is on the one-dollar bill?", choices: ["Lincoln", "George Washington", "a king", "a queen"], answer: 1 },
      { id: "q17", prompt: "Mount Rushmore shows the faces of four U.S.", choices: ["singers", "presidents", "athletes", "kings"], answer: 1, explanation: "Four presidents are carved into the rock." },
      { id: "q18", prompt: "Jackie Robinson was a famous baseball...", choices: ["coach", "player", "fan", "reporter"], answer: 1 },
    ],
  },
  {
    id: "g1-hist-symbols",
    subjectId: "history",
    level: "grade1",
    title: "American Symbols",
    description: "Symbols and songs of the U.S.",
    emoji: "\u{1F1FA}\u{1F1F8}",
    questions: [
      { id: "q1", prompt: "How many stripes are on the U.S. flag?", choices: ["7", "10", "13", "50"], answer: 2 },
      { id: "q2", prompt: "How many stars are on the U.S. flag?", choices: ["13", "25", "50", "100"], answer: 2 },
      { id: "q3", prompt: "Each star stands for a...", choices: ["state", "city", "president", "river"], answer: 0 },
      { id: "q4", prompt: "The bald eagle is our national...", choices: ["flower", "bird", "mascot", "sport"], answer: 1 },
      { id: "q5", prompt: "The Statue of Liberty was a gift from...", choices: ["England", "France", "Mexico", "Japan"], answer: 1 },
      { id: "q6", prompt: "The Liberty Bell is in...", choices: ["Boston", "Philadelphia", "Chicago", "Miami"], answer: 1 },
      { id: "q7", prompt: "Our national anthem is...", choices: ["Happy Birthday", "The Star-Spangled Banner", "Twinkle Twinkle", "Yankee Doodle"], answer: 1 },
      { id: "q8", prompt: "The president lives in the...", choices: ["Capitol", "White House", "Big House", "Mansion"], answer: 1 },
      { id: "q9", prompt: "The U.S. capital city is...", choices: ["New York", "Washington, D.C.", "Los Angeles", "Boston"], answer: 1 },
      { id: "q10", prompt: "Stripes on the flag stand for the original...", choices: ["13 colonies", "50 states", "presidents", "songs"], answer: 0 },
      { id: "q11", prompt: "The colors of the U.S. flag are red, white, and...", choices: ["green", "blue", "yellow", "black"], answer: 1 },
      { id: "q12", prompt: "Another name for the U.S. flag is the...", choices: ["Big Banner", "Stars and Stripes", "Red Cross", "Star Map"], answer: 1, explanation: "The flag has stars and stripes." },
      { id: "q13", prompt: "The Statue of Liberty holds a...", choices: ["flag", "torch", "sword", "drum"], answer: 1 },
      { id: "q14", prompt: "We say the Pledge of Allegiance to the...", choices: ["moon", "flag", "mayor", "school"], answer: 1 },
      { id: "q15", prompt: "Mount Rushmore is carved into a...", choices: ["tree", "mountain", "wall", "cave"], answer: 1, explanation: "Faces are carved into a stone mountain." },
      { id: "q16", prompt: "The Liberty Bell has a famous...", choices: ["song", "crack", "light", "clock"], answer: 1 },
      { id: "q17", prompt: "How many stars did the very first U.S. flag have?", choices: ["7", "13", "25", "50"], answer: 1, explanation: "The first flag had 13 stars for 13 colonies." },
      { id: "q18", prompt: "The national bird, the bald eagle, is a kind of...", choices: ["fish", "bird", "bug", "bear"], answer: 1 },
    ],
  },
  {
    id: "g1-hist-rules",
    subjectId: "history",
    level: "grade1",
    title: "Rules & Citizens",
    description: "Why we have rules and how we help.",
    emoji: "\u2696\u{FE0F}",
    questions: [
      { id: "q1", prompt: "Rules at school help us stay...", choices: ["bored", "safe and fair", "alone", "hungry"], answer: 1 },
      { id: "q2", prompt: "A leader of a city is called the...", choices: ["mayor", "king", "chef", "captain"], answer: 0 },
      { id: "q3", prompt: "People who follow country rules are good...", choices: ["citizens", "tourists", "animals", "trees"], answer: 0 },
      { id: "q4", prompt: "In the U.S., grown-ups choose leaders by...", choices: ["voting", "dancing", "jumping", "singing"], answer: 0 },
      { id: "q5", prompt: "A red traffic light means...", choices: ["go", "slow", "stop", "turn"], answer: 2 },
      { id: "q6", prompt: "At a crosswalk you should...", choices: ["run fast", "look both ways", "close eyes", "jump"], answer: 1 },
      { id: "q7", prompt: "Helping a friend pick up books is being a good...", choices: ["thief", "citizen", "stranger", "runner"], answer: 1 },
      { id: "q8", prompt: "Recycling helps the...", choices: ["trash", "environment", "TV", "phone"], answer: 1 },
      { id: "q9", prompt: "Listening to your teacher is being...", choices: ["silly", "respectful", "sleepy", "loud"], answer: 1 },
      { id: "q10", prompt: "A right we have in the U.S. is to...", choices: ["never share", "speak freely", "break rules", "yell anywhere"], answer: 1 },
      { id: "q11", prompt: "A person who helps keep people safe and follows the law is a...", choices: ["police officer", "clown", "singer", "painter"], answer: 0 },
      { id: "q12", prompt: "A green traffic light means...", choices: ["stop", "go", "slow", "wait"], answer: 1 },
      { id: "q13", prompt: "Taking turns on the slide is being...", choices: ["mean", "fair", "rude", "loud"], answer: 1, explanation: "Sharing and taking turns is fair." },
      { id: "q14", prompt: "The leader of the United States is the...", choices: ["king", "president", "mayor", "captain"], answer: 1 },
      { id: "q15", prompt: "Wearing a seatbelt is a rule that keeps you...", choices: ["safe", "hungry", "late", "cold"], answer: 0 },
      { id: "q16", prompt: "Being honest means telling the...", choices: ["truth", "jokes", "secrets", "stories"], answer: 0, explanation: "Honest people tell the truth." },
      { id: "q17", prompt: "Putting trash in the bin keeps places...", choices: ["dirty", "clean", "messy", "dark"], answer: 1 },
      { id: "q18", prompt: "When you make a mistake, it is kind to say...", choices: ["nothing", "I'm sorry", "run away", "too bad"], answer: 1, explanation: "Saying sorry shows you care." },
    ],
  },

  // -------- GEOGRAPHY (1st Grade) --------
  {
    id: "g1-geo-continents",
    subjectId: "geography",
    level: "grade1",
    title: "Continents & Oceans",
    description: "The biggest pieces of land and water.",
    emoji: "\u{1F30E}",
    questions: [
      { id: "q1", prompt: "How many continents are there?", choices: ["5", "6", "7", "8"], answer: 2 },
      { id: "q2", prompt: "How many oceans are usually named?", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q3", prompt: "The United States is on which continent?", choices: ["Africa", "Asia", "North America", "Europe"], answer: 2 },
      { id: "q4", prompt: "Which is the LARGEST continent?", choices: ["Africa", "Asia", "Europe", "Australia"], answer: 1 },
      { id: "q5", prompt: "Which is the COLDEST continent?", choices: ["Antarctica", "Africa", "Asia", "Australia"], answer: 0 },
      { id: "q6", prompt: "The largest ocean is the...", choices: ["Atlantic", "Pacific", "Indian", "Arctic"], answer: 1 },
      { id: "q7", prompt: "Which continent is Egypt on?", choices: ["Africa", "Asia", "Europe", "North America"], answer: 0 },
      { id: "q8", prompt: "Australia is a country and a...", choices: ["city", "continent", "ocean", "state"], answer: 1 },
      { id: "q9", prompt: "Which is NOT a continent?", choices: ["Africa", "Europe", "Atlantic", "Asia"], answer: 2 },
      { id: "q10", prompt: "South America is south of...", choices: ["Africa", "Asia", "North America", "Antarctica"], answer: 2 },
      { id: "q11", prompt: "Which continent do penguins mostly live on?", choices: ["Africa", "Antarctica", "Europe", "Asia"], answer: 1 },
      { id: "q12", prompt: "The continent just south of Europe is...", choices: ["Africa", "Asia", "Australia", "Antarctica"], answer: 0 },
      { id: "q13", prompt: "The ocean at the very top of Earth is the...", choices: ["Pacific", "Indian", "Arctic", "Atlantic"], answer: 2, explanation: "The Arctic Ocean is near the North Pole." },
      { id: "q14", prompt: "Which continent has no countries?", choices: ["Asia", "Africa", "Antarctica", "Europe"], answer: 2 },
      { id: "q15", prompt: "China is on which continent?", choices: ["Asia", "Africa", "Europe", "Australia"], answer: 0 },
      { id: "q16", prompt: "The Atlantic Ocean is between the Americas and...", choices: ["Asia", "Europe", "Australia", "Antarctica"], answer: 1, explanation: "It lies between America and Europe/Africa." },
      { id: "q17", prompt: "Which is smaller, a continent or an island?", choices: ["a continent", "an island", "they are equal", "an ocean"], answer: 1 },
      { id: "q18", prompt: "The smallest continent is...", choices: ["Asia", "Europe", "Australia", "Africa"], answer: 2, explanation: "Australia is the smallest continent." },
    ],
  },
  {
    id: "g1-geo-maps",
    subjectId: "geography",
    level: "grade1",
    title: "Reading a Map",
    description: "Compass, keys, and directions.",
    emoji: "\u{1F5FA}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "On most maps, north is at the...", choices: ["top", "bottom", "left", "right"], answer: 0 },
      { id: "q2", prompt: "South is the opposite of...", choices: ["east", "north", "west", "up"], answer: 1 },
      { id: "q3", prompt: "The four main directions are N, S, E, and...", choices: ["O", "W", "P", "Q"], answer: 1 },
      { id: "q4", prompt: "A map key tells you what...", choices: ["symbols mean", "song to sing", "weather to expect", "day it is"], answer: 0 },
      { id: "q5", prompt: "A compass shows you...", choices: ["time", "directions", "music", "words"], answer: 1 },
      { id: "q6", prompt: "A globe is a model of...", choices: ["the moon", "a city", "Earth", "a house"], answer: 2 },
      { id: "q7", prompt: "Blue on a map usually shows...", choices: ["land", "water", "roads", "sky"], answer: 1 },
      { id: "q8", prompt: "Green on a map usually shows...", choices: ["oceans", "forests/land", "cities only", "deserts"], answer: 1 },
      { id: "q9", prompt: "A line that shows a road on a map is in the...", choices: ["title", "key", "sky", "date"], answer: 1 },
      { id: "q10", prompt: "If north is up, then east is to the...", choices: ["left", "right", "down", "top"], answer: 1 },
      { id: "q11", prompt: "West is the opposite of...", choices: ["north", "south", "east", "up"], answer: 2 },
      { id: "q12", prompt: "The direction where the sun rises is...", choices: ["north", "east", "south", "west"], answer: 1, explanation: "The sun rises in the east." },
      { id: "q13", prompt: "A picture or model of the round Earth is a...", choices: ["map", "globe", "key", "compass"], answer: 1 },
      { id: "q14", prompt: "Brown on a map often shows...", choices: ["water", "mountains", "roads", "sky"], answer: 1 },
      { id: "q15", prompt: "A small drawing that stands for a real thing on a map is a...", choices: ["symbol", "song", "snack", "date"], answer: 0, explanation: "Map symbols stand for real places or things." },
      { id: "q16", prompt: "If you face north, your back is to the...", choices: ["east", "west", "south", "north"], answer: 2 },
      { id: "q17", prompt: "A flat drawing of a place from above is a...", choices: ["map", "movie", "book", "clock"], answer: 0 },
      { id: "q18", prompt: "The needle of a compass points...", choices: ["down", "north", "south", "east"], answer: 1, explanation: "A compass needle points north." },
    ],
  },
  {
    id: "g1-geo-landforms",
    subjectId: "geography",
    level: "grade1",
    title: "Landforms",
    description: "Mountains, rivers, valleys, and more.",
    emoji: "\u26F0\u{FE0F}",
    questions: [
      { id: "q1", prompt: "A very tall landform is a...", choices: ["valley", "mountain", "plain", "lake"], answer: 1 },
      { id: "q2", prompt: "Flat, grassy land is called a...", choices: ["plain", "mountain", "river", "desert"], answer: 0 },
      { id: "q3", prompt: "A low area between mountains is a...", choices: ["hill", "valley", "cliff", "beach"], answer: 1 },
      { id: "q4", prompt: "Water that flows in a long path is a...", choices: ["pond", "river", "lake", "ocean"], answer: 1 },
      { id: "q5", prompt: "A piece of land with water all around is an...", choices: ["island", "valley", "plain", "forest"], answer: 0 },
      { id: "q6", prompt: "Tall, steep rock at the edge of land is a...", choices: ["cliff", "plain", "lake", "pond"], answer: 0 },
      { id: "q7", prompt: "A small mountain is called a...", choices: ["hill", "river", "sea", "island"], answer: 0 },
      { id: "q8", prompt: "A mountain that can erupt is a...", choices: ["volcano", "hill", "plain", "valley"], answer: 0 },
      { id: "q9", prompt: "A dry land with little rain is a...", choices: ["forest", "desert", "swamp", "jungle"], answer: 1 },
      { id: "q10", prompt: "A peninsula is land with water on...", choices: ["no sides", "one side", "three sides", "all sides"], answer: 2 },
      { id: "q11", prompt: "A large body of salty water is an...", choices: ["pond", "ocean", "creek", "stream"], answer: 1 },
      { id: "q12", prompt: "Sandy land next to the ocean is called a...", choices: ["beach", "valley", "hill", "cave"], answer: 0 },
      { id: "q13", prompt: "A small body of still water is a...", choices: ["ocean", "pond", "river", "sea"], answer: 1, explanation: "A pond is small and calm." },
      { id: "q14", prompt: "Hot melted rock from a volcano is called...", choices: ["mud", "lava", "snow", "sand"], answer: 1 },
      { id: "q15", prompt: "A line of mountains together is a mountain...", choices: ["range", "river", "valley", "road"], answer: 0, explanation: "A row of mountains is a range." },
      { id: "q16", prompt: "Water that falls down over a cliff is a...", choices: ["waterfall", "pond", "plain", "hill"], answer: 0 },
      { id: "q17", prompt: "A wide area of flat land is a...", choices: ["mountain", "plain", "cliff", "volcano"], answer: 1 },
      { id: "q18", prompt: "A thick forest that is warm and very rainy is a...", choices: ["desert", "jungle", "glacier", "prairie"], answer: 1, explanation: "Jungles are warm, wet, and full of plants." },
    ],
  },
  {
    id: "g1-geo-weather",
    subjectId: "geography",
    level: "grade1",
    title: "Weather & Climate",
    description: "Weather, seasons, and where it happens.",
    emoji: "\u{1F324}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "The weather pattern of a place over many years is its...", choices: ["climate", "snack", "map", "clock"], answer: 0 },
      { id: "q2", prompt: "Places near the equator are usually...", choices: ["cold", "warm", "snowy", "dry only"], answer: 1 },
      { id: "q3", prompt: "Places near the poles are usually...", choices: ["hot", "warm", "very cold", "rainy"], answer: 2 },
      { id: "q4", prompt: "A storm with strong winds and rain near the ocean is a...", choices: ["hurricane", "tornado", "blizzard", "earthquake"], answer: 0 },
      { id: "q5", prompt: "A spinning storm on land is a...", choices: ["tornado", "hurricane", "flood", "drought"], answer: 0 },
      { id: "q6", prompt: "A long time with no rain is a...", choices: ["flood", "drought", "snow", "breeze"], answer: 1 },
      { id: "q7", prompt: "Lots of rain that covers land is a...", choices: ["drought", "flood", "sunshine", "frost"], answer: 1 },
      { id: "q8", prompt: "Snow is most common in which season?", choices: ["summer", "spring", "winter", "fall"], answer: 2 },
      { id: "q9", prompt: "A tool to measure temperature is a...", choices: ["ruler", "thermometer", "clock", "scale"], answer: 1 },
      { id: "q10", prompt: "Wind is moving...", choices: ["water", "air", "rock", "sand"], answer: 1 },
      { id: "q11", prompt: "Frozen rain that falls in winter is...", choices: ["rain", "snow", "fog", "dew"], answer: 1 },
      { id: "q12", prompt: "Water drops that fall from clouds are...", choices: ["snow", "rain", "sun", "wind"], answer: 1 },
      { id: "q13", prompt: "The season when leaves fall from trees is...", choices: ["spring", "summer", "fall", "winter"], answer: 2, explanation: "Leaves drop in fall, also called autumn." },
      { id: "q14", prompt: "The warmest season is usually...", choices: ["winter", "summer", "fall", "spring"], answer: 1 },
      { id: "q15", prompt: "A flash of light in the sky during a storm is...", choices: ["lightning", "rainbow", "sunshine", "frost"], answer: 0 },
      { id: "q16", prompt: "A rainbow can appear after it...", choices: ["snows", "rains", "freezes", "gets dark"], answer: 1, explanation: "Sun shining on raindrops makes a rainbow." },
      { id: "q17", prompt: "Clouds are made of tiny drops of...", choices: ["sand", "water", "smoke", "cotton"], answer: 1 },
      { id: "q18", prompt: "On a hot, sunny day you should drink plenty of...", choices: ["soda", "water", "nothing", "juice only"], answer: 1, explanation: "Water keeps you cool and healthy." },
    ],
  },
];
