/**
 * Brainy Buddies — Kindergarten activities.
 * Loaded by brainy-data.ts and merged into the ACTIVITIES list.
 */
import type { Activity } from "@/lib/brainy-data";

export const KINDERGARTEN_ACTIVITIES: Activity[] = [
  // -------- MATH (Kindergarten) --------
  {
    id: "k-math-count",
    subjectId: "math",
    level: "kindergarten",
    title: "Counting 1 to 10",
    description: "Count things and match the number.",
    emoji: "\u{1F522}",
    questions: [
      { id: "q1", prompt: "How many? \u{1F34E}\u{1F34E}\u{1F34E}", choices: ["2", "3", "4", "5"], answer: 1 },
      { id: "q2", prompt: "How many? \u{1F436}\u{1F436}\u{1F436}\u{1F436}\u{1F436}", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q3", prompt: "How many? \u{1F31F}", choices: ["0", "1", "2", "3"], answer: 1 },
      { id: "q4", prompt: "What comes after 6?", choices: ["5", "6", "7", "8"], answer: 2 },
      { id: "q5", prompt: "What comes before 4?", choices: ["2", "3", "5", "6"], answer: 1 },
      { id: "q6", prompt: "How many? \u{1F431}\u{1F431}\u{1F431}\u{1F431}\u{1F431}\u{1F431}\u{1F431}", choices: ["5", "6", "7", "8"], answer: 2 },
      { id: "q7", prompt: "Which number is the biggest?", choices: ["2", "5", "9", "7"], answer: 2 },
      { id: "q8", prompt: "Which number is the smallest?", choices: ["3", "1", "4", "8"], answer: 1 },
      { id: "q9", prompt: "Count: 1, 2, 3, 4, ?", choices: ["5", "6", "3", "7"], answer: 0 },
      { id: "q10", prompt: "How many? \u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}\u{1F953}", choices: ["8", "9", "10", "11"], answer: 2 },
      { id: "q11", prompt: "What number is missing? 7, 8, ?, 10", choices: ["6", "9", "11", "12"], answer: 1 },
      { id: "q12", prompt: "How many fingers on one hand?", choices: ["3", "4", "5", "10"], answer: 2 },
      { id: "q13", prompt: "How many? \u{1F420}\u{1F420}", choices: ["1", "2", "3", "4"], answer: 1 },
      { id: "q14", prompt: "What comes after 9?", choices: ["8", "9", "10", "11"], answer: 2 },
      { id: "q15", prompt: "How many? \u{1F41D}\u{1F41D}\u{1F41D}\u{1F41D}\u{1F41D}\u{1F41D}\u{1F41D}\u{1F41D}", choices: ["6", "7", "8", "9"], answer: 2, explanation: "Count each bee: that is 8." },
      { id: "q16", prompt: "Count down: 5, 4, 3, 2, ?", choices: ["1", "0", "6", "3"], answer: 0 },
      { id: "q17", prompt: "Which is more, 3 or 6?", choices: ["3", "6", "same", "zero"], answer: 1, explanation: "6 is bigger than 3." },
      { id: "q18", prompt: "How many eyes do you have?", choices: ["1", "2", "3", "4"], answer: 1 },
    ],
  },
  {
    id: "k-math-shapes",
    subjectId: "math",
    level: "kindergarten",
    title: "Shape Friends",
    description: "Circles, squares, triangles, and rectangles.",
    emoji: "\u{1F537}",
    questions: [
      { id: "q1", prompt: "A ball is shaped like a...", choices: ["square", "circle", "triangle", "star"], answer: 1 },
      { id: "q2", prompt: "A pizza slice is shaped like a...", choices: ["circle", "square", "triangle", "diamond"], answer: 2 },
      { id: "q3", prompt: "How many sides does a triangle have?", choices: ["2", "3", "4", "5"], answer: 1 },
      { id: "q4", prompt: "How many sides does a square have?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q5", prompt: "A book cover is usually a...", choices: ["circle", "rectangle", "triangle", "star"], answer: 1 },
      { id: "q6", prompt: "Which shape has NO corners?", choices: ["square", "triangle", "circle", "rectangle"], answer: 2 },
      { id: "q7", prompt: "How many corners does a square have?", choices: ["2", "3", "4", "5"], answer: 2 },
      { id: "q8", prompt: "A clock face is usually a...", choices: ["square", "triangle", "circle", "diamond"], answer: 2 },
      { id: "q9", prompt: "How many points does a star have? (the usual one)", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q10", prompt: "A door is usually shaped like a...", choices: ["circle", "triangle", "rectangle", "star"], answer: 2 },
      { id: "q11", prompt: "How many sides does a rectangle have?", choices: ["3", "4", "5", "6"], answer: 1, explanation: "A rectangle has 4 sides." },
      { id: "q12", prompt: "A wheel is shaped like a...", choices: ["square", "triangle", "circle", "star"], answer: 2 },
      { id: "q13", prompt: "Which shape is round?", choices: ["square", "circle", "triangle", "rectangle"], answer: 1 },
      { id: "q14", prompt: "A slice of cheese can look like a...", choices: ["circle", "triangle", "star", "heart"], answer: 1 },
      { id: "q15", prompt: "Which shape has 3 corners?", choices: ["circle", "square", "triangle", "rectangle"], answer: 2, explanation: "A triangle has 3 corners." },
      { id: "q16", prompt: "A window can be shaped like a...", choices: ["circle", "square", "star", "heart"], answer: 1 },
      { id: "q17", prompt: "How many corners does a triangle have?", choices: ["2", "3", "4", "5"], answer: 1 },
      { id: "q18", prompt: "Which shape looks like a full moon?", choices: ["square", "triangle", "circle", "rectangle"], answer: 2 },
    ],
  },
  {
    id: "k-math-add",
    subjectId: "math",
    level: "kindergarten",
    title: "Addition to 10",
    description: "Add two numbers together up to 10.",
    emoji: "\u2795",
    questions: [
      { id: "q1", prompt: "1 + 1 = ?", choices: ["1", "2", "3", "4"], answer: 1 },
      { id: "q2", prompt: "2 + 2 = ?", choices: ["2", "3", "4", "5"], answer: 2 },
      { id: "q3", prompt: "3 + 1 = ?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q4", prompt: "2 + 3 = ?", choices: ["4", "5", "6", "7"], answer: 1 },
      { id: "q5", prompt: "4 + 1 = ?", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q6", prompt: "3 + 3 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
      { id: "q7", prompt: "5 + 2 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q8", prompt: "4 + 4 = ?", choices: ["6", "7", "8", "9"], answer: 2 },
      { id: "q9", prompt: "5 + 5 = ?", choices: ["8", "9", "10", "11"], answer: 2 },
      { id: "q10", prompt: "6 + 2 = ?", choices: ["7", "8", "9", "10"], answer: 1 },
      { id: "q11", prompt: "7 + 1 = ?", choices: ["7", "8", "9", "10"], answer: 1 },
      { id: "q12", prompt: "You have 2 cookies. Mom gives you 1 more. How many now?", choices: ["1", "2", "3", "4"], answer: 2 },
      { id: "q13", prompt: "3 birds + 2 birds = ?", choices: ["4", "5", "6", "7"], answer: 1 },
      { id: "q14", prompt: "You see 4 dogs and 3 cats. How many animals total?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q15", prompt: "6 + 3 = ?", choices: ["8", "9", "10", "11"], answer: 1 },
      { id: "q16", prompt: "5 + 4 = ?", choices: ["7", "8", "9", "10"], answer: 2, explanation: "5 and 4 more makes 9." },
      { id: "q17", prompt: "4 + 2 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
      { id: "q18", prompt: "You have 3 balloons and get 4 more. How many now?", choices: ["6", "7", "8", "9"], answer: 1 },
    ],
  },
  {
    id: "k-math-sub",
    subjectId: "math",
    level: "kindergarten",
    title: "Subtraction to 10",
    description: "Take away numbers from 10 and under.",
    emoji: "\u2796",
    questions: [
      { id: "q1", prompt: "2 - 1 = ?", choices: ["0", "1", "2", "3"], answer: 1 },
      { id: "q2", prompt: "4 - 2 = ?", choices: ["1", "2", "3", "4"], answer: 1 },
      { id: "q3", prompt: "5 - 1 = ?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q4", prompt: "3 - 3 = ?", choices: ["0", "1", "2", "3"], answer: 0 },
      { id: "q5", prompt: "6 - 2 = ?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q6", prompt: "7 - 3 = ?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q7", prompt: "8 - 4 = ?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q8", prompt: "9 - 5 = ?", choices: ["3", "4", "5", "6"], answer: 1 },
      { id: "q9", prompt: "10 - 3 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q10", prompt: "10 - 10 = ?", choices: ["0", "1", "2", "10"], answer: 0 },
      { id: "q11", prompt: "You had 5 apples and ate 2. How many are left?", choices: ["2", "3", "4", "5"], answer: 1 },
      { id: "q12", prompt: "There are 6 birds. 3 fly away. How many stay?", choices: ["2", "3", "4", "5"], answer: 1 },
      { id: "q13", prompt: "You had 8 crayons and lost 1. How many now?", choices: ["6", "7", "8", "9"], answer: 1 },
      { id: "q14", prompt: "10 - 5 = ?", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q15", prompt: "7 - 2 = ?", choices: ["4", "5", "6", "7"], answer: 1 },
      { id: "q16", prompt: "9 - 4 = ?", choices: ["3", "4", "5", "6"], answer: 2, explanation: "Take 4 away from 9 to get 5." },
      { id: "q17", prompt: "6 - 6 = ?", choices: ["0", "1", "2", "6"], answer: 0, explanation: "Take all 6 away and none are left." },
      { id: "q18", prompt: "You have 7 grapes and eat 3. How many are left?", choices: ["3", "4", "5", "6"], answer: 1 },
    ],
  },
  {
    id: "k-math-colors",
    subjectId: "math",
    level: "kindergarten",
    title: "Patterns & Colors",
    description: "Spot patterns and matching colors.",
    emoji: "\u{1F308}",
    questions: [
      { id: "q1", prompt: "What comes next? red, blue, red, blue, ?", choices: ["red", "blue", "green", "yellow"], answer: 0 },
      { id: "q2", prompt: "What comes next? yellow, yellow, red, yellow, yellow, ?", choices: ["yellow", "red", "blue", "green"], answer: 1 },
      { id: "q3", prompt: "The sun is mostly which color?", choices: ["yellow", "blue", "green", "purple"], answer: 0 },
      { id: "q4", prompt: "Grass is mostly which color?", choices: ["red", "green", "blue", "pink"], answer: 1 },
      { id: "q5", prompt: "The sky on a clear day is...", choices: ["green", "yellow", "blue", "orange"], answer: 2 },
      { id: "q6", prompt: "What comes next? green, green, orange, green, green, ?", choices: ["green", "orange", "red", "blue"], answer: 1 },
      { id: "q7", prompt: "A stop sign is what color?", choices: ["green", "yellow", "red", "blue"], answer: 2 },
      { id: "q8", prompt: "Mix red and yellow to get...", choices: ["green", "purple", "orange", "pink"], answer: 2 },
      { id: "q9", prompt: "Mix blue and yellow to get...", choices: ["green", "orange", "purple", "black"], answer: 0 },
      { id: "q10", prompt: "A banana is usually what color?", choices: ["red", "yellow", "blue", "green"], answer: 1 },
      { id: "q11", prompt: "What comes next? blue, green, blue, green, ?", choices: ["blue", "green", "red", "yellow"], answer: 1 },
      { id: "q12", prompt: "An apple is often what color?", choices: ["red", "blue", "purple", "gray"], answer: 0 },
      { id: "q13", prompt: "Snow is what color?", choices: ["black", "green", "white", "red"], answer: 2 },
      { id: "q14", prompt: "What comes next? big, small, big, small, ?", choices: ["big", "small", "huge", "tiny"], answer: 1 },
      { id: "q15", prompt: "Mix red and blue to get...", choices: ["green", "orange", "purple", "yellow"], answer: 2, explanation: "Red and blue make purple." },
      { id: "q16", prompt: "An orange (the fruit) is what color?", choices: ["orange", "blue", "green", "pink"], answer: 0 },
      { id: "q17", prompt: "A leaf in summer is usually what color?", choices: ["green", "red", "blue", "purple"], answer: 0 },
      { id: "q18", prompt: "What comes next? circle, square, circle, square, ?", choices: ["triangle", "star", "circle", "square"], answer: 2 },
    ],
  },

  // -------- SCIENCE (Kindergarten) --------
  {
    id: "k-sci-animals2",
    subjectId: "science",
    level: "kindergarten",
    title: "Animals & Where They Live",
    description: "Farm animals, pets, wild animals, and their homes.",
    emoji: "\u{1F98A}",
    questions: [
      { id: "q1", prompt: "Which animal lives on a farm?", choices: ["lion", "cow", "shark", "penguin"], answer: 1 },
      { id: "q2", prompt: "Which animal is a good pet?", choices: ["bear", "crocodile", "dog", "wolf"], answer: 2 },
      { id: "q3", prompt: "Where does a lion live?", choices: ["farm", "jungle", "pond", "school"], answer: 1 },
      { id: "q4", prompt: "Which animal has a trunk?", choices: ["horse", "elephant", "cat", "rabbit"], answer: 1 },
      { id: "q5", prompt: "Where does a fish live?", choices: ["tree", "sky", "water", "ground"], answer: 2 },
      { id: "q6", prompt: "Which animal has stripes like a zebra?", choices: ["elephant", "giraffe", "zebra", "rhino"], answer: 2 },
      { id: "q7", prompt: "Which animal gives us milk?", choices: ["dog", "cow", "frog", "eagle"], answer: 1 },
      { id: "q8", prompt: "A bird lives in a...", choices: ["burrow", "nest", "puddle", "barn"], answer: 1 },
      { id: "q9", prompt: "Which animal can live as a pet at home?", choices: ["tiger", "elephant", "cat", "shark"], answer: 2 },
      { id: "q10", prompt: "Where does a bear sleep in winter?", choices: ["at school", "in a cave", "in the ocean", "on a cloud"], answer: 1 },
      { id: "q11", prompt: "Which animal has a long neck?", choices: ["frog", "giraffe", "duck", "fish"], answer: 1 },
      { id: "q12", prompt: "Which animal makes honey?", choices: ["ant", "bee", "butterfly", "spider"], answer: 1 },
      { id: "q13", prompt: "Which animal hops and lives near ponds?", choices: ["frog", "horse", "cow", "lion"], answer: 0 },
      { id: "q14", prompt: "Where does a cow live?", choices: ["jungle", "farm", "ocean", "desert"], answer: 1 },
      { id: "q15", prompt: "Which animal lives in the ocean?", choices: ["dog", "whale", "cat", "cow"], answer: 1, explanation: "A whale lives in the ocean." },
      { id: "q16", prompt: "A spider often lives in a...", choices: ["nest", "web", "barn", "cave"], answer: 1 },
      { id: "q17", prompt: "Which animal can swing in trees?", choices: ["fish", "monkey", "cow", "duck"], answer: 1 },
      { id: "q18", prompt: "Which animal lives in cold, snowy places?", choices: ["penguin", "lion", "camel", "parrot"], answer: 0 },
    ],
  },
  {
    id: "k-sci-animals",
    subjectId: "science",
    level: "kindergarten",
    title: "Animal Sounds & Babies",
    description: "What animals say and what their babies are called.",
    emoji: "\u{1F436}",
    questions: [
      { id: "q1", prompt: "What sound does a cow make?", choices: ["woof", "meow", "moo", "quack"], answer: 2 },
      { id: "q2", prompt: "What sound does a duck make?", choices: ["moo", "quack", "oink", "baa"], answer: 1 },
      { id: "q3", prompt: "A baby dog is called a...", choices: ["kitten", "puppy", "calf", "foal"], answer: 1 },
      { id: "q4", prompt: "A baby cat is called a...", choices: ["puppy", "kitten", "chick", "cub"], answer: 1 },
      { id: "q5", prompt: "Which animal can fly?", choices: ["fish", "bird", "frog", "horse"], answer: 1 },
      { id: "q6", prompt: "What sound does a sheep make?", choices: ["baa", "moo", "meow", "oink"], answer: 0 },
      { id: "q7", prompt: "A baby chicken is a...", choices: ["duckling", "chick", "colt", "joey"], answer: 1 },
      { id: "q8", prompt: "Which animal lives in water?", choices: ["cow", "fish", "dog", "horse"], answer: 1 },
      { id: "q9", prompt: "Which animal has feathers?", choices: ["dog", "bird", "cat", "pig"], answer: 1 },
      { id: "q10", prompt: "A baby cow is called a...", choices: ["calf", "kid", "foal", "piglet"], answer: 0 },
      { id: "q11", prompt: "Which animal hops?", choices: ["snake", "frog", "fish", "snail"], answer: 1 },
      { id: "q12", prompt: "What sound does a cat make?", choices: ["moo", "meow", "quack", "baa"], answer: 1 },
      { id: "q13", prompt: "What sound does a dog make?", choices: ["woof", "oink", "baa", "moo"], answer: 0 },
      { id: "q14", prompt: "A baby horse is called a...", choices: ["calf", "foal", "chick", "kitten"], answer: 1, explanation: "A baby horse is a foal." },
      { id: "q15", prompt: "What sound does a pig make?", choices: ["meow", "oink", "quack", "baa"], answer: 1 },
      { id: "q16", prompt: "A baby sheep is called a...", choices: ["lamb", "puppy", "chick", "cub"], answer: 0, explanation: "A baby sheep is a lamb." },
      { id: "q17", prompt: "Which animal has fur?", choices: ["fish", "cat", "bird", "frog"], answer: 1 },
      { id: "q18", prompt: "Which animal swims in water?", choices: ["dog", "duck", "cat", "cow"], answer: 1 },
    ],
  },
  {
    id: "k-sci-weather",
    subjectId: "science",
    level: "kindergarten",
    title: "Weather & Seasons",
    description: "Sunny, rainy, snowy, and the four seasons.",
    emoji: "\u26C5",
    questions: [
      { id: "q1", prompt: "What falls from clouds when it rains?", choices: ["snow", "water", "sand", "leaves"], answer: 1 },
      { id: "q2", prompt: "Which season has snow?", choices: ["summer", "spring", "winter", "fall"], answer: 2 },
      { id: "q3", prompt: "Which season is hot and sunny?", choices: ["winter", "summer", "fall", "spring"], answer: 1 },
      { id: "q4", prompt: "In fall, leaves change color and...", choices: ["grow back", "fall off trees", "turn blue", "sing"], answer: 1 },
      { id: "q5", prompt: "What do you wear when it rains?", choices: ["shorts", "a raincoat", "a swimsuit", "sandals"], answer: 1 },
      { id: "q6", prompt: "How many seasons are in a year?", choices: ["2", "3", "4", "5"], answer: 2 },
      { id: "q7", prompt: "What shines in the sky in the daytime?", choices: ["moon", "sun", "stars", "clouds"], answer: 1 },
      { id: "q8", prompt: "What do you see in the sky at night?", choices: ["sun", "rainbow", "stars", "snowman"], answer: 2 },
      { id: "q9", prompt: "After rain we sometimes see a colorful...", choices: ["snowman", "rainbow", "cloud", "rocket"], answer: 1 },
      { id: "q10", prompt: "Which is COLD?", choices: ["a hot tea", "an ice cube", "the sun", "a candle"], answer: 1 },
      { id: "q11", prompt: "White, cold flakes that fall in winter are...", choices: ["rain", "snow", "sand", "leaves"], answer: 1 },
      { id: "q12", prompt: "In which season do many flowers start to bloom?", choices: ["winter", "spring", "fall", "never"], answer: 1, explanation: "Flowers bloom in spring." },
      { id: "q13", prompt: "What do you use to stay dry in the rain?", choices: ["umbrella", "sunglasses", "a fan", "a kite"], answer: 0 },
      { id: "q14", prompt: "When it is sunny and hot, you might wear...", choices: ["a heavy coat", "shorts", "snow boots", "mittens"], answer: 1 },
      { id: "q15", prompt: "Wind makes leaves and flags...", choices: ["sit still", "move and blow", "freeze", "glow"], answer: 1 },
      { id: "q16", prompt: "A loud rumble in the sky during a storm is...", choices: ["thunder", "a rainbow", "sunshine", "snow"], answer: 0 },
      { id: "q17", prompt: "A bright flash of light in a storm is...", choices: ["lightning", "a rainbow", "the moon", "a star"], answer: 0 },
      { id: "q18", prompt: "Which season comes right after winter?", choices: ["summer", "fall", "spring", "winter again"], answer: 2 },
    ],
  },
  {
    id: "k-sci-fivesenses",
    subjectId: "science",
    level: "kindergarten",
    title: "My Five Senses",
    description: "See, hear, smell, taste, and touch.",
    emoji: "\u{1F441}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "You use your eyes to...", choices: ["hear", "see", "smell", "taste"], answer: 1 },
      { id: "q2", prompt: "You use your ears to...", choices: ["see", "hear", "touch", "taste"], answer: 1 },
      { id: "q3", prompt: "You use your nose to...", choices: ["hear", "smell", "see", "taste"], answer: 1 },
      { id: "q4", prompt: "You use your tongue to...", choices: ["smell", "see", "taste", "hear"], answer: 2 },
      { id: "q5", prompt: "You use your hands to...", choices: ["hear", "touch", "smell", "see"], answer: 1 },
      { id: "q6", prompt: "How many senses do you have?", choices: ["3", "4", "5", "6"], answer: 2 },
      { id: "q7", prompt: "Ice feels...", choices: ["hot", "warm", "cold", "spicy"], answer: 2 },
      { id: "q8", prompt: "A lemon usually tastes...", choices: ["sweet", "sour", "salty", "spicy"], answer: 1 },
      { id: "q9", prompt: "Sugar tastes...", choices: ["bitter", "sour", "sweet", "salty"], answer: 2 },
      { id: "q10", prompt: "A bell makes a sound you can...", choices: ["see", "taste", "hear", "smell"], answer: 2 },
      { id: "q11", prompt: "You smell a flower with your...", choices: ["eyes", "nose", "ears", "feet"], answer: 1 },
      { id: "q12", prompt: "A soft pillow feels...", choices: ["hard", "soft", "sharp", "wet"], answer: 1 },
      { id: "q13", prompt: "You taste food with your...", choices: ["nose", "eyes", "tongue", "ears"], answer: 2, explanation: "Your tongue helps you taste." },
      { id: "q14", prompt: "A rainbow is something you can...", choices: ["taste", "smell", "see", "hear"], answer: 2 },
      { id: "q15", prompt: "Music is something you can...", choices: ["only see", "hear", "taste", "smell"], answer: 1 },
      { id: "q16", prompt: "Salt makes food taste...", choices: ["sweet", "salty", "sour", "cold"], answer: 1 },
      { id: "q17", prompt: "A rock feels...", choices: ["hard", "soft", "fluffy", "wet"], answer: 0 },
      { id: "q18", prompt: "You see colors with your...", choices: ["ears", "nose", "eyes", "hands"], answer: 2 },
    ],
  },
  {
    id: "k-sci-plants",
    subjectId: "science",
    level: "kindergarten",
    title: "Plants & Living Things",
    description: "What plants need and living vs. not living.",
    emoji: "\u{1F331}",
    questions: [
      { id: "q1", prompt: "Plants need ___ to grow.", choices: ["water", "toys", "books", "music"], answer: 0 },
      { id: "q2", prompt: "Plants also need...", choices: ["sunlight", "the moon", "the wind", "rocks"], answer: 0 },
      { id: "q3", prompt: "A baby plant comes from a...", choices: ["rock", "seed", "cloud", "shell"], answer: 1 },
      { id: "q4", prompt: "Which is a living thing?", choices: ["rock", "chair", "tree", "toy car"], answer: 2 },
      { id: "q5", prompt: "Which is NOT living?", choices: ["dog", "flower", "book", "bird"], answer: 2 },
      { id: "q6", prompt: "The part of a plant that holds it down is the...", choices: ["leaf", "flower", "root", "sky"], answer: 2 },
      { id: "q7", prompt: "A flower can grow into a...", choices: ["car", "fruit", "shoe", "rock"], answer: 1 },
      { id: "q8", prompt: "Trees are usually very...", choices: ["tiny", "tall", "flat", "soft"], answer: 1 },
      { id: "q9", prompt: "Plants make a gas that we breathe called...", choices: ["smoke", "oxygen", "steam", "sugar"], answer: 1 },
      { id: "q10", prompt: "You eat the seeds of which plant?", choices: ["a rose", "a sunflower", "a dandelion", "grass"], answer: 1 },
      { id: "q11", prompt: "The green parts of a plant are called...", choices: ["leaves", "rocks", "shoes", "clouds"], answer: 0, explanation: "The green parts are leaves." },
      { id: "q12", prompt: "Which is a living thing?", choices: ["a stone", "a cat", "a spoon", "a hat"], answer: 1 },
      { id: "q13", prompt: "A plant grows from a tiny...", choices: ["seed", "brick", "button", "coin"], answer: 0 },
      { id: "q14", prompt: "Plants drink water through their...", choices: ["leaves", "roots", "flowers", "petals"], answer: 1, explanation: "Roots take in water from the soil." },
      { id: "q15", prompt: "What do plants need from the sky to grow?", choices: ["sunlight", "candy", "toys", "music"], answer: 0 },
      { id: "q16", prompt: "Apples and oranges grow on...", choices: ["trees", "cars", "rocks", "clouds"], answer: 0 },
      { id: "q17", prompt: "Which is NOT a living thing?", choices: ["a fish", "a tree", "a chair", "a bird"], answer: 2 },
      { id: "q18", prompt: "A carrot is a plant part we eat that grows...", choices: ["in the sky", "under the ground", "on clouds", "in the ocean"], answer: 1 },
    ],
  },

  // -------- HISTORY (Kindergarten) --------
  {
    id: "k-hist-holidays2",
    subjectId: "history",
    level: "kindergarten",
    title: "Holidays Around the Year",
    description: "Seasonal celebrations and what makes each special.",
    emoji: "\u{1F384}",
    questions: [
      { id: "q1", prompt: "Which holiday is in winter and has gift-giving?", choices: ["Halloween", "Christmas", "Easter", "July 4th"], answer: 1 },
      { id: "q2", prompt: "On Halloween you say...", choices: ["Happy Birthday!", "Trick or Treat!", "Thank you!", "Hooray!"], answer: 1 },
      { id: "q3", prompt: "Easter is a spring holiday with colored...", choices: ["snowmen", "eggs", "fireworks", "pumpkins"], answer: 1 },
      { id: "q4", prompt: "Which holiday do we celebrate our country's birthday?", choices: ["Thanksgiving", "July 4th", "Easter", "New Year's"], answer: 1 },
      { id: "q5", prompt: "On Thanksgiving we eat a big meal and say...", choices: ["boo!", "trick or treat", "we are thankful", "make a wish"], answer: 2 },
      { id: "q6", prompt: "Which holiday has a big ball dropping at midnight?", choices: ["Easter", "New Year's Eve", "Halloween", "July 4th"], answer: 1 },
      { id: "q7", prompt: "In which season is Halloween?", choices: ["spring", "summer", "fall", "winter"], answer: 2 },
      { id: "q8", prompt: "We give hearts and cards on...", choices: ["Halloween", "July 4th", "Valentine's Day", "Thanksgiving"], answer: 2 },
      { id: "q9", prompt: "The Easter Bunny hides...", choices: ["candy canes", "pumpkins", "eggs", "snowflakes"], answer: 2 },
      { id: "q10", prompt: "Christmas is in which season?", choices: ["summer", "fall", "spring", "winter"], answer: 3 },
      { id: "q11", prompt: "We wear green on...", choices: ["Easter", "St. Patrick's Day", "Halloween", "July 4th"], answer: 1 },
      { id: "q12", prompt: "Which holiday has a turkey?", choices: ["Christmas", "Halloween", "Thanksgiving", "Easter"], answer: 2 },
      { id: "q13", prompt: "We light candles on Hanukkah, which is in...", choices: ["summer", "winter", "spring", "fall"], answer: 1 },
      { id: "q14", prompt: "On July 4th we usually see fireworks at...", choices: ["sunrise", "night", "lunchtime", "never"], answer: 1 },
      { id: "q15", prompt: "Which holiday has pumpkins and costumes?", choices: ["Halloween", "Easter", "July 4th", "New Year's"], answer: 0 },
      { id: "q16", prompt: "On Valentine's Day we share...", choices: ["hearts and cards", "pumpkins", "fireworks", "snowmen"], answer: 0 },
      { id: "q17", prompt: "Which season has Easter and lots of flowers?", choices: ["spring", "winter", "fall", "summer"], answer: 0, explanation: "Easter is a spring holiday." },
      { id: "q18", prompt: "Thanksgiving is in which season?", choices: ["spring", "summer", "fall", "winter"], answer: 2 },
    ],
  },
  {
    id: "k-hist-helpers",
    subjectId: "history",
    level: "kindergarten",
    title: "Helpers in My Town",
    description: "People who help in our community.",
    emoji: "\u{1F692}",
    questions: [
      { id: "q1", prompt: "Who puts out fires?", choices: ["a doctor", "a firefighter", "a teacher", "a chef"], answer: 1 },
      { id: "q2", prompt: "Who helps you when you are sick?", choices: ["a doctor", "a mail carrier", "a farmer", "a baker"], answer: 0 },
      { id: "q3", prompt: "Who teaches you at school?", choices: ["a chef", "a teacher", "a vet", "a builder"], answer: 1 },
      { id: "q4", prompt: "Who brings your mail?", choices: ["a vet", "a mail carrier", "a baker", "a pilot"], answer: 1 },
      { id: "q5", prompt: "Who helps sick animals?", choices: ["a doctor", "a vet", "a chef", "a pilot"], answer: 1 },
      { id: "q6", prompt: "Who flies an airplane?", choices: ["a pilot", "a builder", "a chef", "a teacher"], answer: 0 },
      { id: "q7", prompt: "Who bakes bread?", choices: ["a pilot", "a baker", "a vet", "a farmer"], answer: 1 },
      { id: "q8", prompt: "Who grows food on a farm?", choices: ["a farmer", "a doctor", "a chef", "a librarian"], answer: 0 },
      { id: "q9", prompt: "Who helps keep our streets safe?", choices: ["a police officer", "a chef", "a builder", "a pilot"], answer: 0 },
      { id: "q10", prompt: "Who helps you find books?", choices: ["a chef", "a librarian", "a pilot", "a vet"], answer: 1 },
      { id: "q11", prompt: "Who drives an ambulance to help in an emergency?", choices: ["a chef", "a paramedic", "a painter", "a singer"], answer: 1 },
      { id: "q12", prompt: "Who fixes broken water pipes?", choices: ["a plumber", "a teacher", "a pilot", "a baker"], answer: 0 },
      { id: "q13", prompt: "Who cooks food at a restaurant?", choices: ["a chef", "a vet", "a pilot", "a farmer"], answer: 0 },
      { id: "q14", prompt: "Who drives a bus to take kids to school?", choices: ["a pilot", "a bus driver", "a baker", "a vet"], answer: 1 },
      { id: "q15", prompt: "Who helps fix your teeth?", choices: ["a dentist", "a chef", "a pilot", "a farmer"], answer: 0, explanation: "A dentist takes care of your teeth." },
      { id: "q16", prompt: "Who builds houses?", choices: ["a builder", "a librarian", "a vet", "a pilot"], answer: 0 },
      { id: "q17", prompt: "Who collects the trash to keep the town clean?", choices: ["a chef", "a garbage collector", "a pilot", "a teacher"], answer: 1 },
      { id: "q18", prompt: "Who helps care for sick people at the hospital?", choices: ["a nurse", "a pilot", "a baker", "a builder"], answer: 0 },
    ],
  },
  {
    id: "k-hist-family",
    subjectId: "history",
    level: "kindergarten",
    title: "Family & Long Ago",
    description: "Yesterday, today, and family.",
    emoji: "\u{1F46A}",
    questions: [
      { id: "q1", prompt: "Your mom's mom is your...", choices: ["sister", "aunt", "grandma", "cousin"], answer: 2 },
      { id: "q2", prompt: "Your dad's dad is your...", choices: ["uncle", "grandpa", "brother", "friend"], answer: 1 },
      { id: "q3", prompt: "Things that happened a long time ago are in the...", choices: ["future", "present", "past", "sky"], answer: 2 },
      { id: "q4", prompt: "Right now is called the...", choices: ["past", "present", "future", "finish"], answer: 1 },
      { id: "q5", prompt: "Tomorrow is in the...", choices: ["past", "present", "future", "middle"], answer: 2 },
      { id: "q6", prompt: "A long time ago people often traveled by...", choices: ["airplane", "horse and wagon", "spaceship", "car"], answer: 1 },
      { id: "q7", prompt: "Old photos are usually...", choices: ["brand new", "black and white", "made of plastic", "in 3D"], answer: 1 },
      { id: "q8", prompt: "A birthday celebrates the day you were...", choices: ["born", "asleep", "eating", "swimming"], answer: 0 },
      { id: "q9", prompt: "Your parents' brother is your...", choices: ["cousin", "uncle", "grandpa", "nephew"], answer: 1 },
      { id: "q10", prompt: "Children grow up to be...", choices: ["smaller", "the same size", "adults", "animals"], answer: 2 },
      { id: "q11", prompt: "Your mom's sister is your...", choices: ["aunt", "grandma", "cousin", "sister"], answer: 0 },
      { id: "q12", prompt: "The child of your aunt or uncle is your...", choices: ["brother", "cousin", "grandpa", "nephew"], answer: 1, explanation: "Your aunt or uncle's child is your cousin." },
      { id: "q13", prompt: "Yesterday already happened, so it is in the...", choices: ["future", "past", "present", "sky"], answer: 1 },
      { id: "q14", prompt: "A long time ago there were no TVs or...", choices: ["trees", "phones", "clouds", "water"], answer: 1 },
      { id: "q15", prompt: "A family often lives together in a...", choices: ["home", "store", "zoo", "river"], answer: 0 },
      { id: "q16", prompt: "Your brother or sister has the same...", choices: ["shoes", "parents", "friends", "teacher"], answer: 1 },
      { id: "q17", prompt: "As you get older, you grow...", choices: ["younger", "taller", "smaller", "into a baby"], answer: 1 },
      { id: "q18", prompt: "Long ago, many toys were made of wood instead of...", choices: ["plastic", "grass", "water", "clouds"], answer: 0 },
    ],
  },
  {
    id: "k-hist-holidays",
    subjectId: "history",
    level: "kindergarten",
    title: "Fun Holidays",
    description: "Holidays kids know and love.",
    emoji: "\u{1F389}",
    questions: [
      { id: "q1", prompt: "On which holiday do kids wear costumes and get candy?", choices: ["Halloween", "Easter", "Thanksgiving", "July 4th"], answer: 0 },
      { id: "q2", prompt: "On Thanksgiving we say...", choices: ["boo!", "thank you", "goodbye", "surprise"], answer: 1 },
      { id: "q3", prompt: "What do we see lots of on July 4th?", choices: ["snowmen", "fireworks", "pumpkins", "valentines"], answer: 1 },
      { id: "q4", prompt: "Valentine's Day is in which month?", choices: ["December", "February", "July", "October"], answer: 1 },
      { id: "q5", prompt: "Which holiday has a tree with lights?", choices: ["Christmas", "Earth Day", "Memorial Day", "Mother's Day"], answer: 0 },
      { id: "q6", prompt: "On your birthday we usually have...", choices: ["pumpkins", "a cake", "snowmen", "raincoats"], answer: 1 },
      { id: "q7", prompt: "On New Year's we celebrate a new...", choices: ["week", "day", "year", "hour"], answer: 2 },
      { id: "q8", prompt: "Mother's Day is to thank...", choices: ["teachers", "moms", "firefighters", "chefs"], answer: 1 },
      { id: "q9", prompt: "Father's Day is to thank...", choices: ["moms", "dads", "friends", "cousins"], answer: 1 },
      { id: "q10", prompt: "Earth Day helps us care for the...", choices: ["moon", "planet", "sun", "stars"], answer: 1 },
      { id: "q11", prompt: "On which holiday do we carve pumpkins?", choices: ["Easter", "Halloween", "July 4th", "New Year's"], answer: 1 },
      { id: "q12", prompt: "We blow out candles on a...", choices: ["birthday cake", "pumpkin", "snowman", "tree"], answer: 0 },
      { id: "q13", prompt: "Which holiday has a turkey dinner?", choices: ["Thanksgiving", "Halloween", "July 4th", "Easter"], answer: 0 },
      { id: "q14", prompt: "On July 4th we celebrate America's...", choices: ["birthday", "bedtime", "lunchtime", "nap"], answer: 0, explanation: "July 4th is our country's birthday." },
      { id: "q15", prompt: "On which holiday do kids hunt for eggs?", choices: ["Easter", "Christmas", "Halloween", "July 4th"], answer: 0 },
      { id: "q16", prompt: "We hang stockings at...", choices: ["Easter", "Halloween", "Christmas", "July 4th"], answer: 2 },
      { id: "q17", prompt: "On Valentine's Day we give cards shaped like...", choices: ["stars", "hearts", "squares", "triangles"], answer: 1 },
      { id: "q18", prompt: "New Year's Day is the first day of a new...", choices: ["week", "month", "year", "hour"], answer: 2 },
    ],
  },
  {
    id: "k-hist-symbols",
    subjectId: "history",
    level: "kindergarten",
    title: "Our Country",
    description: "Simple symbols of the U.S.",
    emoji: "\u{1F1FA}\u{1F1F8}",
    questions: [
      { id: "q1", prompt: "What colors are on the U.S. flag?", choices: ["red, white, blue", "green and gold", "pink and purple", "orange and black"], answer: 0 },
      { id: "q2", prompt: "The leader of our country is the...", choices: ["mayor", "president", "chef", "captain"], answer: 1 },
      { id: "q3", prompt: "Our country is called the...", choices: ["United States", "Canada", "Mexico", "France"], answer: 0 },
      { id: "q4", prompt: "The bird that stands for the U.S. is the...", choices: ["chicken", "bald eagle", "penguin", "owl"], answer: 1 },
      { id: "q5", prompt: "Our flag has stars and...", choices: ["hearts", "stripes", "circles", "smiles"], answer: 1 },
      { id: "q6", prompt: "We say the Pledge of Allegiance to the...", choices: ["book", "flag", "chair", "window"], answer: 1 },
      { id: "q7", prompt: "The president lives in the...", choices: ["Red House", "White House", "Big House", "Star House"], answer: 1 },
      { id: "q8", prompt: "The Statue of Liberty is a big...", choices: ["bird", "statue", "painting", "toy"], answer: 1 },
      { id: "q9", prompt: "Stars on the flag stand for the...", choices: ["states", "trees", "books", "days"], answer: 0 },
      { id: "q10", prompt: "The American flag has stripes that are red and...", choices: ["blue", "white", "yellow", "green"], answer: 1 },
      { id: "q11", prompt: "How many colors are on the U.S. flag?", choices: ["one", "two", "three", "ten"], answer: 2, explanation: "The flag has red, white, and blue." },
      { id: "q12", prompt: "The Statue of Liberty stands near the city of...", choices: ["New York", "Paris", "Tokyo", "London"], answer: 0 },
      { id: "q13", prompt: "The Liberty Bell is a big, old...", choices: ["bell", "drum", "flag", "hat"], answer: 0 },
      { id: "q14", prompt: "We celebrate our country's birthday on the Fourth of...", choices: ["June", "July", "May", "March"], answer: 1 },
      { id: "q15", prompt: "The U.S. flag is sometimes called the Stars and...", choices: ["Moons", "Stripes", "Circles", "Hearts"], answer: 1 },
      { id: "q16", prompt: "The president helps lead our...", choices: ["school", "country", "family", "team"], answer: 1 },
      { id: "q17", prompt: "How many stripes are on the U.S. flag?", choices: ["7", "10", "13", "20"], answer: 2, explanation: "The flag has 13 stripes." },
      { id: "q18", prompt: "The bald eagle is a kind of...", choices: ["fish", "bird", "bug", "dog"], answer: 1 },
    ],
  },

  // -------- GEOGRAPHY (Kindergarten) --------
  {
    id: "k-geo-maps",
    subjectId: "geography",
    level: "kindergarten",
    title: "Reading Maps",
    description: "Maps, symbols, and finding places.",
    emoji: "\u{1F5FA}\u{FE0F}",
    questions: [
      { id: "q1", prompt: "A map is a picture that shows us...", choices: ["how to cook", "where places are", "what to wear", "how to count"], answer: 1 },
      { id: "q2", prompt: "A blue color on a map usually means...", choices: ["land", "water", "sky", "roads"], answer: 1 },
      { id: "q3", prompt: "Green on a map usually means...", choices: ["water", "buildings", "land or forests", "sky"], answer: 2 },
      { id: "q4", prompt: "A key on a map tells you what the...", choices: ["lock is", "symbols mean", "date is", "weather is"], answer: 1 },
      { id: "q5", prompt: "A map of your classroom shows the...", choices: ["whole world", "room and where things are", "weather outside", "school lunch menu"], answer: 1 },
      { id: "q6", prompt: "A globe is a round model of the...", choices: ["moon", "sun", "Earth", "sky"], answer: 2 },
      { id: "q7", prompt: "A star on a map often marks a...", choices: ["lake", "mountain", "capital city", "road"], answer: 2 },
      { id: "q8", prompt: "A compass rose on a map shows...", choices: ["the weather", "north, south, east, west", "the time", "how tall things are"], answer: 1 },
      { id: "q9", prompt: "Maps can show us which direction to...", choices: ["eat", "sleep", "go", "grow"], answer: 2 },
      { id: "q10", prompt: "A map of the world shows all the...", choices: ["foods", "countries and oceans", "animals", "numbers"], answer: 1 },
      { id: "q11", prompt: "Brown or dark areas on a map often show...", choices: ["water", "snow", "mountains", "cities"], answer: 2 },
      { id: "q12", prompt: "N on a compass rose stands for...", choices: ["near", "next", "north", "night"], answer: 2 },
      { id: "q13", prompt: "S on a compass rose stands for...", choices: ["sun", "south", "stop", "small"], answer: 1 },
      { id: "q14", prompt: "A road on a map is often drawn as a...", choices: ["long line", "circle", "star", "blue blob"], answer: 0 },
      { id: "q15", prompt: "To find your way, you can use a map or a...", choices: ["compass", "spoon", "pillow", "cup"], answer: 0 },
      { id: "q16", prompt: "A flat picture of the whole world is called a...", choices: ["world map", "globe", "clock", "menu"], answer: 0, explanation: "A flat map of the world is a world map; a round one is a globe." },
      { id: "q17", prompt: "On most maps, which way is up?", choices: ["south", "north", "east", "down"], answer: 1 },
      { id: "q18", prompt: "E on a compass rose stands for...", choices: ["east", "easy", "end", "eat"], answer: 0 },
    ],
  },
  {
    id: "k-geo-earth",
    subjectId: "geography",
    level: "kindergarten",
    title: "Our Big Earth",
    description: "Land, water, and our planet.",
    emoji: "\u{1F30D}",
    questions: [
      { id: "q1", prompt: "What is the shape of Earth?", choices: ["a flat square", "a round ball", "a triangle", "a star"], answer: 1 },
      { id: "q2", prompt: "Most of Earth is covered by...", choices: ["sand", "grass", "water", "rocks"], answer: 2 },
      { id: "q3", prompt: "A really big body of water is called an...", choices: ["ocean", "puddle", "pond", "cup"], answer: 0 },
      { id: "q4", prompt: "A tall, pointy land shape is called a...", choices: ["river", "mountain", "valley", "beach"], answer: 1 },
      { id: "q5", prompt: "A hot, sandy, dry place is a...", choices: ["jungle", "desert", "ocean", "forest"], answer: 1 },
      { id: "q6", prompt: "Where do fish live?", choices: ["in trees", "in water", "in the sky", "in caves"], answer: 1 },
      { id: "q7", prompt: "Sand is mostly found at the...", choices: ["mountains", "beach", "snow", "office"], answer: 1 },
      { id: "q8", prompt: "Earth is also called our...", choices: ["planet", "star", "moon", "toy"], answer: 0 },
      { id: "q9", prompt: "A round model of Earth is called a...", choices: ["map", "globe", "flag", "sign"], answer: 1 },
      { id: "q10", prompt: "The really cold places at the top and bottom of Earth are the...", choices: ["deserts", "poles", "oceans", "hills"], answer: 1 },
      { id: "q11", prompt: "A large area full of trees is called a...", choices: ["forest", "desert", "ocean", "city"], answer: 0 },
      { id: "q12", prompt: "Earth gets its light and warmth from the...", choices: ["moon", "sun", "stars", "clouds"], answer: 1, explanation: "The sun gives Earth light and heat." },
      { id: "q13", prompt: "Dirt and rocks make up the...", choices: ["sky", "land", "ocean", "cloud"], answer: 1 },
      { id: "q14", prompt: "A low place between two mountains is a...", choices: ["valley", "beach", "desert", "island"], answer: 0 },
      { id: "q15", prompt: "Land with water all around it is an...", choices: ["island", "mountain", "desert", "forest"], answer: 0, explanation: "An island has water all around it." },
      { id: "q16", prompt: "The air all around Earth lets us...", choices: ["swim", "breathe", "drive", "cook"], answer: 1 },
      { id: "q17", prompt: "A very hot place with lots of sand is a...", choices: ["forest", "desert", "pond", "cave"], answer: 1 },
      { id: "q18", prompt: "Which is bigger, a pond or an ocean?", choices: ["pond", "ocean", "same size", "neither"], answer: 1 },
    ],
  },
  {
    id: "k-geo-directions",
    subjectId: "geography",
    level: "kindergarten",
    title: "Where Things Are",
    description: "Up, down, left, right, and simple maps.",
    emoji: "\u{1F9ED}",
    questions: [
      { id: "q1", prompt: "The sun rises in the morning in the...", choices: ["east", "west", "north", "south"], answer: 0 },
      { id: "q2", prompt: "The sun sets in the evening in the...", choices: ["east", "west", "north", "south"], answer: 1 },
      { id: "q3", prompt: "A picture that shows where things are is a...", choices: ["map", "book", "phone", "shoe"], answer: 0 },
      { id: "q4", prompt: "'Up' is the opposite of...", choices: ["left", "right", "down", "in"], answer: 2 },
      { id: "q5", prompt: "'Left' is the opposite of...", choices: ["right", "up", "down", "behind"], answer: 0 },
      { id: "q6", prompt: "'In front' is the opposite of...", choices: ["behind", "above", "under", "near"], answer: 0 },
      { id: "q7", prompt: "The pet is UNDER the table. Where is the table?", choices: ["under the pet", "above the pet", "behind the pet", "inside the pet"], answer: 1 },
      { id: "q8", prompt: "Birds usually fly in the...", choices: ["sky", "ocean", "ground", "tunnel"], answer: 0 },
      { id: "q9", prompt: "Cars drive on the...", choices: ["sea", "sky", "road", "roof"], answer: 2 },
      { id: "q10", prompt: "If you are NEXT TO your friend, you are...", choices: ["far away", "beside them", "on top", "under"], answer: 1 },
      { id: "q11", prompt: "The opposite of 'top' is...", choices: ["middle", "bottom", "side", "front"], answer: 1 },
      { id: "q12", prompt: "The opposite of 'near' is...", choices: ["far", "close", "beside", "next"], answer: 0 },
      { id: "q13", prompt: "If a cat is ON the bed, the bed is...", choices: ["under the cat", "over the cat", "beside the sky", "gone"], answer: 0 },
      { id: "q14", prompt: "'Inside' is the opposite of...", choices: ["outside", "under", "above", "near"], answer: 0 },
      { id: "q15", prompt: "The opposite of 'fast' is...", choices: ["slow", "quick", "high", "loud"], answer: 0 },
      { id: "q16", prompt: "When you move forward, you go...", choices: ["ahead", "backward", "sideways", "down"], answer: 0 },
      { id: "q17", prompt: "Fish swim ___ the water.", choices: ["above", "in", "on top of only", "beside"], answer: 1 },
      { id: "q18", prompt: "The opposite of 'first' is...", choices: ["start", "front", "middle", "last"], answer: 3 },
    ],
  },
  {
    id: "k-geo-water",
    subjectId: "geography",
    level: "kindergarten",
    title: "Water Places",
    description: "Rivers, lakes, oceans, and ponds.",
    emoji: "\u{1F30A}",
    questions: [
      { id: "q1", prompt: "A small body of water you can walk around is a...", choices: ["ocean", "pond", "mountain", "forest"], answer: 1 },
      { id: "q2", prompt: "A long, flowing water with two sides of land is a...", choices: ["river", "lake", "sea", "desert"], answer: 0 },
      { id: "q3", prompt: "The biggest water of all is an...", choices: ["ocean", "puddle", "pond", "glass"], answer: 0 },
      { id: "q4", prompt: "Sand meets the ocean at the...", choices: ["forest", "beach", "hill", "barn"], answer: 1 },
      { id: "q5", prompt: "Boats float on...", choices: ["grass", "sand", "water", "trees"], answer: 2 },
      { id: "q6", prompt: "Which animal lives in the ocean?", choices: ["cow", "whale", "horse", "goat"], answer: 1 },
      { id: "q7", prompt: "Water from rain forms a small puddle on the...", choices: ["sky", "ground", "moon", "roof of stars"], answer: 1 },
      { id: "q8", prompt: "Ice cubes are water that is...", choices: ["hot", "warm", "frozen", "singing"], answer: 2 },
      { id: "q9", prompt: "A lake is mostly surrounded by...", choices: ["water", "sky", "land", "clouds"], answer: 2 },
      { id: "q10", prompt: "Salt water tastes...", choices: ["sweet", "salty", "sour", "spicy"], answer: 1 },
      { id: "q11", prompt: "Water that falls from clouds is called...", choices: ["rain", "sand", "rocks", "leaves"], answer: 0 },
      { id: "q12", prompt: "A tiny stream of water is smaller than a...", choices: ["drop", "river", "raindrop", "sip"], answer: 1 },
      { id: "q13", prompt: "Fish breathe and live in...", choices: ["water", "air", "sand", "fire"], answer: 0, explanation: "Fish live in water." },
      { id: "q14", prompt: "When water gets very cold it turns into...", choices: ["steam", "ice", "sand", "sugar"], answer: 1 },
      { id: "q15", prompt: "A duck likes to swim on a...", choices: ["pond", "mountain", "cloud", "road"], answer: 0 },
      { id: "q16", prompt: "The water in the ocean has a lot of...", choices: ["salt", "sugar", "milk", "juice"], answer: 0 },
      { id: "q17", prompt: "We drink water that is clean and...", choices: ["fresh", "salty", "frozen solid", "dirty"], answer: 0 },
      { id: "q18", prompt: "Which one is the smallest?", choices: ["ocean", "lake", "puddle", "river"], answer: 2 },
    ],
  },
  {
    id: "k-geo-home",
    subjectId: "geography",
    level: "kindergarten",
    title: "Around My Home",
    description: "Places near where we live.",
    emoji: "\u{1F3E1}",
    questions: [
      { id: "q1", prompt: "You learn at...", choices: ["a school", "a bakery", "a farm", "a beach"], answer: 0 },
      { id: "q2", prompt: "You buy food at the...", choices: ["library", "grocery store", "zoo", "airport"], answer: 1 },
      { id: "q3", prompt: "You borrow books at the...", choices: ["hospital", "library", "bank", "park"], answer: 1 },
      { id: "q4", prompt: "Sick people go to the...", choices: ["playground", "hospital", "school", "barn"], answer: 1 },
      { id: "q5", prompt: "Animals you can visit live at the...", choices: ["library", "zoo", "office", "airport"], answer: 1 },
      { id: "q6", prompt: "You can swing and slide at the...", choices: ["bank", "playground", "library", "hospital"], answer: 1 },
      { id: "q7", prompt: "Airplanes take off and land at the...", choices: ["airport", "farm", "library", "pond"], answer: 0 },
      { id: "q8", prompt: "Cows, pigs, and chickens often live on a...", choices: ["beach", "farm", "airport", "library"], answer: 1 },
      { id: "q9", prompt: "Many trees and trails are at the...", choices: ["park", "office", "bank", "store"], answer: 0 },
      { id: "q10", prompt: "Houses, streets, and stores together make a...", choices: ["forest", "town", "ocean", "sky"], answer: 1 },
      { id: "q11", prompt: "You mail a letter at the...", choices: ["post office", "zoo", "beach", "farm"], answer: 0 },
      { id: "q12", prompt: "You get medicine at the...", choices: ["airport", "pharmacy", "park", "zoo"], answer: 1 },
      { id: "q13", prompt: "Firefighters work at the fire...", choices: ["station", "store", "farm", "beach"], answer: 0 },
      { id: "q14", prompt: "You can watch a big movie at the...", choices: ["bank", "movie theater", "farm", "airport"], answer: 1 },
      { id: "q15", prompt: "You keep your money safe at the...", choices: ["zoo", "bank", "park", "beach"], answer: 1, explanation: "People keep money at a bank." },
      { id: "q16", prompt: "A place with lots of shops together is a...", choices: ["forest", "ocean", "mall", "farm"], answer: 2 },
      { id: "q17", prompt: "You wait for a train at the train...", choices: ["barn", "station", "beach", "cloud"], answer: 1 },
      { id: "q18", prompt: "You can have a picnic and play at the...", choices: ["hospital", "park", "bank", "airport"], answer: 1 },
    ],
  },
];
