/** Brainy Buddies - 7th Grade core curriculum activities. */
import type { Activity } from "@/lib/brainy-data";

export const GRADE7_ACTIVITIES: Activity[] = [
  {
    id: "g7-math-proportions",
    subjectId: "math",
    level: "grade7",
    title: "Proportions & Rational Numbers",
    description: "Solve proportional relationships and operate confidently with positive and negative numbers.",
    emoji: "📈",
    questions: [
      { id: "q1", prompt: "If 3 tickets cost $18, how much do 5 tickets cost at the same rate?", choices: ["$24", "$30", "$36", "$90"], answer: 1 },
      { id: "q2", prompt: "What is -8 + 13?", choices: ["-21", "-5", "5", "21"], answer: 2 },
      { id: "q3", prompt: "What is (-6)(-4)?", choices: ["-24", "-10", "10", "24"], answer: 3 },
      { id: "q4", prompt: "Which equation represents a proportional relationship?", choices: ["y = 3x", "y = 3x + 2", "y = x²", "y = 3"], answer: 0 },
      { id: "q5", prompt: "A $40 jacket is discounted 25%. What is the sale price?", choices: ["$10", "$25", "$30", "$35"], answer: 2 },
      { id: "q6", prompt: "What is 3/4 divided by 1/2?", choices: ["3/8", "2/3", "1", "3/2"], answer: 3, explanation: "Multiply by the reciprocal: 3/4 x 2/1 = 6/4 = 3/2." },
      { id: "q7", prompt: "The point (4, 10) lies on y = kx. What is k?", choices: ["0.4", "2", "2.5", "6"], answer: 2 },
      { id: "q8", prompt: "A quantity increases from 50 to 60. What is the percent increase?", choices: ["10%", "20%", "50%", "60%"], answer: 1 },
      { id: "q9", prompt: "What is -2.5 - 3.5?", choices: ["-6", "-1", "1", "6"], answer: 0 },
      { id: "q10", prompt: "On a graph of a proportional relationship, what point must the line pass through?", choices: ["(0, 0)", "(0, 1)", "(1, 0)", "(1, 1)"], answer: 0 },
    ],
  },
  {
    id: "g7-math-equations-inequalities",
    subjectId: "math",
    level: "grade7",
    title: "Equations & Inequalities",
    description: "Solve multi-step equations and graph inequalities.",
    emoji: "⚖️",
    questions: [
      { id: "q1", prompt: "Solve 3x + 5 = 20.", choices: ["x = 3", "x = 5", "x = 8", "x = 15"], answer: 1 },
      { id: "q2", prompt: "Solve 4(x - 2) = 24.", choices: ["x = 4", "x = 6", "x = 8", "x = 10"], answer: 2 },
      { id: "q3", prompt: "Solve 5x - 7 = 2x + 8.", choices: ["x = 3", "x = 5", "x = 7", "x = 15"], answer: 1 },
      { id: "q4", prompt: "Which is equivalent to 2(3x + 4) - x?", choices: ["5x + 4", "5x + 8", "6x + 8", "7x + 4"], answer: 1 },
      { id: "q5", prompt: "Solve x/3 - 2 = 4.", choices: ["x = 6", "x = 12", "x = 18", "x = 24"], answer: 2 },
      { id: "q6", prompt: "Which inequality represents 'a number n is at least 12'?", choices: ["n > 12", "n >= 12", "n < 12", "n <= 12"], answer: 1 },
      { id: "q7", prompt: "Solve 2x + 1 < 9.", choices: ["x < 4", "x > 4", "x < 5", "x > 5"], answer: 0 },
      { id: "q8", prompt: "What happens to an inequality sign when both sides are multiplied by -1?", choices: ["It stays the same", "It reverses", "It becomes an equals sign", "It disappears"], answer: 1 },
      { id: "q9", prompt: "Solve -3x > 12.", choices: ["x > -4", "x < -4", "x > 4", "x < 4"], answer: 1 },
      { id: "q10", prompt: "A gym charges $8 plus $3 per visit. Which expression gives the cost for v visits?", choices: ["8v + 3", "3v + 8", "11v", "8(v + 3)"], answer: 1 },
    ],
  },
  {
    id: "g7-math-circles-angles",
    subjectId: "math",
    level: "grade7",
    title: "Circles & Angle Relationships",
    description: "Use circle formulas and relationships among angles.",
    emoji: "⭕",
    questions: [
      { id: "q1", prompt: "A circle has radius 6 cm. What is its diameter?", choices: ["3 cm", "6 cm", "12 cm", "36 cm"], answer: 2 },
      { id: "q2", prompt: "Which formula gives the circumference of a circle?", choices: ["C = pi r²", "C = 2 pi r", "C = r + d", "C = 2r²"], answer: 1 },
      { id: "q3", prompt: "Using pi = 3.14, what is the circumference of a circle with diameter 10 cm?", choices: ["15.7 cm", "31.4 cm", "62.8 cm", "314 cm"], answer: 1 },
      { id: "q4", prompt: "Which formula gives the area of a circle?", choices: ["A = pi r²", "A = 2 pi r", "A = pi d", "A = r²/2"], answer: 0 },
      { id: "q5", prompt: "Using pi = 3.14, what is the area of a circle with radius 4 cm?", choices: ["12.56 cm²", "25.12 cm²", "50.24 cm²", "100.48 cm²"], answer: 2 },
      { id: "q6", prompt: "Two complementary angles add to...", choices: ["45 degrees", "90 degrees", "180 degrees", "360 degrees"], answer: 1 },
      { id: "q7", prompt: "Two supplementary angles add to...", choices: ["90 degrees", "120 degrees", "180 degrees", "360 degrees"], answer: 2 },
      { id: "q8", prompt: "One angle in a supplementary pair is 125 degrees. What is the other?", choices: ["45 degrees", "55 degrees", "65 degrees", "235 degrees"], answer: 1 },
      { id: "q9", prompt: "Vertical angles are always...", choices: ["complementary", "congruent", "supplementary", "right angles"], answer: 1 },
      { id: "q10", prompt: "Two lines intersect. One angle is 72 degrees. What is its vertical angle?", choices: ["18 degrees", "72 degrees", "108 degrees", "288 degrees"], answer: 1 },
    ],
  },
  {
    id: "g7-math-probability",
    subjectId: "math",
    level: "grade7",
    title: "Probability Models",
    description: "Find theoretical and experimental probabilities for simple and compound events.",
    emoji: "🎲",
    questions: [
      { id: "q1", prompt: "What is the probability of rolling a 4 on a fair six-sided die?", choices: ["1/2", "1/4", "1/6", "4/6"], answer: 2 },
      { id: "q2", prompt: "A bag has 3 red and 2 blue marbles. What is P(red)?", choices: ["2/5", "3/5", "1/2", "3/2"], answer: 1 },
      { id: "q3", prompt: "What is the probability of an impossible event?", choices: ["0", "1/2", "1", "100"], answer: 0 },
      { id: "q4", prompt: "What is the probability of a certain event?", choices: ["0", "1/4", "1/2", "1"], answer: 3 },
      { id: "q5", prompt: "A coin is flipped twice. What is the probability of two heads?", choices: ["1/2", "1/3", "1/4", "2/3"], answer: 2 },
      { id: "q6", prompt: "A spinner lands on green 18 times in 60 spins. What is the experimental probability of green?", choices: ["3/10", "18/42", "2/3", "3"], answer: 0 },
      { id: "q7", prompt: "Which list is the sample space for one coin flip?", choices: ["{H}", "{T}", "{H, T}", "{HH, TT}"], answer: 2 },
      { id: "q8", prompt: "What is P(not rolling a 6) on a fair die?", choices: ["1/6", "1/5", "5/6", "1"], answer: 2 },
      { id: "q9", prompt: "A fair coin is flipped 200 times. About how many heads are expected?", choices: ["25", "50", "100", "200"], answer: 2 },
      { id: "q10", prompt: "Why might experimental probability differ from theoretical probability?", choices: ["Chance varies in a limited number of trials", "Theoretical probability is always wrong", "Experiments have no outcomes", "Probability can exceed 1"], answer: 0 },
    ],
  },
  {
    id: "g7-math-sampling-statistics",
    subjectId: "math",
    level: "grade7",
    title: "Sampling & Comparing Data",
    description: "Use random samples and data distributions to draw conclusions.",
    emoji: "📋",
    questions: [
      { id: "q1", prompt: "Why do researchers use a random sample?", choices: ["To guarantee a preferred result", "To give population members a fair chance of selection", "To survey only friends", "To avoid collecting data"], answer: 1 },
      { id: "q2", prompt: "Which sample is most biased for estimating school lunch opinions?", choices: ["Random students from every grade", "Only students who bring lunch from home", "Every 10th student entering school", "Names drawn from the full roster"], answer: 1 },
      { id: "q3", prompt: "A population is...", choices: ["the entire group being studied", "only the people surveyed", "one data value", "the average result"], answer: 0 },
      { id: "q4", prompt: "A sample is...", choices: ["every possible person", "a subset of the population", "always biased", "the largest value"], answer: 1 },
      { id: "q5", prompt: "A random sample of 50 voters has 30 who support a proposal. About what percent support it?", choices: ["30%", "40%", "60%", "80%"], answer: 2 },
      { id: "q6", prompt: "If 60% of a representative sample supports a proposal, about how many of 500 people might support it?", choices: ["60", "200", "300", "440"], answer: 2 },
      { id: "q7", prompt: "Two groups have the same mean. What else should you compare?", choices: ["Only their names", "Their variability and distributions", "Only sample color", "Nothing else"], answer: 1 },
      { id: "q8", prompt: "Which measure describes spread?", choices: ["Median", "Mean absolute deviation", "Mode", "Sample size"], answer: 1 },
      { id: "q9", prompt: "A larger random sample generally produces...", choices: ["a more stable estimate", "a guaranteed exact answer", "more bias automatically", "no variability"], answer: 0 },
      { id: "q10", prompt: "A conclusion from sample data should apply to the population when the sample is...", choices: ["convenient but biased", "representative", "very small and selected", "made of volunteers only"], answer: 1 },
    ],
  },
  {
    id: "g7-math-scale-geometry",
    subjectId: "math",
    level: "grade7",
    title: "Scale Drawings & 3D Geometry",
    description: "Apply scale factors and solve surface-area and volume problems.",
    emoji: "🏗️",
    questions: [
      { id: "q1", prompt: "A scale drawing uses 1 cm = 4 m. What does 6 cm represent?", choices: ["10 m", "20 m", "24 m", "30 m"], answer: 2 },
      { id: "q2", prompt: "A drawing length is 5 in and the actual length is 20 ft. What is the scale?", choices: ["1 in = 2 ft", "1 in = 4 ft", "1 in = 5 ft", "1 in = 20 ft"], answer: 1 },
      { id: "q3", prompt: "A shape is enlarged by scale factor 3. A side of 7 cm becomes...", choices: ["10 cm", "14 cm", "21 cm", "28 cm"], answer: 2 },
      { id: "q4", prompt: "If lengths scale by 2, areas scale by...", choices: ["2", "4", "6", "8"], answer: 1 },
      { id: "q5", prompt: "What is the volume of a rectangular prism 8 cm by 3 cm by 5 cm?", choices: ["16 cm³", "40 cm³", "80 cm³", "120 cm³"], answer: 3 },
      { id: "q6", prompt: "A triangular prism has base area 12 cm² and length 7 cm. What is its volume?", choices: ["19 cm³", "42 cm³", "84 cm³", "168 cm³"], answer: 2 },
      { id: "q7", prompt: "Which measurement is needed for the surface area of a prism?", choices: ["Areas of all exterior faces", "Only its height", "Only its volume", "The number of interior points"], answer: 0 },
      { id: "q8", prompt: "A cube has edge length 4 cm. What is its volume?", choices: ["16 cm³", "24 cm³", "64 cm³", "96 cm³"], answer: 2 },
      { id: "q9", prompt: "A scale factor less than 1 creates...", choices: ["an enlargement", "a reduction", "the same-size figure always", "a reflection only"], answer: 1 },
      { id: "q10", prompt: "A 10 m wall appears as 25 cm on a drawing. How many drawing centimeters represent 2 m?", choices: ["2.5 cm", "5 cm", "10 cm", "20 cm"], answer: 1 },
    ],
  },
  {
    id: "g7-sci-ecosystems",
    subjectId: "science",
    level: "grade7",
    title: "Ecosystems & Natural Selection",
    description: "Analyze energy flow, ecosystem change, inherited traits, and natural selection.",
    emoji: "🧬",
    questions: [
      { id: "q1", prompt: "Which organisms begin most food chains by capturing energy?", choices: ["Consumers", "Decomposers", "Producers", "Predators"], answer: 2 },
      { id: "q2", prompt: "Why is less energy available at higher trophic levels?", choices: ["Energy is used and released as heat", "Plants stop photosynthesis", "Predators create energy", "Matter disappears"], answer: 0 },
      { id: "q3", prompt: "Which is an abiotic factor in an ecosystem?", choices: ["Fungus", "Soil temperature", "Grass", "Bacteria"], answer: 1 },
      { id: "q4", prompt: "What is carrying capacity?", choices: ["The fastest an animal can move", "The largest population an environment can support", "The amount of DNA in a cell", "The number of food chains"], answer: 1 },
      { id: "q5", prompt: "A trait that improves survival and reproduction is called an...", choices: ["adaptation", "ecosystem", "extinction", "equilibrium"], answer: 0 },
      { id: "q6", prompt: "Natural selection acts directly on...", choices: ["acquired wishes", "heritable variation in a population", "all traits equally", "nonliving factors only"], answer: 1 },
      { id: "q7", prompt: "Which relationship benefits both species?", choices: ["Parasitism", "Competition", "Mutualism", "Predation"], answer: 2 },
      { id: "q8", prompt: "What role do decomposers play?", choices: ["They recycle nutrients", "They create sunlight", "They stop all competition", "They remove oxygen"], answer: 0 },
      { id: "q9", prompt: "If a top predator is removed, what can happen first?", choices: ["Prey populations may increase", "All producers disappear immediately", "Energy flow stops", "The climate changes instantly"], answer: 0 },
      { id: "q10", prompt: "Inherited information is stored in...", choices: ["minerals", "DNA", "sunlight", "water"], answer: 1 },
    ],
  },
  {
    id: "g7-sci-chemical-reactions",
    subjectId: "science",
    level: "grade7",
    title: "Chemical Reactions",
    description: "Track atoms, energy, and evidence as substances react.",
    emoji: "🧪",
    questions: [
      { id: "q1", prompt: "The starting substances in a chemical reaction are called...", choices: ["products", "reactants", "catalysts", "solutions"], answer: 1 },
      { id: "q2", prompt: "The new substances formed in a reaction are called...", choices: ["products", "reactants", "elements", "mixtures"], answer: 0 },
      { id: "q3", prompt: "Which can be evidence of a chemical reaction?", choices: ["Gas production", "Color change", "Temperature change", "All of these"], answer: 3 },
      { id: "q4", prompt: "During a chemical reaction, atoms are...", choices: ["created from nothing", "destroyed", "rearranged into new combinations", "changed into energy only"], answer: 2 },
      { id: "q5", prompt: "The law of conservation of mass states that mass is...", choices: ["created in reactions", "destroyed in reactions", "conserved in a closed system", "always doubled"], answer: 2 },
      { id: "q6", prompt: "Which is a chemical change?", choices: ["Cutting paper", "Melting wax", "Rusting iron", "Crushing ice"], answer: 2 },
      { id: "q7", prompt: "An exothermic reaction...", choices: ["releases energy to its surroundings", "absorbs all matter", "has no energy change", "creates atoms"], answer: 0 },
      { id: "q8", prompt: "An endothermic reaction...", choices: ["releases only light", "absorbs energy from its surroundings", "destroys mass", "cannot occur"], answer: 1 },
      { id: "q9", prompt: "Why must chemical equations be balanced?", choices: ["To show the same number of each type of atom on both sides", "To make every coefficient 1", "To remove products", "To change element symbols"], answer: 0 },
      { id: "q10", prompt: "A catalyst speeds up a reaction while...", choices: ["being used up completely", "remaining chemically unchanged overall", "adding new atoms", "doubling the mass"], answer: 1 },
    ],
  },
  {
    id: "g7-sci-genetics",
    subjectId: "science",
    level: "grade7",
    title: "Genetics & Heredity",
    description: "Connect DNA, genes, traits, and patterns of inheritance.",
    emoji: "🧬",
    questions: [
      { id: "q1", prompt: "A gene is a segment of...", choices: ["protein only", "DNA", "cell membrane", "cytoplasm"], answer: 1 },
      { id: "q2", prompt: "Genes are located on structures called...", choices: ["chromosomes", "ribosomes", "tissues", "organelles only"], answer: 0 },
      { id: "q3", prompt: "Different forms of the same gene are called...", choices: ["alleles", "cells", "species", "proteins"], answer: 0 },
      { id: "q4", prompt: "An organism with two identical alleles for a gene is...", choices: ["heterozygous", "homozygous", "mutated", "asexual"], answer: 1 },
      { id: "q5", prompt: "In a simple dominant-recessive pattern, a dominant allele is expressed when...", choices: ["at least one copy is present", "two recessive copies are present", "no alleles are present", "the environment changes"], answer: 0 },
      { id: "q6", prompt: "A Punnett square predicts...", choices: ["possible offspring genotypes", "exact number of offspring", "an organism's age", "acquired skills"], answer: 0 },
      { id: "q7", prompt: "If B is dominant and b is recessive, which genotype is heterozygous?", choices: ["BB", "Bb", "bb", "B only"], answer: 1 },
      { id: "q8", prompt: "A mutation is...", choices: ["a change in DNA", "always harmful", "an acquired habit", "a type of tissue"], answer: 0 },
      { id: "q9", prompt: "Which trait is strongly influenced by both genes and environment?", choices: ["Blood type", "A scar", "Human height", "A learned language only"], answer: 2 },
      { id: "q10", prompt: "Natural selection requires heritable variation because...", choices: ["offspring must be identical", "some inherited traits affect reproductive success", "organisms choose mutations", "environments never change"], answer: 1 },
    ],
  },
  {
    id: "g7-sci-earth-history",
    subjectId: "science",
    level: "grade7",
    title: "Plate Tectonics & Earth History",
    description: "Use plate motion, rocks, and fossils to reconstruct Earth's past.",
    emoji: "🌋",
    questions: [
      { id: "q1", prompt: "Earth's lithosphere is broken into moving...", choices: ["weather fronts", "tectonic plates", "ocean currents", "magnetic poles"], answer: 1 },
      { id: "q2", prompt: "At a divergent boundary, plates...", choices: ["move apart", "collide", "slide past", "stop moving"], answer: 0 },
      { id: "q3", prompt: "At a convergent boundary, plates...", choices: ["move apart", "move toward each other", "always form rivers", "remain fixed"], answer: 1 },
      { id: "q4", prompt: "At a transform boundary, plates...", choices: ["slide past each other", "melt completely", "move only upward", "form no earthquakes"], answer: 0 },
      { id: "q5", prompt: "Most earthquakes and volcanoes occur...", choices: ["near plate boundaries", "only at the Equator", "in the middle of every continent", "only underwater"], answer: 0 },
      { id: "q6", prompt: "Matching fossils on continents now far apart support the idea of...", choices: ["continental drift", "daily weather", "lunar phases", "chemical equilibrium"], answer: 0 },
      { id: "q7", prompt: "In undisturbed sedimentary layers, the oldest layer is usually...", choices: ["at the top", "at the bottom", "in the middle", "the thinnest"], answer: 1 },
      { id: "q8", prompt: "Index fossils help scientists...", choices: ["compare ages of rock layers", "predict tomorrow's weather", "measure gravity", "identify every living organism"], answer: 0 },
      { id: "q9", prompt: "Radiometric dating estimates age using...", choices: ["radioactive decay", "layer color only", "fossil size", "weather patterns"], answer: 0 },
      { id: "q10", prompt: "Pangaea was...", choices: ["an ancient supercontinent", "the first ocean", "a dinosaur species", "a volcanic island"], answer: 0 },
    ],
  },
  {
    id: "g7-sci-waves-electricity",
    subjectId: "science",
    level: "grade7",
    title: "Waves, Sound & Electricity",
    description: "Model wave behavior and energy transfer in electrical circuits.",
    emoji: "〰️",
    questions: [
      { id: "q1", prompt: "A wave transfers...", choices: ["energy", "matter from start to finish", "mass permanently", "atoms into elements"], answer: 0 },
      { id: "q2", prompt: "Wave amplitude is related to the wave's...", choices: ["energy", "speed only", "direction only", "chemical formula"], answer: 0 },
      { id: "q3", prompt: "Frequency is the number of wave cycles that pass a point per...", choices: ["meter", "second", "kilogram", "degree"], answer: 1 },
      { id: "q4", prompt: "A higher-frequency sound is heard as a...", choices: ["higher pitch", "lower pitch", "quieter sound always", "slower sound"], answer: 0 },
      { id: "q5", prompt: "Sound cannot travel through...", choices: ["air", "water", "steel", "a vacuum"], answer: 3 },
      { id: "q6", prompt: "Unlike sound, light can travel through...", choices: ["a vacuum", "solids only", "liquids only", "air only"], answer: 0 },
      { id: "q7", prompt: "An electric circuit must be closed so...", choices: ["current can flow", "voltage disappears", "the battery gains mass", "all wires cool"], answer: 0 },
      { id: "q8", prompt: "Which material is a good electrical conductor?", choices: ["Rubber", "Plastic", "Copper", "Glass"], answer: 2 },
      { id: "q9", prompt: "In a series circuit, opening one part usually...", choices: ["stops current throughout the circuit", "makes every bulb brighter", "creates another battery", "has no effect"], answer: 0 },
      { id: "q10", prompt: "A parallel circuit gives current...", choices: ["only one path", "multiple paths", "no path", "a path through air only"], answer: 1 },
    ],
  },
  {
    id: "g7-hist-medieval-modern",
    subjectId: "history",
    level: "grade7",
    title: "Medieval to Early Modern World",
    description: "Trace how trade, belief, technology, and new ideas transformed societies.",
    emoji: "🏰",
    questions: [
      { id: "q1", prompt: "In feudal Europe, land was exchanged mainly for...", choices: ["military service and loyalty", "factory labor", "voting rights", "paper money"], answer: 0 },
      { id: "q2", prompt: "How did the Silk Road affect societies?", choices: ["It spread goods, ideas, and diseases", "It ended all wars", "It connected only two cities", "It prevented cultural exchange"], answer: 0 },
      { id: "q3", prompt: "The Magna Carta helped establish the idea that...", choices: ["the ruler is subject to law", "kings have unlimited power", "trade should end", "only nobles need laws"], answer: 0 },
      { id: "q4", prompt: "The Renaissance began in Italian cities partly because they...", choices: ["were wealthy centers of trade", "had no contact with other cultures", "banned ancient texts", "had no political competition"], answer: 0 },
      { id: "q5", prompt: "Humanism encouraged scholars to focus on...", choices: ["human potential and classical learning", "ending education", "military rule only", "rejecting all art"], answer: 0 },
      { id: "q6", prompt: "Why was Gutenberg's printing press important?", choices: ["It made books faster and cheaper to produce", "It invented handwriting", "It ended sea travel", "It replaced universities"], answer: 0 },
      { id: "q7", prompt: "One major effect of the Columbian Exchange was...", choices: ["the movement of crops, animals, people, and diseases", "the end of Atlantic travel", "the isolation of continents", "the disappearance of trade"], answer: 0 },
      { id: "q8", prompt: "Which development helped sailors navigate long ocean voyages?", choices: ["Astrolabe and improved maps", "Aqueducts", "Steam engines", "Telegraphs"], answer: 0 },
      { id: "q9", prompt: "A historian comparing conflicting accounts should first consider each author's...", choices: ["perspective and evidence", "handwriting only", "favorite color", "word count"], answer: 0 },
      { id: "q10", prompt: "The Scientific Revolution emphasized...", choices: ["observation and experimentation", "tradition without questions", "ending mathematics", "government by nobles"], answer: 0 },
    ],
  },
  {
    id: "g7-geo-population-economics",
    subjectId: "geography",
    level: "grade7",
    title: "Population, Trade & Development",
    description: "Interpret demographic patterns, global trade, urbanization, and measures of development.",
    emoji: "🧭",
    questions: [
      { id: "q1", prompt: "What is urbanization?", choices: ["Growth of cities and urban populations", "Decline in all trade", "Movement from cities to farms only", "Creation of mountain ranges"], answer: 0 },
      { id: "q2", prompt: "Which is a common pull factor for migration?", choices: ["War", "Drought", "Job opportunities", "Persecution"], answer: 2 },
      { id: "q3", prompt: "What does GDP broadly measure?", choices: ["Value of goods and services produced", "Only population size", "Average rainfall", "Land elevation"], answer: 0 },
      { id: "q4", prompt: "Why do countries specialize in certain products?", choices: ["Resources and skills differ by place", "Every country has identical resources", "Trade is always illegal", "Climate never affects production"], answer: 0 },
      { id: "q5", prompt: "An import is a good that is...", choices: ["brought into a country", "sent out of a country", "never traded", "made only by government"], answer: 0 },
      { id: "q6", prompt: "Which indicator can help compare quality of life?", choices: ["Life expectancy", "Longitude", "Number of borders", "Mountain height"], answer: 0 },
      { id: "q7", prompt: "A population pyramid with a very wide base usually suggests...", choices: ["a high birth rate", "no children", "a shrinking youth population", "equal ages everywhere"], answer: 0 },
      { id: "q8", prompt: "What is a trade-off of rapid urban growth?", choices: ["More jobs but greater pressure on housing and services", "No economic activity", "Fewer transportation needs", "No environmental effects"], answer: 0 },
      { id: "q9", prompt: "A tariff is...", choices: ["a tax on imported goods", "a type of climate", "a migration route", "a population count"], answer: 0 },
      { id: "q10", prompt: "Sustainable development aims to...", choices: ["meet present needs without harming future generations", "use resources as quickly as possible", "stop all economic growth", "eliminate cities"], answer: 0 },
    ],
  },
];