/** Brainy Buddies - 6th Grade core curriculum activities. */
import type { Activity } from "@/lib/brainy-data";

export const GRADE6_ACTIVITIES: Activity[] = [
  {
    id: "g6-math-ratios",
    subjectId: "math",
    level: "grade6",
    title: "Ratios, Rates & Percents",
    description: "Compare quantities, find unit rates, and connect fractions, decimals, and percents.",
    emoji: "📊",
    questions: [
      { id: "q1", prompt: "A recipe uses 2 cups of flour for 3 cups of oats. What is the ratio of flour to oats?", choices: ["2:3", "3:2", "2:5", "3:5"], answer: 0 },
      { id: "q2", prompt: "Five notebooks cost $15. What is the cost per notebook?", choices: ["$2", "$3", "$5", "$10"], answer: 1, explanation: "$15 divided by 5 notebooks is $3 per notebook." },
      { id: "q3", prompt: "Which ratio is equivalent to 4:6?", choices: ["2:3", "3:4", "6:8", "8:10"], answer: 0 },
      { id: "q4", prompt: "What is 25% written as a fraction in simplest form?", choices: ["1/2", "1/3", "1/4", "1/5"], answer: 2 },
      { id: "q5", prompt: "A car travels 180 miles in 3 hours. What is its average rate?", choices: ["30 mph", "60 mph", "90 mph", "540 mph"], answer: 1 },
      { id: "q6", prompt: "What is 0.6 written as a percent?", choices: ["6%", "16%", "60%", "600%"], answer: 2 },
      { id: "q7", prompt: "In a class of 30 students, 18 play a sport. What percent play a sport?", choices: ["40%", "50%", "60%", "80%"], answer: 2 },
      { id: "q8", prompt: "A map scale is 1 inch = 20 miles. How many miles does 3.5 inches represent?", choices: ["23.5", "60", "70", "80"], answer: 2 },
      { id: "q9", prompt: "Which is the better buy?", choices: ["4 pens for $8", "6 pens for $9", "They cost the same per pen", "Not enough information"], answer: 1, explanation: "The unit prices are $2 per pen and $1.50 per pen." },
      { id: "q10", prompt: "What is 15% of 80?", choices: ["8", "12", "15", "20"], answer: 1 },
    ],
  },
  {
    id: "g6-sci-cells",
    subjectId: "science",
    level: "grade6",
    title: "Cells & Body Systems",
    description: "Explore cell structures, specialized cells, and how body systems work together.",
    emoji: "🔬",
    questions: [
      { id: "q1", prompt: "What is the smallest unit of life?", choices: ["Atom", "Cell", "Organ", "Tissue"], answer: 1 },
      { id: "q2", prompt: "Which organelle controls most cell activities and contains DNA?", choices: ["Nucleus", "Cell wall", "Vacuole", "Cytoplasm"], answer: 0 },
      { id: "q3", prompt: "Which structure is found in plant cells but not animal cells?", choices: ["Cell membrane", "Nucleus", "Chloroplast", "Cytoplasm"], answer: 2 },
      { id: "q4", prompt: "What is the main job of mitochondria?", choices: ["Store DNA", "Release usable energy from food", "Make cell walls", "Carry oxygen"], answer: 1 },
      { id: "q5", prompt: "A group of similar cells working together forms a...", choices: ["tissue", "organism", "system", "molecule"], answer: 0 },
      { id: "q6", prompt: "Which body systems work together to deliver oxygen to cells?", choices: ["Digestive and skeletal", "Respiratory and circulatory", "Nervous and muscular", "Skeletal and integumentary"], answer: 1 },
      { id: "q7", prompt: "Why are red blood cells shaped to have a large surface area?", choices: ["To store food", "To carry more oxygen", "To make hormones", "To digest bacteria"], answer: 1 },
      { id: "q8", prompt: "Which level of organization comes directly after tissue?", choices: ["Cell", "Organ", "Organ system", "Organism"], answer: 1 },
      { id: "q9", prompt: "What regulates what enters and leaves a cell?", choices: ["Cell membrane", "Nucleus", "Mitochondrion", "Ribosome"], answer: 0 },
      { id: "q10", prompt: "Photosynthesis occurs mainly in which organelle?", choices: ["Nucleus", "Chloroplast", "Vacuole", "Mitochondrion"], answer: 1 },
    ],
  },
  {
    id: "g6-hist-ancient",
    subjectId: "history",
    level: "grade6",
    title: "Ancient Civilizations",
    description: "Study the rivers, ideas, governments, and achievements that shaped early societies.",
    emoji: "🏺",
    questions: [
      { id: "q1", prompt: "Why did many early civilizations develop near rivers?", choices: ["Rivers blocked all travel", "Rivers provided water and fertile soil", "Rivers prevented farming", "Rivers made the climate colder"], answer: 1 },
      { id: "q2", prompt: "Mesopotamia developed between which two rivers?", choices: ["Nile and Congo", "Tigris and Euphrates", "Indus and Ganges", "Yellow and Yangtze"], answer: 1 },
      { id: "q3", prompt: "What writing system did ancient Egyptians use?", choices: ["Cuneiform", "Hieroglyphics", "Latin", "Sanskrit"], answer: 1 },
      { id: "q4", prompt: "Hammurabi is best known for...", choices: ["a written code of laws", "inventing democracy", "building the Great Wall", "discovering America"], answer: 0 },
      { id: "q5", prompt: "In ancient Athens, citizens participated in an early form of...", choices: ["democracy", "feudalism", "communism", "absolute monarchy"], answer: 0 },
      { id: "q6", prompt: "The Roman Republic influenced modern government through the idea of...", choices: ["elected representatives", "pharaohs", "city-states without laws", "rule by one emperor only"], answer: 0 },
      { id: "q7", prompt: "Which achievement is associated with the Indus Valley civilization?", choices: ["Planned cities and drainage systems", "Roman aqueducts", "Mayan calendars", "Viking longships"], answer: 0 },
      { id: "q8", prompt: "The Silk Road was important because it...", choices: ["connected regions for trade and cultural exchange", "was used only by soldiers", "surrounded Rome", "carried water to farms"], answer: 0 },
      { id: "q9", prompt: "Which Chinese philosophy emphasized respect, duty, and education?", choices: ["Confucianism", "Humanism", "Feudalism", "Mercantilism"], answer: 0 },
      { id: "q10", prompt: "What is a primary source?", choices: ["A modern textbook", "Evidence created during the time being studied", "A fictional story", "A summary written centuries later"], answer: 1 },
    ],
  },
  {
    id: "g6-geo-human-physical",
    subjectId: "geography",
    level: "grade6",
    title: "Physical & Human Geography",
    description: "Connect landforms, climate, resources, migration, and the ways people shape places.",
    emoji: "🌍",
    questions: [
      { id: "q1", prompt: "Which is an example of physical geography?", choices: ["Languages spoken", "Mountain ranges", "Population density", "National borders"], answer: 1 },
      { id: "q2", prompt: "Which is an example of human geography?", choices: ["River valleys", "Climate zones", "Settlement patterns", "Tectonic plates"], answer: 2 },
      { id: "q3", prompt: "Lines of latitude measure distance...", choices: ["east or west of the Prime Meridian", "north or south of the Equator", "above sea level", "between time zones"], answer: 1 },
      { id: "q4", prompt: "What is population density?", choices: ["The total land area", "The number of people per unit of area", "The birth rate only", "The number of cities"], answer: 1 },
      { id: "q5", prompt: "A reason that pushes people to leave a place is called a...", choices: ["pull factor", "push factor", "trade barrier", "natural resource"], answer: 1 },
      { id: "q6", prompt: "Which resource is renewable?", choices: ["Coal", "Oil", "Solar energy", "Natural gas"], answer: 2 },
      { id: "q7", prompt: "A rain shadow commonly forms on which side of a mountain?", choices: ["Windward", "Leeward", "Northern only", "Coastal only"], answer: 1 },
      { id: "q8", prompt: "Why are many large cities located near coasts or rivers?", choices: ["Easier trade and transportation", "No risk of flooding", "Colder weather everywhere", "Fewer natural resources"], answer: 0 },
      { id: "q9", prompt: "A region sharing language, religion, or traditions is a...", choices: ["physical region", "cultural region", "climate zone", "watershed"], answer: 1 },
      { id: "q10", prompt: "What does a map scale help you determine?", choices: ["Actual distance", "Population age", "Climate history", "Political leadership"], answer: 0 },
    ],
  },
];