/** Brainy Buddies - 10th Grade core curriculum activities. */
import type { Activity } from "@/lib/brainy-data";

export const GRADE10_ACTIVITIES: Activity[] = [
  {
    id: "g10-math-geometry-proof",
    subjectId: "math",
    level: "grade10",
    title: "Geometry, Proof & Trigonometry",
    description: "Use deductive reasoning, similarity, circles, and right-triangle trigonometry.",
    emoji: "📐",
    questions: [
      { id: "q1", prompt: "If two parallel lines are cut by a transversal, alternate interior angles are...", choices: ["supplementary only", "congruent", "always right angles", "unrelated"], answer: 1 },
      { id: "q2", prompt: "Which theorem proves two triangles congruent using two sides and the included angle?", choices: ["AAA", "SAS", "SSA", "AAS only"], answer: 1 },
      { id: "q3", prompt: "In a right triangle, sin(theta) equals...", choices: ["adjacent/hypotenuse", "opposite/hypotenuse", "opposite/adjacent", "hypotenuse/opposite"], answer: 1 },
      { id: "q4", prompt: "A circle has radius 5. What is its area?", choices: ["10 pi", "20 pi", "25 pi", "50 pi"], answer: 2 },
      { id: "q5", prompt: "Similar figures have corresponding side lengths that are...", choices: ["equal only", "proportional", "perpendicular", "unrelated"], answer: 1 },
    ],
  },
  {
    id: "g10-sci-chemistry",
    subjectId: "science",
    level: "grade10",
    title: "Chemistry: Reactions & Quantities",
    description: "Connect atomic structure, bonding, moles, reactions, and energy changes.",
    emoji: "🧪",
    questions: [
      { id: "q1", prompt: "One mole contains approximately how many particles?", choices: ["6.02 x 10^23", "9.8", "3.00 x 10^8", "1.60 x 10^-19"], answer: 0 },
      { id: "q2", prompt: "An ionic bond generally forms through...", choices: ["sharing protons", "transfer of electrons", "sharing neutrons", "loss of nuclei"], answer: 1 },
      { id: "q3", prompt: "What does a coefficient in a balanced equation represent?", choices: ["Relative amounts of substances", "Atomic charge", "Temperature", "Reaction speed"], answer: 0 },
      { id: "q4", prompt: "A catalyst speeds a reaction by...", choices: ["raising product mass", "lowering activation energy", "changing equilibrium products", "creating atoms"], answer: 1 },
      { id: "q5", prompt: "Oxidation involves the...", choices: ["gain of electrons", "loss of electrons", "gain of neutrons", "loss of protons"], answer: 1 },
    ],
  },
  {
    id: "g10-hist-modern-global",
    subjectId: "history",
    level: "grade10",
    title: "Global Conflict & Transformation",
    description: "Analyze nationalism, world wars, decolonization, and international institutions.",
    emoji: "🌐",
    questions: [
      { id: "q1", prompt: "Which event directly triggered World War I?", choices: ["The invasion of Poland", "The assassination of Archduke Franz Ferdinand", "The Russian Revolution", "The stock market crash"], answer: 1 },
      { id: "q2", prompt: "Total war affects...", choices: ["only professional soldiers", "military and civilian society", "only national borders", "trade but not politics"], answer: 1 },
      { id: "q3", prompt: "The United Nations was created primarily to...", choices: ["promote international cooperation and peace", "govern every country", "replace all national laws", "control global trade only"], answer: 0 },
      { id: "q4", prompt: "Decolonization refers to...", choices: ["the expansion of empires", "colonies gaining independence", "urban population decline", "the end of industry"], answer: 1 },
      { id: "q5", prompt: "A historian corroborates a claim by...", choices: ["checking it against independent sources", "choosing the longest source", "ignoring context", "using only one witness"], answer: 0 },
    ],
  },
  {
    id: "g10-geo-urbanization",
    subjectId: "geography",
    level: "grade10",
    title: "Urbanization & Spatial Change",
    description: "Evaluate city growth, land use, migration, infrastructure, and sustainable planning.",
    emoji: "🏙️",
    questions: [
      { id: "q1", prompt: "Urban sprawl describes...", choices: ["compact vertical growth", "low-density expansion into surrounding land", "rural population growth only", "declining transportation"], answer: 1 },
      { id: "q2", prompt: "A push factor for migration is...", choices: ["job opportunity", "political instability", "better education", "family reunification"], answer: 1 },
      { id: "q3", prompt: "Public transit can make cities more sustainable by...", choices: ["increasing traffic per rider", "reducing per-person emissions", "requiring more parking", "expanding sprawl"], answer: 1 },
      { id: "q4", prompt: "Gentrification may bring investment while also...", choices: ["displacing longtime residents", "ending all development", "lowering every rent", "eliminating transit"], answer: 0 },
      { id: "q5", prompt: "A topographic map primarily displays...", choices: ["elevation and landform shape", "political parties", "language families", "trade values"], answer: 0 },
    ],
  },
  {
    id: "g10-lang-world-literature",
    subjectId: "language",
    level: "grade10",
    title: "World Literature & Comparative Analysis",
    description: "Compare themes, structures, perspectives, and cultural contexts across texts.",
    emoji: "📚",
    questions: [
      { id: "q1", prompt: "A comparative thesis should...", choices: ["make a defensible claim about meaningful similarities or differences", "summarize two plots", "list quotations", "avoid interpretation"], answer: 0 },
      { id: "q2", prompt: "Cultural context helps readers understand...", choices: ["the values and assumptions surrounding a text", "only punctuation", "the author's handwriting", "the book's price"], answer: 0 },
      { id: "q3", prompt: "An archetype is...", choices: ["a recurring character, symbol, or situation", "a factual error", "a citation style", "a rhyme pattern only"], answer: 0 },
      { id: "q4", prompt: "Juxtaposition places elements together to...", choices: ["highlight contrast or connection", "remove ambiguity", "shorten every sentence", "prove chronology"], answer: 0 },
      { id: "q5", prompt: "Strong textual analysis explains...", choices: ["how evidence supports an interpretation", "only what happened", "whether the reader liked the text", "the author's biography alone"], answer: 0 },
    ],
  },
  {
    id: "g10-python-oop",
    subjectId: "python",
    level: "grade10",
    title: "Python Classes & Program Design",
    description: "Model systems with classes, methods, encapsulation, and modular program structure.",
    emoji: "🐍",
    questions: [
      { id: "q1", prompt: "A class is best described as...", choices: ["a blueprint for objects", "one loop", "a syntax error", "a package installer"], answer: 0 },
      { id: "q2", prompt: "What does __init__ typically do?", choices: ["Initializes a new object's attributes", "Deletes a class", "Imports every module", "Stops iteration"], answer: 0 },
      { id: "q3", prompt: "In an instance method, self refers to...", choices: ["the current object", "the Python interpreter", "all classes", "the parent directory"], answer: 0 },
      { id: "q4", prompt: "Encapsulation helps by...", choices: ["grouping data with related behavior", "making every variable global", "removing functions", "preventing reuse"], answer: 0 },
      { id: "q5", prompt: "Inheritance allows a class to...", choices: ["reuse and extend another class's behavior", "run without code", "avoid all testing", "store only strings"], answer: 0 },
    ],
  },
  {
    id: "g10-sel-transition-balance",
    subjectId: "sel",
    level: "grade10",
    title: "High School Balance & Self-Advocacy",
    description: "Balance commitments, communicate needs, and make sustainable academic choices.",
    emoji: "⚖️",
    questions: [
      { id: "q1", prompt: "Effective self-advocacy begins with...", choices: ["clearly identifying and communicating a need", "waiting for others to guess", "demanding a specific outcome", "avoiding the issue"], answer: 0 },
      { id: "q2", prompt: "A sustainable schedule should include...", choices: ["work, sleep, relationships, and recovery", "work every available hour", "no challenging goals", "identical days"], answer: 0 },
      { id: "q3", prompt: "You are overcommitted. A responsible response is to...", choices: ["review priorities and renegotiate commitments early", "miss deadlines silently", "stop sleeping", "blame teammates"], answer: 0 },
      { id: "q4", prompt: "Burnout often involves prolonged...", choices: ["exhaustion and reduced effectiveness", "curiosity", "short-term excitement", "physical growth"], answer: 0 },
      { id: "q5", prompt: "Asking a teacher for help is most effective when you...", choices: ["describe what you tried and where you are stuck", "say only that nothing works", "wait until after the deadline", "ask someone else to speak for you"], answer: 0 },
    ],
  },
];