/** Age-appropriate Python curriculum for grades 2 through 7. */
import type { Activity } from "@/lib/brainy-data";

export const PYTHON_ACTIVITIES: Activity[] = [
  {
    id: "g2-python-commands",
    subjectId: "python",
    level: "grade2",
    title: "Code in Order",
    description: "Follow simple Python commands one step at a time.",
    emoji: "🐍",
    questions: [
      { id: "q1", prompt: "What does print(\"Hello!\") do?", choices: ["Shows Hello!", "Erases Hello!", "Draws a circle", "Closes Python"], answer: 0, explanation: "print shows a message on the screen." },
      { id: "q2", prompt: "Which command shows the word Cat?", choices: ["print(\"Cat\")", "say Cat", "Cat = print", "show[Cat]"], answer: 0 },
      { id: "q3", prompt: "Python runs these lines from...", choices: ["bottom to top", "top to bottom", "right to left", "random order"], answer: 1 },
      { id: "q4", prompt: "What appears first?\nprint(\"Red\")\nprint(\"Blue\")", choices: ["Blue", "Red", "Both at once", "Nothing"], answer: 1 },
      { id: "q5", prompt: "Words inside quotation marks are called...", choices: ["strings", "loops", "bugs", "numbers"], answer: 0 },
      { id: "q6", prompt: "Which line has matching quotation marks?", choices: ["print(\"Hi\")", "print(\"Hi)", "print(Hi\")", "print Hi"], answer: 0 },
    ],
  },
  {
    id: "g2-python-values",
    subjectId: "python",
    level: "grade2",
    title: "Numbers in Python",
    description: "Let Python add, subtract, and compare small numbers.",
    emoji: "🔢",
    questions: [
      { id: "q1", prompt: "What does print(2 + 3) show?", choices: ["2 + 3", "5", "23", "6"], answer: 1 },
      { id: "q2", prompt: "What does print(7 - 4) show?", choices: ["3", "4", "7", "11"], answer: 0 },
      { id: "q3", prompt: "Which symbol tells Python to add?", choices: ["-", "+", "=", "?"], answer: 1 },
      { id: "q4", prompt: "What does print(3 * 2) show?", choices: ["5", "6", "32", "3"], answer: 1, explanation: "In Python, * means multiply." },
      { id: "q5", prompt: "Which is a number, not a string?", choices: ["\"8\"", "eight", "8", "\"eight\""], answer: 2 },
      { id: "q6", prompt: "What does print(5 == 5) show?", choices: ["True", "False", "10", "5"], answer: 0, explanation: "Two equal signs ask whether two values are equal." },
    ],
  },
  {
    id: "g3-python-variables",
    subjectId: "python",
    level: "grade3",
    title: "Variable Treasure Boxes",
    description: "Store words and numbers in named variables.",
    emoji: "📦",
    questions: [
      { id: "q1", prompt: "score = 5\nWhat value is stored in score?", choices: ["score", "0", "5", "\"5\""], answer: 2 },
      { id: "q2", prompt: "pet = \"Milo\"\nprint(pet) shows...", choices: ["pet", "Milo", "Nothing", "An error"], answer: 1 },
      { id: "q3", prompt: "Which is a clear variable name?", choices: ["x7z", "student_name", "?name", "student name"], answer: 1 },
      { id: "q4", prompt: "stars = 3\nstars = 4\nprint(stars) shows...", choices: ["3", "4", "7", "stars"], answer: 1, explanation: "The newer value replaces the older value." },
      { id: "q5", prompt: "age = 8\nprint(age + 1) shows...", choices: ["8", "9", "81", "age + 1"], answer: 1 },
      { id: "q6", prompt: "Which line stores the word blue?", choices: ["color = \"blue\"", "\"color\" = blue", "color == blue", "print = blue"], answer: 0 },
    ],
  },
  {
    id: "g3-python-turtle-loops",
    subjectId: "python",
    level: "grade3",
    title: "Loops & Turtle Steps",
    description: "Repeat commands to spot patterns and imagine drawings.",
    emoji: "🐢",
    questions: [
      { id: "q1", prompt: "A loop helps a program...", choices: ["repeat steps", "forget steps", "turn off", "change languages"], answer: 0 },
      { id: "q2", prompt: "How many times does this repeat?\nfor step in range(3):", choices: ["1", "2", "3", "4"], answer: 2 },
      { id: "q3", prompt: "What must come after a for line?", choices: ["a colon :", "a question mark ?", "quotation marks", "a plus sign"], answer: 0 },
      { id: "q4", prompt: "Which command would move a turtle ahead?", choices: ["turtle.forward(50)", "turtle.sleep(50)", "forward = turtle", "turtle.color?"], answer: 0 },
      { id: "q5", prompt: "A turtle repeats forward and right 4 times. What shape can it draw?", choices: ["square", "triangle", "circle only", "straight line only"], answer: 0 },
      { id: "q6", prompt: "range(5) gives five counting values starting with...", choices: ["0", "1", "5", "10"], answer: 0 },
    ],
  },
  {
    id: "g4-python-conditionals",
    subjectId: "python",
    level: "grade4",
    title: "Make a Choice with If",
    description: "Use conditions to choose which code should run.",
    emoji: "🚦",
    questions: [
      { id: "q1", prompt: "An if statement runs code when its condition is...", choices: ["True", "a string", "hidden", "always False"], answer: 0 },
      { id: "q2", prompt: "temperature = 80\nIs temperature > 70 True or False?", choices: ["True", "False", "80", "70"], answer: 0 },
      { id: "q3", prompt: "Which keyword handles the other choice?", choices: ["else", "repeat", "print", "input"], answer: 0 },
      { id: "q4", prompt: "What does == mean in a condition?", choices: ["store a value", "is equal to", "add", "not equal to"], answer: 1 },
      { id: "q5", prompt: "score = 9\nif score >= 8:\n    print(\"Great!\")\nWhat appears?", choices: ["Great!", "9", "Nothing", "False"], answer: 0 },
      { id: "q6", prompt: "Why is the print line indented after if?", choices: ["It belongs to the if block", "It is a title", "It is a comment", "Indenting is optional"], answer: 0 },
    ],
  },
  {
    id: "g4-python-loops",
    subjectId: "python",
    level: "grade4",
    title: "Powerful Loops",
    description: "Trace for loops and build repeating patterns.",
    emoji: "🔁",
    questions: [
      { id: "q1", prompt: "How many times does print run?\nfor n in range(4):\n    print(n)", choices: ["3", "4", "5", "Forever"], answer: 1 },
      { id: "q2", prompt: "What values does range(3) produce?", choices: ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "3 only"], answer: 0 },
      { id: "q3", prompt: "What is the last value printed?\nfor n in range(1, 4):\n    print(n)", choices: ["1", "3", "4", "5"], answer: 1 },
      { id: "q4", prompt: "Which loop is best when you know the repeat count?", choices: ["for loop", "if statement", "variable", "comment"], answer: 0 },
      { id: "q5", prompt: "total = 0\nfor n in range(3):\n    total = total + 2\nWhat is total?", choices: ["2", "3", "5", "6"], answer: 3 },
      { id: "q6", prompt: "What does break do inside a loop?", choices: ["stops the loop", "restarts Python", "prints a line", "adds a value"], answer: 0 },
    ],
  },
  {
    id: "g5-python-lists",
    subjectId: "python",
    level: "grade5",
    title: "Lists of Data",
    description: "Create, read, and update ordered collections.",
    emoji: "📋",
    questions: [
      { id: "q1", prompt: "Which value is colors[0]?\ncolors = [\"red\", \"blue\", \"green\"]", choices: ["red", "blue", "green", "0"], answer: 0 },
      { id: "q2", prompt: "Python list positions begin at...", choices: ["0", "1", "-2", "10"], answer: 0 },
      { id: "q3", prompt: "What does colors.append(\"yellow\") do?", choices: ["adds yellow", "removes yellow", "sorts the list", "prints yellow"], answer: 0 },
      { id: "q4", prompt: "What does len([4, 8, 12]) return?", choices: ["2", "3", "12", "24"], answer: 1 },
      { id: "q5", prompt: "Which loop visits every pet?", choices: ["for pet in pets:", "if pet in pets:", "pets = pet", "print for pets"], answer: 0 },
      { id: "q6", prompt: "What is nums[-1] for nums = [2, 4, 6]?", choices: ["2", "4", "6", "-1"], answer: 2, explanation: "Index -1 means the last item." },
    ],
  },
  {
    id: "g5-python-functions",
    subjectId: "python",
    level: "grade5",
    title: "Build a Function",
    description: "Name reusable steps and pass information into them.",
    emoji: "🧰",
    questions: [
      { id: "q1", prompt: "Which keyword begins a function definition?", choices: ["def", "for", "make", "function"], answer: 0 },
      { id: "q2", prompt: "In def greet(name):, name is a...", choices: ["parameter", "loop", "list", "comment"], answer: 0 },
      { id: "q3", prompt: "How do you call a function named cheer?", choices: ["cheer()", "call cheer", "def cheer", "cheer[]"], answer: 0 },
      { id: "q4", prompt: "What does return do?", choices: ["sends a value back", "repeats forever", "deletes the function", "adds a comment"], answer: 0 },
      { id: "q5", prompt: "def double(n):\n    return n * 2\nWhat is double(4)?", choices: ["2", "4", "6", "8"], answer: 3 },
      { id: "q6", prompt: "Why use functions?", choices: ["to reuse organized code", "to avoid all variables", "to make every line repeat", "to remove output"], answer: 0 },
    ],
  },
  {
    id: "g6-python-dictionaries",
    subjectId: "python",
    level: "grade6",
    title: "Dictionaries & Data",
    description: "Connect keys to values and model useful information.",
    emoji: "🗂️",
    questions: [
      { id: "q1", prompt: "student = {\"name\": \"Ava\", \"grade\": 6}\nWhat is student[\"name\"]?", choices: ["student", "name", "Ava", "6"], answer: 2 },
      { id: "q2", prompt: "A dictionary stores...", choices: ["key-value pairs", "only numbers", "only loops", "unnamed values only"], answer: 0 },
      { id: "q3", prompt: "Which creates an empty dictionary?", choices: ["{}", "[]", "()", "\"\""], answer: 0 },
      { id: "q4", prompt: "scores[\"Kai\"] = 10 does what?", choices: ["sets Kai's score to 10", "removes Kai", "prints all scores", "creates a list"], answer: 0 },
      { id: "q5", prompt: "What does data.get(\"missing\", 0) return if the key is absent?", choices: ["missing", "None only", "0", "an error"], answer: 2 },
      { id: "q6", prompt: "Which loop visits dictionary keys?", choices: ["for key in data:", "if key = data:", "data.loop(key)", "while data[key]"], answer: 0 },
    ],
  },
  {
    id: "g6-python-debugging",
    subjectId: "python",
    level: "grade6",
    title: "Debug the Program",
    description: "Read errors, test ideas, and repair common mistakes.",
    emoji: "🛠️",
    questions: [
      { id: "q1", prompt: "A bug is...", choices: ["a mistake in a program", "a Python command", "a saved variable", "a type of loop"], answer: 0 },
      { id: "q2", prompt: "What is wrong with print(\"Hello)?", choices: ["missing closing quote", "print is misspelled", "Hello must be a number", "nothing"], answer: 0 },
      { id: "q3", prompt: "An IndentationError usually means...", choices: ["spaces do not line up correctly", "a number is too large", "the computer is offline", "a list is empty"], answer: 0 },
      { id: "q4", prompt: "What happens with 10 / 0?", choices: ["ZeroDivisionError", "10", "0", "1"], answer: 0 },
      { id: "q5", prompt: "Which is the best first debugging step?", choices: ["read the error message", "delete the whole program", "guess without testing", "add random code"], answer: 0 },
      { id: "q6", prompt: "Why test with small examples?", choices: ["they make behavior easier to check", "they hide every bug", "Python requires it", "they remove variables"], answer: 0 },
    ],
  },
  {
    id: "g7-python-algorithms",
    subjectId: "python",
    level: "grade7",
    title: "Algorithms & Efficiency",
    description: "Design clear steps and compare ways to solve problems.",
    emoji: "🧭",
    questions: [
      { id: "q1", prompt: "An algorithm is...", choices: ["a step-by-step solution", "a Python error", "a single number", "a file name"], answer: 0 },
      { id: "q2", prompt: "Which finds the largest value in nums?", choices: ["max(nums)", "len(nums)", "sum(nums)", "nums.append()"], answer: 0 },
      { id: "q3", prompt: "What is sum([2, 5, 3])?", choices: ["3", "5", "10", "253"], answer: 2 },
      { id: "q4", prompt: "Which expression keeps only even n values?", choices: ["n % 2 == 0", "n / 2", "n == 2", "n % 2 == 1"], answer: 0 },
      { id: "q5", prompt: "Why might a set be useful?", choices: ["it keeps unique values", "it keeps duplicates in order", "it only stores strings", "it runs functions"], answer: 0 },
      { id: "q6", prompt: "A loop checks 1,000 items one by one. About how many checks can it need?", choices: ["1", "10", "100", "1,000"], answer: 3 },
    ],
  },
  {
    id: "g7-python-comprehensions",
    subjectId: "python",
    level: "grade7",
    title: "Transform Data",
    description: "Use expressions, filtering, and comprehensions with care.",
    emoji: "⚙️",
    questions: [
      { id: "q1", prompt: "What is [n * 2 for n in [1, 2, 3]]?", choices: ["[1, 2, 3]", "[2, 4, 6]", "[3, 6]", "6"], answer: 1 },
      { id: "q2", prompt: "What does [n for n in nums if n > 0] keep?", choices: ["positive values", "negative values", "only zero", "all strings"], answer: 0 },
      { id: "q3", prompt: "What is bool(0)?", choices: ["True", "False", "0", "None"], answer: 1 },
      { id: "q4", prompt: "Which condition requires both tests to be true?", choices: ["and", "or", "not", "else"], answer: 0 },
      { id: "q5", prompt: "names = [\"Ada\", \"Lin\"]\nWhat is [name.upper() for name in names]?", choices: ["[\"ada\", \"lin\"]", "[\"ADA\", \"LIN\"]", "[3, 3]", "ADA LIN"], answer: 1 },
      { id: "q6", prompt: "When is a normal loop better than a comprehension?", choices: ["when the logic needs several clear steps", "never", "only for numbers", "when no code should run"], answer: 0 },
    ],
  },
];