/**
 * Brainy Buddies — 3rd Grade activities.
 * Loaded by brainy-data.ts and merged into the ACTIVITIES list.
 */
import type { Activity } from "@/lib/brainy-data";

export const GRADE3_ACTIVITIES: Activity[] = [
    // -------- MATH --------
    {
        id: "g3-math-mult",
        subjectId: "math",
        level: "grade3",
        title: "Multiplication Facts",
        description: "Master times tables from 0 to 10.",
        emoji: "✖️",
        questions: [
            { id: "q1", prompt: "6 × 7 = ?", choices: ["36", "42", "48", "54"], answer: 1, explanation: "6 × 7 = 42. Think: 6 × 6 = 36, then add 6 more." },
            { id: "q2", prompt: "8 × 4 = ?", choices: ["28", "32", "36", "40"], answer: 1 },
            { id: "q3", prompt: "9 × 3 = ?", choices: ["21", "24", "27", "30"], answer: 2 },
            { id: "q4", prompt: "7 × 7 = ?", choices: ["42", "46", "49", "56"], answer: 2 },
            { id: "q5", prompt: "5 × 8 = ?", choices: ["35", "40", "45", "50"], answer: 1 },
            { id: "q6", prompt: "There are 6 boxes with 9 crayons each. How many crayons total?", choices: ["48", "54", "56", "63"], answer: 1 },
            { id: "q7", prompt: "4 × 4 = ?", choices: ["8", "12", "16", "20"], answer: 2 },
            { id: "q8", prompt: "10 × 7 = ?", choices: ["17", "57", "70", "77"], answer: 2 },
            { id: "q9", prompt: "3 × 9 = ?", choices: ["21", "27", "30", "33"], answer: 1 },
            { id: "q10", prompt: "6 × 6 = ?", choices: ["30", "34", "36", "42"], answer: 2 },
            { id: "q11", prompt: "8 × 8 = ?", choices: ["56", "60", "64", "72"], answer: 2 },
            { id: "q12", prompt: "Sam plants 5 rows of flowers with 7 in each row. How many flowers?", choices: ["30", "35", "40", "45"], answer: 1 },
            { id: "q13", prompt: "0 × 99 = ?", choices: ["0", "9", "99", "990"], answer: 0, explanation: "Any number times zero is always zero!" },
            { id: "q14", prompt: "9 × 9 = ?", choices: ["81", "79", "72", "90"], answer: 0, explanation: "9 × 9 = 81." },
            { id: "q15", prompt: "7 × 8 = ?", choices: ["54", "56", "63", "48"], answer: 1 },
            { id: "q16", prompt: "A baker fills 4 trays with 8 muffins each. How many muffins?", choices: ["24", "28", "30", "32"], answer: 3 },
            { id: "q17", prompt: "2 × 10 = ?", choices: ["12", "20", "22", "102"], answer: 1 },
            { id: "q18", prompt: "9 × 4 = ?", choices: ["32", "36", "40", "45"], answer: 1, explanation: "9 × 4 = 36." },
        ],
    },
    {
        id: "g3-math-div",
        subjectId: "math",
        level: "grade3",
        title: "Division Basics",
        description: "Divide fairly and find equal groups.",
        emoji: "➗",
        questions: [
            { id: "q1", prompt: "24 ÷ 6 = ?", choices: ["3", "4", "6", "8"], answer: 1, explanation: "Think: 6 × ? = 24. The answer is 4." },
            { id: "q2", prompt: "36 ÷ 9 = ?", choices: ["3", "4", "5", "6"], answer: 1 },
            { id: "q3", prompt: "42 ÷ 7 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
            { id: "q4", prompt: "18 cookies split equally among 3 friends. Each gets...", choices: ["4", "5", "6", "9"], answer: 2 },
            { id: "q5", prompt: "56 ÷ 8 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
            { id: "q6", prompt: "30 ÷ 5 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
            { id: "q7", prompt: "45 ÷ 9 = ?", choices: ["4", "5", "6", "7"], answer: 1 },
            { id: "q8", prompt: "32 ÷ 4 = ?", choices: ["6", "7", "8", "9"], answer: 2 },
            { id: "q9", prompt: "40 apples shared equally between 8 bags. Each bag has...", choices: ["4", "5", "6", "8"], answer: 1 },
            { id: "q10", prompt: "63 ÷ 7 = ?", choices: ["7", "8", "9", "10"], answer: 2 },
            { id: "q11", prompt: "Which equation is in the same fact family as 4 × 6 = 24?", choices: ["24 ÷ 3", "24 ÷ 4", "24 ÷ 8", "24 ÷ 12"], answer: 1 },
            { id: "q12", prompt: "72 ÷ 8 = ?", choices: ["7", "8", "9", "10"], answer: 2 },
            { id: "q13", prompt: "If you have 0 grapes and put them in 5 groups, each group has...", choices: ["0", "1", "5", "50"], answer: 0 },
            { id: "q14", prompt: "28 ÷ 4 = ?", choices: ["6", "7", "8", "9"], answer: 1 },
            { id: "q15", prompt: "48 ÷ 8 = ?", choices: ["5", "6", "7", "8"], answer: 1 },
            { id: "q16", prompt: "21 ÷ 3 = ?", choices: ["5", "6", "7", "8"], answer: 2 },
            { id: "q17", prompt: "27 crayons are shared into 9 equal groups. Each group has...", choices: ["3", "4", "6", "9"], answer: 0 },
            { id: "q18", prompt: "81 ÷ 9 = ?", choices: ["6", "7", "8", "9"], answer: 3, explanation: "9 × 9 = 81, so 81 ÷ 9 = 9." },
        ],
    },
    {
        id: "g3-math-fractions",
        subjectId: "math",
        level: "grade3",
        title: "Fractions",
        description: "Understand halves, thirds, fourths, and more.",
        emoji: "🍕",
        questions: [
            { id: "q1", prompt: "A pizza is cut into 4 equal slices. You eat 1. What fraction did you eat?", choices: ["1/2", "1/3", "1/4", "4/1"], answer: 2 },
            { id: "q2", prompt: "Which fraction is greater: 1/2 or 1/4?", choices: ["1/4", "1/2", "They are equal", "Can't tell"], answer: 1, explanation: "The larger the denominator, the smaller the piece. 1/2 > 1/4." },
            { id: "q3", prompt: "What is 2/4 equivalent to?", choices: ["1/4", "1/3", "1/2", "2/3"], answer: 2 },
            { id: "q4", prompt: "A pie is cut into 8 equal pieces. 3 are eaten. What fraction is left?", choices: ["3/8", "5/8", "3/5", "5/3"], answer: 1 },
            { id: "q5", prompt: "Which fraction is CLOSEST to 1 whole?", choices: ["1/4", "1/3", "2/3", "3/4"], answer: 3 },
            { id: "q6", prompt: "3/3 equals...", choices: ["0", "1/3", "1", "3"], answer: 2, explanation: "Any fraction where the top and bottom are the same equals 1 whole." },
            { id: "q7", prompt: "A number line goes from 0 to 1. Where does 1/2 go?", choices: ["at 0", "at the middle", "at 1", "past 1"], answer: 1 },
            { id: "q8", prompt: "Which is less than 1/2?", choices: ["2/3", "3/4", "1/3", "5/8"], answer: 2 },
            { id: "q9", prompt: "A ribbon is 6/6 long. What whole number does that equal?", choices: ["0", "1/6", "1", "6"], answer: 2 },
            { id: "q10", prompt: "Order these from smallest to largest: 1/4, 1/2, 1/3", choices: ["1/4, 1/3, 1/2", "1/2, 1/3, 1/4", "1/3, 1/4, 1/2", "1/4, 1/2, 1/3"], answer: 0 },
            { id: "q11", prompt: "Which fraction means one third?", choices: ["1/2", "1/3", "1/4", "3/1"], answer: 1 },
            { id: "q12", prompt: "A chocolate bar has 6 equal pieces. You eat 2. What fraction did you eat?", choices: ["2/6", "4/6", "6/2", "2/4"], answer: 0 },
            { id: "q13", prompt: "Which fraction is the same as one half?", choices: ["2/4", "1/3", "3/4", "1/5"], answer: 0, explanation: "2/4 and 1/2 cover the same amount, so they are equal." },
            { id: "q14", prompt: "One whole pizza is cut into 4 equal slices. How many slices make the whole pizza?", choices: ["2", "3", "4", "8"], answer: 2 },
            { id: "q15", prompt: "Which fraction is bigger: 3/4 or 1/4?", choices: ["1/4", "3/4", "They are equal", "Can't tell"], answer: 1 },
            { id: "q16", prompt: "The bottom number of a fraction is called the...", choices: ["numerator", "denominator", "divisor", "whole"], answer: 1, explanation: "The denominator tells how many equal parts are in the whole." },
            { id: "q17", prompt: "The top number of a fraction is called the...", choices: ["numerator", "denominator", "total", "sum"], answer: 0 },
            { id: "q18", prompt: "Sara colored 4 out of 8 equal boxes. What fraction did she color?", choices: ["4/8", "8/4", "4/4", "1/8"], answer: 0 },
        ],
    },
    {
        id: "g3-math-rounding",
        subjectId: "math",
        level: "grade3",
        title: "Rounding Numbers",
        description: "Round to the nearest 10 and 100.",
        emoji: "🎯",
        questions: [
            { id: "q1", prompt: "Round 47 to the nearest 10.", choices: ["40", "45", "50", "47"], answer: 2, explanation: "47 is closer to 50 than 40. Look at the ones digit: 7 ≥ 5, so round up." },
            { id: "q2", prompt: "Round 83 to the nearest 10.", choices: ["70", "80", "90", "85"], answer: 1 },
            { id: "q3", prompt: "Round 245 to the nearest 100.", choices: ["200", "240", "250", "300"], answer: 0, explanation: "The tens digit is 4 (less than 5), so round down to 200." },
            { id: "q4", prompt: "Round 762 to the nearest 100.", choices: ["700", "760", "770", "800"], answer: 3 },
            { id: "q5", prompt: "Round 35 to the nearest 10.", choices: ["30", "35", "40", "50"], answer: 2, explanation: "When the ones digit is 5, round UP. So 35 → 40." },
            { id: "q6", prompt: "Which number rounds to 500?", choices: ["439", "451", "545", "560"], answer: 1 },
            { id: "q7", prompt: "A school has 478 students. To the nearest 100, about how many?", choices: ["400", "470", "480", "500"], answer: 3 },
            { id: "q8", prompt: "Round 614 to the nearest 10.", choices: ["600", "610", "620", "614"], answer: 1 },
            { id: "q9", prompt: "Round 95 to the nearest 10.", choices: ["80", "90", "95", "100"], answer: 3 },
            { id: "q10", prompt: "Which number rounds to 300 when rounded to the nearest 100?", choices: ["249", "351", "250", "199"], answer: 2, explanation: "250 is exactly halfway — it rounds up to 300." },
            { id: "q11", prompt: "Round 28 to the nearest 10.", choices: ["20", "25", "28", "30"], answer: 3, explanation: "The ones digit is 8 (≥ 5), so round up to 30." },
            { id: "q12", prompt: "Round 52 to the nearest 10.", choices: ["50", "55", "60", "52"], answer: 0 },
            { id: "q13", prompt: "Round 350 to the nearest 100.", choices: ["300", "350", "400", "450"], answer: 2, explanation: "50 is halfway, so round up to 400." },
            { id: "q14", prompt: "Round 199 to the nearest 100.", choices: ["100", "150", "200", "190"], answer: 2 },
            { id: "q15", prompt: "Round 64 to the nearest 10.", choices: ["60", "65", "70", "64"], answer: 0 },
            { id: "q16", prompt: "Which number rounds to 70 when rounded to the nearest 10?", choices: ["63", "66", "61", "60"], answer: 1 },
            { id: "q17", prompt: "Round 805 to the nearest 10.", choices: ["800", "805", "810", "850"], answer: 2 },
            { id: "q18", prompt: "A stadium has 687 seats. To the nearest 100, about how many seats?", choices: ["600", "680", "690", "700"], answer: 3 },
        ],
    },
    {
        id: "g3-math-area",
        subjectId: "math",
        level: "grade3",
        title: "Area & Perimeter",
        description: "Measure the space inside and around shapes.",
        emoji: "📐",
        questions: [
            { id: "q1", prompt: "A rectangle is 4 cm long and 3 cm wide. What is its area?", choices: ["7 cm²", "12 cm²", "14 cm²", "24 cm²"], answer: 1, explanation: "Area = length × width = 4 × 3 = 12 cm²." },
            { id: "q2", prompt: "A square has sides of 5 cm. What is its perimeter?", choices: ["10 cm", "15 cm", "20 cm", "25 cm"], answer: 2, explanation: "Perimeter = 4 × side = 4 × 5 = 20 cm." },
            { id: "q3", prompt: "Perimeter is...", choices: ["the space inside a shape", "the distance around a shape", "height × width", "the number of sides"], answer: 1 },
            { id: "q4", prompt: "A garden is 6 m long and 2 m wide. What is the area?", choices: ["8 m²", "10 m²", "12 m²", "16 m²"], answer: 2 },
            { id: "q5", prompt: "A rectangle has an area of 20 cm² and a length of 5 cm. What is the width?", choices: ["2 cm", "4 cm", "10 cm", "15 cm"], answer: 1 },
            { id: "q6", prompt: "What is the area of a rectangle that is 8 units × 3 units?", choices: ["11 units²", "22 units²", "24 units²", "48 units²"], answer: 2 },
            { id: "q7", prompt: "A square room has 9 square tiles along each side. How many tiles cover the floor?", choices: ["18", "36", "72", "81"], answer: 3 },
            { id: "q8", prompt: "A path is 10 m long and 1 m wide. What is its area?", choices: ["5 m²", "10 m²", "11 m²", "100 m²"], answer: 1 },
            { id: "q9", prompt: "What unit is used to measure area?", choices: ["cm", "cm²", "cm³", "m"], answer: 1 },
            { id: "q10", prompt: "Two rectangles each have an area of 12 cm². They must be the same shape.", choices: ["True — area determines shape", "False — they can have different lengths and widths", "Only true if they are squares", "Only true for rectangles"], answer: 1 },
            { id: "q11", prompt: "A rectangle is 7 cm long and 2 cm wide. What is its area?", choices: ["9 cm²", "14 cm²", "18 cm²", "28 cm²"], answer: 1, explanation: "Area = 7 × 2 = 14 cm²." },
            { id: "q12", prompt: "A rectangle is 5 m long and 4 m wide. What is its perimeter?", choices: ["9 m", "18 m", "20 m", "40 m"], answer: 1, explanation: "Perimeter = 5 + 4 + 5 + 4 = 18 m." },
            { id: "q13", prompt: "A square has sides of 6 cm. What is its area?", choices: ["36 cm²", "12 cm²", "24 cm²", "18 cm²"], answer: 0 },
            { id: "q14", prompt: "Area is the amount of space...", choices: ["around a shape", "inside a shape", "under a shape", "beside a shape"], answer: 1 },
            { id: "q15", prompt: "A rug is 3 m long and 3 m wide. What is its area?", choices: ["12 m²", "6 m²", "18 m²", "9 m²"], answer: 3 },
            { id: "q16", prompt: "A rectangle has an area of 18 cm² and a width of 3 cm. What is its length?", choices: ["3 cm", "9 cm", "6 cm", "15 cm"], answer: 2 },
            { id: "q17", prompt: "A square garden has a perimeter of 16 m. How long is each side?", choices: ["2 m", "4 m", "8 m", "16 m"], answer: 1, explanation: "A square has 4 equal sides: 16 ÷ 4 = 4 m." },
            { id: "q18", prompt: "Which has the larger area: a 2 × 6 rectangle or a 3 × 3 square?", choices: ["the rectangle (12)", "the square (9)", "they are equal", "can't tell"], answer: 0 },
        ],
    },

    // -------- SCIENCE --------
    {
        id: "g3-sci-lifecycle",
        subjectId: "science",
        level: "grade3",
        title: "Life Cycles",
        description: "How plants and animals grow and change.",
        emoji: "🦋",
        questions: [
            { id: "q1", prompt: "What are the 4 stages of a butterfly's life cycle in order?", choices: ["egg, caterpillar, cocoon, butterfly", "egg, pupa, larva, butterfly", "larva, egg, pupa, adult", "cocoon, egg, larva, adult"], answer: 0 },
            { id: "q2", prompt: "A frog's life cycle goes: egg → tadpole → froglet → ?", choices: ["caterpillar", "pupa", "adult frog", "larva"], answer: 2 },
            { id: "q3", prompt: "What do we call the stage when a caterpillar is inside a chrysalis?", choices: ["larva", "pupa", "egg", "nymph"], answer: 1 },
            { id: "q4", prompt: "Which plant part contains the seed?", choices: ["leaf", "root", "stem", "fruit"], answer: 3 },
            { id: "q5", prompt: "A complete change in body form during a life cycle is called...", choices: ["hibernation", "metamorphosis", "germination", "migration"], answer: 1 },
            { id: "q6", prompt: "A grasshopper's life cycle has 3 stages: egg, nymph, adult. This is called...", choices: ["complete metamorphosis", "incomplete metamorphosis", "germination", "pollination"], answer: 1 },
            { id: "q7", prompt: "Which of the following shows plant germination?", choices: ["a leaf turning orange", "a seed sprouting into a seedling", "a flower making pollen", "roots soaking up water"], answer: 1 },
            { id: "q8", prompt: "Animals that lay eggs include...", choices: ["only birds", "only fish", "birds and reptiles and fish", "all animals"], answer: 2 },
            { id: "q9", prompt: "What is the first stage of a butterfly's life cycle?", choices: ["larva", "pupa", "egg", "adult"], answer: 2 },
            { id: "q10", prompt: "Seeds need ___ and ___ to germinate.", choices: ["light and wind", "water and warmth", "soil and insects", "cold and ice"], answer: 1 },
            { id: "q11", prompt: "Which animal hatches from an egg?", choices: ["dog", "chicken", "cat", "horse"], answer: 1 },
            { id: "q12", prompt: "A young plant that has just sprouted from a seed is called a...", choices: ["seedling", "flower", "fruit", "root"], answer: 0 },
            { id: "q13", prompt: "Which part of a plant takes in water from the soil?", choices: ["leaves", "flower", "roots", "fruit"], answer: 2 },
            { id: "q14", prompt: "Bees help plants by carrying pollen from flower to flower. This is called...", choices: ["germination", "pollination", "migration", "digestion"], answer: 1, explanation: "Pollination helps plants make seeds and fruit." },
            { id: "q15", prompt: "Which life stage comes right after the egg in a butterfly's life cycle?", choices: ["adult", "pupa", "caterpillar", "cocoon"], answer: 2 },
            { id: "q16", prompt: "Which animals usually have live babies instead of laying eggs?", choices: ["fish", "frogs", "dogs and cats", "birds"], answer: 2 },
            { id: "q17", prompt: "A young frog that lives in water and has a tail is a...", choices: ["tadpole", "nymph", "larva", "pupa"], answer: 0 },
            { id: "q18", prompt: "What do plants need from the sun in order to grow?", choices: ["soil", "light and energy", "water", "wind"], answer: 1 },
        ],
    },
    {
        id: "g3-sci-ecosystems",
        subjectId: "science",
        level: "grade3",
        title: "Ecosystems & Food Chains",
        description: "How living things depend on each other.",
        emoji: "🌿",
        questions: [
            { id: "q1", prompt: "In a food chain, what do plants use to make their own food?", choices: ["other animals", "sunlight", "meat", "rocks"], answer: 1 },
            { id: "q2", prompt: "A food chain starts with a...", choices: ["predator", "carnivore", "producer", "decomposer"], answer: 2, explanation: "Producers (plants) capture energy from the sun — they're always first." },
            { id: "q3", prompt: "What do decomposers do?", choices: ["eat plants", "eat animals", "break down dead things into soil", "make food from sunlight"], answer: 2 },
            { id: "q4", prompt: "In the chain: grass → rabbit → fox, the fox is a...", choices: ["producer", "primary consumer", "secondary consumer", "decomposer"], answer: 2 },
            { id: "q5", prompt: "What would most likely happen if all the rabbits disappeared from a meadow?", choices: ["foxes would have more food", "grass would grow less", "foxes would struggle to find food", "plants would die"], answer: 2 },
            { id: "q6", prompt: "An ecosystem includes...", choices: ["only living things", "only non-living things", "both living and non-living things", "only animals"], answer: 2 },
            { id: "q7", prompt: "Mushrooms that break down a fallen log are examples of...", choices: ["producers", "predators", "consumers", "decomposers"], answer: 3 },
            { id: "q8", prompt: "Which shows a correct food chain?", choices: ["fox → rabbit → grass", "grass → rabbit → fox", "rabbit → fox → grass", "sun → fox → grass"], answer: 1 },
            { id: "q9", prompt: "An animal that eats only meat is a...", choices: ["herbivore", "omnivore", "carnivore", "producer"], answer: 2 },
            { id: "q10", prompt: "Why do food chains always start with a plant?", choices: ["plants taste best", "plants can make their own food using sunlight", "animals cannot eat plants", "plants move fast"], answer: 1 },
            { id: "q11", prompt: "An animal that eats only plants is a...", choices: ["carnivore", "herbivore", "decomposer", "producer"], answer: 1 },
            { id: "q12", prompt: "An animal that eats both plants and animals is an...", choices: ["omnivore", "herbivore", "carnivore", "producer"], answer: 0 },
            { id: "q13", prompt: "In a desert ecosystem, a cactus that makes its own food is a...", choices: ["producer", "consumer", "decomposer", "predator"], answer: 0 },
            { id: "q14", prompt: "An animal that hunts other animals for food is a...", choices: ["prey", "producer", "predator", "decomposer"], answer: 2 },
            { id: "q15", prompt: "An animal that is hunted and eaten by another animal is called...", choices: ["predator", "prey", "producer", "decomposer"], answer: 1 },
            { id: "q16", prompt: "Where does almost all the energy in a food chain come from?", choices: ["the sun", "the soil", "the water", "the wind"], answer: 0 },
            { id: "q17", prompt: "In the chain grass → grasshopper → bird, the grasshopper is a...", choices: ["producer", "primary consumer", "secondary consumer", "decomposer"], answer: 1 },
            { id: "q18", prompt: "Earthworms help an ecosystem by...", choices: ["scaring predators", "hunting mice", "breaking down dead plants to make soil rich", "eating sunlight"], answer: 2 },
        ],
    },
    {
        id: "g3-sci-matter",
        subjectId: "science",
        level: "grade3",
        title: "States of Matter",
        description: "Solids, liquids, gases, and how they change.",
        emoji: "⚗️",
        questions: [
            { id: "q1", prompt: "What are the three common states of matter?", choices: ["hot, cold, warm", "solid, liquid, gas", "rock, water, air", "ice, water, steam"], answer: 1 },
            { id: "q2", prompt: "When liquid water turns into ice it is called...", choices: ["melting", "evaporation", "freezing", "condensation"], answer: 2 },
            { id: "q3", prompt: "When ice turns into liquid water it is called...", choices: ["freezing", "melting", "boiling", "evaporation"], answer: 1 },
            { id: "q4", prompt: "Which property describes how heavy something is?", choices: ["volume", "mass", "texture", "color"], answer: 1 },
            { id: "q5", prompt: "A gas...", choices: ["has a definite shape and volume", "has a definite shape but not volume", "has no definite shape or volume", "is always invisible"], answer: 2 },
            { id: "q6", prompt: "Steam is water in which state?", choices: ["solid", "liquid", "gas", "plasma"], answer: 2 },
            { id: "q7", prompt: "What happens to most solids when they are heated?", choices: ["they freeze", "they turn into liquid", "they disappear", "they get heavier"], answer: 1 },
            { id: "q8", prompt: "A liquid...", choices: ["has a definite shape", "takes the shape of its container", "always floats", "cannot be poured"], answer: 1 },
            { id: "q9", prompt: "Which is an example of a solid?", choices: ["juice", "air", "rock", "steam"], answer: 2 },
            { id: "q10", prompt: "When liquid water evaporates, it becomes...", choices: ["ice", "a gas", "heavier", "a rock"], answer: 1 },
            { id: "q11", prompt: "Which of these is a gas at room temperature?", choices: ["ice", "wood", "air", "milk"], answer: 2 },
            { id: "q12", prompt: "When water vapor in the air cools and turns back into liquid, it is called...", choices: ["melting", "condensation", "freezing", "evaporation"], answer: 1, explanation: "Condensation is why dew forms on grass in the morning." },
            { id: "q13", prompt: "Which state of matter keeps its own shape?", choices: ["solid", "liquid", "gas", "all of them"], answer: 0 },
            { id: "q14", prompt: "When boiling turns liquid water into a gas, this change is called...", choices: ["freezing", "melting", "evaporation", "condensation"], answer: 2 },
            { id: "q15", prompt: "Matter is anything that has mass and takes up...", choices: ["color", "space", "heat", "sound"], answer: 1 },
            { id: "q16", prompt: "Which can be poured and takes the shape of its container?", choices: ["a brick", "a liquid", "a balloon", "a rock"], answer: 1 },
            { id: "q17", prompt: "Adding heat to an ice cube will cause it to...", choices: ["freeze harder", "melt", "get colder", "stay the same"], answer: 1 },
            { id: "q18", prompt: "What change happens when you put liquid water in the freezer?", choices: ["it evaporates", "it boils", "it freezes into a solid", "it becomes a gas"], answer: 2 },
        ],
    },
    {
        id: "g3-sci-forces",
        subjectId: "science",
        level: "grade3",
        title: "Forces & Motion",
        description: "Pushes, pulls, and how objects move.",
        emoji: "🚀",
        questions: [
            { id: "q1", prompt: "A force is...", choices: ["always a push", "a push or a pull", "only made by machines", "only gravity"], answer: 1 },
            { id: "q2", prompt: "What force pulls objects toward Earth?", choices: ["magnetism", "friction", "gravity", "electricity"], answer: 2 },
            { id: "q3", prompt: "Friction is a force that...", choices: ["speeds things up", "pulls things down", "slows things down", "pushes things sideways"], answer: 2 },
            { id: "q4", prompt: "Which surface would create the MOST friction?", choices: ["ice", "sandpaper", "smooth glass", "polished wood"], answer: 1 },
            { id: "q5", prompt: "When two equal forces push in opposite directions, the object...", choices: ["speeds up", "slows down", "does not move", "spins in circles"], answer: 2 },
            { id: "q6", prompt: "A ball rolling across the floor slows down because of...", choices: ["gravity", "friction", "magnets", "wind"], answer: 1 },
            { id: "q7", prompt: "Which of these uses a magnet?", choices: ["a paper towel", "a rubber eraser", "a compass", "a glass of water"], answer: 2 },
            { id: "q8", prompt: "Magnets attract objects made of...", choices: ["plastic", "iron and steel", "wood", "rubber"], answer: 1 },
            { id: "q9", prompt: "What happens when you apply a larger force to push an object?", choices: ["it moves slower", "it moves faster", "it stays still", "it shrinks"], answer: 1 },
            { id: "q10", prompt: "Two magnets facing north pole to north pole will...", choices: ["attract each other", "repel each other", "stick together", "spin in circles"], answer: 1 },
            { id: "q11", prompt: "A push or a pull that can start an object moving is called a...", choices: ["force", "color", "sound", "shadow"], answer: 0 },
            { id: "q12", prompt: "What makes a bike slow down after you stop pedaling?", choices: ["gravity pulling it up", "friction with the ground and air", "magnets", "sunlight"], answer: 1 },
            { id: "q13", prompt: "If you drop a ball, gravity pulls it...", choices: ["up", "sideways", "down", "in circles"], answer: 2 },
            { id: "q14", prompt: "The two ends of a magnet are called its...", choices: ["poles", "sides", "tips", "arms"], answer: 0 },
            { id: "q15", prompt: "Opposite poles of two magnets (N and S) will...", choices: ["repel", "attract", "explode", "disappear"], answer: 1 },
            { id: "q16", prompt: "To make a heavy box easier to slide across the floor, you could reduce...", choices: ["friction", "gravity", "its color", "the air"], answer: 0 },
            { id: "q17", prompt: "Which one needs MORE force to start it moving?", choices: ["a box full of books", "an empty box", "a feather", "a balloon"], answer: 0 },
            { id: "q18", prompt: "A rolling ball would keep going forever unless a force like ___ slows it down.", choices: ["light", "friction", "color", "sound"], answer: 1 },
        ],
    },
    {
        id: "g3-sci-elements",
        subjectId: "science",
        level: "grade3",
        title: "Periodic Table Basics",
        description: "Explore elements, their symbols, and what makes them special.",
        emoji: "🧪",
        questions: [
            { id: "q1", prompt: "The Periodic Table is a chart that organizes all known...", choices: ["animals", "planets", "elements", "molecules"], answer: 2, explanation: "There are 118 known elements organized on the periodic table." },
            { id: "q2", prompt: "What number is Hydrogen (H) on the periodic table?", choices: ["1", "2", "6", "8"], answer: 0, explanation: "Hydrogen is element #1 — the lightest and most common element in the universe." },
            { id: "q3", prompt: "What is the symbol for Oxygen?", choices: ["Ox", "Og", "O", "Om"], answer: 2 },
            { id: "q4", prompt: "Carbon's symbol is 'C'. Carbon is the element that makes up...", choices: ["water", "air", "all living things", "rocks only"], answer: 2, explanation: "Carbon is the backbone of all life on Earth — found in every living organism." },
            { id: "q5", prompt: "Noble gases (like Helium and Neon) are special because they...", choices: ["are very heavy", "rarely react with other elements", "always melt at high temperatures", "are all solid at room temperature"], answer: 1, explanation: "Noble gases are very stable — they don't easily bond with other elements." },
            { id: "q6", prompt: "The element with the symbol 'Na' is...", choices: ["Nitrogen", "Neon", "Sodium", "Nickel"], answer: 2, explanation: "Na comes from 'Natrium' — the Latin name for Sodium." },
            { id: "q7", prompt: "Metals like gold and silver are generally...", choices: ["dull and breakable", "shiny and conduct electricity", "gases at room temperature", "lighter than air"], answer: 1 },
            { id: "q8", prompt: "The number of protons in an atom tells us its...", choices: ["mass number", "atomic number", "charge", "state of matter"], answer: 1, explanation: "Every element has a unique atomic number equal to its proton count." },
            { id: "q9", prompt: "What is the symbol for the element Calcium?", choices: ["Ca", "C", "Cm", "Co"], answer: 0, explanation: "Calcium (Ca) is element 20. Your bones and teeth are mostly calcium!" },
            { id: "q10", prompt: "Neon signs glow because the element Neon...", choices: ["is magnetic", "glows when electricity passes through it", "burns very hot", "reflects sunlight"], answer: 1 },
            { id: "q11", prompt: "Which of these is a metal?", choices: ["Oxygen", "Nitrogen", "Chlorine", "Iron"], answer: 3, explanation: "Iron (Fe) is a metal — it's magnetic and found in steel." },
            { id: "q12", prompt: "The element Helium has 2 protons. What is its atomic number?", choices: ["1", "2", "4", "6"], answer: 1 },
            { id: "q13", prompt: "What is the symbol for the element Gold?", choices: ["Go", "Gd", "Au", "Ga"], answer: 2, explanation: "Au comes from 'aurum', the Latin word for gold." },
            { id: "q14", prompt: "Which gas do humans need to breathe in to stay alive?", choices: ["Helium", "Oxygen", "Neon", "Hydrogen"], answer: 1 },
            { id: "q15", prompt: "The element with the symbol 'Fe' is...", choices: ["Iron", "Fluorine", "Francium", "Lead"], answer: 0, explanation: "Fe comes from 'ferrum', the Latin word for iron." },
            { id: "q16", prompt: "The tiny particles that make up all matter are called...", choices: ["cells", "atoms", "crystals", "grains"], answer: 1 },
            { id: "q17", prompt: "Which element is used to fill balloons and makes them float?", choices: ["Helium", "Oxygen", "Carbon", "Iron"], answer: 0 },
            { id: "q18", prompt: "What is the symbol for the element Hydrogen?", choices: ["He", "Hy", "H", "Hd"], answer: 2 },
        ],
    },

    // -------- HISTORY --------
    {
        id: "g3-hist-america",
        subjectId: "history",
        level: "grade3",
        title: "American Symbols & Heroes",
        description: "Famous people and symbols of the United States.",
        emoji: "🦅",
        questions: [
            { id: "q1", prompt: "Who was the first President of the United States?", choices: ["Abraham Lincoln", "George Washington", "Benjamin Franklin", "Thomas Jefferson"], answer: 1 },
            { id: "q2", prompt: "Abraham Lincoln helped end...", choices: ["World War I", "the Civil War and slavery", "the American Revolution", "the Great Depression"], answer: 1 },
            { id: "q3", prompt: "The Statue of Liberty is a symbol of...", choices: ["war", "freedom and welcome", "the president", "the military"], answer: 1 },
            { id: "q4", prompt: "Martin Luther King Jr. is famous for...", choices: ["winning a war", "inventing the telephone", "fighting for equal rights for all people", "becoming the first president"], answer: 2 },
            { id: "q5", prompt: "The national bird of the United States is the...", choices: ["robin", "owl", "bald eagle", "dove"], answer: 2 },
            { id: "q6", prompt: "The Declaration of Independence was signed in...", choices: ["1620", "1776", "1865", "1900"], answer: 1 },
            { id: "q7", prompt: "Who wrote the Declaration of Independence?", choices: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"], answer: 2 },
            { id: "q8", prompt: "The American flag has how many stripes?", choices: ["10", "13", "15", "50"], answer: 1, explanation: "13 stripes represent the original 13 colonies." },
            { id: "q9", prompt: "What does the Pledge of Allegiance honor?", choices: ["the president", "the army", "the flag and the country", "the Constitution"], answer: 2 },
            { id: "q10", prompt: "Susan B. Anthony fought for women's right to...", choices: ["go to school", "own land", "vote", "work"], answer: 2 },
            { id: "q11", prompt: "Independence Day is celebrated on...", choices: ["June 4th", "July 4th", "September 17th", "November 11th"], answer: 1 },
            { id: "q12", prompt: "Who led the colonists in fighting for independence from Britain?", choices: ["Abraham Lincoln", "George Washington", "Thomas Edison", "Benjamin Franklin"], answer: 1 },
            { id: "q13", prompt: "The Liberty Bell is a famous symbol located in which city?", choices: ["Boston", "Philadelphia", "New York City", "Washington, D.C."], answer: 1 },
            { id: "q14", prompt: "How many stars are on the American flag today?", choices: ["13", "48", "50", "52"], answer: 2, explanation: "There is one star for each of the 50 states." },
            { id: "q15", prompt: "Who is famous for a midnight ride to warn that the British soldiers were coming?", choices: ["Paul Revere", "George Washington", "Thomas Edison", "John Adams"], answer: 0 },
            { id: "q16", prompt: "Rosa Parks is remembered for bravely standing up for equal rights by...", choices: ["flying a plane", "refusing to give up her bus seat", "writing the Constitution", "leading an army"], answer: 1 },
            { id: "q17", prompt: "The White House is the home of the...", choices: ["governor", "mayor", "President", "Supreme Court"], answer: 2 },
            { id: "q18", prompt: "Which document begins with the words 'We the People'?", choices: ["the Declaration of Independence", "the U.S. Constitution", "the Gettysburg Address", "the Pledge of Allegiance"], answer: 1, explanation: "The U.S. Constitution opens with 'We the People.'" },
        ],
    },
    {
        id: "g3-hist-communities",
        subjectId: "history",
        level: "grade3",
        title: "Communities & Government",
        description: "How communities are organized and governed.",
        emoji: "🏛️",
        questions: [
            { id: "q1", prompt: "The leader of a city is usually called the...", choices: ["president", "governor", "mayor", "senator"], answer: 2 },
            { id: "q2", prompt: "The leader of a U.S. state is called the...", choices: ["mayor", "governor", "president", "senator"], answer: 1 },
            { id: "q3", prompt: "The leader of the United States is the...", choices: ["mayor", "governor", "king", "president"], answer: 3 },
            { id: "q4", prompt: "Laws are rules that...", choices: ["only teachers follow", "everyone must follow", "only adults follow", "only the president follows"], answer: 1 },
            { id: "q5", prompt: "What do we call the basic rules that govern the United States?", choices: ["the Declaration", "the Constitution", "the Bill of Laws", "the Pledge"], answer: 1 },
            { id: "q6", prompt: "Citizens can choose their leaders by...", choices: ["writing letters", "voting", "marching", "paying taxes"], answer: 1 },
            { id: "q7", prompt: "A community is...", choices: ["a single family", "only a city", "a group of people who live and work near each other", "a school"], answer: 2 },
            { id: "q8", prompt: "Which is a community helper?", choices: ["a firefighter", "a volcano", "a rainstorm", "a mountain"], answer: 0 },
            { id: "q9", prompt: "The three branches of the U.S. government are legislative, executive, and...", choices: ["local", "judicial", "state", "community"], answer: 1 },
            { id: "q10", prompt: "The U.S. Congress makes...", choices: ["movies", "laws", "food", "weather"], answer: 1 },
            { id: "q11", prompt: "Paying taxes helps a community pay for things like...", choices: ["video games", "schools, roads, and libraries", "family vacations", "toys"], answer: 1 },
            { id: "q12", prompt: "A good citizen shows responsibility by...", choices: ["littering", "following rules and helping others", "skipping voting", "ignoring laws"], answer: 1 },
            { id: "q13", prompt: "Which person helps keep a community safe?", choices: ["a police officer", "a cloud", "a river", "a mountain"], answer: 0 },
            { id: "q14", prompt: "The judicial branch of government is in charge of...", choices: ["making laws", "courts and deciding if laws are followed fairly", "leading the army", "printing money"], answer: 1 },
            { id: "q15", prompt: "The President of the United States leads which branch of government?", choices: ["legislative", "judicial", "executive", "local"], answer: 2 },
            { id: "q16", prompt: "A right that citizens have is the freedom to...", choices: ["break laws", "speak their opinion", "take others' things", "skip school forever"], answer: 1 },
            { id: "q17", prompt: "What do we call a rule made by a government that everyone must follow?", choices: ["a law", "a wish", "a hobby", "a game"], answer: 0 },
            { id: "q18", prompt: "Voting is one important way that citizens can...", choices: ["choose their leaders", "build roads", "fight fires", "grow food"], answer: 0 },
        ],
    },

    // -------- GEOGRAPHY --------
    {
        id: "g3-geo-usmap",
        subjectId: "geography",
        level: "grade3",
        title: "U.S. Map & Regions",
        description: "States, capitals, and regions of the United States.",
        emoji: "🗺️",
        questions: [
            { id: "q1", prompt: "How many states are in the United States?", choices: ["48", "49", "50", "52"], answer: 2 },
            { id: "q2", prompt: "What is the capital of the United States?", choices: ["New York City", "Los Angeles", "Washington D.C.", "Chicago"], answer: 2 },
            { id: "q3", prompt: "The largest state by area is...", choices: ["Texas", "California", "Alaska", "Montana"], answer: 2 },
            { id: "q4", prompt: "Hawaii is located...", choices: ["next to California", "in the Pacific Ocean", "in the Atlantic Ocean", "near Florida"], answer: 1 },
            { id: "q5", prompt: "Which ocean is on the East Coast of the United States?", choices: ["Pacific Ocean", "Arctic Ocean", "Indian Ocean", "Atlantic Ocean"], answer: 3 },
            { id: "q6", prompt: "Which ocean is on the West Coast of the United States?", choices: ["Pacific Ocean", "Arctic Ocean", "Indian Ocean", "Atlantic Ocean"], answer: 0 },
            { id: "q7", prompt: "Which of these is a U.S. state?", choices: ["Ontario", "Quebec", "Texas", "Mexico City"], answer: 2 },
            { id: "q8", prompt: "The Great Plains region of the U.S. is known for...", choices: ["mountains", "flat farming land", "tropical forests", "deserts"], answer: 1 },
            { id: "q9", prompt: "What country is north of the United States?", choices: ["Mexico", "Cuba", "Canada", "Brazil"], answer: 2 },
            { id: "q10", prompt: "What country is south of the United States?", choices: ["Canada", "Brazil", "Mexico", "Peru"], answer: 2 },
            { id: "q11", prompt: "The Mississippi River flows from north to south through the...", choices: ["East Coast", "West Coast", "middle of the country", "Great Plains"], answer: 2 },
            { id: "q12", prompt: "Which state is famous for sunny beaches and is in the southeast corner of the U.S.?", choices: ["Florida", "Maine", "Oregon", "Ohio"], answer: 0 },
            { id: "q13", prompt: "The Rocky Mountains are found in which part of the United States?", choices: ["the East", "the South", "the West", "the Midwest"], answer: 2 },
            { id: "q14", prompt: "Which state is in the far northwest and is separated from the rest of the U.S. by Canada?", choices: ["Alaska", "Hawaii", "Texas", "Florida"], answer: 0 },
            { id: "q15", prompt: "Texas is located in which region of the United States?", choices: ["Northeast", "South", "Pacific Northwest", "New England"], answer: 1 },
            { id: "q16", prompt: "Which of these is NOT a U.S. state?", choices: ["California", "Nevada", "Toronto", "Arizona"], answer: 2 },
            { id: "q17", prompt: "The 50th state to join the United States was...", choices: ["Hawaii", "Alaska", "Arizona", "Texas"], answer: 0, explanation: "Hawaii became the 50th state in 1959." },
            { id: "q18", prompt: "Which river forms part of the border between Texas and Mexico?", choices: ["the Mississippi River", "the Rio Grande", "the Hudson River", "the Colorado River"], answer: 1 },
        ],
    },
    {
        id: "g3-geo-world",
        subjectId: "geography",
        level: "grade3",
        title: "Continents & Oceans",
        description: "Name and locate the 7 continents and 5 oceans.",
        emoji: "🌎",
        questions: [
            { id: "q1", prompt: "How many continents are there?", choices: ["5", "6", "7", "8"], answer: 2 },
            { id: "q2", prompt: "How many oceans are there?", choices: ["4", "5", "6", "7"], answer: 1 },
            { id: "q3", prompt: "The largest continent is...", choices: ["Africa", "North America", "Asia", "Europe"], answer: 2 },
            { id: "q4", prompt: "The smallest continent is...", choices: ["Europe", "Australia", "Antarctica", "South America"], answer: 1 },
            { id: "q5", prompt: "Which continent is mostly covered by ice?", choices: ["Africa", "Australia", "Antarctica", "Europe"], answer: 2 },
            { id: "q6", prompt: "The Amazon rainforest is in...", choices: ["Africa", "Asia", "North America", "South America"], answer: 3 },
            { id: "q7", prompt: "What is the largest ocean?", choices: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], answer: 2 },
            { id: "q8", prompt: "Europe and Asia are on the same landmass. Together they are called...", choices: ["Afro-Eurasia", "Eurasia", "The Old World", "The Supercontinent"], answer: 1 },
            { id: "q9", prompt: "The Sahara Desert is in...", choices: ["Asia", "Africa", "Australia", "South America"], answer: 1 },
            { id: "q10", prompt: "Which continent is the United States part of?", choices: ["South America", "Europe", "North America", "Asia"], answer: 2 },
            { id: "q11", prompt: "The Nile River is in...", choices: ["Asia", "Europe", "South America", "Africa"], answer: 3 },
            { id: "q12", prompt: "Which continent is directly south of Europe, across the Mediterranean Sea?", choices: ["Asia", "Africa", "Australia", "Antarctica"], answer: 1 },
            { id: "q13", prompt: "Australia is special because it is both a country and a...", choices: ["city", "continent", "ocean", "river"], answer: 1 },
            { id: "q14", prompt: "Which ocean is the smallest and coldest, found at the very top of the Earth?", choices: ["Pacific Ocean", "Atlantic Ocean", "Arctic Ocean", "Indian Ocean"], answer: 2 },
            { id: "q15", prompt: "The continent of Antarctica is found at the...", choices: ["equator", "North Pole", "South Pole", "middle of Asia"], answer: 2 },
            { id: "q16", prompt: "Which ocean separates North America from Europe?", choices: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], answer: 1 },
            { id: "q17", prompt: "Which continent has countries like Egypt, Kenya, and Nigeria?", choices: ["Asia", "Europe", "Africa", "South America"], answer: 2 },
            { id: "q18", prompt: "The imaginary line around the middle of the Earth is called the...", choices: ["equator", "border", "North Pole", "prime line"], answer: 0 },
        ],
    },
    {
        id: "g3-geo-maps",
        subjectId: "geography",
        level: "grade3",
        title: "Reading Maps",
        description: "Keys, compass roses, latitude, and longitude.",
        emoji: "🧭",
        questions: [
            { id: "q1", prompt: "The cardinal directions are...", choices: ["up, down, left, right", "north, south, east, west", "front, back, side, top", "positive, negative, zero, one"], answer: 1 },
            { id: "q2", prompt: "A map key (legend) tells you...", choices: ["how old the map is", "what the symbols on the map mean", "who made the map", "the distance between places"], answer: 1 },
            { id: "q3", prompt: "A compass rose shows...", choices: ["the size of a place", "directions on a map", "the weather", "the population"], answer: 1 },
            { id: "q4", prompt: "Lines on a map that run east-west and measure distance from the equator are called...", choices: ["longitudes", "latitudes", "meridians", "borders"], answer: 1 },
            { id: "q5", prompt: "The equator divides Earth into the Northern and...", choices: ["Eastern Hemisphere", "Western Hemisphere", "Southern Hemisphere", "Pacific Hemisphere"], answer: 2 },
            { id: "q6", prompt: "A scale on a map shows you...", choices: ["what colors mean", "how to read directions", "the real distance a map distance represents", "where water is"], answer: 2 },
            { id: "q7", prompt: "If you travel from New York to California, you are traveling...", choices: ["north", "south", "east", "west"], answer: 3 },
            { id: "q8", prompt: "A physical map shows...", choices: ["country borders only", "landforms like mountains and rivers", "only roads", "city populations"], answer: 1 },
            { id: "q9", prompt: "A political map shows...", choices: ["mountains and rivers", "weather patterns", "countries, states, and borders", "wildlife"], answer: 2 },
            { id: "q10", prompt: "The North Pole is at the very...", choices: ["bottom of Earth", "middle of Earth", "top of Earth", "side of Earth"], answer: 2 },
            { id: "q11", prompt: "On most maps, which direction is at the top?", choices: ["south", "north", "east", "west"], answer: 1 },
            { id: "q12", prompt: "The direction halfway between north and east is called...", choices: ["northeast", "northwest", "southeast", "southwest"], answer: 0 },
            { id: "q13", prompt: "A small tree symbol on a map probably stands for a...", choices: ["city", "forest or park", "river", "road"], answer: 1 },
            { id: "q14", prompt: "Blue areas on most maps usually show...", choices: ["mountains", "deserts", "water", "cities"], answer: 2 },
            { id: "q15", prompt: "A globe is a model of Earth shaped like a...", choices: ["square", "flat sheet", "sphere (ball)", "triangle"], answer: 2 },
            { id: "q16", prompt: "Which direction is the OPPOSITE of east?", choices: ["north", "south", "west", "up"], answer: 2 },
            { id: "q17", prompt: "Lines that run north-south and measure distance east or west are called...", choices: ["latitude", "longitude", "the equator", "borders"], answer: 1 },
            { id: "q18", prompt: "To find the real distance between two cities on a map, you use the map's...", choices: ["map key", "compass rose", "scale", "title"], answer: 2 },
        ],
    },
    {
        id: "g3-geo-landforms",
        subjectId: "geography",
        level: "grade3",
        title: "Landforms",
        description: "Mountains, valleys, plains, plateaus, islands, and more.",
        emoji: "🏔️",
        questions: [
            { id: "q1", prompt: "A large area of flat, level land is called a...", choices: ["mountain", "plain", "valley", "cliff"], answer: 1 },
            { id: "q2", prompt: "A piece of land completely surrounded by water is an...", choices: ["isthmus", "island", "peninsula", "bay"], answer: 1 },
            { id: "q3", prompt: "The low land between two mountains or hills is a...", choices: ["valley", "plateau", "summit", "ridge"], answer: 0 },
            { id: "q4", prompt: "A piece of land surrounded by water on THREE sides is a...", choices: ["island", "peninsula", "lake", "delta"], answer: 1, explanation: "Florida is a famous peninsula — water touches it on three sides." },
            { id: "q5", prompt: "A flat-topped area of high land is called a...", choices: ["canyon", "valley", "plateau", "plain"], answer: 2 },
            { id: "q6", prompt: "A very tall landform with steep sides and a pointed top is a...", choices: ["hill", "mountain", "plain", "meadow"], answer: 1 },
            { id: "q7", prompt: "A deep, narrow valley with steep rocky walls, often carved by a river, is a...", choices: ["canyon", "plateau", "dune", "bay"], answer: 0 },
            { id: "q8", prompt: "A landform that is like a small mountain but lower and more rounded is a...", choices: ["cliff", "hill", "cave", "ridge"], answer: 1 },
            { id: "q9", prompt: "A narrow strip of land that connects two larger areas of land is an...", choices: ["island", "isthmus", "inlet", "estuary"], answer: 1 },
            { id: "q10", prompt: "A large area of dry land with very little rain and few plants is a...", choices: ["forest", "desert", "swamp", "prairie"], answer: 1 },
            { id: "q11", prompt: "The land along the edge of an ocean is called the...", choices: ["coast", "plateau", "basin", "summit"], answer: 0 },
            { id: "q12", prompt: "Which landform is created when a volcano erupts and lava cools?", choices: ["a valley", "a plain", "new rock or land", "a canyon"], answer: 2 },
            { id: "q13", prompt: "A wide, flat area of grassland with very few trees, like in the central U.S., is called a...", choices: ["canyon", "prairie", "glacier", "reef"], answer: 1 },
            { id: "q14", prompt: "A large stream of water that flows across the land is a...", choices: ["river", "mountain", "plain", "plateau"], answer: 0 },
            { id: "q15", prompt: "Mount Everest is an example of which landform?", choices: ["valley", "mountain", "island", "plain"], answer: 1 },
            { id: "q16", prompt: "A hill of sand piled up by the wind in a desert is called a...", choices: ["cliff", "dune", "cave", "cape"], answer: 1 },
            { id: "q17", prompt: "A steep, high rock face, often found near the ocean, is a...", choices: ["plain", "valley", "cliff", "prairie"], answer: 2 },
            { id: "q18", prompt: "The Hawaiian Islands were formed by...", choices: ["wind", "volcanoes", "glaciers", "rivers"], answer: 1, explanation: "Volcanoes built the Hawaiian Islands up from the ocean floor." },
        ],
    },
    {
        id: "g3-geo-rivers",
        subjectId: "geography",
        level: "grade3",
        title: "Rivers & Lakes",
        description: "How water flows and the world's famous rivers and lakes.",
        emoji: "🏞️",
        questions: [
            { id: "q1", prompt: "The place where a river begins is called its...", choices: ["mouth", "source", "bank", "delta"], answer: 1 },
            { id: "q2", prompt: "The place where a river flows into a larger body of water is its...", choices: ["source", "mouth", "bend", "spring"], answer: 1 },
            { id: "q3", prompt: "What force makes a river flow downhill?", choices: ["wind", "gravity", "magnetism", "sunlight"], answer: 1 },
            { id: "q4", prompt: "The longest river in the world is the...", choices: ["Amazon", "Nile", "Mississippi", "Yangtze"], answer: 1 },
            { id: "q5", prompt: "A smaller river or stream that flows into a bigger river is called a...", choices: ["delta", "tributary", "canal", "lagoon"], answer: 1 },
            { id: "q6", prompt: "The longest river in the United States is the...", choices: ["Hudson", "Colorado", "Mississippi", "Rio Grande"], answer: 2 },
            { id: "q7", prompt: "A large body of water surrounded by land is a...", choices: ["lake", "ocean", "bay", "gulf"], answer: 0 },
            { id: "q8", prompt: "The Amazon River flows mostly through which country?", choices: ["Mexico", "Brazil", "Egypt", "China"], answer: 1 },
            { id: "q9", prompt: "The five large lakes between the U.S. and Canada are called the...", choices: ["Finger Lakes", "Great Lakes", "Salt Lakes", "Twin Lakes"], answer: 1 },
            { id: "q10", prompt: "Land where a river splits into smaller streams as it meets the sea is called a...", choices: ["delta", "dam", "canyon", "reef"], answer: 0, explanation: "A delta forms from soil the river drops where it meets the ocean." },
            { id: "q11", prompt: "Rivers and lakes usually contain water that is...", choices: ["salty", "fresh", "frozen", "boiling"], answer: 1 },
            { id: "q12", prompt: "People build a ___ across a river to hold back water and make electricity.", choices: ["bridge", "dam", "tunnel", "pier"], answer: 1 },
            { id: "q13", prompt: "Which of the Great Lakes is the largest?", choices: ["Lake Erie", "Lake Superior", "Lake Ontario", "Lake Huron"], answer: 1, explanation: "Lake Superior is the largest of the five Great Lakes." },
            { id: "q14", prompt: "Water that is safe to drink and is found in most rivers and lakes is called...", choices: ["salt water", "fresh water", "sea water", "ocean water"], answer: 1 },
            { id: "q15", prompt: "The Nile River is found on which continent?", choices: ["Asia", "Europe", "Africa", "South America"], answer: 2 },
            { id: "q16", prompt: "When a river overflows its banks and spreads over the land, it causes a...", choices: ["drought", "flood", "delta", "dam"], answer: 1 },
            { id: "q17", prompt: "The land right along the edge of a river is called the river's...", choices: ["bank", "mouth", "source", "delta"], answer: 0 },
            { id: "q18", prompt: "Which of these is the largest body of salt water?", choices: ["a lake", "a river", "an ocean", "a pond"], answer: 2 },
        ],
    },
    {
        id: "g3-geo-mountains",
        subjectId: "geography",
        level: "grade3",
        title: "Mountains & Volcanoes",
        description: "The world's tallest peaks and fiery volcanoes.",
        emoji: "🌋",
        questions: [
            { id: "q1", prompt: "The tallest mountain in the world is...", choices: ["Mount Fuji", "Mount Everest", "Mount Kilimanjaro", "Mount Rushmore"], answer: 1 },
            { id: "q2", prompt: "A group of mountains in a row is called a mountain...", choices: ["valley", "range", "plain", "peak"], answer: 1 },
            { id: "q3", prompt: "Hot, melted rock UNDER the ground is called...", choices: ["lava", "magma", "ash", "steam"], answer: 1 },
            { id: "q4", prompt: "Once melted rock erupts and flows on TOP of the ground, it is called...", choices: ["magma", "lava", "mud", "soil"], answer: 1, explanation: "Magma becomes lava once it reaches the surface." },
            { id: "q5", prompt: "Mount Everest is part of which mountain range?", choices: ["the Alps", "the Andes", "the Himalayas", "the Rockies"], answer: 2 },
            { id: "q6", prompt: "The longest mountain range on land is the...", choices: ["Andes", "Rockies", "Himalayas", "Alps"], answer: 0 },
            { id: "q7", prompt: "The very top of a mountain is called the...", choices: ["base", "summit", "slope", "foot"], answer: 1 },
            { id: "q8", prompt: "The Rocky Mountains are found on which continent?", choices: ["Europe", "Asia", "North America", "Africa"], answer: 2 },
            { id: "q9", prompt: "Which mountain is the tallest in Africa?", choices: ["Mount Fuji", "Mount Kilimanjaro", "Mount Everest", "Mount McKinley"], answer: 1 },
            { id: "q10", prompt: "A volcano that has not erupted in a long time but still could is called...", choices: ["extinct", "dormant", "active", "frozen"], answer: 1 },
            { id: "q11", prompt: "Many of Earth's volcanoes circle the Pacific Ocean in an area called the...", choices: ["Ring of Fire", "Bermuda Triangle", "Great Divide", "Ice Belt"], answer: 0 },
            { id: "q12", prompt: "Mountains are usually ___ at the top than at the bottom.", choices: ["warmer", "colder", "flatter", "wetter"], answer: 1, explanation: "The higher you go, the colder it gets — tall peaks often have snow." },
            { id: "q13", prompt: "The land at the very bottom of a mountain is called its...", choices: ["summit", "base or foot", "peak", "ridge"], answer: 1 },
            { id: "q14", prompt: "A volcano that is erupting now or could erupt soon is called...", choices: ["extinct", "dormant", "active", "frozen"], answer: 2 },
            { id: "q15", prompt: "A volcano that scientists believe will never erupt again is called...", choices: ["active", "dormant", "extinct", "sleeping"], answer: 2 },
            { id: "q16", prompt: "The bowl-shaped opening at the top of a volcano where lava comes out is the...", choices: ["crater", "valley", "cave", "peak"], answer: 0 },
            { id: "q17", prompt: "The Alps are a famous mountain range on which continent?", choices: ["Asia", "Africa", "Europe", "Australia"], answer: 2 },
            { id: "q18", prompt: "Climbers wear warm clothes on tall mountains because the air gets ___ as they climb higher.", choices: ["warmer", "colder", "thicker", "wetter"], answer: 1 },
        ],
    },
    {
        id: "g3-geo-weather",
        subjectId: "geography",
        level: "grade3",
        title: "Weather & Climate",
        description: "Climate zones, biomes, and the weather around the world.",
        emoji: "🌦️",
        questions: [
            { id: "q1", prompt: "The weather a place has over MANY years is called its...", choices: ["forecast", "climate", "temperature", "season"], answer: 1, explanation: "Weather changes day to day; climate is the usual pattern over a long time." },
            { id: "q2", prompt: "Areas near the equator usually have a climate that is...", choices: ["cold and snowy", "hot and warm", "dry and freezing", "windy and icy"], answer: 1 },
            { id: "q3", prompt: "A hot, wet forest with lots of plants and animals is called a...", choices: ["desert", "rainforest", "tundra", "prairie"], answer: 1 },
            { id: "q4", prompt: "A very cold, treeless area near the poles is called the...", choices: ["tundra", "savanna", "rainforest", "wetland"], answer: 0 },
            { id: "q5", prompt: "Which place would have the COLDEST climate?", choices: ["the equator", "a tropical island", "the North Pole", "a desert"], answer: 2 },
            { id: "q6", prompt: "A large biome of open grass with few trees is a...", choices: ["grassland", "forest", "ocean", "glacier"], answer: 0 },
            { id: "q7", prompt: "Deserts are known for being very...", choices: ["wet", "dry", "snowy", "green"], answer: 1 },
            { id: "q8", prompt: "Which tool measures temperature?", choices: ["thermometer", "compass", "ruler", "scale"], answer: 0 },
            { id: "q9", prompt: "A long period with little or no rain that can harm crops is called a...", choices: ["flood", "drought", "blizzard", "breeze"], answer: 1 },
            { id: "q10", prompt: "Which season is usually the warmest in most of the United States?", choices: ["winter", "spring", "summer", "fall"], answer: 2 },
            { id: "q11", prompt: "A spinning storm with very strong winds that forms over warm ocean water is a...", choices: ["tornado", "hurricane", "blizzard", "drizzle"], answer: 1 },
            { id: "q12", prompt: "Places at the top of tall mountains are usually ___ than the land below.", choices: ["warmer", "colder", "drier", "sunnier"], answer: 1 },
            { id: "q13", prompt: "Which tool is used to measure how much rain has fallen?", choices: ["thermometer", "rain gauge", "compass", "telescope"], answer: 1 },
            { id: "q14", prompt: "Frozen water that falls from clouds as soft white flakes is called...", choices: ["hail", "sleet", "snow", "fog"], answer: 2 },
            { id: "q15", prompt: "A scientist who studies and predicts the weather is called a...", choices: ["geologist", "meteorologist", "biologist", "astronomer"], answer: 1 },
            { id: "q16", prompt: "A spinning column of air that touches the ground on land is a...", choices: ["tornado", "hurricane", "blizzard", "drought"], answer: 0 },
            { id: "q17", prompt: "Which season usually has the coldest weather in most of the United States?", choices: ["summer", "spring", "winter", "fall"], answer: 2 },
            { id: "q18", prompt: "Tropical rainforests near the equator get a LOT of...", choices: ["rain", "snow", "ice", "sand"], answer: 0 },
        ],
    },
    {
        id: "g3-geo-capitals",
        subjectId: "geography",
        level: "grade3",
        title: "Capital Cities",
        description: "Match U.S. states and world countries to their capitals.",
        emoji: "🏛️",
        questions: [
            { id: "q1", prompt: "What is the capital of the United States?", choices: ["New York City", "Washington, D.C.", "Los Angeles", "Boston"], answer: 1 },
            { id: "q2", prompt: "A capital city is the place where the ___ of a state or country is located.", choices: ["biggest mall", "government", "tallest building", "airport"], answer: 1 },
            { id: "q3", prompt: "What is the capital of California?", choices: ["Los Angeles", "San Francisco", "Sacramento", "San Diego"], answer: 2 },
            { id: "q4", prompt: "What is the capital of Texas?", choices: ["Houston", "Dallas", "Austin", "San Antonio"], answer: 2 },
            { id: "q5", prompt: "What is the capital of New York state?", choices: ["New York City", "Buffalo", "Albany", "Rochester"], answer: 2, explanation: "The biggest city isn't always the capital — Albany is New York's capital." },
            { id: "q6", prompt: "What is the capital of France?", choices: ["Paris", "Lyon", "Nice", "Marseille"], answer: 0 },
            { id: "q7", prompt: "What is the capital of Canada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: 2 },
            { id: "q8", prompt: "What is the capital of Japan?", choices: ["Osaka", "Tokyo", "Kyoto", "Nagoya"], answer: 1 },
            { id: "q9", prompt: "What is the capital of Mexico?", choices: ["Cancún", "Guadalajara", "Mexico City", "Tijuana"], answer: 2 },
            { id: "q10", prompt: "What is the capital of England (United Kingdom)?", choices: ["London", "Manchester", "Liverpool", "Oxford"], answer: 0 },
            { id: "q11", prompt: "What is the capital of Florida?", choices: ["Miami", "Orlando", "Tallahassee", "Tampa"], answer: 2 },
            { id: "q12", prompt: "What is the capital of Italy?", choices: ["Milan", "Venice", "Rome", "Naples"], answer: 2 },
            { id: "q13", prompt: "What is the capital of Illinois?", choices: ["Chicago", "Springfield", "Peoria", "Rockford"], answer: 1, explanation: "Chicago is the biggest city, but Springfield is the capital." },
            { id: "q14", prompt: "What is the capital of Germany?", choices: ["Berlin", "Hamburg", "Munich", "Frankfurt"], answer: 0 },
            { id: "q15", prompt: "What is the capital of Spain?", choices: ["Barcelona", "Madrid", "Seville", "Valencia"], answer: 1 },
            { id: "q16", prompt: "What is the capital of Washington state?", choices: ["Seattle", "Spokane", "Olympia", "Tacoma"], answer: 2 },
            { id: "q17", prompt: "What is the capital of China?", choices: ["Beijing", "Shanghai", "Hong Kong", "Guangzhou"], answer: 0 },
            { id: "q18", prompt: "What is the capital of Australia?", choices: ["Sydney", "Melbourne", "Canberra", "Perth"], answer: 2, explanation: "Canberra is the capital, even though Sydney is bigger." },
        ],
    },
    {
        id: "g3-geo-landmarks",
        subjectId: "geography",
        level: "grade3",
        title: "Famous Landmarks",
        description: "Amazing landmarks and wonders around the world.",
        emoji: "🗽",
        questions: [
            { id: "q1", prompt: "The Statue of Liberty stands in which U.S. city?", choices: ["Boston", "New York City", "Washington, D.C.", "Chicago"], answer: 1 },
            { id: "q2", prompt: "The Eiffel Tower is a famous landmark in which city?", choices: ["London", "Rome", "Paris", "Berlin"], answer: 2 },
            { id: "q3", prompt: "The Great Wall is a huge landmark in which country?", choices: ["Japan", "India", "China", "Korea"], answer: 2 },
            { id: "q4", prompt: "The Pyramids of Giza are found in which country?", choices: ["Egypt", "Greece", "Mexico", "Iraq"], answer: 0 },
            { id: "q5", prompt: "Mount Rushmore shows the carved faces of four...", choices: ["explorers", "U.S. presidents", "athletes", "inventors"], answer: 1 },
            { id: "q6", prompt: "The Grand Canyon is a famous natural landmark in which U.S. state?", choices: ["Utah", "Arizona", "Nevada", "Colorado"], answer: 1 },
            { id: "q7", prompt: "Big Ben is a famous clock tower in which city?", choices: ["Paris", "London", "Dublin", "New York"], answer: 1 },
            { id: "q8", prompt: "The Colosseum, an ancient arena, is found in which city?", choices: ["Athens", "Cairo", "Rome", "Madrid"], answer: 2 },
            { id: "q9", prompt: "The Taj Mahal is a beautiful marble building in which country?", choices: ["China", "India", "Iran", "Turkey"], answer: 1 },
            { id: "q10", prompt: "The Sydney Opera House is located in which country?", choices: ["New Zealand", "Australia", "England", "Canada"], answer: 1 },
            { id: "q11", prompt: "Niagara Falls sits on the border of the U.S. and which country?", choices: ["Mexico", "Canada", "Cuba", "Brazil"], answer: 1 },
            { id: "q12", prompt: "The Golden Gate Bridge is a famous landmark in which city?", choices: ["Seattle", "Los Angeles", "San Francisco", "San Diego"], answer: 2 },
            { id: "q13", prompt: "The Leaning Tower of Pisa, which tilts to one side, is in which country?", choices: ["Spain", "Italy", "Greece", "France"], answer: 1 },
            { id: "q14", prompt: "Machu Picchu, an ancient city high in the mountains, is found in which country?", choices: ["Peru", "Mexico", "Brazil", "Chile"], answer: 0 },
            { id: "q15", prompt: "The Statue of Liberty was a gift to the United States from which country?", choices: ["England", "France", "Spain", "Italy"], answer: 1, explanation: "France gave the Statue of Liberty to the U.S. in 1886." },
            { id: "q16", prompt: "Mount Fuji is a famous mountain landmark in which country?", choices: ["China", "Korea", "Japan", "Vietnam"], answer: 2 },
            { id: "q17", prompt: "Yellowstone, the first national park, with its geysers, is found in the...", choices: ["United States", "Canada", "Mexico", "Australia"], answer: 0 },
            { id: "q18", prompt: "The Sahara, the largest hot desert, is a natural landmark on which continent?", choices: ["Asia", "Africa", "Australia", "Europe"], answer: 1 },
        ],
    },
];
