/**
 * Brainy Buddies — 4th Grade activities.
 * Loaded by brainy-data.ts and merged into the ACTIVITIES list.
 */
import type { Activity } from "@/lib/brainy-data";

export const GRADE4_ACTIVITIES: Activity[] = [

  // ── MATH ─────────────────────────────────────────────────────────────────

  {
    id: "g4-math-mult",
    subjectId: "math",
    level: "grade4",
    title: "Multi-Digit Multiplication",
    description: "Multiply 2-digit and 3-digit numbers.",
    emoji: "✖️",
    questions: [
      { id: "q1",  prompt: "23 × 4 = ?", choices: ["82", "92", "112", "122"], answer: 1, explanation: "4×3=12 (write 2 carry 1), 4×2=8+1=9. So 92." },
      { id: "q2",  prompt: "36 × 5 = ?", choices: ["155", "175", "180", "185"], answer: 2 },
      { id: "q3",  prompt: "47 × 3 = ?", choices: ["121", "131", "141", "151"], answer: 2 },
      { id: "q4",  prompt: "12 × 12 = ?", choices: ["124", "134", "144", "154"], answer: 2, explanation: "12×12 = (10×12) + (2×12) = 120+24 = 144." },
      { id: "q5",  prompt: "25 × 8 = ?", choices: ["160", "180", "200", "220"], answer: 2, explanation: "Think: 25×8 = 25×4×2 = 100×2 = 200." },
      { id: "q6",  prompt: "A school has 24 classrooms with 28 students each. How many students total?", choices: ["552", "622", "672", "692"], answer: 2 },
      { id: "q7",  prompt: "52 × 6 = ?", choices: ["302", "312", "322", "332"], answer: 1 },
      { id: "q8",  prompt: "100 × 34 = ?", choices: ["340", "3,400", "34,000", "3,040"], answer: 1 },
      { id: "q9",  prompt: "18 × 9 = ?", choices: ["152", "162", "172", "182"], answer: 1, explanation: "18×9 = 18×10 − 18 = 180 − 18 = 162." },
      { id: "q10", prompt: "63 × 7 = ?", choices: ["431", "441", "451", "461"], answer: 1 },
      { id: "q11", prompt: "14 × 15 = ?", choices: ["190", "200", "210", "220"], answer: 2, explanation: "14×15 = 14×10 + 14×5 = 140+70 = 210." },
      { id: "q12", prompt: "Each egg carton holds 12 eggs. How many eggs in 15 cartons?", choices: ["170", "180", "190", "200"], answer: 1 },
      { id: "q13", prompt: "45 × 20 = ?", choices: ["800", "850", "900", "950"], answer: 2 },
      { id: "q14", prompt: "Which of these equals 6 × 40?", choices: ["210", "240", "260", "280"], answer: 1 },
      { id: "q15", prompt: "34 × 30 = ?", choices: ["1,020", "1,120", "920", "1,200"], answer: 0, explanation: "34×3 = 102, then add a zero for the ×30: 1,020." },
      { id: "q16", prompt: "16 × 25 = ?", choices: ["350", "400", "420", "450"], answer: 1, explanation: "16×25 = 16×100÷4 = 1,600÷4 = 400." },
      { id: "q17", prompt: "125 × 4 = ?", choices: ["400", "450", "500", "550"], answer: 2 },
      { id: "q18", prompt: "A theater has 28 rows with 32 seats each. How many seats total?", choices: ["872", "896", "912", "928"], answer: 1 },
    ],
  },

  {
    id: "g4-math-div",
    subjectId: "math",
    level: "grade4",
    title: "Long Division",
    description: "Divide 3- and 4-digit numbers by 1-digit divisors.",
    emoji: "➗",
    questions: [
      { id: "q1",  prompt: "84 ÷ 4 = ?", choices: ["19", "21", "23", "24"], answer: 1, explanation: "84 ÷ 4: 8÷4=2, 4÷4=1, so 21." },
      { id: "q2",  prompt: "96 ÷ 8 = ?", choices: ["10", "11", "12", "13"], answer: 2 },
      { id: "q3",  prompt: "126 ÷ 6 = ?", choices: ["19", "20", "21", "22"], answer: 2 },
      { id: "q4",  prompt: "150 ÷ 5 = ?", choices: ["25", "28", "30", "35"], answer: 2 },
      { id: "q5",  prompt: "245 books split equally onto 7 shelves. Books per shelf?", choices: ["33", "35", "37", "39"], answer: 1 },
      { id: "q6",  prompt: "72 ÷ 6 = ?", choices: ["11", "12", "13", "14"], answer: 1 },
      { id: "q7",  prompt: "What is the remainder when 17 is divided by 5?", choices: ["0", "1", "2", "3"], answer: 2, explanation: "5×3=15, 17−15=2. Remainder is 2." },
      { id: "q8",  prompt: "185 ÷ 5 = ?", choices: ["35", "37", "38", "39"], answer: 1 },
      { id: "q9",  prompt: "A jar has 128 marbles. You pour them equally into 4 bags. Each bag gets...", choices: ["28", "30", "32", "36"], answer: 2 },
      { id: "q10", prompt: "256 ÷ 8 = ?", choices: ["30", "32", "34", "36"], answer: 1 },
      { id: "q11", prompt: "360 ÷ 9 = ?", choices: ["30", "35", "40", "45"], answer: 2 },
      { id: "q12", prompt: "What is 100 ÷ 4?", choices: ["20", "25", "30", "40"], answer: 1 },
      { id: "q13", prompt: "48 ÷ 3 = ?", choices: ["14", "16", "18", "20"], answer: 1 },
      { id: "q14", prompt: "Which has NO remainder: 50 ÷ 6, 50 ÷ 5, 50 ÷ 7, or 50 ÷ 9?", choices: ["50 ÷ 6", "50 ÷ 5", "50 ÷ 7", "50 ÷ 9"], answer: 1 },
      { id: "q15", prompt: "144 ÷ 6 = ?", choices: ["22", "24", "26", "28"], answer: 1, explanation: "6×24 = 144, so 144 ÷ 6 = 24." },
      { id: "q16", prompt: "273 ÷ 3 = ?", choices: ["81", "89", "91", "93"], answer: 2 },
      { id: "q17", prompt: "What is the remainder when 38 is divided by 5?", choices: ["1", "2", "3", "4"], answer: 2, explanation: "5×7 = 35, and 38 − 35 = 3. Remainder is 3." },
      { id: "q18", prompt: "420 stickers shared equally among 6 kids. Each kid gets...", choices: ["60", "70", "80", "90"], answer: 1 },
    ],
  },

  {
    id: "g4-math-fractions",
    subjectId: "math",
    level: "grade4",
    title: "Fractions & Equivalence",
    description: "Compare fractions, find equivalents, and add fractions with like denominators.",
    emoji: "🍕",
    questions: [
      { id: "q1",  prompt: "Which fraction is equivalent to 2/4?", choices: ["1/3", "1/2", "2/3", "3/4"], answer: 1, explanation: "2/4 = 1/2. Divide numerator and denominator by 2." },
      { id: "q2",  prompt: "1/3 + 1/3 = ?", choices: ["1/6", "1/3", "2/3", "2/6"], answer: 2 },
      { id: "q3",  prompt: "Which is the largest fraction?", choices: ["3/8", "1/2", "5/8", "3/4"], answer: 3, explanation: "3/4 = 6/8, which is greater than 5/8." },
      { id: "q4",  prompt: "3/5 + 1/5 = ?", choices: ["4/5", "4/10", "3/10", "2/5"], answer: 0 },
      { id: "q5",  prompt: "Which fraction equals 6/9?", choices: ["1/3", "2/3", "3/4", "1/2"], answer: 1, explanation: "6/9 ÷ 3/3 = 2/3." },
      { id: "q6",  prompt: "5/6 − 2/6 = ?", choices: ["1/6", "2/6", "3/6", "7/6"], answer: 2 },
      { id: "q7",  prompt: "Which is LESS than 1/2?", choices: ["4/6", "5/8", "3/8", "3/4"], answer: 2, explanation: "3/8 = 0.375, which is less than 0.5." },
      { id: "q8",  prompt: "What fraction of an hour is 30 minutes?", choices: ["1/4", "1/3", "1/2", "3/4"], answer: 2 },
      { id: "q9",  prompt: "A number line shows 0 to 1. Where is 3/4?", choices: ["1/4 of the way", "halfway", "3/4 of the way", "at 1"], answer: 2 },
      { id: "q10", prompt: "7/8 − 3/8 = ?", choices: ["3/8", "4/8", "4/16", "10/8"], answer: 1 },
      { id: "q11", prompt: "Which fraction is between 1/2 and 1?", choices: ["1/4", "1/3", "2/3", "1/8"], answer: 2 },
      { id: "q12", prompt: "Sam ate 2/6 of a pie. What simpler fraction is that?", choices: ["1/4", "1/3", "2/4", "1/2"], answer: 1, explanation: "2/6 ÷ 2/2 = 1/3." },
      { id: "q13", prompt: "Which makes a whole (= 1)?", choices: ["4/5 + 1/5", "3/4 + 1/8", "2/3 + 1/4", "1/2 + 1/4"], answer: 0 },
      { id: "q14", prompt: "Order from least to greatest: 3/4, 1/4, 2/4", choices: ["1/4, 2/4, 3/4", "3/4, 2/4, 1/4", "1/4, 3/4, 2/4", "2/4, 1/4, 3/4"], answer: 0 },
      { id: "q15", prompt: "2/8 + 3/8 = ?", choices: ["5/8", "5/16", "1/8", "6/8"], answer: 0, explanation: "Add the numerators, keep the denominator: 2+3 = 5, so 5/8." },
      { id: "q16", prompt: "Which fraction is equivalent to 4/8?", choices: ["1/4", "1/3", "1/2", "2/3"], answer: 2, explanation: "4/8 ÷ 4/4 = 1/2." },
      { id: "q17", prompt: "6/7 − 4/7 = ?", choices: ["2/7", "2/14", "10/7", "1/7"], answer: 0 },
      { id: "q18", prompt: "Which fraction is greater: 2/3 or 1/2?", choices: ["1/2", "2/3", "They are equal", "Can't tell"], answer: 1, explanation: "2/3 ≈ 0.67, which is greater than 1/2 = 0.5." },
    ],
  },

  {
    id: "g4-math-decimals",
    subjectId: "math",
    level: "grade4",
    title: "Decimals",
    description: "Understand, read, compare, and round decimals to tenths and hundredths.",
    emoji: "🔢",
    questions: [
      { id: "q1",  prompt: "What is the value of the digit 3 in 5.38?", choices: ["3 ones", "3 tenths", "3 hundredths", "3 thousandths"], answer: 1 },
      { id: "q2",  prompt: "Which decimal is greater: 0.7 or 0.5?", choices: ["0.5", "0.7", "They are equal", "Can't compare"], answer: 1 },
      { id: "q3",  prompt: "0.50 is the same as...", choices: ["0.005", "0.05", "0.5", "5.0"], answer: 2, explanation: "0.50 = 0.5 — the trailing zero doesn't change the value." },
      { id: "q4",  prompt: "What decimal equals 7/10?", choices: ["0.07", "0.17", "0.7", "7.0"], answer: 2 },
      { id: "q5",  prompt: "What decimal equals 45/100?", choices: ["0.045", "0.45", "4.5", "45.0"], answer: 1 },
      { id: "q6",  prompt: "Round 3.76 to the nearest tenth.", choices: ["3.7", "3.8", "4.0", "3.0"], answer: 1, explanation: "The hundredths digit (6) is ≥ 5, so round up the tenths: 3.76 → 3.8." },
      { id: "q7",  prompt: "1.4 + 2.3 = ?", choices: ["3.5", "3.6", "3.7", "4.0"], answer: 2 },
      { id: "q8",  prompt: "Order from least to greatest: 0.9, 0.09, 0.99", choices: ["0.09, 0.9, 0.99", "0.9, 0.09, 0.99", "0.99, 0.9, 0.09", "0.09, 0.99, 0.9"], answer: 0 },
      { id: "q9",  prompt: "A book costs $4.75. You pay $5.00. How much change?", choices: ["$0.15", "$0.20", "$0.25", "$0.30"], answer: 2 },
      { id: "q10", prompt: "Which decimal is between 0.4 and 0.6?", choices: ["0.3", "0.5", "0.7", "0.04"], answer: 1 },
      { id: "q11", prompt: "5.6 − 2.1 = ?", choices: ["2.5", "3.4", "3.5", "3.6"], answer: 2 },
      { id: "q12", prompt: "What is 1/4 written as a decimal?", choices: ["0.1", "0.2", "0.25", "0.4"], answer: 2 },
      { id: "q13", prompt: "The digit 8 in 2.08 is in the...", choices: ["ones place", "tenths place", "hundredths place", "thousandths place"], answer: 2 },
      { id: "q14", prompt: "Which shows 'three and five tenths' as a decimal?", choices: ["0.35", "3.05", "3.5", "35.0"], answer: 2 },
      { id: "q15", prompt: "0.3 + 0.45 = ?", choices: ["0.48", "0.75", "0.78", "0.84"], answer: 1, explanation: "Line up the decimals: 0.30 + 0.45 = 0.75." },
      { id: "q16", prompt: "Round 6.42 to the nearest tenth.", choices: ["6.4", "6.5", "6.0", "7.0"], answer: 0, explanation: "The hundredths digit (2) is less than 5, so round down: 6.42 → 6.4." },
      { id: "q17", prompt: "Which decimal is greater: 0.08 or 0.1?", choices: ["0.08", "0.1", "They are equal", "0.008"], answer: 1, explanation: "0.1 is the same as 0.10, which is greater than 0.08." },
      { id: "q18", prompt: "What is 1/2 written as a decimal?", choices: ["0.2", "0.5", "0.12", "0.05"], answer: 1 },
    ],
  },

  {
    id: "g4-math-geometry",
    subjectId: "math",
    level: "grade4",
    title: "Angles & Geometry",
    description: "Identify angles, classify shapes, and find area and perimeter.",
    emoji: "📐",
    questions: [
      { id: "q1",  prompt: "A right angle measures exactly...", choices: ["45°", "90°", "180°", "360°"], answer: 1 },
      { id: "q2",  prompt: "An ACUTE angle is...", choices: ["exactly 90°", "greater than 90°", "less than 90°", "exactly 180°"], answer: 2 },
      { id: "q3",  prompt: "An OBTUSE angle is...", choices: ["less than 90°", "exactly 90°", "between 90° and 180°", "exactly 180°"], answer: 2 },
      { id: "q4",  prompt: "A rectangle is 8 cm long and 5 cm wide. What is its area?", choices: ["26 cm²", "30 cm²", "40 cm²", "45 cm²"], answer: 2, explanation: "Area = length × width = 8 × 5 = 40 cm²." },
      { id: "q5",  prompt: "A square has sides of 6 m. What is its perimeter?", choices: ["12 m", "18 m", "24 m", "36 m"], answer: 2, explanation: "Perimeter = 4 × side = 4 × 6 = 24 m." },
      { id: "q6",  prompt: "How many right angles does a rectangle have?", choices: ["1", "2", "3", "4"], answer: 3 },
      { id: "q7",  prompt: "Which shape has exactly 3 angles?", choices: ["Square", "Pentagon", "Triangle", "Hexagon"], answer: 2 },
      { id: "q8",  prompt: "A triangle's angles always add up to...", choices: ["90°", "180°", "270°", "360°"], answer: 1 },
      { id: "q9",  prompt: "What type of angle is 135°?", choices: ["Acute", "Right", "Obtuse", "Straight"], answer: 2 },
      { id: "q10", prompt: "A room is 12 ft × 10 ft. How many square feet of carpet are needed?", choices: ["22 ft²", "44 ft²", "100 ft²", "120 ft²"], answer: 3 },
      { id: "q11", prompt: "A straight line forms an angle of...", choices: ["90°", "120°", "180°", "360°"], answer: 2 },
      { id: "q12", prompt: "A parallelogram has how many pairs of parallel sides?", choices: ["0", "1", "2", "4"], answer: 2 },
      { id: "q13", prompt: "A garden is 15 m long and 9 m wide. What is its perimeter?", choices: ["24 m", "48 m", "135 m", "135 m²"], answer: 1, explanation: "Perimeter = 2×(15+9) = 2×24 = 48 m." },
      { id: "q14", prompt: "Which angle is formed by the hands of a clock at 3:00?", choices: ["Acute", "Right", "Obtuse", "Straight"], answer: 1 },
      { id: "q15", prompt: "A triangle with all three sides equal is called...", choices: ["Scalene", "Isosceles", "Equilateral", "Right"], answer: 2 },
      { id: "q16", prompt: "A square has sides of 9 cm. What is its area?", choices: ["18 cm²", "36 cm²", "72 cm²", "81 cm²"], answer: 3, explanation: "Area of a square = side × side = 9 × 9 = 81 cm²." },
      { id: "q17", prompt: "What type of angle measures exactly 90°?", choices: ["Acute", "Right", "Obtuse", "Straight"], answer: 1 },
      { id: "q18", prompt: "A rectangle is 7 m long and 3 m wide. What is its perimeter?", choices: ["10 m", "20 m", "21 m", "24 m"], answer: 1, explanation: "Perimeter = 2 × (7 + 3) = 2 × 10 = 20 m." },
    ],
  },

  // ── SCIENCE ──────────────────────────────────────────────────────────────

  {
    id: "g4-sci-earth",
    subjectId: "science",
    level: "grade4",
    title: "Earth's Structure & Landforms",
    description: "Explore Earth's layers, plate tectonics, and major landforms.",
    emoji: "🌋",
    questions: [
      { id: "q1",  prompt: "Earth's outermost layer is called the...", choices: ["Mantle", "Core", "Crust", "Magma"], answer: 2 },
      { id: "q2",  prompt: "The layer directly below Earth's crust is the...", choices: ["Inner core", "Outer core", "Mantle", "Tectonic plate"], answer: 2 },
      { id: "q3",  prompt: "Earth's inner core is made mostly of...", choices: ["Rock", "Water", "Gas", "Iron and nickel"], answer: 3 },
      { id: "q4",  prompt: "Large pieces of Earth's crust that move slowly are called...", choices: ["Volcanoes", "Tectonic plates", "Fault lines", "Sediment layers"], answer: 1 },
      { id: "q5",  prompt: "When two tectonic plates collide, they can form...", choices: ["Oceans", "Mountains", "Valleys only", "Flat plains"], answer: 1 },
      { id: "q6",  prompt: "Molten (melted) rock inside the earth is called...", choices: ["Lava", "Magma", "Sediment", "Granite"], answer: 1, explanation: "Magma is molten rock underground; when it reaches the surface it becomes lava." },
      { id: "q7",  prompt: "A crack in Earth's crust where rocks slip and cause earthquakes is called a...", choices: ["Volcano", "Canyon", "Fault", "Ridge"], answer: 2 },
      { id: "q8",  prompt: "The Grand Canyon was mainly formed by...", choices: ["A volcano", "An earthquake", "A glacier", "The Colorado River eroding rock"], answer: 3 },
      { id: "q9",  prompt: "Which process breaks rocks into smaller pieces over time?", choices: ["Weathering", "Deposition", "Fossilization", "Condensation"], answer: 0 },
      { id: "q10", prompt: "What kind of landform is a long, narrow body of water between two mountains?", choices: ["Delta", "Canyon", "Valley", "Peninsula"], answer: 2 },
      { id: "q11", prompt: "A landmass surrounded by water on three sides is a...", choices: ["Island", "Peninsula", "Isthmus", "Bay"], answer: 1 },
      { id: "q12", prompt: "Igneous rocks form from...", choices: ["Layers of sediment pressed together", "Cooled magma or lava", "Extreme heat and pressure underground", "Sea creatures' shells"], answer: 1 },
      { id: "q13", prompt: "Which tells us that Earth's tectonic plates are STILL moving?", choices: ["Sunsets", "Earthquakes and volcanic eruptions", "Ocean tides", "Wind patterns"], answer: 1 },
      { id: "q14", prompt: "The Ring of Fire is a zone of frequent earthquakes and volcanoes located around the...", choices: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], answer: 2 },
      { id: "q15", prompt: "Which layer of the Earth is the HOTTEST?", choices: ["Crust", "Mantle", "Outer core", "Inner core"], answer: 3, explanation: "The inner core is the deepest and hottest layer, even hotter than the surface of the sun." },
      { id: "q16", prompt: "Sedimentary rock forms from...", choices: ["Cooled lava", "Layers of sediment pressed together over time", "Heat and pressure deep underground", "Erupting magma"], answer: 1 },
      { id: "q17", prompt: "An opening in Earth's crust where lava, ash, and gases erupt is called a...", choices: ["Fault", "Volcano", "Glacier", "Canyon"], answer: 1 },
      { id: "q18", prompt: "The movement of weathered rock and soil to a new place by wind or water is called...", choices: ["Erosion", "Condensation", "Eruption", "Magnetism"], answer: 0, explanation: "Erosion carries away pieces of rock and soil that weathering has broken loose." },
    ],
  },

  {
    id: "g4-sci-weather",
    subjectId: "science",
    level: "grade4",
    title: "Weather & Climate",
    description: "Understand weather patterns, the water cycle, and how climate differs from weather.",
    emoji: "🌦️",
    questions: [
      { id: "q1",  prompt: "Weather describes conditions in the atmosphere...", choices: ["Over millions of years", "Over a short period of time", "Only in winter", "Underground"], answer: 1 },
      { id: "q2",  prompt: "CLIMATE is the...", choices: ["Temperature today", "Average weather over a long time (30+ years)", "Speed of the wind", "Amount of sunlight"], answer: 1 },
      { id: "q3",  prompt: "In the water cycle, water vapor rising and cooling to form clouds is called...", choices: ["Evaporation", "Precipitation", "Condensation", "Runoff"], answer: 2 },
      { id: "q4",  prompt: "Which is NOT a form of precipitation?", choices: ["Rain", "Snow", "Hail", "Fog"], answer: 3, explanation: "Fog is water droplets suspended in air — it is not precipitation because it doesn't fall from the sky." },
      { id: "q5",  prompt: "What causes wind?", choices: ["Earth rotating on its axis", "Differences in air pressure", "The moon's gravity", "Ocean currents only"], answer: 1 },
      { id: "q6",  prompt: "A barometer measures...", choices: ["Temperature", "Wind speed", "Air pressure", "Humidity"], answer: 2 },
      { id: "q7",  prompt: "Which biome has the MOST rainfall?", choices: ["Desert", "Grassland", "Tundra", "Tropical rainforest"], answer: 3 },
      { id: "q8",  prompt: "The layer of atmosphere closest to Earth, where weather occurs, is the...", choices: ["Stratosphere", "Thermosphere", "Troposphere", "Mesosphere"], answer: 2 },
      { id: "q9",  prompt: "A tornado is most likely to form in which type of storm system?", choices: ["Blizzard", "Thunderstorm", "Fog bank", "Heat wave"], answer: 1 },
      { id: "q10", prompt: "Places near the equator are generally...", choices: ["Cold and snowy", "Warm and wet", "Dry and flat", "Cold and dry"], answer: 1 },
      { id: "q11", prompt: "The sun's energy drives the water cycle mainly through...", choices: ["Precipitation", "Evaporation", "Condensation", "Runoff"], answer: 1 },
      { id: "q12", prompt: "Which instrument measures wind speed?", choices: ["Barometer", "Thermometer", "Anemometer", "Hygrometer"], answer: 2 },
      { id: "q13", prompt: "El Niño is a weather pattern caused by warmer-than-normal...", choices: ["Arctic temperatures", "Pacific Ocean surface temperatures", "Atlantic Ocean temperatures", "Jet stream changes"], answer: 1 },
      { id: "q14", prompt: "Which season in the Northern Hemisphere has the MOST daylight hours?", choices: ["Winter", "Spring", "Summer", "Fall"], answer: 2 },
      { id: "q15", prompt: "Which type of cloud is puffy and white, often seen on fair-weather days?", choices: ["Cirrus", "Cumulus", "Stratus", "Nimbus"], answer: 1 },
      { id: "q16", prompt: "Humidity is a measure of the amount of ___ in the air.", choices: ["Oxygen", "Water vapor", "Dust", "Pollen"], answer: 1 },
      { id: "q17", prompt: "A long period of unusually dry weather with little or no rain is called a...", choices: ["Flood", "Drought", "Blizzard", "Hurricane"], answer: 1 },
      { id: "q18", prompt: "Hurricanes get their energy from...", choices: ["Cold mountain air", "Warm ocean water", "Dry desert sand", "Polar ice"], answer: 1, explanation: "Hurricanes form over warm ocean water, which fuels the giant storm." },
    ],
  },

  {
    id: "g4-sci-electricity",
    subjectId: "science",
    level: "grade4",
    title: "Electricity & Magnetism",
    description: "Learn about circuits, conductors, insulators, and magnetic forces.",
    emoji: "⚡",
    questions: [
      { id: "q1",  prompt: "Electric current needs a complete path called a...", choices: ["Battery", "Circuit", "Switch", "Conductor"], answer: 1 },
      { id: "q2",  prompt: "A material that allows electricity to pass through it is a...", choices: ["Insulator", "Resistor", "Conductor", "Transformer"], answer: 2 },
      { id: "q3",  prompt: "Which is the BEST conductor of electricity?", choices: ["Wood", "Rubber", "Plastic", "Copper wire"], answer: 3 },
      { id: "q4",  prompt: "A material that BLOCKS the flow of electricity is an...", choices: ["Conductor", "Insulator", "Amplifier", "Electrode"], answer: 1 },
      { id: "q5",  prompt: "In a series circuit, if one bulb burns out...", choices: ["Only that bulb goes out", "All bulbs go out", "The circuit stays the same", "The voltage doubles"], answer: 1 },
      { id: "q6",  prompt: "Like magnetic poles (N-N or S-S)...", choices: ["Attract each other", "Repel each other", "Have no effect", "Fuse together"], answer: 1 },
      { id: "q7",  prompt: "Opposite magnetic poles (N-S)...", choices: ["Repel", "Attract", "Neutralize", "Disappear"], answer: 1 },
      { id: "q8",  prompt: "An electromagnet is created by passing electricity through a...", choices: ["Plastic tube", "Rubber band", "Coil of wire around iron", "Battery alone"], answer: 2 },
      { id: "q9",  prompt: "Which is NOT magnetic?", choices: ["Iron", "Nickel", "Cobalt", "Aluminum"], answer: 3 },
      { id: "q10", prompt: "A switch in a circuit is used to...", choices: ["Store electricity", "Increase voltage", "Start or stop the flow of current", "Change the color of light"], answer: 2 },
      { id: "q11", prompt: "Static electricity is caused by...", choices: ["Moving water", "A build-up of electric charge on a surface", "Magnetism", "Chemical reactions only"], answer: 1 },
      { id: "q12", prompt: "Lightning is an example of...", choices: ["An electric circuit", "Static electricity discharge", "Magnetism", "Electromagnetic induction"], answer: 1 },
      { id: "q13", prompt: "Which device converts electrical energy into light energy?", choices: ["Motor", "Battery", "Lightbulb", "Switch"], answer: 2 },
      { id: "q14", prompt: "Earth acts like a giant magnet — that is why a compass needle always points toward...", choices: ["The sun", "True east", "Magnetic north", "Magnetic south"], answer: 2 },
      { id: "q15", prompt: "A battery in a circuit provides the ___ that pushes the current along.", choices: ["Light", "Energy", "Magnetism", "Sound"], answer: 1 },
      { id: "q16", prompt: "In a PARALLEL circuit, if one bulb burns out, the other bulbs...", choices: ["All go out too", "Stay lit", "Get brighter forever", "Stop the battery"], answer: 1, explanation: "In a parallel circuit each bulb has its own path, so the others keep working." },
      { id: "q17", prompt: "Which material is an INSULATOR?", choices: ["Copper", "Silver", "Rubber", "Iron"], answer: 2 },
      { id: "q18", prompt: "The area around a magnet where its force can be felt is called the magnetic...", choices: ["Pole", "Field", "Circuit", "Charge"], answer: 1, explanation: "A magnetic field is strongest near the poles of the magnet." },
    ],
  },

  {
    id: "g4-sci-body",
    subjectId: "science",
    level: "grade4",
    title: "Human Body Systems",
    description: "Explore the major systems that keep the human body working.",
    emoji: "🫀",
    questions: [
      { id: "q1",  prompt: "The main job of the skeletal system is to...", choices: ["Pump blood", "Digest food", "Support and protect the body", "Fight disease"], answer: 2 },
      { id: "q2",  prompt: "The heart is part of which body system?", choices: ["Digestive", "Respiratory", "Circulatory", "Skeletal"], answer: 2 },
      { id: "q3",  prompt: "The main job of the circulatory system is to...", choices: ["Breathe in oxygen", "Carry blood, oxygen, and nutrients throughout the body", "Break down food", "Control movement"], answer: 1 },
      { id: "q4",  prompt: "Gas exchange (oxygen in, carbon dioxide out) happens in the...", choices: ["Stomach", "Brain", "Lungs", "Kidneys"], answer: 2 },
      { id: "q5",  prompt: "The digestive system breaks food into nutrients. Where does digestion BEGIN?", choices: ["Stomach", "Small intestine", "Mouth", "Large intestine"], answer: 2 },
      { id: "q6",  prompt: "Muscles are connected to bones by...", choices: ["Ligaments", "Tendons", "Cartilage", "Nerves"], answer: 1 },
      { id: "q7",  prompt: "Bones are connected to other bones by...", choices: ["Tendons", "Ligaments", "Muscles", "Veins"], answer: 1 },
      { id: "q8",  prompt: "The nervous system's 'control center' is the...", choices: ["Heart", "Spinal cord", "Brain", "Stomach"], answer: 2 },
      { id: "q9",  prompt: "Blood gets oxygen in the lungs, then travels to the body. What color is oxygen-RICH blood?", choices: ["Blue", "Green", "Dark red", "Bright red"], answer: 3 },
      { id: "q10", prompt: "The largest organ in the human body is the...", choices: ["Heart", "Liver", "Skin", "Brain"], answer: 2 },
      { id: "q11", prompt: "Which system filters waste from your blood and produces urine?", choices: ["Circulatory", "Digestive", "Nervous", "Urinary / Excretory"], answer: 3 },
      { id: "q12", prompt: "What do white blood cells do?", choices: ["Carry oxygen", "Fight infection and disease", "Digest food", "Send nerve signals"], answer: 1 },
      { id: "q13", prompt: "The small intestine's main job is to...", choices: ["Store food", "Absorb nutrients into the blood", "Filter blood", "Control breathing"], answer: 1 },
      { id: "q14", prompt: "Your ribs protect which vital organs?", choices: ["Brain and eyes", "Stomach and kidneys", "Heart and lungs", "Liver and intestines"], answer: 2 },
      { id: "q15", prompt: "What is the main job of red blood cells?", choices: ["Fight germs", "Carry oxygen around the body", "Send nerve signals", "Digest food"], answer: 1 },
      { id: "q16", prompt: "The dome-shaped muscle below the lungs that helps you breathe is the...", choices: ["Biceps", "Diaphragm", "Hamstring", "Triceps"], answer: 1 },
      { id: "q17", prompt: "Which body system includes the brain, spinal cord, and nerves?", choices: ["Circulatory", "Digestive", "Nervous", "Respiratory"], answer: 2 },
      { id: "q18", prompt: "About how many bones are in an adult human body?", choices: ["106", "206", "306", "406"], answer: 1, explanation: "Adults have about 206 bones (babies are born with even more!)." },
    ],
  },

  {
    id: "g4-sci-elements",
    subjectId: "science",
    level: "grade4",
    title: "Elements & Compounds",
    description: "Dive deeper into atoms, the periodic table, and how elements combine.",
    emoji: "⚛️",
    questions: [
      { id: "q1",  prompt: "An atom's atomic number tells you the number of...", choices: ["Neutrons", "Electrons", "Protons", "Molecules"], answer: 2, explanation: "The atomic number equals the number of protons in an atom's nucleus." },
      { id: "q2",  prompt: "An element is a pure substance that...", choices: ["Can be broken down by heating", "Cannot be broken down into simpler substances", "Is always a gas", "Is always a metal"], answer: 1 },
      { id: "q3",  prompt: "When two or more elements chemically combine, they form a...", choices: ["Mixture", "Compound", "Solution", "Alloy"], answer: 1, explanation: "H₂O is a compound — hydrogen and oxygen chemically bonded together." },
      { id: "q4",  prompt: "The chemical formula for water is...", choices: ["H₂", "O₂", "H₂O", "CO₂"], answer: 2 },
      { id: "q5",  prompt: "Carbon dioxide (CO₂) is a compound made of carbon and...", choices: ["Hydrogen", "Nitrogen", "Oxygen", "Helium"], answer: 2 },
      { id: "q6",  prompt: "Table salt (NaCl) is a compound made of Sodium and...", choices: ["Carbon", "Chlorine", "Calcium", "Chromium"], answer: 1 },
      { id: "q7",  prompt: "In the periodic table, elements in the same COLUMN (group) have similar...", choices: ["Atomic masses", "Colors", "Chemical properties", "Densities"], answer: 2, explanation: "Elements in the same group share similar valence electron configurations." },
      { id: "q8",  prompt: "The noble gases (Group 18) are special because they have...", choices: ["The most electrons", "A full outer electron shell and rarely react", "The highest atomic numbers", "The lowest melting points"], answer: 1 },
      { id: "q9",  prompt: "A mixture is different from a compound because in a mixture the parts...", choices: ["Are chemically bonded", "Can be separated physically", "Form a new substance", "Always change color"], answer: 1, explanation: "Salt water is a mixture — you can evaporate the water to get the salt back." },
      { id: "q10", prompt: "The element with atomic number 6 and symbol 'C' is...", choices: ["Calcium", "Cobalt", "Carbon", "Chromium"], answer: 2 },
      { id: "q11", prompt: "Which two elements make up water (H₂O)?", choices: ["Hydrogen and Helium", "Hydrogen and Oxygen", "Helium and Oxygen", "Hydrogen and Nitrogen"], answer: 1 },
      { id: "q12", prompt: "The element Iron has the symbol 'Fe'. Its atomic number is 26. This means Iron has 26...", choices: ["Neutrons", "Electrons only", "Protons", "Compounds"], answer: 2 },
      { id: "q13", prompt: "Diamond and graphite (pencil lead) are both made entirely of which element?", choices: ["Silicon", "Oxygen", "Carbon", "Nitrogen"], answer: 2, explanation: "Different arrangements of carbon atoms create very different materials!" },
      { id: "q14", prompt: "Which of these is a mixture (NOT a compound)?", choices: ["Water (H₂O)", "Salt (NaCl)", "Carbon dioxide (CO₂)", "Trail mix (nuts and raisins)"], answer: 3, explanation: "Trail mix is a mixture — you can pick out each part without a chemical reaction." },
      { id: "q15", prompt: "The center of an atom is called the...", choices: ["Electron", "Nucleus", "Shell", "Compound"], answer: 1, explanation: "The nucleus holds the protons and neutrons at the atom's center." },
      { id: "q16", prompt: "What is the chemical symbol for Oxygen?", choices: ["Ox", "O", "Og", "Oy"], answer: 1 },
      { id: "q17", prompt: "Tiny particles with a negative charge that move around the nucleus are called...", choices: ["Protons", "Neutrons", "Electrons", "Atoms"], answer: 2 },
      { id: "q18", prompt: "The chemical symbol for the element Gold is...", choices: ["Go", "Gd", "Au", "Ag"], answer: 2, explanation: "Au comes from 'aurum,' the Latin word for gold." },
    ],
  },

  // ── HISTORY ──────────────────────────────────────────────────────────────

  {
    id: "g4-hist-revolution",
    subjectId: "history",
    level: "grade4",
    title: "American Revolution",
    description: "Discover how the 13 colonies broke free from British rule.",
    emoji: "🦅",
    questions: [
      { id: "q1",  prompt: "The American Revolution was a war between the American colonies and...", choices: ["France", "Spain", "Britain", "Canada"], answer: 2 },
      { id: "q2",  prompt: "The colonists' rallying cry 'No taxation without representation' protested...", choices: ["British trade laws", "Taxes by Britain without colonial votes", "Low wages", "Military service"], answer: 1 },
      { id: "q3",  prompt: "The Boston Tea Party (1773) was a protest against a tax on...", choices: ["Sugar", "Stamps", "Tea", "Cloth"], answer: 2 },
      { id: "q4",  prompt: "The Declaration of Independence was signed in...", choices: ["1773", "1775", "1776", "1783"], answer: 2 },
      { id: "q5",  prompt: "Who wrote most of the Declaration of Independence?", choices: ["George Washington", "Benjamin Franklin", "John Adams", "Thomas Jefferson"], answer: 3 },
      { id: "q6",  prompt: "The Declaration of Independence famously states that all men are created...", choices: ["Obedient", "Equal", "Free from taxes", "Subject to the king"], answer: 1 },
      { id: "q7",  prompt: "George Washington was the commander-in-chief of the...", choices: ["British army", "French navy", "Continental Army", "Minutemen militia"], answer: 2 },
      { id: "q8",  prompt: "The Battle of Lexington and Concord in 1775 is known as the...", choices: ["End of the Revolution", "First battle of the Revolution", "Battle of Boston Harbor", "Final surrender"], answer: 1 },
      { id: "q9",  prompt: "Which country was an important ally to the American colonies during the Revolution?", choices: ["Spain", "France", "Portugal", "Netherlands"], answer: 1 },
      { id: "q10", prompt: "The Treaty of Paris (1783) officially ended the Revolution and recognized American...", choices: ["Defeat", "Alliance with France", "Independence", "Trade rights only"], answer: 2 },
      { id: "q11", prompt: "Loyalists during the Revolution were colonists who...", choices: ["Wanted independence", "Supported Britain", "Fought for France", "Opposed all taxes"], answer: 1 },
      { id: "q12", prompt: "Paul Revere's famous midnight ride warned colonists that...", choices: ["The Declaration was signed", "British troops were coming", "Washington had won", "The French had arrived"], answer: 1 },
      { id: "q13", prompt: "Where did Washington's army famously cross the Delaware River on Christmas night, 1776?", choices: ["To attack Philadelphia", "To attack Trenton, New Jersey", "To retreat to Boston", "To meet the French fleet"], answer: 1 },
      { id: "q14", prompt: "The last major battle of the Revolution, at Yorktown, ended with the surrender of...", choices: ["George Washington", "Thomas Jefferson", "General Cornwallis (British)", "General Lafayette (French)"], answer: 2 },
      { id: "q15", prompt: "The pamphlet 'Common Sense,' which urged colonists to seek independence, was written by...", choices: ["Thomas Jefferson", "Thomas Paine", "John Hancock", "Patrick Henry"], answer: 1 },
      { id: "q16", prompt: "Who became the first President of the United States after the Revolution?", choices: ["John Adams", "Thomas Jefferson", "Benjamin Franklin", "George Washington"], answer: 3 },
      { id: "q17", prompt: "The Sons of Liberty were a group of colonists who...", choices: ["Supported the British king", "Protested British taxes and rule", "Fought for France", "Collected taxes for Britain"], answer: 1 },
      { id: "q18", prompt: "Whose large, bold signature on the Declaration of Independence became famous?", choices: ["Thomas Jefferson", "John Hancock", "Paul Revere", "Benjamin Franklin"], answer: 1, explanation: "John Hancock signed his name large enough for the king to read without glasses." },
    ],
  },

  {
    id: "g4-hist-constitution",
    subjectId: "history",
    level: "grade4",
    title: "The Constitution & Government",
    description: "Learn how America's government was formed and how it works.",
    emoji: "📜",
    questions: [
      { id: "q1",  prompt: "The U.S. Constitution was written in...", choices: ["1776", "1783", "1787", "1800"], answer: 2 },
      { id: "q2",  prompt: "Where was the Constitutional Convention held?", choices: ["Washington D.C.", "Boston", "Philadelphia", "New York City"], answer: 2 },
      { id: "q3",  prompt: "The Constitution divides power into how many branches of government?", choices: ["2", "3", "4", "5"], answer: 1 },
      { id: "q4",  prompt: "The Legislative branch (Congress) is responsible for...", choices: ["Enforcing laws", "Making laws", "Interpreting laws", "Leading the military"], answer: 1 },
      { id: "q5",  prompt: "Congress is made up of two parts. They are the...", choices: ["President and Vice President", "Senate and House of Representatives", "Supreme Court and Federal Courts", "FBI and CIA"], answer: 1 },
      { id: "q6",  prompt: "The Executive branch is led by the...", choices: ["Speaker of the House", "Chief Justice", "President", "Senate majority leader"], answer: 2 },
      { id: "q7",  prompt: "The Judicial branch interprets the Constitution and is led by the...", choices: ["President", "Congress", "Supreme Court", "Electoral College"], answer: 2 },
      { id: "q8",  prompt: "The system of 'checks and balances' ensures that...", choices: ["All citizens pay taxes", "No branch of government becomes too powerful", "The president can veto Congress forever", "Judges serve 4-year terms"], answer: 1 },
      { id: "q9",  prompt: "The first 10 amendments to the Constitution are called the...", choices: ["Preamble", "Articles of Confederation", "Bill of Rights", "Declaration of Rights"], answer: 2 },
      { id: "q10", prompt: "The 1st Amendment protects freedom of speech, religion, press, and the right to...", choices: ["Bear arms", "Vote", "Peaceful assembly", "Fair trial"], answer: 2 },
      { id: "q11", prompt: "James Madison is called the 'Father of the Constitution' because...", choices: ["He was the first president", "He did more than anyone to write and ratify it", "He invented the Bill of Rights name", "He signed it first"], answer: 1 },
      { id: "q12", prompt: "The U.S. Constitution is the supreme law of the land, meaning...", choices: ["Congress can ignore it", "All other laws must agree with it", "The president can rewrite it", "States can replace it"], answer: 1 },
      { id: "q13", prompt: "How many senators are in the U.S. Senate?", choices: ["50", "100", "150", "435"], answer: 1, explanation: "Each of the 50 states sends 2 senators = 100 senators total." },
      { id: "q14", prompt: "To become president, you must be at least how old?", choices: ["25", "30", "35", "40"], answer: 2 },
      { id: "q15", prompt: "The Preamble (introduction) to the Constitution begins with the words 'We the ___.'", choices: ["Kings", "People", "States", "Soldiers"], answer: 1 },
      { id: "q16", prompt: "A change or addition to the Constitution is called an...", choices: ["Article", "Amendment", "Preamble", "Clause"], answer: 1 },
      { id: "q17", prompt: "The President can reject a bill passed by Congress by using a...", choices: ["Pardon", "Veto", "Filibuster", "Petition"], answer: 1, explanation: "A veto is the president's power to reject a bill so it does not become law." },
      { id: "q18", prompt: "How many years long is one term for a U.S. President?", choices: ["2 years", "4 years", "6 years", "8 years"], answer: 1 },
    ],
  },

  {
    id: "g4-hist-expansion",
    subjectId: "history",
    level: "grade4",
    title: "Westward Expansion",
    description: "Follow America's growth from the East Coast to the Pacific Ocean.",
    emoji: "🤠",
    questions: [
      { id: "q1",  prompt: "The Louisiana Purchase (1803) roughly doubled the size of the U.S. The land was purchased from...", choices: ["Britain", "Spain", "France", "Mexico"], answer: 2 },
      { id: "q2",  prompt: "Who led the expedition to explore the Louisiana Territory?", choices: ["Daniel Boone & Kit Carson", "Lewis & Clark", "Zebulon Pike & John Frémont", "Washington & Jefferson"], answer: 1 },
      { id: "q3",  prompt: "The idea that Americans were destined to settle the entire continent was called...", choices: ["Westward Ho", "Manifest Destiny", "Continental Expansion", "The Great Migration"], answer: 1 },
      { id: "q4",  prompt: "The Oregon Trail was a route used by pioneers heading to...", choices: ["Texas", "California", "The Pacific Northwest (Oregon)", "Florida"], answer: 2 },
      { id: "q5",  prompt: "The discovery of gold at Sutter's Mill in 1848 sparked the...", choices: ["Oregon Trail migration", "California Gold Rush", "Pony Express", "Transcontinental Railroad"], answer: 1 },
      { id: "q6",  prompt: "The Transcontinental Railroad, completed in 1869, connected the East to...", choices: ["Texas", "Colorado", "California", "Oregon"], answer: 2 },
      { id: "q7",  prompt: "Native American nations were most directly harmed by westward expansion through...", choices: ["Better farming techniques", "Forced removal from their lands", "More trading opportunities", "Population growth"], answer: 1 },
      { id: "q8",  prompt: "The Indian Removal Act of 1830 forced thousands of Native Americans on a deadly march called the...", choices: ["Dust Bowl", "Long Walk", "Trail of Tears", "Great Migration"], answer: 2 },
      { id: "q9",  prompt: "Texas was admitted to the Union in 1845 after being an independent...", choices: ["Territory", "Colony", "Republic", "Province"], answer: 2 },
      { id: "q10", prompt: "The Missouri Compromise (1820) tried to balance new states entering as free states or...", choices: ["Democratic states", "Slave states", "Farming states", "Independent states"], answer: 1 },
      { id: "q11", prompt: "Sacagawea helped the Lewis and Clark expedition mainly as a...", choices: ["Soldier", "Cook", "Guide and interpreter", "Map maker"], answer: 2 },
      { id: "q12", prompt: "The Homestead Act of 1862 encouraged westward settlement by offering...", choices: ["Gold mining rights", "Free land to settlers who farmed it", "Railroad tickets", "Cash payments"], answer: 1 },
      { id: "q13", prompt: "The Pony Express was a fast mail service that ran between Missouri and...", choices: ["Chicago", "Texas", "California", "Oregon"], answer: 2 },
      { id: "q14", prompt: "By 1850, the U.S. reached from the Atlantic to the...", choices: ["Mississippi River", "Rocky Mountains", "Pacific Ocean", "Great Plains"], answer: 2 },
      { id: "q15", prompt: "Pioneers often traveled west in vehicles called covered...", choices: ["Trains", "Wagons", "Boats", "Carriages"], answer: 1 },
      { id: "q16", prompt: "The people who rushed to California to find gold in 1849 were nicknamed the...", choices: ["Pioneers", "Forty-Niners", "Cowboys", "Settlers"], answer: 1 },
      { id: "q17", prompt: "Lewis and Clark were searching for a water route to which ocean?", choices: ["Atlantic Ocean", "Gulf of Mexico", "Pacific Ocean", "Arctic Ocean"], answer: 2 },
      { id: "q18", prompt: "Which state joined the Union in 1850, shortly after its Gold Rush?", choices: ["Texas", "Oregon", "California", "Nevada"], answer: 2, explanation: "California became the 31st state in 1850." },
    ],
  },

  // ── GEOGRAPHY ────────────────────────────────────────────────────────────

  {
    id: "g4-geo-usregions",
    subjectId: "geography",
    level: "grade4",
    title: "U.S. Regions In-Depth",
    description: "Explore the geography, climate, and landmarks of America's five regions.",
    emoji: "🗺️",
    questions: [
      { id: "q1",  prompt: "Which U.S. region includes New York, Massachusetts, and Pennsylvania?", choices: ["Southeast", "Midwest", "Northeast", "Southwest"], answer: 2 },
      { id: "q2",  prompt: "The Great Plains, famous for farming and flat terrain, are mainly in the...", choices: ["Northeast", "Midwest", "Southwest", "West"], answer: 1 },
      { id: "q3",  prompt: "Which region includes Florida, Georgia, and Louisiana?", choices: ["Northeast", "Southeast", "Midwest", "Southwest"], answer: 1 },
      { id: "q4",  prompt: "The Rocky Mountains are mainly in which region?", choices: ["Midwest", "Southwest", "Southeast", "West"], answer: 3 },
      { id: "q5",  prompt: "The Grand Canyon is located in which state?", choices: ["Nevada", "Utah", "Arizona", "New Mexico"], answer: 2 },
      { id: "q6",  prompt: "The Great Lakes — Superior, Michigan, Huron, Erie, and Ontario — border which region?", choices: ["Northeast", "Midwest", "Southeast", "West"], answer: 1 },
      { id: "q7",  prompt: "Which two states are NOT connected to the contiguous (mainland) United States?", choices: ["Oregon and Washington", "Alaska and Hawaii", "California and Florida", "Texas and Maine"], answer: 1 },
      { id: "q8",  prompt: "The Mississippi River flows from Minnesota to the Gulf of Mexico, passing through the...", choices: ["Western region", "Northeastern region", "Midwestern region", "Eastern seaboard"], answer: 2 },
      { id: "q9",  prompt: "The Appalachian Mountains run along which coast of the U.S.?", choices: ["West", "East", "South", "North"], answer: 1 },
      { id: "q10", prompt: "Which region gets the least rainfall and includes the Mojave and Sonoran Deserts?", choices: ["Midwest", "Southeast", "Southwest", "Northeast"], answer: 2 },
      { id: "q11", prompt: "The country's most populated city, New York City, is in which region?", choices: ["Midwest", "Southeast", "Northeast", "Mid-Atlantic"], answer: 2 },
      { id: "q12", prompt: "The Pacific Crest Trail runs through which coast?", choices: ["East Coast", "West Coast", "Gulf Coast", "Great Lakes"], answer: 1 },
      { id: "q13", prompt: "Silicon Valley — hub of the U.S. technology industry — is in which state?", choices: ["Texas", "New York", "Washington", "California"], answer: 3 },
      { id: "q14", prompt: "Which region includes the nation's capital, Washington D.C.?", choices: ["Southeast", "Midwest", "Northeast", "Southwest"], answer: 2 },
      { id: "q15", prompt: "Mount Rushmore, with four U.S. presidents carved into it, is in which state?", choices: ["Wyoming", "Montana", "South Dakota", "Colorado"], answer: 2 },
      { id: "q16", prompt: "Which region is famous for maple syrup and colorful fall foliage?", choices: ["Southwest", "Northeast", "West", "Midwest"], answer: 1 },
      { id: "q17", prompt: "The Everglades, a huge tropical wetland, are located in which state?", choices: ["Louisiana", "Georgia", "Florida", "Texas"], answer: 2 },
      { id: "q18", prompt: "Yellowstone, the first U.S. national park, is mostly located in which state?", choices: ["Montana", "Wyoming", "Idaho", "Utah"], answer: 1, explanation: "Most of Yellowstone National Park lies within Wyoming." },
    ],
  },

  {
    id: "g4-geo-world",
    subjectId: "geography",
    level: "grade4",
    title: "World Geography",
    description: "Explore continents, major countries, mountains, rivers, and oceans.",
    emoji: "🌍",
    questions: [
      { id: "q1",  prompt: "Which is the LONGEST river in the world?", choices: ["Amazon", "Mississippi", "Nile", "Yangtze"], answer: 2 },
      { id: "q2",  prompt: "Which is the HIGHEST mountain in the world?", choices: ["K2", "Mount Everest", "Kilimanjaro", "Mont Blanc"], answer: 1 },
      { id: "q3",  prompt: "Mount Everest is located in which mountain range?", choices: ["Andes", "Alps", "Himalayas", "Rockies"], answer: 2 },
      { id: "q4",  prompt: "The Amazon Rainforest is mostly located in which country?", choices: ["Colombia", "Peru", "Brazil", "Venezuela"], answer: 2 },
      { id: "q5",  prompt: "Which continent is SOUTH of Europe across the Mediterranean Sea?", choices: ["Asia", "South America", "Antarctica", "Africa"], answer: 3 },
      { id: "q6",  prompt: "The Sahara Desert is in which continent?", choices: ["Asia", "Australia", "Africa", "South America"], answer: 2 },
      { id: "q7",  prompt: "Which country has the MOST people in the world?", choices: ["United States", "India", "Russia", "Brazil"], answer: 1, explanation: "India recently surpassed China as the most populous country." },
      { id: "q8",  prompt: "Which ocean lies between Europe/Africa and the Americas?", choices: ["Pacific", "Indian", "Arctic", "Atlantic"], answer: 3 },
      { id: "q9",  prompt: "The Andes Mountains run along the western side of which continent?", choices: ["North America", "Africa", "South America", "Asia"], answer: 2 },
      { id: "q10", prompt: "Australia is both a country AND a...", choices: ["Peninsula", "Island", "Continent", "Archipelago"], answer: 2 },
      { id: "q11", prompt: "Russia is the LARGEST country by land area. It spans which TWO continents?", choices: ["Europe and Asia", "Asia and Africa", "Europe and Africa", "North America and Europe"], answer: 0 },
      { id: "q12", prompt: "The Great Barrier Reef — the world's largest coral reef system — is off the coast of...", choices: ["South Africa", "Australia", "New Zealand", "Indonesia"], answer: 1 },
      { id: "q13", prompt: "Which European country is known for the Eiffel Tower?", choices: ["Italy", "Germany", "Spain", "France"], answer: 3 },
      { id: "q14", prompt: "The Panama Canal connects the Atlantic and Pacific Oceans and cuts through which country?", choices: ["Mexico", "Colombia", "Panama", "Costa Rica"], answer: 2 },
      { id: "q15", prompt: "Which is the LARGEST ocean on Earth?", choices: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2 },
      { id: "q16", prompt: "How many continents are there on Earth?", choices: ["5", "6", "7", "8"], answer: 2 },
      { id: "q17", prompt: "The Great Wall is a famous landmark in which country?", choices: ["Japan", "China", "India", "South Korea"], answer: 1 },
      { id: "q18", prompt: "The Nile River flows through which continent?", choices: ["Asia", "Europe", "Africa", "South America"], answer: 2, explanation: "The Nile flows northward through northeastern Africa." },
    ],
  },

  {
    id: "g4-geo-latlong",
    subjectId: "geography",
    level: "grade4",
    title: "Latitude & Longitude",
    description: "Use latitude and longitude coordinates to find locations on Earth.",
    emoji: "🧭",
    questions: [
      { id: "q1",  prompt: "Latitude lines run which direction on a map?", choices: ["Vertically (up-down)", "Horizontally (left-right)", "Diagonally", "In circles around poles"], answer: 1 },
      { id: "q2",  prompt: "Longitude lines run which direction on a map?", choices: ["Horizontally (left-right)", "Vertically (up-down)", "Diagonally", "Around the equator"], answer: 1 },
      { id: "q3",  prompt: "The equator is at...", choices: ["90° N latitude", "0° latitude", "180° longitude", "45° S latitude"], answer: 1 },
      { id: "q4",  prompt: "The Prime Meridian is at...", choices: ["0° latitude", "90° longitude", "0° longitude", "180° longitude"], answer: 2 },
      { id: "q5",  prompt: "A place at 90° N latitude is at the...", choices: ["Equator", "North Pole", "South Pole", "Prime Meridian"], answer: 1 },
      { id: "q6",  prompt: "Latitude measures how far north or south you are from the...", choices: ["Prime Meridian", "International Date Line", "Equator", "North Pole"], answer: 2 },
      { id: "q7",  prompt: "Longitude measures how far east or west you are from the...", choices: ["Equator", "North Pole", "Prime Meridian", "Tropic of Cancer"], answer: 2 },
      { id: "q8",  prompt: "What coordinate pair (lat, long) roughly marks the location of New York City?", choices: ["51° N, 0° W", "41° N, 74° W", "33° S, 70° W", "48° N, 2° E"], answer: 1 },
      { id: "q9",  prompt: "The Tropic of Cancer is at approximately...", choices: ["0° latitude", "23.5° N latitude", "45° N latitude", "66.5° N latitude"], answer: 1 },
      { id: "q10", prompt: "A ship at 0°, 0° is located where?", choices: ["New York Harbor", "In the Pacific Ocean", "In the Atlantic Ocean near Africa", "The North Pole"], answer: 2 },
      { id: "q11", prompt: "Time zones are based on lines of...", choices: ["Latitude", "Longitude", "The equator", "The Prime Meridian only"], answer: 1 },
      { id: "q12", prompt: "Which direction do latitude numbers INCREASE?", choices: ["East and West", "North and South from equator", "Toward the Prime Meridian", "Along the equator"], answer: 1 },
      { id: "q13", prompt: "The International Date Line is at approximately...", choices: ["0° longitude", "90° E longitude", "180° longitude", "45° W longitude"], answer: 2 },
      { id: "q14", prompt: "If a city is at 30° S, 31° E, it is in which hemisphere?", choices: ["Northern and Eastern", "Northern and Western", "Southern and Eastern", "Southern and Western"], answer: 2 },
      { id: "q15", prompt: "Together, the crossing lines of latitude and longitude form a...", choices: ["Compass", "Grid", "Globe", "Legend"], answer: 1 },
      { id: "q16", prompt: "Which imaginary line divides Earth into the Northern and Southern Hemispheres?", choices: ["Prime Meridian", "Equator", "International Date Line", "Tropic of Cancer"], answer: 1 },
      { id: "q17", prompt: "Which imaginary line divides Earth into the Eastern and Western Hemispheres?", choices: ["Equator", "Prime Meridian", "Tropic of Capricorn", "Arctic Circle"], answer: 1 },
      { id: "q18", prompt: "A location at 40° N, 105° W is in which hemispheres?", choices: ["Northern and Eastern", "Northern and Western", "Southern and Eastern", "Southern and Western"], answer: 1, explanation: "N latitude means Northern Hemisphere; W longitude means Western Hemisphere." },
    ],
  },
];
