/** Brainy Buddies - 11th Grade core curriculum activities. */
import type { Activity } from "@/lib/brainy-data";

export const GRADE11_ACTIVITIES: Activity[] = [
  {
    id: "g11-math-algebra2",
    subjectId: "math",
    level: "grade11",
    title: "Algebra II & Advanced Functions",
    description: "Analyze polynomial, rational, exponential, and logarithmic functions.",
    emoji: "📈",
    questions: [
      { id: "q1", prompt: "What are the zeros of x² - 5x + 6?", choices: ["-2 and -3", "2 and 3", "1 and 6", "-1 and -6"], answer: 1 },
      { id: "q2", prompt: "log10(1000) equals...", choices: ["2", "3", "10", "100"], answer: 1 },
      { id: "q3", prompt: "Which is the inverse of f(x) = 3x + 6?", choices: ["(x - 6)/3", "3x - 6", "x/3 + 6", "1/(3x + 6)"], answer: 0 },
      { id: "q4", prompt: "The remainder when P(x) is divided by x - a equals...", choices: ["P(a)", "P(-a)", "aP(x)", "zero always"], answer: 0 },
      { id: "q5", prompt: "An exponential decay model has a base...", choices: ["greater than 1", "between 0 and 1", "equal to 0", "less than 0"], answer: 1 },
    ],
  },
  {
    id: "g11-sci-physics",
    subjectId: "science",
    level: "grade11",
    title: "Physics: Motion, Energy & Momentum",
    description: "Apply mathematical models to forces, energy, momentum, and waves.",
    emoji: "⚡",
    questions: [
      { id: "q1", prompt: "Newton's second law is represented by...", choices: ["F = ma", "E = mc²", "p = V/I", "v = f/lambda"], answer: 0 },
      { id: "q2", prompt: "The kinetic energy of an object is...", choices: ["mgh", "1/2 mv²", "mv", "Fd/t"], answer: 1 },
      { id: "q3", prompt: "In a closed system, total momentum is...", choices: ["conserved", "always zero", "equal to force", "destroyed in collisions"], answer: 0 },
      { id: "q4", prompt: "Work is done when a force causes...", choices: ["displacement", "mass", "temperature only", "constant velocity only"], answer: 0 },
      { id: "q5", prompt: "Wave speed equals...", choices: ["frequency x wavelength", "frequency / wavelength", "amplitude x time", "mass x acceleration"], answer: 0 },
    ],
  },
  {
    id: "g11-hist-us-history",
    subjectId: "history",
    level: "grade11",
    title: "U.S. History: Industry to the Present",
    description: "Evaluate political, economic, and social change in modern United States history.",
    emoji: "🇺🇸",
    questions: [
      { id: "q1", prompt: "Progressive Era reformers generally sought to...", choices: ["address problems created by industrialization", "restore feudalism", "end public education", "reduce voting access"], answer: 0 },
      { id: "q2", prompt: "The New Deal responded primarily to...", choices: ["the Great Depression", "World War I", "the Cold War", "Reconstruction"], answer: 0 },
      { id: "q3", prompt: "The Great Migration moved many Black Americans from...", choices: ["the rural South to northern and western cities", "Europe to Asia", "cities to plantations", "the West to the colonial East"], answer: 0 },
      { id: "q4", prompt: "Brown v. Board of Education rejected...", choices: ["school segregation", "freedom of speech", "federal taxation", "women's suffrage"], answer: 0 },
      { id: "q5", prompt: "A sound historical argument should address...", choices: ["evidence that complicates its claim", "only supporting facts", "no primary sources", "present-day opinion only"], answer: 0 },
    ],
  },
  {
    id: "g11-geo-global-systems",
    subjectId: "geography",
    level: "grade11",
    title: "Global Systems & Geopolitics",
    description: "Analyze borders, resources, trade networks, conflict, and international cooperation.",
    emoji: "🗺️",
    questions: [
      { id: "q1", prompt: "Geopolitics examines how power relates to...", choices: ["geography and territory", "grammar", "cell division", "musical form"], answer: 0 },
      { id: "q2", prompt: "A chokepoint is strategically important because it...", choices: ["concentrates movement through a narrow route", "has no trade", "eliminates borders", "contains every resource"], answer: 0 },
      { id: "q3", prompt: "Comparative advantage encourages countries to...", choices: ["specialize where opportunity cost is lower", "produce everything equally", "avoid trade", "use identical currencies"], answer: 0 },
      { id: "q4", prompt: "A refugee differs from a voluntary migrant because a refugee...", choices: ["is forced to flee danger or persecution", "always moves for higher wages", "never crosses a border", "must travel by sea"], answer: 0 },
      { id: "q5", prompt: "Resource scarcity can increase conflict when...", choices: ["groups compete for limited essentials", "supply exceeds demand", "trade costs fall", "population declines everywhere"], answer: 0 },
    ],
  },
  {
    id: "g11-lang-american-rhetoric",
    subjectId: "language",
    level: "grade11",
    title: "American Literature & Rhetoric",
    description: "Trace ideas across American texts and evaluate sophisticated rhetorical choices.",
    emoji: "🖋️",
    questions: [
      { id: "q1", prompt: "Rhetorical situation includes the speaker, audience, purpose, and...", choices: ["context", "page count", "font", "price"], answer: 0 },
      { id: "q2", prompt: "An allusion is...", choices: ["an indirect reference to another text, person, or event", "a direct definition", "a plot summary", "a repeated consonant"], answer: 0 },
      { id: "q3", prompt: "Syntax can shape meaning through...", choices: ["sentence structure and pacing", "book binding", "historical dates only", "citation format"], answer: 0 },
      { id: "q4", prompt: "A concession strengthens an argument by...", choices: ["acknowledging a valid opposing point", "ignoring counterevidence", "changing the topic", "repeating the thesis"], answer: 0 },
      { id: "q5", prompt: "Synthesis writing requires a writer to...", choices: ["connect multiple sources in support of an original claim", "summarize one source", "avoid citations", "use quotations without analysis"], answer: 0 },
    ],
  },
  {
    id: "g11-python-data-structures",
    subjectId: "python",
    level: "grade11",
    title: "Python Data Structures & Algorithms",
    description: "Choose efficient structures and analyze searching, sorting, and recursive algorithms.",
    emoji: "💻",
    questions: [
      { id: "q1", prompt: "Average dictionary key lookup is typically...", choices: ["O(1)", "O(n)", "O(n²)", "O(2^n)"], answer: 0 },
      { id: "q2", prompt: "A stack follows which access pattern?", choices: ["First in, first out", "Last in, first out", "Random only", "Sorted only"], answer: 1 },
      { id: "q3", prompt: "Binary search has time complexity...", choices: ["O(log n)", "O(n²)", "O(2^n)", "O(n!)"], answer: 0 },
      { id: "q4", prompt: "A recursive function must move toward...", choices: ["a base case", "a global variable", "an import", "an infinite loop"], answer: 0 },
      { id: "q5", prompt: "Breadth-first search commonly uses a...", choices: ["queue", "stack only", "string", "tuple only"], answer: 0 },
    ],
  },
  {
    id: "g11-sel-future-planning",
    subjectId: "sel",
    level: "grade11",
    title: "Future Planning & Values-Based Choices",
    description: "Explore pathways, evaluate trade-offs, and make flexible plans grounded in your values.",
    emoji: "🧭",
    questions: [
      { id: "q1", prompt: "A values-based goal should reflect...", choices: ["what matters to you, not only external pressure", "the most popular choice", "a guaranteed outcome", "someone else's timeline"], answer: 0 },
      { id: "q2", prompt: "Opportunity cost is...", choices: ["the next-best option given up by a choice", "money already spent", "a guaranteed benefit", "an unexpected reward"], answer: 0 },
      { id: "q3", prompt: "Informational interviews are useful for...", choices: ["learning about a field from someone in it", "guaranteeing a job", "replacing all research", "avoiding questions"], answer: 0 },
      { id: "q4", prompt: "A flexible plan includes...", choices: ["milestones plus room to revise as you learn", "one unchangeable path", "no deadlines", "only distant goals"], answer: 0 },
      { id: "q5", prompt: "When family expectations conflict with your goals, a constructive step is to...", choices: ["discuss values, concerns, and options respectfully", "hide every plan", "end the relationship", "agree without reflection"], answer: 0 },
    ],
  },
];