import type { LearnItem } from "@/lib/science-learn-data";

export const GRADE6_7_LEARN_DATA: Record<string, LearnItem[]> = {
  "g6-math-ratios": [
    { emoji: "⚖️", title: "Ratios Compare Quantities", fact: "A ratio compares two quantities in a chosen order. If there are 2 red beads and 3 blue beads, the ratio of red to blue is 2:3." },
    { emoji: "🔁", title: "Equivalent Ratios", fact: "Multiply or divide both parts by the same number. The ratios 2:3, 4:6, and 10:15 all describe the same relationship." },
    { emoji: "🏷️", title: "Unit Rates", fact: "A unit rate compares a quantity to 1. If 5 notebooks cost $15, divide 15 by 5 to get $3 per notebook." },
    { emoji: "%", title: "Percent Means Per Hundred", fact: "A percent is a ratio out of 100. So 25% = 25/100 = 1/4 = 0.25." },
    { emoji: "🗺️", title: "Scale Drawings", fact: "A scale connects a drawing to real size. If 1 inch represents 20 miles, multiply map inches by 20 to find actual miles." },
  ],
  "g6-math-number-system": [
    { emoji: "↔️", title: "Read the Number Line", fact: "Numbers farther right are greater. Negative numbers reverse the usual-looking order: -3 is greater than -8 because -3 is closer to zero." },
    { emoji: "📏", title: "Absolute Value", fact: "Absolute value is distance from zero, so it is never negative. Both 12 and -12 have an absolute value of 12." },
    { emoji: "➕", title: "Add Signed Numbers", fact: "Same signs: add their absolute values and keep the sign. Different signs: subtract the smaller absolute value from the larger and keep the sign of the larger absolute value." },
    { emoji: "✖️", title: "Multiply and Divide Signs", fact: "Two numbers with the same sign make a positive product or quotient. Different signs make a negative result." },
    { emoji: "💳", title: "Integers in Context", fact: "Positive numbers can represent deposits, gains, or heights above sea level. Negative numbers can represent withdrawals, losses, or positions below sea level." },
  ],
  "g6-math-expressions-equations": [
    { emoji: "🔤", title: "Variables and Expressions", fact: "A variable represents a number. To evaluate 3x + 5 when x = 4, substitute 4: 3(4) + 5 = 17." },
    { emoji: "🧲", title: "Combine Like Terms", fact: "Terms can combine when they have the same variable part. For example, 4a + 2a = 6a, but 4a + 2 cannot combine." },
    { emoji: "📦", title: "Distributive Property", fact: "Multiply every term inside parentheses: 3(x + 4) = 3x + 12." },
    { emoji: "⚖️", title: "Keep Equations Balanced", fact: "An equation is like a balanced scale. Use inverse operations on both sides to isolate the variable." },
    { emoji: "🔍", title: "Check Your Solution", fact: "Substitute your answer into the original equation. If both sides have the same value, the solution checks." },
  ],
  "g6-math-geometry": [
    { emoji: "🔺", title: "Triangle Area", fact: "A triangle is half of a matching parallelogram, so A = 1/2 bh. Use the perpendicular height, not a slanted side." },
    { emoji: "▱", title: "Parallelogram Area", fact: "The area of a parallelogram is base times perpendicular height: A = bh." },
    { emoji: "📦", title: "Volume of a Prism", fact: "Volume measures space inside a solid. For a rectangular prism, V = length x width x height, measured in cubic units." },
    { emoji: "🎁", title: "Surface Area", fact: "Surface area is the total area of every outside face. A net unfolds a solid so you can see and add all of its faces." },
    { emoji: "🧩", title: "Decompose Complex Shapes", fact: "Split an irregular figure into rectangles, triangles, or other familiar shapes. Find each area, then add or subtract as needed." },
  ],
  "g6-math-statistics": [
    { emoji: "❓", title: "Statistical Questions", fact: "A statistical question expects variability in its answers, such as how many minutes students read each day." },
    { emoji: "🎯", title: "Measures of Center", fact: "The mean is the sum divided by the count. The median is the middle ordered value, and the mode is the most frequent value." },
    { emoji: "↔️", title: "Measures of Spread", fact: "Range is maximum minus minimum. Mean absolute deviation describes the typical distance of values from the mean." },
    { emoji: "📍", title: "Read Dot and Box Plots", fact: "Dot plots show individual values. Box plots summarize a distribution with its minimum, quartiles, median, and maximum." },
    { emoji: "⚠️", title: "Watch for Outliers", fact: "An outlier lies far from most values. It can pull the mean strongly, while the median is often more resistant." },
  ],
  "g6-math-coordinate-plane": [
    { emoji: "🗺️", title: "Ordered Pairs", fact: "An ordered pair is written (x, y). Move horizontally to x first, then vertically to y." },
    { emoji: "4️⃣", title: "Four Quadrants", fact: "Quadrant I is (+,+), II is (-,+), III is (-,-), and IV is (+,-). Points on an axis are not in a quadrant." },
    { emoji: "🪞", title: "Reflections", fact: "Reflecting across the y-axis changes the sign of x. Reflecting across the x-axis changes the sign of y." },
    { emoji: "📏", title: "Horizontal and Vertical Distance", fact: "For points on the same horizontal or vertical line, subtract the changing coordinates and use the absolute value." },
    { emoji: "🎯", title: "Distance From an Axis", fact: "A point's distance from the x-axis is |y|. Its distance from the y-axis is |x|." },
  ],
  "g6-sci-cells": [
    { emoji: "🔬", title: "Cells Are the Basic Unit of Life", fact: "Every living thing is made of one or more cells. Cells perform the basic processes organisms need to survive." },
    { emoji: "🧠", title: "Nucleus and Cell Membrane", fact: "The nucleus contains DNA and directs cell activities. The cell membrane controls which materials enter and leave." },
    { emoji: "⚡", title: "Energy Organelles", fact: "Mitochondria release usable energy from food. In plant cells, chloroplasts capture light energy during photosynthesis." },
    { emoji: "🌿", title: "Plant and Animal Cells", fact: "Both have membranes, cytoplasm, and nuclei. Plant cells also have rigid cell walls, chloroplasts, and usually a large central vacuole." },
    { emoji: "🫀", title: "Levels of Organization", fact: "Cells form tissues, tissues form organs, organs form organ systems, and organ systems work together in an organism." },
  ],
  "g6-sci-matter-atoms": [
    { emoji: "⚛️", title: "Atoms Build Matter", fact: "An atom is the smallest unit that keeps an element's properties. Protons and neutrons occupy the nucleus, while electrons move around it." },
    { emoji: "➕", title: "Subatomic Charges", fact: "Protons are positive, electrons are negative, and neutrons have no charge. The atomic number tells how many protons an atom has." },
    { emoji: "🧪", title: "Elements and Compounds", fact: "An element contains one type of atom. A compound contains atoms of different elements chemically bonded in a fixed ratio, such as H2O." },
    { emoji: "🥣", title: "Mixtures", fact: "A mixture combines substances physically, so each keeps its properties. Mixtures can often be separated by filtering, evaporation, or other physical methods." },
    { emoji: "📏", title: "Density", fact: "Density = mass / volume. It describes how tightly matter is packed and can help identify a substance." },
  ],
  "g6-sci-forces-energy": [
    { emoji: "🏃", title: "Describe Motion", fact: "Speed = distance / time. Velocity also includes direction, and acceleration is any change in velocity." },
    { emoji: "⚖️", title: "Balanced and Unbalanced Forces", fact: "Balanced forces have a net force of zero and do not change motion. An unbalanced net force causes acceleration." },
    { emoji: "🛝", title: "Potential and Kinetic Energy", fact: "Potential energy is stored because of position or condition. Kinetic energy is energy of motion." },
    { emoji: "🔄", title: "Energy Transforms", fact: "Energy changes form without being created or destroyed. A falling object converts gravitational potential energy into kinetic energy." },
    { emoji: "🧤", title: "Friction and Work", fact: "Friction opposes motion and often produces thermal energy. Scientific work occurs when a force moves an object through a distance." },
  ],
  "g6-sci-earth-systems": [
    { emoji: "🌎", title: "Interacting Earth Systems", fact: "The geosphere, hydrosphere, atmosphere, and biosphere exchange matter and energy. A change in one system can affect the others." },
    { emoji: "🌦️", title: "Weather and Climate", fact: "Weather is the atmosphere's short-term condition. Climate is the long-term pattern of weather in a region." },
    { emoji: "💧", title: "The Water Cycle", fact: "Solar energy drives evaporation. Cooling causes condensation, water returns as precipitation, and runoff or infiltration moves it through Earth systems." },
    { emoji: "🪨", title: "The Rock Cycle", fact: "Cooling magma forms igneous rock, compacted sediments form sedimentary rock, and heat plus pressure form metamorphic rock." },
    { emoji: "🌊", title: "Climate Drivers", fact: "Latitude, elevation, landforms, oceans, and currents shape climate by influencing how solar and thermal energy move." },
  ],
  "g6-sci-space-gravity": [
    { emoji: "🪐", title: "Gravity Creates Orbits", fact: "Gravity attracts masses. It continually bends a planet's forward motion into an orbit around the Sun and the Moon's motion into an orbit around Earth." },
    { emoji: "🌍", title: "Rotation and Revolution", fact: "Earth rotates once about every 24 hours, causing day and night. It revolves around the Sun once about every 365 days." },
    { emoji: "☀️", title: "Why Seasons Change", fact: "Earth's tilted axis changes the angle and length of sunlight during its orbit. Seasons are not caused by Earth moving much closer to the Sun." },
    { emoji: "🌙", title: "Phases and Eclipses", fact: "Moon phases show different portions of its sunlit half. Eclipses occur when the Sun, Earth, and Moon align closely." },
    { emoji: "✨", title: "The Scale of Space", fact: "Our solar system lies within the Milky Way. A light-year is a distance: how far light travels in one year." },
  ],
  "g6-hist-ancient": [
    { emoji: "🌊", title: "River Valley Civilizations", fact: "Reliable water and fertile floodplains supported farming and cities near the Nile, Tigris-Euphrates, Indus, and Yellow rivers." },
    { emoji: "✍️", title: "Writing and Government", fact: "Writing helped societies track trade, laws, and beliefs. Hammurabi's Code is an early example of laws written for the public." },
    { emoji: "🏛️", title: "Greek and Roman Government", fact: "Athens developed direct democracy for citizens. Rome's republic used elected representatives and influenced later governments." },
    { emoji: "🐫", title: "Trade Spreads Ideas", fact: "Routes such as the Silk Road moved silk and spices, but also religions, technologies, languages, and diseases." },
    { emoji: "📜", title: "Reading Historical Evidence", fact: "Primary sources were created during the period being studied. Historians compare sources and consider each creator's perspective." },
  ],
  "g6-geo-human-physical": [
    { emoji: "🏔️", title: "Physical Geography", fact: "Physical geography studies natural features and processes such as landforms, climate, rivers, ecosystems, and tectonic plates." },
    { emoji: "🏙️", title: "Human Geography", fact: "Human geography studies people and places, including culture, population, migration, cities, economies, and political borders." },
    { emoji: "🧭", title: "Location and Scale", fact: "Latitude measures north or south of the Equator; longitude measures east or west of the Prime Meridian. Scale converts map distance to real distance." },
    { emoji: "🧳", title: "Migration Factors", fact: "Push factors such as conflict encourage people to leave. Pull factors such as safety, education, or jobs attract them elsewhere." },
    { emoji: "☀️", title: "Resources and Settlement", fact: "Water, fertile land, energy, and transportation influence where communities grow. Renewable resources can naturally replenish over time." },
  ],
  "g7-math-proportions": [
    { emoji: "📈", title: "Proportional Relationships", fact: "In a proportional relationship, y = kx. The constant k is the unit rate, and the graph is a straight line through (0, 0)." },
    { emoji: "➖", title: "Adding Signed Numbers", fact: "Same signs: add absolute values and keep the sign. Different signs: subtract absolute values and keep the sign of the number farther from zero." },
    { emoji: "✖️", title: "Multiplying Signed Numbers", fact: "Same signs produce a positive product. Different signs produce a negative product: (-6)(-4)=24, but (-6)(4)=-24." },
    { emoji: "🛍️", title: "Percent Change", fact: "Percent change = change divided by original amount, then multiply by 100. Discounts subtract from the original price; markups add to it." },
    { emoji: "🍕", title: "Dividing Fractions", fact: "Keep the first fraction, change division to multiplication, and flip the second fraction. Then multiply and simplify." },
  ],
  "g7-math-equations-inequalities": [
    { emoji: "⚖️", title: "Solve Multi-Step Equations", fact: "Simplify each side first, then use inverse operations to isolate the variable. Apply every operation to both sides." },
    { emoji: "📦", title: "Distribute and Combine", fact: "Use the distributive property before combining like terms. For example, 2(3x + 4) - x = 6x + 8 - x = 5x + 8." },
    { emoji: "↔️", title: "Variables on Both Sides", fact: "Move variable terms to one side and constants to the other. For 5x - 7 = 2x + 8, subtract 2x, then add 7." },
    { emoji: "🔁", title: "Reverse Negative Inequalities", fact: "When multiplying or dividing both sides of an inequality by a negative number, reverse the inequality sign." },
    { emoji: "📍", title: "Graph Inequalities", fact: "Use an open point for < or > and a closed point for <= or >=. Shade toward all values that make the inequality true." },
  ],
  "g7-math-circles-angles": [
    { emoji: "⭕", title: "Radius and Diameter", fact: "The radius runs from center to circle. The diameter crosses the center and equals twice the radius: d = 2r." },
    { emoji: "🧵", title: "Circumference", fact: "Circumference is distance around a circle. Use C = pi d or C = 2 pi r." },
    { emoji: "🎯", title: "Area of a Circle", fact: "Area measures the region inside a circle. Use A = pi r², and report the answer in square units." },
    { emoji: "📐", title: "Complementary and Supplementary", fact: "Complementary angles total 90 degrees. Supplementary angles total 180 degrees." },
    { emoji: "✖️", title: "Vertical Angles", fact: "When two lines intersect, opposite vertical angles are congruent. Adjacent angles form a supplementary pair." },
  ],
  "g7-math-probability": [
    { emoji: "🎲", title: "Probability as a Ratio", fact: "For equally likely outcomes, probability = favorable outcomes / total outcomes. Values range from 0 for impossible to 1 for certain." },
    { emoji: "🗂️", title: "Sample Spaces", fact: "A sample space lists every possible outcome. For one coin flip it is {H, T}; for two flips it is {HH, HT, TH, TT}." },
    { emoji: "🌳", title: "Compound Events", fact: "For independent events joined by 'and,' multiply probabilities. Two heads in two fair flips has probability 1/2 x 1/2 = 1/4." },
    { emoji: "🧪", title: "Experimental Probability", fact: "Experimental probability = times the event occurred / number of trials. More trials usually bring it closer to theoretical probability." },
    { emoji: "🔄", title: "Use the Complement", fact: "The probability that an event does not happen is 1 minus the probability that it does happen." },
  ],
  "g7-math-sampling-statistics": [
    { emoji: "👥", title: "Population and Sample", fact: "A population is the full group of interest. A sample is the smaller group actually observed." },
    { emoji: "🎟️", title: "Random Samples", fact: "Random selection gives population members a fair chance to be chosen and reduces selection bias." },
    { emoji: "⚠️", title: "Recognize Biased Samples", fact: "A sample is biased when its selection favors certain responses, such as surveying only students who already prefer one lunch option." },
    { emoji: "🔭", title: "Estimate a Population", fact: "Use a representative sample proportion to estimate a population count. If 60% support an idea, estimate 0.60 times the population." },
    { emoji: "📊", title: "Compare Distributions", fact: "Compare both center and variability. Similar means do not guarantee similar distributions or spreads." },
  ],
  "g7-math-scale-geometry": [
    { emoji: "📏", title: "Read a Drawing Scale", fact: "A scale pairs drawing length with actual length. Multiply or divide using the same scale relationship for every measurement." },
    { emoji: "🔍", title: "Scale Factors", fact: "Multiply every original length by the scale factor. Factors greater than 1 enlarge; factors between 0 and 1 reduce." },
    { emoji: "◼️", title: "How Area Scales", fact: "If lengths scale by factor k, areas scale by k². A length factor of 2 creates an area factor of 4." },
    { emoji: "📦", title: "Prism Volume", fact: "For any prism, V = base area x prism length or height. Keep all measurements in compatible units." },
    { emoji: "🎁", title: "Surface Area of Solids", fact: "Find the area of every exterior face and add. A net can help organize the faces without missing or double-counting one." },
  ],
  "g7-sci-ecosystems": [
    { emoji: "☀️", title: "Energy Flows", fact: "Producers capture energy, consumers obtain it by eating, and decomposers recycle matter. Some energy is released as heat at every trophic level." },
    { emoji: "🌡️", title: "Biotic and Abiotic Factors", fact: "Biotic factors are living, such as plants and bacteria. Abiotic factors are nonliving, such as water, light, soil, and temperature." },
    { emoji: "📏", title: "Carrying Capacity", fact: "Food, water, shelter, and space limit population size. Carrying capacity is the largest population an environment can support over time." },
    { emoji: "🧬", title: "Variation and Inheritance", fact: "DNA stores inherited information. Individuals in a population vary, and some variations affect survival and reproduction." },
    { emoji: "🦋", title: "Natural Selection", fact: "Heritable traits that improve reproductive success tend to become more common over generations. Populations evolve, not individual organisms." },
  ],
  "g7-sci-chemical-reactions": [
    { emoji: "🧪", title: "Reactants Become Products", fact: "Reactants are starting substances. During a chemical reaction, their atoms rearrange into products with different properties." },
    { emoji: "🔎", title: "Evidence of Reaction", fact: "Possible evidence includes gas formation, a lasting color change, a precipitate, light, odor, or an unexpected temperature change." },
    { emoji: "⚖️", title: "Conservation of Mass", fact: "Atoms are rearranged, not created or destroyed. In a closed system, total product mass equals total reactant mass." },
    { emoji: "🔥", title: "Energy in Reactions", fact: "Exothermic reactions release energy to their surroundings. Endothermic reactions absorb energy from their surroundings." },
    { emoji: "📝", title: "Balance Equations", fact: "A balanced equation has the same count of each type of atom on both sides. Change coefficients, never the chemical formulas." },
  ],
  "g7-sci-genetics": [
    { emoji: "🧬", title: "DNA, Genes, and Chromosomes", fact: "DNA stores hereditary information. Genes are DNA segments found on chromosomes and influence traits by providing instructions." },
    { emoji: "🔤", title: "Alleles", fact: "Alleles are versions of a gene. Homozygous organisms have two matching alleles; heterozygous organisms have two different alleles." },
    { emoji: "◻️", title: "Punnett Squares", fact: "A Punnett square shows possible allele combinations in offspring. It predicts probabilities, not the exact traits of every child." },
    { emoji: "🔄", title: "Mutations Create Variation", fact: "A mutation is a DNA change. Mutations may be harmful, neutral, or helpful, and only heritable mutations can pass to offspring." },
    { emoji: "🌱", title: "Genes and Environment", fact: "Many traits reflect both inherited information and environmental conditions. Nutrition, for example, can influence genetically affected height." },
  ],
  "g7-sci-earth-history": [
    { emoji: "🧩", title: "Moving Plates", fact: "Earth's lithosphere is divided into tectonic plates that move slowly over the softer mantle because of energy inside Earth." },
    { emoji: "↔️", title: "Plate Boundaries", fact: "Divergent plates separate, convergent plates collide, and transform plates slide past. These interactions shape Earth's surface." },
    { emoji: "🌋", title: "Geologic Activity", fact: "Earthquakes and volcanoes cluster near plate boundaries. Subduction can produce trenches, volcanoes, and powerful earthquakes." },
    { emoji: "🪨", title: "Relative Rock Ages", fact: "In undisturbed sedimentary layers, older layers lie below younger ones. Index fossils help correlate layers across locations." },
    { emoji: "⏳", title: "Absolute Ages and Continental Drift", fact: "Radiometric dating uses predictable radioactive decay. Matching rocks, fossils, and coastlines support the movement from Pangaea to today's continents." },
  ],
  "g7-sci-waves-electricity": [
    { emoji: "〰️", title: "Waves Transfer Energy", fact: "A wave transfers energy without carrying matter all the way from source to destination. Amplitude relates to energy, while frequency counts cycles per second." },
    { emoji: "🔊", title: "Sound Waves", fact: "Sound is a mechanical wave and needs matter to travel. Higher frequency produces higher pitch, while greater amplitude usually sounds louder." },
    { emoji: "💡", title: "Light Waves", fact: "Light is electromagnetic and can cross a vacuum. It can reflect, refract, transmit, or be absorbed when it meets matter." },
    { emoji: "🔋", title: "Closed Circuits", fact: "Electric current needs a closed conducting path and an energy source. Metals such as copper conduct well; rubber and plastic insulate." },
    { emoji: "🔀", title: "Series and Parallel", fact: "Series circuits provide one current path, so one break stops the circuit. Parallel circuits provide multiple paths for current." },
  ],
  "g7-hist-medieval-modern": [
    { emoji: "🏰", title: "Feudal Societies", fact: "In medieval Europe, land, loyalty, and military service connected kings, nobles, knights, and peasants in a feudal hierarchy." },
    { emoji: "📜", title: "Limits on Rulers", fact: "The Magna Carta of 1215 reinforced that even a king was subject to law and helped shape later ideas about rights and limited government." },
    { emoji: "🎨", title: "Renaissance and Humanism", fact: "Trade wealth helped Italian cities support artists and scholars. Humanists renewed interest in classical learning and human potential." },
    { emoji: "🖨️", title: "Printing Accelerates Change", fact: "Movable-type printing made books cheaper and ideas faster to share, supporting literacy, religious debate, and scientific exchange." },
    { emoji: "🔭", title: "Evidence and Experiment", fact: "Scientific Revolution thinkers used observation, mathematics, and repeatable experiments to test explanations of the natural world." },
  ],
  "g7-geo-population-economics": [
    { emoji: "🏙️", title: "Urbanization", fact: "Urbanization is the growth of cities and city populations. It can expand jobs and services while straining housing, transportation, and water systems." },
    { emoji: "🧳", title: "Population Movement", fact: "Migration patterns reflect push and pull factors. Population pyramids reveal the age and sex structure of a population." },
    { emoji: "🚢", title: "Trade and Specialization", fact: "Places specialize based on resources, skills, and costs. Exports leave a country, imports enter it, and tariffs are taxes on imports." },
    { emoji: "📊", title: "Measuring Development", fact: "GDP measures production, but quality of life also involves health, education, income, safety, and access to essential services." },
    { emoji: "🌱", title: "Sustainable Development", fact: "Sustainable development balances economic, social, and environmental needs so present progress does not reduce future opportunities." },
  ],
};