import type { LearnItem } from "@/lib/activity-learn-data";

export const HISTORY_EXPANSION_LEARN_DATA: Record<string, LearnItem[]> = {
  "g3-hist-indigenous-regions": [
    { emoji: "🗺️", title: "Many Nations", fact: "North America was home to hundreds of distinct Indigenous nations long before Europeans arrived. Each had its own government, language, and traditions." },
    { emoji: "🏠", title: "Homes Fit the Place", fact: "Communities built with local materials and adapted to climate. Homes included pueblos, longhouses, plank houses, and portable tipis." },
    { emoji: "🌽", title: "Food & Environment", fact: "People farmed, hunted, fished, and gathered according to their region. Corn, beans, and squash were important crops in many communities." },
    { emoji: "🤝", title: "Government & Cooperation", fact: "The Haudenosaunee Confederacy united several nations under the Great Law of Peace while each nation kept its own identity." },
    { emoji: "🗣️", title: "Living Cultures", fact: "Native nations are living communities today. Oral histories, languages, ceremonies, and governments continue and change over time." },
  ],
  "g3-hist-exploration-encounters": [
    { emoji: "⛵", title: "Reasons to Explore", fact: "European voyages sought trade routes, wealth, territory, and knowledge. Sailors used tools such as compasses and improved maps." },
    { emoji: "🌎", title: "A Populated World", fact: "The Americas were already home to millions of people in complex societies. Explorers did not arrive in an empty land." },
    { emoji: "🔄", title: "Columbian Exchange", fact: "Plants, animals, people, and diseases moved between the Eastern and Western Hemispheres after 1492." },
    { emoji: "🦠", title: "Unequal Consequences", fact: "European diseases caused enormous Indigenous population loss. Conquest and colonization also brought violence and forced change." },
    { emoji: "👀", title: "Multiple Perspectives", fact: "A voyage can look different to an explorer, sailor, trader, or Indigenous community. Historians compare these perspectives." },
  ],
  "g3-hist-colonial-life": [
    { emoji: "🏘️", title: "Thirteen Colonies", fact: "The thirteen British colonies developed along the Atlantic coast. Geography shaped farming, trade, and daily work." },
    { emoji: "🔨", title: "Work & Apprentices", fact: "Farmers, blacksmiths, printers, merchants, and other workers supported communities. Apprentices learned trades from skilled craftspeople." },
    { emoji: "🏫", title: "School & Home", fact: "Children often worked at home and some attended one-room schools. Access to education depended on region, wealth, race, and gender." },
    { emoji: "⚖️", title: "Freedom Was Unequal", fact: "Colonial society included enslaved Africans and displaced Indigenous peoples. Not everyone shared the rights claimed by colonists." },
    { emoji: "🧰", title: "Evidence of Daily Life", fact: "Tools, diaries, buildings, and household objects help historians understand ordinary life in colonial communities." },
  ],
  "g4-hist-indigenous-early-america": [
    { emoji: "🪶", title: "Distinct Native Nations", fact: "Indigenous nations had distinct political systems, economies, languages, and relationships with the land before and after European arrival." },
    { emoji: "🤝", title: "Trade & Alliances", fact: "Native nations and Europeans formed alliances for trade, diplomacy, and war. These relationships changed as interests changed." },
    { emoji: "🌽", title: "Shared Knowledge", fact: "Indigenous knowledge of crops, seasons, and local environments helped many early colonists survive." },
    { emoji: "📜", title: "Treaties", fact: "Treaties are formal agreements between nations. Many agreements with Native nations were later violated as settlers claimed more land." },
    { emoji: "🔎", title: "Compare Perspectives", fact: "Oral histories, treaties, maps, artifacts, and written accounts reveal different views of cooperation and conflict." },
  ],
  "g4-hist-civic-change": [
    { emoji: "📣", title: "What Is Reform?", fact: "Reformers organize to improve laws or society. Speeches, newspapers, petitions, marches, and voting can build support for change." },
    { emoji: "✍️", title: "Abolition", fact: "Frederick Douglass and many others spoke, wrote, and organized to end slavery and expand freedom." },
    { emoji: "🗳️", title: "Votes for Women", fact: "Susan B. Anthony and generations of activists worked for women's voting rights, protected nationally by the 19th Amendment in 1920." },
    { emoji: "🚌", title: "Civil Rights Movement", fact: "Rosa Parks, Martin Luther King Jr., and many local activists used organized nonviolent action to challenge segregation." },
    { emoji: "🤲", title: "Citizens Create Change", fact: "Civic change is usually a group effort. People research issues, speak up, organize, vote, and serve their communities." },
  ],
  "g5-hist-indigenous-america": [
    { emoji: "🌎", title: "Complex Societies", fact: "Indigenous societies built cities, trade networks, farms, and governments across North America long before European colonization." },
    { emoji: "⚖️", title: "Sovereignty", fact: "Sovereignty is a nation's authority to govern itself. Tribal nations retain political status and governments today." },
    { emoji: "🦠", title: "Colonization", fact: "Disease, warfare, settlement, and forced removal caused devastating losses while Native communities adapted and resisted." },
    { emoji: "👣", title: "Forced Removal", fact: "The U.S. government forced the Cherokee and other southeastern nations west. Thousands died on routes remembered as the Trail of Tears." },
    { emoji: "🗣️", title: "Continuity & Renewal", fact: "Native peoples continue to protect sovereignty, restore languages, teach traditions, and shape modern life." },
  ],
  "g5-hist-founding-nation": [
    { emoji: "📣", title: "Road to Revolution", fact: "Disputes over taxation, representation, and political rights pushed thirteen colonies toward independence from Great Britain." },
    { emoji: "📜", title: "Declaration", fact: "The Declaration of Independence stated ideals of natural rights and government by consent, even though those ideals were not equally applied." },
    { emoji: "🏛️", title: "A New Constitution", fact: "The Constitution replaced the weak Articles of Confederation and created legislative, executive, and judicial branches." },
    { emoji: "⚖️", title: "Limited Power", fact: "Checks and balances, federalism, and elections divide government power. The Bill of Rights protects individual freedoms." },
    { emoji: "🔎", title: "Founding Contradictions", fact: "The new nation celebrated liberty while slavery continued and voting rights remained limited. Later generations challenged those contradictions." },
  ],
  "g6-hist-egypt-kush": [
    { emoji: "🌊", title: "Gift of the Nile", fact: "Nile floods deposited fertile soil, supporting agriculture, transportation, and dense settlements in Egypt and Kush." },
    { emoji: "👑", title: "Pharaoh & Society", fact: "Pharaohs combined political and religious authority. Officials, scribes, artisans, farmers, and laborers filled different roles." },
    { emoji: "𓂀", title: "Writing & Belief", fact: "Hieroglyphics recorded language. Mummification and monumental tombs reflected beliefs about death and the afterlife." },
    { emoji: "⚒️", title: "Kingdom of Kush", fact: "Kush grew south of Egypt and gained wealth through gold, iron production, and trade. Meroe became an important center." },
    { emoji: "🔄", title: "Cultural Exchange", fact: "Egypt and Kush traded, fought, ruled one another, and adapted each other's artistic, religious, and political traditions." },
  ],
  "g6-hist-greece": [
    { emoji: "🗺️", title: "Geography & City-States", fact: "Mountains and seas encouraged separate Greek city-states such as Athens and Sparta, each with its own government." },
    { emoji: "🗳️", title: "Athenian Democracy", fact: "Male citizens voted directly in Athens, but women, enslaved people, and non-citizens were excluded." },
    { emoji: "🛡️", title: "Athens & Sparta", fact: "Athens emphasized civic debate and culture; Sparta emphasized military discipline. Both relied on unequal social systems." },
    { emoji: "🎭", title: "Ideas & Culture", fact: "Greek philosophy, theater, history, mathematics, art, and architecture influenced later societies." },
    { emoji: "🌍", title: "Hellenistic World", fact: "Alexander's conquests spread Greek culture, which blended with Egyptian, Persian, and Asian traditions." },
  ],
  "g6-hist-rome": [
    { emoji: "🏛️", title: "Roman Republic", fact: "Rome's republic used elected officials, a senate, assemblies, and written laws, though political participation was unequal." },
    { emoji: "👑", title: "Republic to Empire", fact: "Civil conflict and the rise of Julius Caesar weakened the republic. Augustus became the first Roman emperor." },
    { emoji: "🛣️", title: "Building an Empire", fact: "Roads, aqueducts, ports, armies, and common laws connected a vast territory around the Mediterranean." },
    { emoji: "✝️", title: "Religion & Change", fact: "Christianity began under Roman rule, spread despite persecution, and eventually became the empire's official religion." },
    { emoji: "📉", title: "Transformation", fact: "Political instability, economic problems, division, and invasions weakened the western empire, while the eastern empire continued." },
  ],
  "g6-hist-india-china": [
    { emoji: "🏙️", title: "Indus Cities", fact: "Harappa and Mohenjo-daro featured planned streets and drainage systems, evidence of organized urban life." },
    { emoji: "🪷", title: "Beliefs in India", fact: "Hindu traditions developed over centuries. Buddhism began with Siddhartha Gautama and spread under rulers such as Ashoka." },
    { emoji: "🌊", title: "Chinese River Civilizations", fact: "Early Chinese societies developed near the Huang He and Yangtze, where fertile land supported farming and states." },
    { emoji: "📚", title: "Government & Philosophy", fact: "The Mandate of Heaven explained dynastic rule. Confucianism stressed education, duty, and ethical relationships." },
    { emoji: "🐫", title: "Innovation & Exchange", fact: "Chinese paper, ironwork, and other innovations spread through trade networks including the Silk Road." },
  ],
  "g7-hist-medieval-societies": [
    { emoji: "🏰", title: "Medieval Europe", fact: "Feudal obligations and manor agriculture shaped much of Europe, while the Church influenced politics, education, and culture." },
    { emoji: "⛪", title: "Byzantine Empire", fact: "The Byzantine Empire preserved and adapted Roman law and Greek learning from its capital at Constantinople." },
    { emoji: "🌙", title: "Islamic Golden Age", fact: "Scholars across the Islamic world advanced mathematics, medicine, astronomy, philosophy, and literature." },
    { emoji: "🐫", title: "Africa & Asia", fact: "Mali prospered through trans-Saharan trade; China used civil service exams; Mongol rule expanded exchange across Eurasia." },
    { emoji: "🦠", title: "Black Death", fact: "The plague killed millions across Eurasia and North Africa, changing labor systems, economies, and social relationships." },
  ],
  "g7-hist-renaissance-reformation": [
    { emoji: "🎨", title: "Renaissance", fact: "Wealthy Italian city-states supported renewed study of classical art and learning. Humanism emphasized human experience and potential." },
    { emoji: "📐", title: "Art & Observation", fact: "Artists used perspective, anatomy, light, and close observation to make images appear realistic and three-dimensional." },
    { emoji: "🖨️", title: "Printing Revolution", fact: "Movable-type printing made texts faster and cheaper to reproduce, spreading literacy and debate." },
    { emoji: "📜", title: "Protestant Reformation", fact: "Martin Luther and other reformers challenged Church authority, leading to new Christian denominations and political conflict." },
    { emoji: "🔄", title: "Catholic Reformation", fact: "The Catholic Church clarified teachings, reformed some practices, and expanded education and missions in response." },
  ],
  "g7-hist-global-exchange": [
    { emoji: "🧭", title: "Oceanic Exploration", fact: "Improved navigation and state support helped European sailors seek direct trade routes, wealth, territory, and power." },
    { emoji: "🌽", title: "Columbian Exchange", fact: "Crops and animals crossed oceans, reshaping diets and environments. Diseases devastated Indigenous populations." },
    { emoji: "💰", title: "Colonies & Mercantilism", fact: "European powers used colonies as sources of raw materials and markets within competitive mercantilist systems." },
    { emoji: "⛓️", title: "Atlantic Slavery", fact: "The transatlantic slave trade violently forced millions of Africans across the Middle Passage and into hereditary slavery." },
    { emoji: "✊", title: "Agency & Resistance", fact: "Indigenous and African peoples negotiated, preserved cultures, escaped, rebelled, and created new communities under colonial rule." },
  ],
  "g7-hist-revolutions-industry": [
    { emoji: "💡", title: "Enlightenment Ideas", fact: "Thinkers debated natural rights, consent of the governed, religious freedom, and limits on political authority." },
    { emoji: "📣", title: "Atlantic Revolutions", fact: "Revolutions in America, France, Haiti, and Latin America challenged imperial or monarchical rule with different outcomes." },
    { emoji: "⚙️", title: "Industrial Revolution", fact: "Coal, capital, inventions, and transport helped Britain develop factories before industrialization spread elsewhere." },
    { emoji: "🏙️", title: "Urban & Social Change", fact: "Factory work drew people into growing cities, where workers often faced long hours, low pay, and dangerous conditions." },
    { emoji: "🤝", title: "Responses to Industry", fact: "Workers formed unions and reformers pursued labor laws, public health, education, and political representation." },
  ],
};