/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { dataSourcesInfo } from '../../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@microsoft/power-apps/data';
import { getClient } from '@microsoft/power-apps/data';
import type { IGetOptions, IGetAllOptions } from '../models/commonModels';
import type { AppNotes } from '../models/AppNotesModel';

/* NOTE(ai): DO NOT REMOVE OR MODIFY — Power Apps App SDK service class
Purpose: UI needs to implement CRUD operations using this service class as is. */

export class AppNotesService {
    private static readonly dataSourceName = 'appnotes';
    private static _client: ReturnType<typeof getClient> | null = null;

    private static async getClient() {
        if (!this._client) {
            this._client = getClient(dataSourcesInfo);
        }

        return this._client;
    }

    /**
     * Creates a new AppNotes record in the data source.
     *
     * @param record - The AppNotes data to create. ID field is automatically generated and should be omitted.
     * @returns A Promise that resolves to an IOperationResult containing the created AppNotes with its generated ID,
     *          or error information if the operation fails.
     *
     * @example
     * ```typescript
     * const newAppNotes = { title: "Sample AppNotes", noteId: "1234" };
     * const result = await AppNotesService.create(newAppNotes);
     * ```
     */
    public static async create(record: Omit<AppNotes, 'ID'>): Promise<IOperationResult<AppNotes>> {
        const client = await AppNotesService.getClient();
        const result = await client.createRecordAsync<Omit<AppNotes, 'ID'>, AppNotes>(AppNotesService.dataSourceName, record);
        return result;
    }

    /**
     * Updates an existing AppNotes record in the data source.
     *
     * @param ID - The unique identifier of the AppNotes to update.
     * @param changedFields - An object containing only the fields to be updated. ID field cannot be modified.
     * @returns A Promise that resolves to an IOperationResult containing the updated AppNotes,
     *          or error information if the operation fails.
     *
     * @example
     * ```typescript
     * const updatedAppNotes = { title: "Updated AppNotes", noteId: "1234" };
     * const result = await AppNotesService.update(AppNotes.ID, updatedAppNotes);
     * ```
     */
    public static async update(ID: number, changedFields: Partial<Omit<AppNotes, 'ID'>>): Promise<IOperationResult<AppNotes>> {
        const client = await AppNotesService.getClient();
        const result = await client.updateRecordAsync<Partial<Omit<AppNotes, 'ID'>>, AppNotes>(AppNotesService.dataSourceName, ID.toString(), changedFields);
        return result;
    }

    /**
     * Deletes a AppNotes record from the data source.
     *
     * @param ID - The unique identifier of the AppNotes to delete.
     * @returns A Promise that resolves to an IOperationResult indicating success or failure of the delete operation,
     *          or error information if the operation fails.
     *
     * @example
     * ```typescript
     * const result = await AppNotesService.delete(AppNotes.ID);
     * ```
     */
    public static async delete(ID: number): Promise<IOperationResult<void>> {
        const client = await AppNotesService.getClient();
        const result = await client.deleteRecordAsync(AppNotesService.dataSourceName, ID.toString());
        return result;
    }

    /**
     * Retrieves a single AppNotes record by its ID.
     *
     * @param ID - The unique identifier of the AppNotes to retrieve.
     * @param options - Optional query options for the retrieval operation (e.g., select fields, expand related data).
     * @returns A Promise that resolves to an IOperationResult containing the AppNotes,
     *          or error information if the operation fails or the AppNotes is not found.
     *
     * @example
     * ```typescript
     * const result = await AppNotesService.get(AppNotes.ID);
     * ```
     */
    public static async get(ID: number, options?: IGetOptions): Promise<IOperationResult<AppNotes>> {
        const client = await AppNotesService.getClient();
        const result = await client.retrieveRecordAsync<AppNotes>(AppNotesService.dataSourceName, ID.toString(), options);
        return result;
    }

    /**
     * Retrieves all AppNotes records from the data source.
     *
     * @param options - Optional query options for the retrieval operation (e.g., filtering, sorting, pagination).
     * @returns A Promise that resolves to an IOperationResult containing an array of AppNotes,
     *          or error information if the operation fails.
     *
     * @example
     * ```typescript
     * const result = await AppNotesService.getAll();
     * ```
     */
    public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<AppNotes[]>> {
        const client = await AppNotesService.getClient();
        const result = await client.retrieveMultipleRecordsAsync<AppNotes>(AppNotesService.dataSourceName, options);
        return result;
    }
}