/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface AppNotes {
    ID?: number;
    noteId?: string;
    title: string;
    body?: string;
}
